#pragma once
#ifndef SRC_EXTRAS_KCONFIG_QT6C_LIBKSTANDARDACTIONS_H
#define SRC_EXTRAS_KCONFIG_QT6C_LIBKSTANDARDACTIONS_H

#include <stdbool.h>
#include <stddef.h>

#include "../libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

/// https://api.kde.org/kstandardactions.html

/// [Upstream resources](https://api.kde.org/kstandardactions.html#_kgui_createInternal)
///
/// @param param1 enum KStandardActions__StandardAction
/// @param param2 QObject*
QAction* k_standardactions_kgui_create_internal(int32_t param1, void* param2);

/// [Upstream resources](https://api.kde.org/kstandardactions.html#name)
///
/// Caller is responsible for freeing the returned memory
///
/// @param param1 enum KStandardActions__StandardAction
const char* k_standardactions_name(int32_t param1);

/// [Upstream resources](https://api.kde.org/kstandardactions.html#actionIds)
///
///
/// @return libqt_list of enum KStandardActions__StandardAction
libqt_list /* of int32_t */ k_standardactions_action_ids();

/// [Upstream resources](https://api.kde.org/kstandardactions.html#shortcutForActionId)
///
/// @param param1 enum KStandardActions__StandardAction
///
/// @return enum KStandardShortcut__StandardShortcut
int32_t k_standardactions_shortcut_for_action_id(int32_t param1);

/// https://api.kde.org/kstandardactions.html#types

typedef enum {
    KSTANDARDACTIONS_STANDARDACTION_ACTIONNONE = 0,
    KSTANDARDACTIONS_STANDARDACTION_NEW = 1,
    KSTANDARDACTIONS_STANDARDACTION_OPEN = 2,
    KSTANDARDACTIONS_STANDARDACTION_OPENRECENT = 3,
    KSTANDARDACTIONS_STANDARDACTION_SAVE = 4,
    KSTANDARDACTIONS_STANDARDACTION_SAVEAS = 5,
    KSTANDARDACTIONS_STANDARDACTION_REVERT = 6,
    KSTANDARDACTIONS_STANDARDACTION_CLOSE = 7,
    KSTANDARDACTIONS_STANDARDACTION_PRINT = 8,
    KSTANDARDACTIONS_STANDARDACTION_PRINTPREVIEW = 9,
    KSTANDARDACTIONS_STANDARDACTION_MAIL = 10,
    KSTANDARDACTIONS_STANDARDACTION_QUIT = 11,
    KSTANDARDACTIONS_STANDARDACTION_UNDO = 12,
    KSTANDARDACTIONS_STANDARDACTION_REDO = 13,
    KSTANDARDACTIONS_STANDARDACTION_CUT = 14,
    KSTANDARDACTIONS_STANDARDACTION_COPY = 15,
    KSTANDARDACTIONS_STANDARDACTION_PASTE = 16,
    KSTANDARDACTIONS_STANDARDACTION_SELECTALL = 17,
    KSTANDARDACTIONS_STANDARDACTION_DESELECT = 18,
    KSTANDARDACTIONS_STANDARDACTION_FIND = 19,
    KSTANDARDACTIONS_STANDARDACTION_FINDNEXT = 20,
    KSTANDARDACTIONS_STANDARDACTION_FINDPREV = 21,
    KSTANDARDACTIONS_STANDARDACTION_REPLACE = 22,
    KSTANDARDACTIONS_STANDARDACTION_ACTUALSIZE = 23,
    KSTANDARDACTIONS_STANDARDACTION_FITTOPAGE = 24,
    KSTANDARDACTIONS_STANDARDACTION_FITTOWIDTH = 25,
    KSTANDARDACTIONS_STANDARDACTION_FITTOHEIGHT = 26,
    KSTANDARDACTIONS_STANDARDACTION_ZOOMIN = 27,
    KSTANDARDACTIONS_STANDARDACTION_ZOOMOUT = 28,
    KSTANDARDACTIONS_STANDARDACTION_ZOOM = 29,
    KSTANDARDACTIONS_STANDARDACTION_REDISPLAY = 30,
    KSTANDARDACTIONS_STANDARDACTION_UP = 31,
    KSTANDARDACTIONS_STANDARDACTION_BACK = 32,
    KSTANDARDACTIONS_STANDARDACTION_FORWARD = 33,
    KSTANDARDACTIONS_STANDARDACTION_HOME = 34,
    KSTANDARDACTIONS_STANDARDACTION_PRIOR = 35,
    KSTANDARDACTIONS_STANDARDACTION_NEXT = 36,
    KSTANDARDACTIONS_STANDARDACTION_GOTO = 37,
    KSTANDARDACTIONS_STANDARDACTION_GOTOPAGE = 38,
    KSTANDARDACTIONS_STANDARDACTION_GOTOLINE = 39,
    KSTANDARDACTIONS_STANDARDACTION_FIRSTPAGE = 40,
    KSTANDARDACTIONS_STANDARDACTION_LASTPAGE = 41,
    KSTANDARDACTIONS_STANDARDACTION_DOCUMENTBACK = 42,
    KSTANDARDACTIONS_STANDARDACTION_DOCUMENTFORWARD = 43,
    KSTANDARDACTIONS_STANDARDACTION_ADDBOOKMARK = 44,
    KSTANDARDACTIONS_STANDARDACTION_EDITBOOKMARKS = 45,
    KSTANDARDACTIONS_STANDARDACTION_SPELLING = 46,
    KSTANDARDACTIONS_STANDARDACTION_SHOWMENUBAR = 47,
    KSTANDARDACTIONS_STANDARDACTION_SHOWTOOLBAR = 48,
    KSTANDARDACTIONS_STANDARDACTION_SHOWSTATUSBAR = 49,
    KSTANDARDACTIONS_STANDARDACTION_KEYBINDINGS = 50,
    KSTANDARDACTIONS_STANDARDACTION_PREFERENCES = 51,
    KSTANDARDACTIONS_STANDARDACTION_CONFIGURETOOLBARS = 52,
    KSTANDARDACTIONS_STANDARDACTION_HELPCONTENTS = 53,
    KSTANDARDACTIONS_STANDARDACTION_WHATSTHIS = 54,
    KSTANDARDACTIONS_STANDARDACTION_REPORTBUG = 55,
    KSTANDARDACTIONS_STANDARDACTION_ABOUTAPP = 56,
    KSTANDARDACTIONS_STANDARDACTION_ABOUTKDE = 57,
    KSTANDARDACTIONS_STANDARDACTION_CONFIGURENOTIFICATIONS = 58,
    KSTANDARDACTIONS_STANDARDACTION_FULLSCREEN = 59,
    KSTANDARDACTIONS_STANDARDACTION_CLEAR = 60,
    KSTANDARDACTIONS_STANDARDACTION_SWITCHAPPLICATIONLANGUAGE = 61,
    KSTANDARDACTIONS_STANDARDACTION_DELETEFILE = 62,
    KSTANDARDACTIONS_STANDARDACTION_RENAMEFILE = 63,
    KSTANDARDACTIONS_STANDARDACTION_MOVETOTRASH = 64,
    KSTANDARDACTIONS_STANDARDACTION_DONATE = 65,
    KSTANDARDACTIONS_STANDARDACTION_HAMBURGERMENU = 66
} KStandardActions__StandardAction;

#endif
