#pragma once
#ifndef SRC_EXTRAS_KUNITCONVERSION_QT6C_LIBUNIT_H
#define SRC_EXTRAS_KUNITCONVERSION_QT6C_LIBUNIT_H

#include <stdbool.h>
#include <stddef.h>

#include "../libqttypedefs.h"
#include "../qtlibc.h"

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html)

/// k_unitconversion__unit_new constructs a new KUnitConversion::Unit object.
///
KUnitConversion__Unit* k_unitconversion__unit_new();

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html)

/// k_unitconversion__unit_new2 constructs a new KUnitConversion::Unit object.
///
/// @param other KUnitConversion__Unit*
///
KUnitConversion__Unit* k_unitconversion__unit_new2(void* other);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#operator-eq)
///
/// @param self KUnitConversion__Unit*
/// @param other KUnitConversion__Unit*
///
void k_unitconversion__unit_operator_assign(void* self, void* other);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#operator-eq-eq)
///
/// @param self KUnitConversion__Unit*
/// @param other KUnitConversion__Unit*
///
bool k_unitconversion__unit_operator_equal(void* self, void* other);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#operator-not-eq)
///
/// @param self KUnitConversion__Unit*
/// @param other KUnitConversion__Unit*
///
bool k_unitconversion__unit_operator_not_equal(void* self, void* other);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#isNull)
///
/// @param self KUnitConversion__Unit*
///
bool k_unitconversion__unit_is_null(void* self);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#isValid)
///
/// @param self KUnitConversion__Unit*
///
bool k_unitconversion__unit_is_valid(void* self);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#id)
///
/// @param self KUnitConversion__Unit*
///
/// @return enum KUnitConversion__UnitId
///
int32_t k_unitconversion__unit_id(void* self);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#categoryId)
///
/// @param self KUnitConversion__Unit*
///
/// @return enum KUnitConversion__CategoryId
///
int32_t k_unitconversion__unit_category_id(void* self);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#category)
///
/// @param self KUnitConversion__Unit*
///
KUnitConversion__UnitCategory* k_unitconversion__unit_category(void* self);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#description)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
///
const char* k_unitconversion__unit_description(void* self);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#symbol)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
///
const char* k_unitconversion__unit_symbol(void* self);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#toString)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
/// @param value double
///
const char* k_unitconversion__unit_to_string(void* self, double value);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#toSymbolString)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
/// @param value double
///
const char* k_unitconversion__unit_to_symbol_string(void* self, double value);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#toString)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
/// @param value double
/// @param fieldWidth int
///
const char* k_unitconversion__unit_to_string2(void* self, double value, int fieldWidth);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#toString)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
/// @param value double
/// @param fieldWidth int
/// @param format char
///
const char* k_unitconversion__unit_to_string3(void* self, double value, int fieldWidth, char format);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#toString)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
/// @param value double
/// @param fieldWidth int
/// @param format char
/// @param precision int
///
const char* k_unitconversion__unit_to_string4(void* self, double value, int fieldWidth, char format, int precision);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#toString)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
/// @param value double
/// @param fieldWidth int
/// @param format char
/// @param precision int
/// @param fillChar QChar*
///
const char* k_unitconversion__unit_to_string5(void* self, double value, int fieldWidth, char format, int precision, void* fillChar);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#toSymbolString)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
/// @param value double
/// @param fieldWidth int
///
const char* k_unitconversion__unit_to_symbol_string2(void* self, double value, int fieldWidth);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#toSymbolString)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
/// @param value double
/// @param fieldWidth int
/// @param format char
///
const char* k_unitconversion__unit_to_symbol_string3(void* self, double value, int fieldWidth, char format);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#toSymbolString)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
/// @param value double
/// @param fieldWidth int
/// @param format char
/// @param precision int
///
const char* k_unitconversion__unit_to_symbol_string4(void* self, double value, int fieldWidth, char format, int precision);

/// [Upstream resources](https://api.kde.org/kunitconversion-unit.html#toSymbolString)
///
/// @warning Caller is responsible for freeing the returned memory using `libqt_free()`
///
/// @param self KUnitConversion__Unit*
/// @param value double
/// @param fieldWidth int
/// @param format char
/// @param precision int
/// @param fillChar QChar*
///
const char* k_unitconversion__unit_to_symbol_string5(void* self, double value, int fieldWidth, char format, int precision, void* fillChar);

/// Delete this object from C++ memory.
///
/// @param self KUnitConversion__Unit*
///
void k_unitconversion__unit_delete(void* self);

/// [Upstream resources](https://api.kde.org/kunitconversion.html#public-types)

typedef enum {
    KUNITCONVERSION_CATEGORYID_INVALIDCATEGORY = -1,
    KUNITCONVERSION_CATEGORYID_LENGTHCATEGORY = 0,
    KUNITCONVERSION_CATEGORYID_AREACATEGORY = 1,
    KUNITCONVERSION_CATEGORYID_VOLUMECATEGORY = 2,
    KUNITCONVERSION_CATEGORYID_TEMPERATURECATEGORY = 3,
    KUNITCONVERSION_CATEGORYID_VELOCITYCATEGORY = 4,
    KUNITCONVERSION_CATEGORYID_MASSCATEGORY = 5,
    KUNITCONVERSION_CATEGORYID_PRESSURECATEGORY = 6,
    KUNITCONVERSION_CATEGORYID_ENERGYCATEGORY = 7,
    KUNITCONVERSION_CATEGORYID_CURRENCYCATEGORY = 8,
    KUNITCONVERSION_CATEGORYID_POWERCATEGORY = 9,
    KUNITCONVERSION_CATEGORYID_TIMECATEGORY = 10,
    KUNITCONVERSION_CATEGORYID_FUELEFFICIENCYCATEGORY = 11,
    KUNITCONVERSION_CATEGORYID_DENSITYCATEGORY = 12,
    KUNITCONVERSION_CATEGORYID_WEIGHTPERAREACATEGORY = 13,
    KUNITCONVERSION_CATEGORYID_ACCELERATIONCATEGORY = 14,
    KUNITCONVERSION_CATEGORYID_ANGLECATEGORY = 15,
    KUNITCONVERSION_CATEGORYID_FREQUENCYCATEGORY = 16,
    KUNITCONVERSION_CATEGORYID_FORCECATEGORY = 17,
    KUNITCONVERSION_CATEGORYID_THERMALCONDUCTIVITYCATEGORY = 18,
    KUNITCONVERSION_CATEGORYID_THERMALFLUXCATEGORY = 19,
    KUNITCONVERSION_CATEGORYID_THERMALGENERATIONCATEGORY = 20,
    KUNITCONVERSION_CATEGORYID_VOLTAGECATEGORY = 21,
    KUNITCONVERSION_CATEGORYID_ELECTRICALCURRENTCATEGORY = 22,
    KUNITCONVERSION_CATEGORYID_ELECTRICALRESISTANCECATEGORY = 23,
    KUNITCONVERSION_CATEGORYID_PERMEABILITYCATEGORY = 24,
    KUNITCONVERSION_CATEGORYID_BINARYDATACATEGORY = 25
} KUnitConversion__CategoryId;

/// [Upstream resources](https://api.kde.org/kunitconversion.html#public-types)

typedef enum {
    KUNITCONVERSION_UNITID_INVALIDUNIT = -1,
    KUNITCONVERSION_UNITID_NOUNIT = 0,
    KUNITCONVERSION_UNITID_PERCENT = 1,
    KUNITCONVERSION_UNITID_SQUAREYOTTAMETER = 1000,
    KUNITCONVERSION_UNITID_SQUAREZETTAMETER = 1001,
    KUNITCONVERSION_UNITID_SQUAREEXAMETER = 1002,
    KUNITCONVERSION_UNITID_SQUAREPETAMETER = 1003,
    KUNITCONVERSION_UNITID_SQUARETERAMETER = 1004,
    KUNITCONVERSION_UNITID_SQUAREGIGAMETER = 1005,
    KUNITCONVERSION_UNITID_SQUAREMEGAMETER = 1006,
    KUNITCONVERSION_UNITID_SQUAREKILOMETER = 1007,
    KUNITCONVERSION_UNITID_SQUAREHECTOMETER = 1008,
    KUNITCONVERSION_UNITID_SQUAREDECAMETER = 1009,
    KUNITCONVERSION_UNITID_SQUAREMETER = 1010,
    KUNITCONVERSION_UNITID_SQUAREDECIMETER = 1011,
    KUNITCONVERSION_UNITID_SQUARECENTIMETER = 1012,
    KUNITCONVERSION_UNITID_SQUAREMILLIMETER = 1013,
    KUNITCONVERSION_UNITID_SQUAREMICROMETER = 1014,
    KUNITCONVERSION_UNITID_SQUARENANOMETER = 1015,
    KUNITCONVERSION_UNITID_SQUAREPICOMETER = 1016,
    KUNITCONVERSION_UNITID_SQUAREFEMTOMETER = 1017,
    KUNITCONVERSION_UNITID_SQUAREATTOMETER = 1018,
    KUNITCONVERSION_UNITID_SQUAREZEPTOMETER = 1019,
    KUNITCONVERSION_UNITID_SQUAREYOCTOMETER = 1020,
    KUNITCONVERSION_UNITID_ACRE = 1021,
    KUNITCONVERSION_UNITID_SQUAREFOOT = 1022,
    KUNITCONVERSION_UNITID_SQUAREINCH = 1023,
    KUNITCONVERSION_UNITID_SQUAREMILE = 1024,
    KUNITCONVERSION_UNITID_YOTTAMETER = 2000,
    KUNITCONVERSION_UNITID_ZETTAMETER = 2001,
    KUNITCONVERSION_UNITID_EXAMETER = 2002,
    KUNITCONVERSION_UNITID_PETAMETER = 2003,
    KUNITCONVERSION_UNITID_TERAMETER = 2004,
    KUNITCONVERSION_UNITID_GIGAMETER = 2005,
    KUNITCONVERSION_UNITID_MEGAMETER = 2006,
    KUNITCONVERSION_UNITID_KILOMETER = 2007,
    KUNITCONVERSION_UNITID_HECTOMETER = 2008,
    KUNITCONVERSION_UNITID_DECAMETER = 2009,
    KUNITCONVERSION_UNITID_METER = 2010,
    KUNITCONVERSION_UNITID_DECIMETER = 2011,
    KUNITCONVERSION_UNITID_CENTIMETER = 2012,
    KUNITCONVERSION_UNITID_MILLIMETER = 2013,
    KUNITCONVERSION_UNITID_MICROMETER = 2014,
    KUNITCONVERSION_UNITID_NANOMETER = 2015,
    KUNITCONVERSION_UNITID_PICOMETER = 2016,
    KUNITCONVERSION_UNITID_FEMTOMETER = 2017,
    KUNITCONVERSION_UNITID_ATTOMETER = 2018,
    KUNITCONVERSION_UNITID_ZEPTOMETER = 2019,
    KUNITCONVERSION_UNITID_YOCTOMETER = 2020,
    KUNITCONVERSION_UNITID_INCH = 2021,
    KUNITCONVERSION_UNITID_FOOT = 2022,
    KUNITCONVERSION_UNITID_YARD = 2023,
    KUNITCONVERSION_UNITID_MILE = 2024,
    KUNITCONVERSION_UNITID_NAUTICALMILE = 2025,
    KUNITCONVERSION_UNITID_LIGHTYEAR = 2026,
    KUNITCONVERSION_UNITID_PARSEC = 2027,
    KUNITCONVERSION_UNITID_ASTRONOMICALUNIT = 2028,
    KUNITCONVERSION_UNITID_THOU = 2029,
    KUNITCONVERSION_UNITID_ANGSTROM = 2030,
    KUNITCONVERSION_UNITID_RACKUNIT = 2031,
    KUNITCONVERSION_UNITID_CUBICYOTTAMETER = 3000,
    KUNITCONVERSION_UNITID_CUBICZETTAMETER = 3001,
    KUNITCONVERSION_UNITID_CUBICEXAMETER = 3002,
    KUNITCONVERSION_UNITID_CUBICPETAMETER = 3003,
    KUNITCONVERSION_UNITID_CUBICTERAMETER = 3004,
    KUNITCONVERSION_UNITID_CUBICGIGAMETER = 3005,
    KUNITCONVERSION_UNITID_CUBICMEGAMETER = 3006,
    KUNITCONVERSION_UNITID_CUBICKILOMETER = 3007,
    KUNITCONVERSION_UNITID_CUBICHECTOMETER = 3008,
    KUNITCONVERSION_UNITID_CUBICDECAMETER = 3009,
    KUNITCONVERSION_UNITID_CUBICMETER = 3010,
    KUNITCONVERSION_UNITID_CUBICDECIMETER = 3011,
    KUNITCONVERSION_UNITID_CUBICCENTIMETER = 3012,
    KUNITCONVERSION_UNITID_CUBICMILLIMETER = 3013,
    KUNITCONVERSION_UNITID_CUBICMICROMETER = 3014,
    KUNITCONVERSION_UNITID_CUBICNANOMETER = 3015,
    KUNITCONVERSION_UNITID_CUBICPICOMETER = 3016,
    KUNITCONVERSION_UNITID_CUBICFEMTOMETER = 3017,
    KUNITCONVERSION_UNITID_CUBICATTOMETER = 3018,
    KUNITCONVERSION_UNITID_CUBICZEPTOMETER = 3019,
    KUNITCONVERSION_UNITID_CUBICYOCTOMETER = 3020,
    KUNITCONVERSION_UNITID_YOTTALITER = 3021,
    KUNITCONVERSION_UNITID_ZETTALITER = 3022,
    KUNITCONVERSION_UNITID_EXALITER = 3023,
    KUNITCONVERSION_UNITID_PETALITER = 3024,
    KUNITCONVERSION_UNITID_TERALITER = 3025,
    KUNITCONVERSION_UNITID_GIGALITER = 3026,
    KUNITCONVERSION_UNITID_MEGALITER = 3027,
    KUNITCONVERSION_UNITID_KILOLITER = 3028,
    KUNITCONVERSION_UNITID_HECTOLITER = 3029,
    KUNITCONVERSION_UNITID_DECALITER = 3030,
    KUNITCONVERSION_UNITID_LITER = 3031,
    KUNITCONVERSION_UNITID_DECILITER = 3032,
    KUNITCONVERSION_UNITID_CENTILITER = 3033,
    KUNITCONVERSION_UNITID_MILLILITER = 3034,
    KUNITCONVERSION_UNITID_MICROLITER = 3035,
    KUNITCONVERSION_UNITID_NANOLITER = 3036,
    KUNITCONVERSION_UNITID_PICOLITER = 3037,
    KUNITCONVERSION_UNITID_FEMTOLITER = 3038,
    KUNITCONVERSION_UNITID_ATTOLITER = 3039,
    KUNITCONVERSION_UNITID_ZEPTOLITER = 3040,
    KUNITCONVERSION_UNITID_YOCTOLITER = 3041,
    KUNITCONVERSION_UNITID_CUBICFOOT = 3042,
    KUNITCONVERSION_UNITID_CUBICINCH = 3043,
    KUNITCONVERSION_UNITID_CUBICMILE = 3044,
    KUNITCONVERSION_UNITID_FLUIDOUNCE = 3045,
    KUNITCONVERSION_UNITID_CUP = 3046,
    KUNITCONVERSION_UNITID_TEASPOON = 3047,
    KUNITCONVERSION_UNITID_TABLESPOON = 3048,
    KUNITCONVERSION_UNITID_GALLONUS = 3049,
    KUNITCONVERSION_UNITID_PINTIMPERIAL = 3050,
    KUNITCONVERSION_UNITID_OILBARREL = 3051,
    KUNITCONVERSION_UNITID_GALLONIMPERIAL = 3052,
    KUNITCONVERSION_UNITID_PINTUS = 3053,
    KUNITCONVERSION_UNITID_YOTTAGRAM = 4000,
    KUNITCONVERSION_UNITID_ZETTAGRAM = 4001,
    KUNITCONVERSION_UNITID_EXAGRAM = 4002,
    KUNITCONVERSION_UNITID_PETAGRAM = 4003,
    KUNITCONVERSION_UNITID_TERAGRAM = 4004,
    KUNITCONVERSION_UNITID_GIGAGRAM = 4005,
    KUNITCONVERSION_UNITID_MEGAGRAM = 4006,
    KUNITCONVERSION_UNITID_KILOGRAM = 4007,
    KUNITCONVERSION_UNITID_HECTOGRAM = 4008,
    KUNITCONVERSION_UNITID_DECAGRAM = 4009,
    KUNITCONVERSION_UNITID_GRAM = 4010,
    KUNITCONVERSION_UNITID_DECIGRAM = 4011,
    KUNITCONVERSION_UNITID_CENTIGRAM = 4012,
    KUNITCONVERSION_UNITID_MILLIGRAM = 4013,
    KUNITCONVERSION_UNITID_MICROGRAM = 4014,
    KUNITCONVERSION_UNITID_NANOGRAM = 4015,
    KUNITCONVERSION_UNITID_PICOGRAM = 4016,
    KUNITCONVERSION_UNITID_FEMTOGRAM = 4017,
    KUNITCONVERSION_UNITID_ATTOGRAM = 4018,
    KUNITCONVERSION_UNITID_ZEPTOGRAM = 4019,
    KUNITCONVERSION_UNITID_YOCTOGRAM = 4020,
    KUNITCONVERSION_UNITID_TON = 4021,
    KUNITCONVERSION_UNITID_CARAT = 4022,
    KUNITCONVERSION_UNITID_POUND = 4023,
    KUNITCONVERSION_UNITID_OUNCE = 4024,
    KUNITCONVERSION_UNITID_TROYOUNCE = 4025,
    KUNITCONVERSION_UNITID_MASSNEWTON = 4026,
    KUNITCONVERSION_UNITID_KILONEWTON = 4027,
    KUNITCONVERSION_UNITID_STONE = 4028,
    KUNITCONVERSION_UNITID_YOTTAPASCAL = 5000,
    KUNITCONVERSION_UNITID_ZETTAPASCAL = 5001,
    KUNITCONVERSION_UNITID_EXAPASCAL = 5002,
    KUNITCONVERSION_UNITID_PETAPASCAL = 5003,
    KUNITCONVERSION_UNITID_TERAPASCAL = 5004,
    KUNITCONVERSION_UNITID_GIGAPASCAL = 5005,
    KUNITCONVERSION_UNITID_MEGAPASCAL = 5006,
    KUNITCONVERSION_UNITID_KILOPASCAL = 5007,
    KUNITCONVERSION_UNITID_HECTOPASCAL = 5008,
    KUNITCONVERSION_UNITID_DECAPASCAL = 5009,
    KUNITCONVERSION_UNITID_PASCAL = 5010,
    KUNITCONVERSION_UNITID_DECIPASCAL = 5011,
    KUNITCONVERSION_UNITID_CENTIPASCAL = 5012,
    KUNITCONVERSION_UNITID_MILLIPASCAL = 5013,
    KUNITCONVERSION_UNITID_MICROPASCAL = 5014,
    KUNITCONVERSION_UNITID_NANOPASCAL = 5015,
    KUNITCONVERSION_UNITID_PICOPASCAL = 5016,
    KUNITCONVERSION_UNITID_FEMTOPASCAL = 5017,
    KUNITCONVERSION_UNITID_ATTOPASCAL = 5018,
    KUNITCONVERSION_UNITID_ZEPTOPASCAL = 5019,
    KUNITCONVERSION_UNITID_YOCTOPASCAL = 5020,
    KUNITCONVERSION_UNITID_BAR = 5021,
    KUNITCONVERSION_UNITID_MILLIBAR = 5022,
    KUNITCONVERSION_UNITID_DECIBAR = 5023,
    KUNITCONVERSION_UNITID_TORR = 5024,
    KUNITCONVERSION_UNITID_TECHNICALATMOSPHERE = 5025,
    KUNITCONVERSION_UNITID_ATMOSPHERE = 5026,
    KUNITCONVERSION_UNITID_POUNDFORCEPERSQUAREINCH = 5027,
    KUNITCONVERSION_UNITID_INCHESOFMERCURY = 5028,
    KUNITCONVERSION_UNITID_MILLIMETERSOFMERCURY = 5029,
    KUNITCONVERSION_UNITID_KELVIN = 6000,
    KUNITCONVERSION_UNITID_CELSIUS = 6001,
    KUNITCONVERSION_UNITID_FAHRENHEIT = 6002,
    KUNITCONVERSION_UNITID_RANKINE = 6003,
    KUNITCONVERSION_UNITID_DELISLE = 6004,
    KUNITCONVERSION_UNITID_TEMPERATURENEWTON = 6005,
    KUNITCONVERSION_UNITID_REAUMUR = 6006,
    KUNITCONVERSION_UNITID_ROMER = 6007,
    KUNITCONVERSION_UNITID_YOTTAJOULE = 7000,
    KUNITCONVERSION_UNITID_ZETTAJOULE = 7001,
    KUNITCONVERSION_UNITID_EXAJOULE = 7002,
    KUNITCONVERSION_UNITID_PETAJOULE = 7003,
    KUNITCONVERSION_UNITID_TERAJOULE = 7004,
    KUNITCONVERSION_UNITID_GIGAJOULE = 7005,
    KUNITCONVERSION_UNITID_MEGAJOULE = 7006,
    KUNITCONVERSION_UNITID_KILOJOULE = 7007,
    KUNITCONVERSION_UNITID_HECTOJOULE = 7008,
    KUNITCONVERSION_UNITID_DECAJOULE = 7009,
    KUNITCONVERSION_UNITID_JOULE = 7010,
    KUNITCONVERSION_UNITID_DECIJOULE = 7011,
    KUNITCONVERSION_UNITID_CENTIJOULE = 7012,
    KUNITCONVERSION_UNITID_MILLIJOULE = 7013,
    KUNITCONVERSION_UNITID_MICROJOULE = 7014,
    KUNITCONVERSION_UNITID_NANOJOULE = 7015,
    KUNITCONVERSION_UNITID_PICOJOULE = 7016,
    KUNITCONVERSION_UNITID_FEMTOJOULE = 7017,
    KUNITCONVERSION_UNITID_ATTOJOULE = 7018,
    KUNITCONVERSION_UNITID_ZEPTOJOULE = 7019,
    KUNITCONVERSION_UNITID_YOCTOJOULE = 7020,
    KUNITCONVERSION_UNITID_GUIDELINEDAILYAMOUNT = 7021,
    KUNITCONVERSION_UNITID_ELECTRONVOLT = 7022,
    KUNITCONVERSION_UNITID_RYDBERG = 7023,
    KUNITCONVERSION_UNITID_KILOCALORIE = 7024,
    KUNITCONVERSION_UNITID_PHOTONWAVELENGTH = 7025,
    KUNITCONVERSION_UNITID_KILOJOULEPERMOLE = 7026,
    KUNITCONVERSION_UNITID_JOULEPERMOLE = 7027,
    KUNITCONVERSION_UNITID_BTU = 7028,
    KUNITCONVERSION_UNITID_ERG = 7029,
    KUNITCONVERSION_UNITID_EUR = 8000,
    KUNITCONVERSION_UNITID_ATS = 8001,
    KUNITCONVERSION_UNITID_BEF = 8002,
    KUNITCONVERSION_UNITID_NLG = 8003,
    KUNITCONVERSION_UNITID_FIM = 8004,
    KUNITCONVERSION_UNITID_FRF = 8005,
    KUNITCONVERSION_UNITID_DEM = 8006,
    KUNITCONVERSION_UNITID_IEP = 8007,
    KUNITCONVERSION_UNITID_ITL = 8008,
    KUNITCONVERSION_UNITID_LUF = 8009,
    KUNITCONVERSION_UNITID_PTE = 8010,
    KUNITCONVERSION_UNITID_ESP = 8011,
    KUNITCONVERSION_UNITID_GRD = 8012,
    KUNITCONVERSION_UNITID_SIT = 8013,
    KUNITCONVERSION_UNITID_CYP = 8014,
    KUNITCONVERSION_UNITID_MTL = 8015,
    KUNITCONVERSION_UNITID_SKK = 8016,
    KUNITCONVERSION_UNITID_USD = 8017,
    KUNITCONVERSION_UNITID_JPY = 8018,
    KUNITCONVERSION_UNITID_BGN = 8019,
    KUNITCONVERSION_UNITID_CZK = 8020,
    KUNITCONVERSION_UNITID_DKK = 8021,
    KUNITCONVERSION_UNITID_EEK = 8022,
    KUNITCONVERSION_UNITID_GBP = 8023,
    KUNITCONVERSION_UNITID_HUF = 8024,
    KUNITCONVERSION_UNITID_LTL = 8025,
    KUNITCONVERSION_UNITID_LVL = 8026,
    KUNITCONVERSION_UNITID_PLN = 8027,
    KUNITCONVERSION_UNITID_RON = 8028,
    KUNITCONVERSION_UNITID_SEK = 8029,
    KUNITCONVERSION_UNITID_CHF = 8030,
    KUNITCONVERSION_UNITID_NOK = 8031,
    KUNITCONVERSION_UNITID_HRK = 8032,
    KUNITCONVERSION_UNITID_RUB = 8033,
    KUNITCONVERSION_UNITID_TRY = 8034,
    KUNITCONVERSION_UNITID_AUD = 8035,
    KUNITCONVERSION_UNITID_BRL = 8036,
    KUNITCONVERSION_UNITID_CAD = 8037,
    KUNITCONVERSION_UNITID_CNY = 8038,
    KUNITCONVERSION_UNITID_HKD = 8039,
    KUNITCONVERSION_UNITID_IDR = 8040,
    KUNITCONVERSION_UNITID_INR = 8041,
    KUNITCONVERSION_UNITID_KRW = 8042,
    KUNITCONVERSION_UNITID_MXN = 8043,
    KUNITCONVERSION_UNITID_MYR = 8044,
    KUNITCONVERSION_UNITID_NZD = 8045,
    KUNITCONVERSION_UNITID_PHP = 8046,
    KUNITCONVERSION_UNITID_SGD = 8047,
    KUNITCONVERSION_UNITID_THB = 8048,
    KUNITCONVERSION_UNITID_ZAR = 8049,
    KUNITCONVERSION_UNITID_ILS = 8050,
    KUNITCONVERSION_UNITID_ISK = 8051,
    KUNITCONVERSION_UNITID_XPF = 8052,
    KUNITCONVERSION_UNITID_METERPERSECOND = 9000,
    KUNITCONVERSION_UNITID_KILOMETERPERHOUR = 9001,
    KUNITCONVERSION_UNITID_MILEPERHOUR = 9002,
    KUNITCONVERSION_UNITID_FOOTPERSECOND = 9003,
    KUNITCONVERSION_UNITID_INCHPERSECOND = 9004,
    KUNITCONVERSION_UNITID_KNOT = 9005,
    KUNITCONVERSION_UNITID_MACH = 9006,
    KUNITCONVERSION_UNITID_SPEEDOFLIGHT = 9007,
    KUNITCONVERSION_UNITID_BEAUFORT = 9008,
    KUNITCONVERSION_UNITID_YOTTAWATT = 10000,
    KUNITCONVERSION_UNITID_ZETTAWATT = 10001,
    KUNITCONVERSION_UNITID_EXAWATT = 10002,
    KUNITCONVERSION_UNITID_PETAWATT = 10003,
    KUNITCONVERSION_UNITID_TERAWATT = 10004,
    KUNITCONVERSION_UNITID_GIGAWATT = 10005,
    KUNITCONVERSION_UNITID_MEGAWATT = 10006,
    KUNITCONVERSION_UNITID_KILOWATT = 10007,
    KUNITCONVERSION_UNITID_HECTOWATT = 10008,
    KUNITCONVERSION_UNITID_DECAWATT = 10009,
    KUNITCONVERSION_UNITID_WATT = 10010,
    KUNITCONVERSION_UNITID_DECIWATT = 10011,
    KUNITCONVERSION_UNITID_CENTIWATT = 10012,
    KUNITCONVERSION_UNITID_MILLIWATT = 10013,
    KUNITCONVERSION_UNITID_MICROWATT = 10014,
    KUNITCONVERSION_UNITID_NANOWATT = 10015,
    KUNITCONVERSION_UNITID_PICOWATT = 10016,
    KUNITCONVERSION_UNITID_FEMTOWATT = 10017,
    KUNITCONVERSION_UNITID_ATTOWATT = 10018,
    KUNITCONVERSION_UNITID_ZEPTOWATT = 10019,
    KUNITCONVERSION_UNITID_YOCTOWATT = 10020,
    KUNITCONVERSION_UNITID_HORSEPOWER = 10021,
    KUNITCONVERSION_UNITID_DECIBELKILOWATT = 10022,
    KUNITCONVERSION_UNITID_DECIBELWATT = 10023,
    KUNITCONVERSION_UNITID_DECIBELMILLIWATT = 10024,
    KUNITCONVERSION_UNITID_DECIBELMICROWATT = 10025,
    KUNITCONVERSION_UNITID_YOTTASECOND = 11000,
    KUNITCONVERSION_UNITID_ZETTASECOND = 11001,
    KUNITCONVERSION_UNITID_EXASECOND = 11002,
    KUNITCONVERSION_UNITID_PETASECOND = 11003,
    KUNITCONVERSION_UNITID_TERASECOND = 11004,
    KUNITCONVERSION_UNITID_GIGASECOND = 11005,
    KUNITCONVERSION_UNITID_MEGASECOND = 11006,
    KUNITCONVERSION_UNITID_KILOSECOND = 11007,
    KUNITCONVERSION_UNITID_HECTOSECOND = 11008,
    KUNITCONVERSION_UNITID_DECASECOND = 11009,
    KUNITCONVERSION_UNITID_SECOND = 11010,
    KUNITCONVERSION_UNITID_DECISECOND = 11011,
    KUNITCONVERSION_UNITID_CENTISECOND = 11012,
    KUNITCONVERSION_UNITID_MILLISECOND = 11013,
    KUNITCONVERSION_UNITID_MICROSECOND = 11014,
    KUNITCONVERSION_UNITID_NANOSECOND = 11015,
    KUNITCONVERSION_UNITID_PICOSECOND = 11016,
    KUNITCONVERSION_UNITID_FEMTOSECOND = 11017,
    KUNITCONVERSION_UNITID_ATTOSECOND = 11018,
    KUNITCONVERSION_UNITID_ZEPTOSECOND = 11019,
    KUNITCONVERSION_UNITID_YOCTOSECOND = 11020,
    KUNITCONVERSION_UNITID_MINUTE = 11021,
    KUNITCONVERSION_UNITID_HOUR = 11022,
    KUNITCONVERSION_UNITID_DAY = 11023,
    KUNITCONVERSION_UNITID_WEEK = 11024,
    KUNITCONVERSION_UNITID_JULIANYEAR = 11025,
    KUNITCONVERSION_UNITID_LEAPYEAR = 11026,
    KUNITCONVERSION_UNITID_YEAR = 11027,
    KUNITCONVERSION_UNITID_LITERSPER100KILOMETERS = 12000,
    KUNITCONVERSION_UNITID_MILEPERUSGALLON = 12001,
    KUNITCONVERSION_UNITID_MILEPERIMPERIALGALLON = 12002,
    KUNITCONVERSION_UNITID_KILOMETREPERLITRE = 12003,
    KUNITCONVERSION_UNITID_YOTTAKILOGRAMSPERCUBICMETER = 13000,
    KUNITCONVERSION_UNITID_ZETTAKILOGRAMPERCUBICMETER = 13001,
    KUNITCONVERSION_UNITID_EXAKILOGRAMPERCUBICMETER = 13002,
    KUNITCONVERSION_UNITID_PETAKILOGRAMPERCUBICMETER = 13003,
    KUNITCONVERSION_UNITID_TERAKILOGRAMPERCUBICMETER = 13004,
    KUNITCONVERSION_UNITID_GIGAKILOGRAMPERCUBICMETER = 13005,
    KUNITCONVERSION_UNITID_MEGAKILOGRAMPERCUBICMETER = 13006,
    KUNITCONVERSION_UNITID_KILOKILOGRAMPERCUBICMETER = 13007,
    KUNITCONVERSION_UNITID_HECTOKILOGRAMSPERCUBICMETER = 13008,
    KUNITCONVERSION_UNITID_DECAKILOGRAMSPERCUBICMETER = 13009,
    KUNITCONVERSION_UNITID_KILOGRAMSPERCUBICMETER = 13010,
    KUNITCONVERSION_UNITID_DECIKILOGRAMSPERCUBICMETER = 13011,
    KUNITCONVERSION_UNITID_CENTIKILOGRAMSPERCUBICMETER = 13012,
    KUNITCONVERSION_UNITID_MILLIKILOGRAMSPERCUBICMETER = 13013,
    KUNITCONVERSION_UNITID_MICROKILOGRAMSPERCUBICMETER = 13014,
    KUNITCONVERSION_UNITID_NANOKILOGRAMSPERCUBICMETER = 13015,
    KUNITCONVERSION_UNITID_PICOKILOGRAMSPERCUBICMETER = 13016,
    KUNITCONVERSION_UNITID_FEMTOKILOGRAMSPERCUBICMETER = 13017,
    KUNITCONVERSION_UNITID_ATTOKILOGRAMSPERCUBICMETER = 13018,
    KUNITCONVERSION_UNITID_ZEPTOKILOGRAMSPERCUBICMETER = 13019,
    KUNITCONVERSION_UNITID_YOCTOKILOGRAMSPERCUBICMETER = 13020,
    KUNITCONVERSION_UNITID_KILOGRAMPERLITER = 13021,
    KUNITCONVERSION_UNITID_GRAMPERLITER = 13022,
    KUNITCONVERSION_UNITID_GRAMPERMILLILITER = 13023,
    KUNITCONVERSION_UNITID_OUNCEPERCUBICINCH = 13024,
    KUNITCONVERSION_UNITID_OUNCEPERCUBICFOOT = 13025,
    KUNITCONVERSION_UNITID_OUNCEPERCUBICYARD = 13026,
    KUNITCONVERSION_UNITID_POUNDPERCUBICINCH = 13027,
    KUNITCONVERSION_UNITID_POUNDPERCUBICFOOT = 13028,
    KUNITCONVERSION_UNITID_POUNDPERCUBICYARD = 13029,
    KUNITCONVERSION_UNITID_GRAMSPERSQUAREMETER = 13030,
    KUNITCONVERSION_UNITID_OUNCESPERSQUAREYARD = 13031,
    KUNITCONVERSION_UNITID_METRESPERSECONDSQUARED = 14000,
    KUNITCONVERSION_UNITID_FEETPERSECONDSQUARED = 14001,
    KUNITCONVERSION_UNITID_STANDARDGRAVITY = 14002,
    KUNITCONVERSION_UNITID_YOTTANEWTON = 15000,
    KUNITCONVERSION_UNITID_ZETTANEWTON = 15001,
    KUNITCONVERSION_UNITID_EXANEWTON = 15002,
    KUNITCONVERSION_UNITID_PETANEWTON = 15003,
    KUNITCONVERSION_UNITID_TERANEWTON = 15004,
    KUNITCONVERSION_UNITID_GIGANEWTON = 15005,
    KUNITCONVERSION_UNITID_MEGANEWTON = 15006,
    KUNITCONVERSION_UNITID_KILONEWTONFORCE = 15007,
    KUNITCONVERSION_UNITID_HECTONEWTON = 15008,
    KUNITCONVERSION_UNITID_DECANEWTON = 15009,
    KUNITCONVERSION_UNITID_NEWTON = 15010,
    KUNITCONVERSION_UNITID_DECINEWTON = 15011,
    KUNITCONVERSION_UNITID_CENTINEWTON = 15012,
    KUNITCONVERSION_UNITID_MILLINEWTON = 15013,
    KUNITCONVERSION_UNITID_MICRONEWTON = 15014,
    KUNITCONVERSION_UNITID_NANONEWTON = 15015,
    KUNITCONVERSION_UNITID_PICONEWTON = 15016,
    KUNITCONVERSION_UNITID_FEMTONEWTON = 15017,
    KUNITCONVERSION_UNITID_ATTONEWTON = 15018,
    KUNITCONVERSION_UNITID_ZEPTONEWTON = 15019,
    KUNITCONVERSION_UNITID_YOCTONEWTON = 15020,
    KUNITCONVERSION_UNITID_DYNE = 15021,
    KUNITCONVERSION_UNITID_KILOPOND = 15022,
    KUNITCONVERSION_UNITID_POUNDFORCE = 15023,
    KUNITCONVERSION_UNITID_POUNDAL = 15024,
    KUNITCONVERSION_UNITID_DEGREE = 16000,
    KUNITCONVERSION_UNITID_RADIAN = 16001,
    KUNITCONVERSION_UNITID_GRADIAN = 16002,
    KUNITCONVERSION_UNITID_ARCMINUTE = 16003,
    KUNITCONVERSION_UNITID_ARCSECOND = 16004,
    KUNITCONVERSION_UNITID_YOTTAHERTZ = 17000,
    KUNITCONVERSION_UNITID_ZETTAHERTZ = 17001,
    KUNITCONVERSION_UNITID_EXAHERTZ = 17002,
    KUNITCONVERSION_UNITID_PETAHERTZ = 17003,
    KUNITCONVERSION_UNITID_TERAHERTZ = 17004,
    KUNITCONVERSION_UNITID_GIGAHERTZ = 17005,
    KUNITCONVERSION_UNITID_MEGAHERTZ = 17006,
    KUNITCONVERSION_UNITID_KILOHERTZ = 17007,
    KUNITCONVERSION_UNITID_HECTOHERTZ = 17008,
    KUNITCONVERSION_UNITID_DECAHERTZ = 17009,
    KUNITCONVERSION_UNITID_HERTZ = 17010,
    KUNITCONVERSION_UNITID_DECIHERTZ = 17011,
    KUNITCONVERSION_UNITID_CENTIHERTZ = 17012,
    KUNITCONVERSION_UNITID_MILLIHERTZ = 17013,
    KUNITCONVERSION_UNITID_MICROHERTZ = 17014,
    KUNITCONVERSION_UNITID_NANOHERTZ = 17015,
    KUNITCONVERSION_UNITID_PICOHERTZ = 17016,
    KUNITCONVERSION_UNITID_FEMTOHERTZ = 17017,
    KUNITCONVERSION_UNITID_ATTOHERTZ = 17018,
    KUNITCONVERSION_UNITID_ZEPTOHERTZ = 17019,
    KUNITCONVERSION_UNITID_YOCTOHERTZ = 17020,
    KUNITCONVERSION_UNITID_RPM = 17021,
    KUNITCONVERSION_UNITID_WATTPERMETERKELVIN = 18000,
    KUNITCONVERSION_UNITID_BTUPERFOOTHOURFAHRENHEIT = 18001,
    KUNITCONVERSION_UNITID_BTUPERSQUAREFOOTHOURFAHRENHEITPERINCH = 18002,
    KUNITCONVERSION_UNITID_WATTPERSQUAREMETER = 19000,
    KUNITCONVERSION_UNITID_BTUPERHOURPERSQUAREFOOT = 19001,
    KUNITCONVERSION_UNITID_WATTPERCUBICMETER = 20000,
    KUNITCONVERSION_UNITID_BTUPERHOURPERCUBICFOOT = 20001,
    KUNITCONVERSION_UNITID_YOTTAVOLTS = 30000,
    KUNITCONVERSION_UNITID_ZETTAVOLTS = 30001,
    KUNITCONVERSION_UNITID_EXAVOLTS = 30002,
    KUNITCONVERSION_UNITID_PETAVOLTS = 30003,
    KUNITCONVERSION_UNITID_TERAVOLTS = 30004,
    KUNITCONVERSION_UNITID_GIGAVOLTS = 30005,
    KUNITCONVERSION_UNITID_MEGAVOLTS = 30006,
    KUNITCONVERSION_UNITID_KILOVOLTS = 30007,
    KUNITCONVERSION_UNITID_HECTOVOLTS = 30008,
    KUNITCONVERSION_UNITID_DECAVOLTS = 30009,
    KUNITCONVERSION_UNITID_VOLTS = 30010,
    KUNITCONVERSION_UNITID_DECIVOLTS = 30011,
    KUNITCONVERSION_UNITID_CENTIVOLTS = 30012,
    KUNITCONVERSION_UNITID_MILLIVOLTS = 30013,
    KUNITCONVERSION_UNITID_MICROVOLTS = 30014,
    KUNITCONVERSION_UNITID_NANOVOLTS = 30015,
    KUNITCONVERSION_UNITID_PICOVOLTS = 30016,
    KUNITCONVERSION_UNITID_FEMTOVOLTS = 30017,
    KUNITCONVERSION_UNITID_ATTOVOLTS = 30018,
    KUNITCONVERSION_UNITID_ZEPTOVOLTS = 30019,
    KUNITCONVERSION_UNITID_YOCTOVOLTS = 30020,
    KUNITCONVERSION_UNITID_STATVOLTS = 30021,
    KUNITCONVERSION_UNITID_YOTTAAMPERE = 31000,
    KUNITCONVERSION_UNITID_ZETTAAMPERE = 31001,
    KUNITCONVERSION_UNITID_EXAAMPERE = 31002,
    KUNITCONVERSION_UNITID_PETAAMPERE = 31003,
    KUNITCONVERSION_UNITID_TERAAMPERE = 31004,
    KUNITCONVERSION_UNITID_GIGAAMPERE = 31005,
    KUNITCONVERSION_UNITID_MEGAAMPERE = 31006,
    KUNITCONVERSION_UNITID_KILOAMPERE = 31007,
    KUNITCONVERSION_UNITID_HECTOAMPERE = 31008,
    KUNITCONVERSION_UNITID_DECAAMPERE = 31009,
    KUNITCONVERSION_UNITID_AMPERE = 31010,
    KUNITCONVERSION_UNITID_DECIAMPERE = 31011,
    KUNITCONVERSION_UNITID_CENTIAMPERE = 31012,
    KUNITCONVERSION_UNITID_MILLIAMPERE = 31013,
    KUNITCONVERSION_UNITID_MICROAMPERE = 31014,
    KUNITCONVERSION_UNITID_NANOAMPERE = 31015,
    KUNITCONVERSION_UNITID_PICOAMPERE = 31016,
    KUNITCONVERSION_UNITID_FEMTOAMPERE = 31017,
    KUNITCONVERSION_UNITID_ATTOAMPERE = 31018,
    KUNITCONVERSION_UNITID_ZEPTOAMPERE = 31019,
    KUNITCONVERSION_UNITID_YOCTOAMPERE = 31020,
    KUNITCONVERSION_UNITID_YOTTAOHMS = 32000,
    KUNITCONVERSION_UNITID_ZETTAOHMS = 32001,
    KUNITCONVERSION_UNITID_EXAOHMS = 32002,
    KUNITCONVERSION_UNITID_PETAOHMS = 32003,
    KUNITCONVERSION_UNITID_TERAOHMS = 32004,
    KUNITCONVERSION_UNITID_GIGAOHMS = 32005,
    KUNITCONVERSION_UNITID_MEGAOHMS = 32006,
    KUNITCONVERSION_UNITID_KILOOHMS = 32007,
    KUNITCONVERSION_UNITID_HECTOOHMS = 32008,
    KUNITCONVERSION_UNITID_DECAOHMS = 32009,
    KUNITCONVERSION_UNITID_OHMS = 32010,
    KUNITCONVERSION_UNITID_DECIOHMS = 32011,
    KUNITCONVERSION_UNITID_CENTIOHMS = 32012,
    KUNITCONVERSION_UNITID_MILLIOHMS = 32013,
    KUNITCONVERSION_UNITID_MICROOHMS = 32014,
    KUNITCONVERSION_UNITID_NANOOHMS = 32015,
    KUNITCONVERSION_UNITID_PICOOHMS = 32016,
    KUNITCONVERSION_UNITID_FEMTOOHMS = 32017,
    KUNITCONVERSION_UNITID_ATTOOHMS = 32018,
    KUNITCONVERSION_UNITID_ZEPTOOHMS = 32019,
    KUNITCONVERSION_UNITID_YOCTOOHMS = 32020,
    KUNITCONVERSION_UNITID_DARCY = 33000,
    KUNITCONVERSION_UNITID_MILIDARCY = 33001,
    KUNITCONVERSION_UNITID_PERMEABILITYSQUAREMICROMETER = 33002,
    KUNITCONVERSION_UNITID_YOBIBYTE = 34000,
    KUNITCONVERSION_UNITID_YOBIBIT = 34001,
    KUNITCONVERSION_UNITID_YOTTABYTE = 34002,
    KUNITCONVERSION_UNITID_YOTTABIT = 34003,
    KUNITCONVERSION_UNITID_ZEBIBYTE = 34004,
    KUNITCONVERSION_UNITID_ZEBIBIT = 34005,
    KUNITCONVERSION_UNITID_ZETTABYTE = 34006,
    KUNITCONVERSION_UNITID_ZETTABIT = 34007,
    KUNITCONVERSION_UNITID_EXBIBYTE = 34008,
    KUNITCONVERSION_UNITID_EXBIBIT = 34009,
    KUNITCONVERSION_UNITID_EXABYTE = 34010,
    KUNITCONVERSION_UNITID_EXABIT = 34011,
    KUNITCONVERSION_UNITID_PEBIBYTE = 34012,
    KUNITCONVERSION_UNITID_PEBIBIT = 34013,
    KUNITCONVERSION_UNITID_PETABYTE = 34014,
    KUNITCONVERSION_UNITID_PETABIT = 34015,
    KUNITCONVERSION_UNITID_TEBIBYTE = 34016,
    KUNITCONVERSION_UNITID_TEBIBIT = 34017,
    KUNITCONVERSION_UNITID_TERABYTE = 34018,
    KUNITCONVERSION_UNITID_TERABIT = 34019,
    KUNITCONVERSION_UNITID_GIBIBYTE = 34020,
    KUNITCONVERSION_UNITID_GIBIBIT = 34021,
    KUNITCONVERSION_UNITID_GIGABYTE = 34022,
    KUNITCONVERSION_UNITID_GIGABIT = 34023,
    KUNITCONVERSION_UNITID_MEBIBYTE = 34024,
    KUNITCONVERSION_UNITID_MEBIBIT = 34025,
    KUNITCONVERSION_UNITID_MEGABYTE = 34026,
    KUNITCONVERSION_UNITID_MEGABIT = 34027,
    KUNITCONVERSION_UNITID_KIBIBYTE = 34028,
    KUNITCONVERSION_UNITID_KIBIBIT = 34029,
    KUNITCONVERSION_UNITID_KILOBYTE = 34030,
    KUNITCONVERSION_UNITID_KILOBIT = 34031,
    KUNITCONVERSION_UNITID_BYTE = 34032,
    KUNITCONVERSION_UNITID_BIT = 34033
} KUnitConversion__UnitId;

#endif
