#pragma once
#ifndef SRC_RESTRICTED_EXTRAS_QSCINTILLA_QT6C_LIBQSCICOMMAND_H
#define SRC_RESTRICTED_EXTRAS_QSCINTILLA_QT6C_LIBQSCICOMMAND_H

#include <stdbool.h>
#include <stddef.h>

#include "../libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

/// [Upstream resources](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciCommand.html)

/// [Upstream resources](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciCommand.html)
///
/// @param self QsciCommand*
///
/// @return enum QsciCommand__Command
///
int32_t q_scicommand_command(void* self);

/// [Upstream resources](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciCommand.html)
///
/// @param self QsciCommand*
///
void q_scicommand_execute(void* self);

/// [Upstream resources](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciCommand.html)
///
/// @param self QsciCommand*
/// @param key int
///
void q_scicommand_set_key(void* self, int key);

/// [Upstream resources](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciCommand.html)
///
/// @param self QsciCommand*
/// @param altkey int
///
void q_scicommand_set_alternate_key(void* self, int altkey);

/// [Upstream resources](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciCommand.html)
///
/// @param self QsciCommand*
///
int32_t q_scicommand_key(void* self);

/// [Upstream resources](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciCommand.html)
///
/// @param self QsciCommand*
///
int32_t q_scicommand_alternate_key(void* self);

/// [Upstream resources](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciCommand.html)
///
/// @param key int
///
bool q_scicommand_valid_key(int key);

/// [Upstream resources](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciCommand.html)
///
/// @warning Caller is responsible for freeing the returned memory
///
/// @param self QsciCommand*
///
const char* q_scicommand_description(void* self);

/// [Upstream resources](https://www.riverbankcomputing.com/static/Docs/QScintilla/classQsciCommand.html)
///
/// Delete this object from C++ memory.
///
/// @param self QsciCommand*
///
void q_scicommand_delete(void* self);

typedef enum {
    QSCICOMMAND_COMMAND_LINEDOWN = 2300,
    QSCICOMMAND_COMMAND_LINEDOWNEXTEND = 2301,
    QSCICOMMAND_COMMAND_LINEDOWNRECTEXTEND = 2426,
    QSCICOMMAND_COMMAND_LINESCROLLDOWN = 2342,
    QSCICOMMAND_COMMAND_LINEUP = 2302,
    QSCICOMMAND_COMMAND_LINEUPEXTEND = 2303,
    QSCICOMMAND_COMMAND_LINEUPRECTEXTEND = 2427,
    QSCICOMMAND_COMMAND_LINESCROLLUP = 2343,
    QSCICOMMAND_COMMAND_SCROLLTOSTART = 2628,
    QSCICOMMAND_COMMAND_SCROLLTOEND = 2629,
    QSCICOMMAND_COMMAND_VERTICALCENTRECARET = 2619,
    QSCICOMMAND_COMMAND_PARADOWN = 2413,
    QSCICOMMAND_COMMAND_PARADOWNEXTEND = 2414,
    QSCICOMMAND_COMMAND_PARAUP = 2415,
    QSCICOMMAND_COMMAND_PARAUPEXTEND = 2416,
    QSCICOMMAND_COMMAND_CHARLEFT = 2304,
    QSCICOMMAND_COMMAND_CHARLEFTEXTEND = 2305,
    QSCICOMMAND_COMMAND_CHARLEFTRECTEXTEND = 2428,
    QSCICOMMAND_COMMAND_CHARRIGHT = 2306,
    QSCICOMMAND_COMMAND_CHARRIGHTEXTEND = 2307,
    QSCICOMMAND_COMMAND_CHARRIGHTRECTEXTEND = 2429,
    QSCICOMMAND_COMMAND_WORDLEFT = 2308,
    QSCICOMMAND_COMMAND_WORDLEFTEXTEND = 2309,
    QSCICOMMAND_COMMAND_WORDRIGHT = 2310,
    QSCICOMMAND_COMMAND_WORDRIGHTEXTEND = 2311,
    QSCICOMMAND_COMMAND_WORDLEFTEND = 2439,
    QSCICOMMAND_COMMAND_WORDLEFTENDEXTEND = 2440,
    QSCICOMMAND_COMMAND_WORDRIGHTEND = 2441,
    QSCICOMMAND_COMMAND_WORDRIGHTENDEXTEND = 2442,
    QSCICOMMAND_COMMAND_WORDPARTLEFT = 2390,
    QSCICOMMAND_COMMAND_WORDPARTLEFTEXTEND = 2391,
    QSCICOMMAND_COMMAND_WORDPARTRIGHT = 2392,
    QSCICOMMAND_COMMAND_WORDPARTRIGHTEXTEND = 2393,
    QSCICOMMAND_COMMAND_HOME = 2312,
    QSCICOMMAND_COMMAND_HOMEEXTEND = 2313,
    QSCICOMMAND_COMMAND_HOMERECTEXTEND = 2430,
    QSCICOMMAND_COMMAND_HOMEDISPLAY = 2345,
    QSCICOMMAND_COMMAND_HOMEDISPLAYEXTEND = 2346,
    QSCICOMMAND_COMMAND_HOMEWRAP = 2349,
    QSCICOMMAND_COMMAND_HOMEWRAPEXTEND = 2450,
    QSCICOMMAND_COMMAND_VCHOME = 2331,
    QSCICOMMAND_COMMAND_VCHOMEEXTEND = 2332,
    QSCICOMMAND_COMMAND_VCHOMERECTEXTEND = 2431,
    QSCICOMMAND_COMMAND_VCHOMEWRAP = 2453,
    QSCICOMMAND_COMMAND_VCHOMEWRAPEXTEND = 2454,
    QSCICOMMAND_COMMAND_LINEEND = 2314,
    QSCICOMMAND_COMMAND_LINEENDEXTEND = 2315,
    QSCICOMMAND_COMMAND_LINEENDRECTEXTEND = 2432,
    QSCICOMMAND_COMMAND_LINEENDDISPLAY = 2347,
    QSCICOMMAND_COMMAND_LINEENDDISPLAYEXTEND = 2348,
    QSCICOMMAND_COMMAND_LINEENDWRAP = 2451,
    QSCICOMMAND_COMMAND_LINEENDWRAPEXTEND = 2452,
    QSCICOMMAND_COMMAND_DOCUMENTSTART = 2316,
    QSCICOMMAND_COMMAND_DOCUMENTSTARTEXTEND = 2317,
    QSCICOMMAND_COMMAND_DOCUMENTEND = 2318,
    QSCICOMMAND_COMMAND_DOCUMENTENDEXTEND = 2319,
    QSCICOMMAND_COMMAND_PAGEUP = 2320,
    QSCICOMMAND_COMMAND_PAGEUPEXTEND = 2321,
    QSCICOMMAND_COMMAND_PAGEUPRECTEXTEND = 2433,
    QSCICOMMAND_COMMAND_PAGEDOWN = 2322,
    QSCICOMMAND_COMMAND_PAGEDOWNEXTEND = 2323,
    QSCICOMMAND_COMMAND_PAGEDOWNRECTEXTEND = 2434,
    QSCICOMMAND_COMMAND_STUTTEREDPAGEUP = 2435,
    QSCICOMMAND_COMMAND_STUTTEREDPAGEUPEXTEND = 2436,
    QSCICOMMAND_COMMAND_STUTTEREDPAGEDOWN = 2437,
    QSCICOMMAND_COMMAND_STUTTEREDPAGEDOWNEXTEND = 2438,
    QSCICOMMAND_COMMAND_DELETE = 2180,
    QSCICOMMAND_COMMAND_DELETEBACK = 2326,
    QSCICOMMAND_COMMAND_DELETEBACKNOTLINE = 2344,
    QSCICOMMAND_COMMAND_DELETEWORDLEFT = 2335,
    QSCICOMMAND_COMMAND_DELETEWORDRIGHT = 2336,
    QSCICOMMAND_COMMAND_DELETEWORDRIGHTEND = 2518,
    QSCICOMMAND_COMMAND_DELETELINELEFT = 2395,
    QSCICOMMAND_COMMAND_DELETELINERIGHT = 2396,
    QSCICOMMAND_COMMAND_LINEDELETE = 2338,
    QSCICOMMAND_COMMAND_LINECUT = 2337,
    QSCICOMMAND_COMMAND_LINECOPY = 2455,
    QSCICOMMAND_COMMAND_LINETRANSPOSE = 2339,
    QSCICOMMAND_COMMAND_LINEDUPLICATE = 2404,
    QSCICOMMAND_COMMAND_SELECTALL = 2013,
    QSCICOMMAND_COMMAND_MOVESELECTEDLINESUP = 2620,
    QSCICOMMAND_COMMAND_MOVESELECTEDLINESDOWN = 2621,
    QSCICOMMAND_COMMAND_SELECTIONDUPLICATE = 2469,
    QSCICOMMAND_COMMAND_SELECTIONLOWERCASE = 2340,
    QSCICOMMAND_COMMAND_SELECTIONUPPERCASE = 2341,
    QSCICOMMAND_COMMAND_SELECTIONCUT = 2177,
    QSCICOMMAND_COMMAND_SELECTIONCOPY = 2178,
    QSCICOMMAND_COMMAND_PASTE = 2179,
    QSCICOMMAND_COMMAND_EDITTOGGLEOVERTYPE = 2324,
    QSCICOMMAND_COMMAND_NEWLINE = 2329,
    QSCICOMMAND_COMMAND_FORMFEED = 2330,
    QSCICOMMAND_COMMAND_TAB = 2327,
    QSCICOMMAND_COMMAND_BACKTAB = 2328,
    QSCICOMMAND_COMMAND_CANCEL = 2325,
    QSCICOMMAND_COMMAND_UNDO = 2176,
    QSCICOMMAND_COMMAND_REDO = 2011,
    QSCICOMMAND_COMMAND_ZOOMIN = 2333,
    QSCICOMMAND_COMMAND_ZOOMOUT = 2334,
    QSCICOMMAND_COMMAND_REVERSELINES = 2354
} QsciCommand__Command;

#endif
