#pragma once
#ifndef SRC_EXTRAS_KFILEMETADATA_QT6C_LIBEMBEDDEDIMAGEDATA_H
#define SRC_EXTRAS_KFILEMETADATA_QT6C_LIBEMBEDDEDIMAGEDATA_H

#include <stdbool.h>
#include <stddef.h>

#include "../libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

/// [Upstream resources](https://api.kde.org/kfilemetadata-embeddedimagedata.html)

/// k_filemetadata__embeddedimagedata_new constructs a new KFileMetaData::EmbeddedImageData object.
///
KFileMetaData__EmbeddedImageData* k_filemetadata__embeddedimagedata_new();

/// Delete this object from C++ memory.
///
/// @param self KFileMetaData__EmbeddedImageData*
///
void k_filemetadata__embeddedimagedata_delete(void* self);

/// [Upstream resources](https://api.kde.org/kfilemetadata-embeddedimagedata.html#public-types)

typedef enum {
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_FRONTCOVER = 1,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_OTHER = 2,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_FILEICON = 4,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_OTHERFILEICON = 8,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_BACKCOVER = 16,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_LEAFLETPAGE = 32,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_MEDIA = 64,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_LEADARTIST = 128,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_ARTIST = 256,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_CONDUCTOR = 512,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_BAND = 1024,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_COMPOSER = 2048,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_LYRICIST = 4096,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_RECORDINGLOCATION = 8192,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_DURINGRECORDING = 16384,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_DURINGPERFORMANCE = 32768,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_MOVIESCREENCAPTURE = 65536,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_COLOUREDFISH = 131072,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_ILLUSTRATION = 262144,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_BANDLOGO = 524288,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_PUBLISHERLOGO = 1048576,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_UNKNOWN = 1073741824,
    KFILEMETADATA_EMBEDDEDIMAGEDATA_IMAGETYPE_ALLIMAGES = 2147483647
} KFileMetaData__EmbeddedImageData__ImageType;

#endif
