#pragma once
#ifndef SRC_EXTRAS_KFILEMETADATA_QT6C_LIBPROPERTIES_H
#define SRC_EXTRAS_KFILEMETADATA_QT6C_LIBPROPERTIES_H

#include <stdbool.h>
#include <stddef.h>

#include "../libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "../qtlibc.h"

/// [Upstream resources](https://api.kde.org/kfilemetadata-properties.html#public-types)

typedef enum {
    KFILEMETADATA_PROPERTY_PROPERTY_EMPTY = 0,
    KFILEMETADATA_PROPERTY_PROPERTY_BITRATE = 1,
    KFILEMETADATA_PROPERTY_PROPERTY_CHANNELS = 2,
    KFILEMETADATA_PROPERTY_PROPERTY_DURATION = 3,
    KFILEMETADATA_PROPERTY_PROPERTY_GENRE = 4,
    KFILEMETADATA_PROPERTY_PROPERTY_SAMPLERATE = 5,
    KFILEMETADATA_PROPERTY_PROPERTY_TRACKNUMBER = 6,
    KFILEMETADATA_PROPERTY_PROPERTY_RELEASEYEAR = 7,
    KFILEMETADATA_PROPERTY_PROPERTY_COMMENT = 8,
    KFILEMETADATA_PROPERTY_PROPERTY_ARTIST = 9,
    KFILEMETADATA_PROPERTY_PROPERTY_ALBUM = 10,
    KFILEMETADATA_PROPERTY_PROPERTY_ALBUMARTIST = 11,
    KFILEMETADATA_PROPERTY_PROPERTY_COMPOSER = 12,
    KFILEMETADATA_PROPERTY_PROPERTY_LYRICIST = 13,
    KFILEMETADATA_PROPERTY_PROPERTY_AUTHOR = 14,
    KFILEMETADATA_PROPERTY_PROPERTY_TITLE = 15,
    KFILEMETADATA_PROPERTY_PROPERTY_SUBJECT = 16,
    KFILEMETADATA_PROPERTY_PROPERTY_GENERATOR = 17,
    KFILEMETADATA_PROPERTY_PROPERTY_PAGECOUNT = 18,
    KFILEMETADATA_PROPERTY_PROPERTY_WORDCOUNT = 19,
    KFILEMETADATA_PROPERTY_PROPERTY_LINECOUNT = 20,
    KFILEMETADATA_PROPERTY_PROPERTY_LANGUAGE = 21,
    KFILEMETADATA_PROPERTY_PROPERTY_COPYRIGHT = 22,
    KFILEMETADATA_PROPERTY_PROPERTY_PUBLISHER = 23,
    KFILEMETADATA_PROPERTY_PROPERTY_CREATIONDATE = 24,
    KFILEMETADATA_PROPERTY_PROPERTY_KEYWORDS = 25,
    KFILEMETADATA_PROPERTY_PROPERTY_WIDTH = 26,
    KFILEMETADATA_PROPERTY_PROPERTY_HEIGHT = 27,
    KFILEMETADATA_PROPERTY_PROPERTY_ASPECTRATIO = 28,
    KFILEMETADATA_PROPERTY_PROPERTY_FRAMERATE = 29,
    KFILEMETADATA_PROPERTY_PROPERTY_MANUFACTURER = 30,
    KFILEMETADATA_PROPERTY_PROPERTY_MODEL = 31,
    KFILEMETADATA_PROPERTY_PROPERTY_IMAGEDATETIME = 32,
    KFILEMETADATA_PROPERTY_PROPERTY_IMAGEORIENTATION = 33,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOFLASH = 34,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOPIXELXDIMENSION = 35,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOPIXELYDIMENSION = 36,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTODATETIMEORIGINAL = 37,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOFOCALLENGTH = 38,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOFOCALLENGTHIN35MMFILM = 39,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOEXPOSURETIME = 40,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOFNUMBER = 41,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOAPERTUREVALUE = 42,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOEXPOSUREBIASVALUE = 43,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOWHITEBALANCE = 44,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOMETERINGMODE = 45,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOISOSPEEDRATINGS = 46,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOSATURATION = 47,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOSHARPNESS = 48,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOGPSLATITUDE = 49,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOGPSLONGITUDE = 50,
    KFILEMETADATA_PROPERTY_PROPERTY_PHOTOGPSALTITUDE = 51,
    KFILEMETADATA_PROPERTY_PROPERTY_TRANSLATIONUNITSTOTAL = 52,
    KFILEMETADATA_PROPERTY_PROPERTY_TRANSLATIONUNITSWITHTRANSLATION = 53,
    KFILEMETADATA_PROPERTY_PROPERTY_TRANSLATIONUNITSWITHDRAFTTRANSLATION = 54,
    KFILEMETADATA_PROPERTY_PROPERTY_TRANSLATIONLASTAUTHOR = 55,
    KFILEMETADATA_PROPERTY_PROPERTY_TRANSLATIONLASTUPDATE = 56,
    KFILEMETADATA_PROPERTY_PROPERTY_TRANSLATIONTEMPLATEDATE = 57,
    KFILEMETADATA_PROPERTY_PROPERTY_ORIGINURL = 58,
    KFILEMETADATA_PROPERTY_PROPERTY_ORIGINEMAILSUBJECT = 59,
    KFILEMETADATA_PROPERTY_PROPERTY_ORIGINEMAILSENDER = 60,
    KFILEMETADATA_PROPERTY_PROPERTY_ORIGINEMAILMESSAGEID = 61,
    KFILEMETADATA_PROPERTY_PROPERTY_DISCNUMBER = 62,
    KFILEMETADATA_PROPERTY_PROPERTY_LOCATION = 63,
    KFILEMETADATA_PROPERTY_PROPERTY_PERFORMER = 64,
    KFILEMETADATA_PROPERTY_PROPERTY_ENSEMBLE = 65,
    KFILEMETADATA_PROPERTY_PROPERTY_ARRANGER = 66,
    KFILEMETADATA_PROPERTY_PROPERTY_CONDUCTOR = 67,
    KFILEMETADATA_PROPERTY_PROPERTY_OPUS = 68,
    KFILEMETADATA_PROPERTY_PROPERTY_LABEL = 69,
    KFILEMETADATA_PROPERTY_PROPERTY_COMPILATION = 70,
    KFILEMETADATA_PROPERTY_PROPERTY_LICENSE = 71,
    KFILEMETADATA_PROPERTY_PROPERTY_RATING = 72,
    KFILEMETADATA_PROPERTY_PROPERTY_LYRICS = 73,
    KFILEMETADATA_PROPERTY_PROPERTY_REPLAYGAINALBUMPEAK = 74,
    KFILEMETADATA_PROPERTY_PROPERTY_REPLAYGAINALBUMGAIN = 75,
    KFILEMETADATA_PROPERTY_PROPERTY_REPLAYGAINTRACKPEAK = 76,
    KFILEMETADATA_PROPERTY_PROPERTY_REPLAYGAINTRACKGAIN = 77,
    KFILEMETADATA_PROPERTY_PROPERTY_DESCRIPTION = 78,
    KFILEMETADATA_PROPERTY_PROPERTY_VIDEOCODEC = 79,
    KFILEMETADATA_PROPERTY_PROPERTY_AUDIOCODEC = 80,
    KFILEMETADATA_PROPERTY_PROPERTY_PIXELFORMAT = 81,
    KFILEMETADATA_PROPERTY_PROPERTY_COLORSPACE = 82
} KFileMetaData__Property__Property;

#endif
