#pragma once
#ifndef SRCQT6C_LIBQMENUBAR_H
#define SRCQT6C_LIBQMENUBAR_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#include "libqaction.h"
#include "libqevent.h"
#include "libqanystringview.h"
#include "libqbackingstore.h"
#include "libqbindingstorage.h"
#include "libqbitmap.h"
#include "libqcursor.h"
#include "libqfont.h"
#include "libqfontinfo.h"
#include "libqfontmetrics.h"
#include "libqgraphicseffect.h"
#include "libqgraphicsproxywidget.h"
#include "libqicon.h"
#include "libqkeysequence.h"
#include "libqlayout.h"
#include "libqlocale.h"
#include "libqmargins.h"
#include "libqmenu.h"
#include "libqmetaobject.h"
#include "libqobject.h"
#include "libqpaintdevice.h"
#include "libqpaintengine.h"
#include "libqpainter.h"
#include "libqpalette.h"
#include "libqpixmap.h"
#include "libqpoint.h"
#include "libqrect.h"
#include "libqregion.h"
#include "libqscreen.h"
#include "libqsize.h"
#include "libqsizepolicy.h"
#include <string.h>
#include "libqstyle.h"
#include "libqstyleoption.h"
#include "libqthread.h"
#include "libqvariant.h"
#include "libqwidget.h"
#include "libqwindow.h"

QMenuBar* q_menubar_new(void* parent);
QMenuBar* q_menubar_new2();
QMetaObject* q_menubar_meta_object(void* self);
void* q_menubar_metacast(void* self, const char* param1);
int32_t q_menubar_metacall(void* self, int64_t param1, int param2, void* param3);
void q_menubar_on_metacall(void* self, int32_t (*slot)(void*, int64_t, int, void*));
int32_t q_menubar_qbase_metacall(void* self, int64_t param1, int param2, void* param3);
const char* q_menubar_tr(const char* s);
QAction* q_menubar_add_menu(void* self, void* menu);
QMenu* q_menubar_add_menu_with_title(void* self, const char* title);
QMenu* q_menubar_add_menu2(void* self, void* icon, const char* title);
QAction* q_menubar_add_separator(void* self);
QAction* q_menubar_insert_separator(void* self, void* before);
QAction* q_menubar_insert_menu(void* self, void* before, void* menu);
void q_menubar_clear(void* self);
QAction* q_menubar_active_action(void* self);
void q_menubar_set_active_action(void* self, void* action);
void q_menubar_set_default_up(void* self, bool defaultUp);
bool q_menubar_is_default_up(void* self);
QSize* q_menubar_size_hint(void* self);
void q_menubar_on_size_hint(void* self, QSize* (*slot)());
QSize* q_menubar_qbase_size_hint(void* self);
QSize* q_menubar_minimum_size_hint(void* self);
void q_menubar_on_minimum_size_hint(void* self, QSize* (*slot)());
QSize* q_menubar_qbase_minimum_size_hint(void* self);
int32_t q_menubar_height_for_width(void* self, int param1);
void q_menubar_on_height_for_width(void* self, int32_t (*slot)(void*, int));
int32_t q_menubar_qbase_height_for_width(void* self, int param1);
QRect* q_menubar_action_geometry(void* self, void* param1);
QAction* q_menubar_action_at(void* self, void* param1);
void q_menubar_set_corner_widget(void* self, void* w);
QWidget* q_menubar_corner_widget(void* self);
bool q_menubar_is_native_menu_bar(void* self);
void q_menubar_set_native_menu_bar(void* self, bool nativeMenuBar);
void q_menubar_set_visible(void* self, bool visible);
void q_menubar_on_set_visible(void* self, void (*slot)(void*, bool));
void q_menubar_qbase_set_visible(void* self, bool visible);
void q_menubar_triggered(void* self, void* action);
void q_menubar_on_triggered(void* self, void (*slot)(void*, void*));
void q_menubar_hovered(void* self, void* action);
void q_menubar_on_hovered(void* self, void (*slot)(void*, void*));
void q_menubar_change_event(void* self, void* param1);
void q_menubar_on_change_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_change_event(void* self, void* param1);
void q_menubar_key_press_event(void* self, void* param1);
void q_menubar_on_key_press_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_key_press_event(void* self, void* param1);
void q_menubar_mouse_release_event(void* self, void* param1);
void q_menubar_on_mouse_release_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_mouse_release_event(void* self, void* param1);
void q_menubar_mouse_press_event(void* self, void* param1);
void q_menubar_on_mouse_press_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_mouse_press_event(void* self, void* param1);
void q_menubar_mouse_move_event(void* self, void* param1);
void q_menubar_on_mouse_move_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_mouse_move_event(void* self, void* param1);
void q_menubar_leave_event(void* self, void* param1);
void q_menubar_on_leave_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_leave_event(void* self, void* param1);
void q_menubar_paint_event(void* self, void* param1);
void q_menubar_on_paint_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_paint_event(void* self, void* param1);
void q_menubar_resize_event(void* self, void* param1);
void q_menubar_on_resize_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_resize_event(void* self, void* param1);
void q_menubar_action_event(void* self, void* param1);
void q_menubar_on_action_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_action_event(void* self, void* param1);
void q_menubar_focus_out_event(void* self, void* param1);
void q_menubar_on_focus_out_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_focus_out_event(void* self, void* param1);
void q_menubar_focus_in_event(void* self, void* param1);
void q_menubar_on_focus_in_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_focus_in_event(void* self, void* param1);
void q_menubar_timer_event(void* self, void* param1);
void q_menubar_on_timer_event(void* self, void (*slot)(void*, void*));
void q_menubar_qbase_timer_event(void* self, void* param1);
bool q_menubar_event_filter(void* self, void* param1, void* param2);
void q_menubar_on_event_filter(void* self, bool (*slot)(void*, void*, void*));
bool q_menubar_qbase_event_filter(void* self, void* param1, void* param2);
bool q_menubar_event(void* self, void* param1);
void q_menubar_on_event(void* self, bool (*slot)(void*, void*));
bool q_menubar_qbase_event(void* self, void* param1);
void q_menubar_init_style_option(void* self, void* option, void* action);
void q_menubar_on_init_style_option(void* self, void (*slot)(void*, void*, void*));
void q_menubar_qbase_init_style_option(void* self, void* option, void* action);
const char* q_menubar_tr2(const char* s, const char* c);
const char* q_menubar_tr3(const char* s, const char* c, int n);
void q_menubar_set_corner_widget2(void* self, void* w, int64_t corner);
QWidget* q_menubar_corner_widget1(void* self, int64_t corner);
uintptr_t q_menubar_win_id(void* self);
void q_menubar_create_win_id(void* self);
uintptr_t q_menubar_internal_win_id(void* self);
uintptr_t q_menubar_effective_win_id(void* self);
QStyle* q_menubar_style(void* self);
void q_menubar_set_style(void* self, void* style);
bool q_menubar_is_top_level(void* self);
bool q_menubar_is_window(void* self);
bool q_menubar_is_modal(void* self);
int64_t q_menubar_window_modality(void* self);
void q_menubar_set_window_modality(void* self, int64_t windowModality);
bool q_menubar_is_enabled(void* self);
bool q_menubar_is_enabled_to(void* self, void* param1);
void q_menubar_set_enabled(void* self, bool enabled);
void q_menubar_set_disabled(void* self, bool disabled);
void q_menubar_set_window_modified(void* self, bool windowModified);
QRect* q_menubar_frame_geometry(void* self);
QRect* q_menubar_geometry(void* self);
QRect* q_menubar_normal_geometry(void* self);
int32_t q_menubar_x(void* self);
int32_t q_menubar_y(void* self);
QPoint* q_menubar_pos(void* self);
QSize* q_menubar_frame_size(void* self);
QSize* q_menubar_size(void* self);
int32_t q_menubar_width(void* self);
int32_t q_menubar_height(void* self);
QRect* q_menubar_rect(void* self);
QRect* q_menubar_children_rect(void* self);
QRegion* q_menubar_children_region(void* self);
QSize* q_menubar_minimum_size(void* self);
QSize* q_menubar_maximum_size(void* self);
int32_t q_menubar_minimum_width(void* self);
int32_t q_menubar_minimum_height(void* self);
int32_t q_menubar_maximum_width(void* self);
int32_t q_menubar_maximum_height(void* self);
void q_menubar_set_minimum_size(void* self, void* minimumSize);
void q_menubar_set_minimum_size2(void* self, int minw, int minh);
void q_menubar_set_maximum_size(void* self, void* maximumSize);
void q_menubar_set_maximum_size2(void* self, int maxw, int maxh);
void q_menubar_set_minimum_width(void* self, int minw);
void q_menubar_set_minimum_height(void* self, int minh);
void q_menubar_set_maximum_width(void* self, int maxw);
void q_menubar_set_maximum_height(void* self, int maxh);
QSize* q_menubar_size_increment(void* self);
void q_menubar_set_size_increment(void* self, void* sizeIncrement);
void q_menubar_set_size_increment2(void* self, int w, int h);
QSize* q_menubar_base_size(void* self);
void q_menubar_set_base_size(void* self, void* baseSize);
void q_menubar_set_base_size2(void* self, int basew, int baseh);
void q_menubar_set_fixed_size(void* self, void* fixedSize);
void q_menubar_set_fixed_size2(void* self, int w, int h);
void q_menubar_set_fixed_width(void* self, int w);
void q_menubar_set_fixed_height(void* self, int h);
QPointF* q_menubar_map_to_global(void* self, void* param1);
QPoint* q_menubar_map_to_global_with_q_point(void* self, void* param1);
QPointF* q_menubar_map_from_global(void* self, void* param1);
QPoint* q_menubar_map_from_global_with_q_point(void* self, void* param1);
QPointF* q_menubar_map_to_parent(void* self, void* param1);
QPoint* q_menubar_map_to_parent_with_q_point(void* self, void* param1);
QPointF* q_menubar_map_from_parent(void* self, void* param1);
QPoint* q_menubar_map_from_parent_with_q_point(void* self, void* param1);
QPointF* q_menubar_map_to(void* self, void* param1, void* param2);
QPoint* q_menubar_map_to2(void* self, void* param1, void* param2);
QPointF* q_menubar_map_from(void* self, void* param1, void* param2);
QPoint* q_menubar_map_from2(void* self, void* param1, void* param2);
QWidget* q_menubar_window(void* self);
QWidget* q_menubar_native_parent_widget(void* self);
QWidget* q_menubar_top_level_widget(void* self);
QPalette* q_menubar_palette(void* self);
void q_menubar_set_palette(void* self, void* palette);
void q_menubar_set_background_role(void* self, int64_t backgroundRole);
int64_t q_menubar_background_role(void* self);
void q_menubar_set_foreground_role(void* self, int64_t foregroundRole);
int64_t q_menubar_foreground_role(void* self);
QFont* q_menubar_font(void* self);
void q_menubar_set_font(void* self, void* font);
QFontMetrics* q_menubar_font_metrics(void* self);
QFontInfo* q_menubar_font_info(void* self);
QCursor* q_menubar_cursor(void* self);
void q_menubar_set_cursor(void* self, void* cursor);
void q_menubar_unset_cursor(void* self);
void q_menubar_set_mouse_tracking(void* self, bool enable);
bool q_menubar_has_mouse_tracking(void* self);
bool q_menubar_under_mouse(void* self);
void q_menubar_set_tablet_tracking(void* self, bool enable);
bool q_menubar_has_tablet_tracking(void* self);
void q_menubar_set_mask(void* self, void* mask);
void q_menubar_set_mask_with_mask(void* self, void* mask);
QRegion* q_menubar_mask(void* self);
void q_menubar_clear_mask(void* self);
void q_menubar_render(void* self, void* target);
void q_menubar_render_with_painter(void* self, void* painter);
QPixmap* q_menubar_grab(void* self);
QGraphicsEffect* q_menubar_graphics_effect(void* self);
void q_menubar_set_graphics_effect(void* self, void* effect);
void q_menubar_grab_gesture(void* self, int64_t typeVal);
void q_menubar_ungrab_gesture(void* self, int64_t typeVal);
void q_menubar_set_window_title(void* self, const char* windowTitle);
void q_menubar_set_style_sheet(void* self, const char* styleSheet);
const char* q_menubar_style_sheet(void* self);
const char* q_menubar_window_title(void* self);
void q_menubar_set_window_icon(void* self, void* icon);
QIcon* q_menubar_window_icon(void* self);
void q_menubar_set_window_icon_text(void* self, const char* windowIconText);
const char* q_menubar_window_icon_text(void* self);
void q_menubar_set_window_role(void* self, const char* windowRole);
const char* q_menubar_window_role(void* self);
void q_menubar_set_window_file_path(void* self, const char* filePath);
const char* q_menubar_window_file_path(void* self);
void q_menubar_set_window_opacity(void* self, double level);
double q_menubar_window_opacity(void* self);
bool q_menubar_is_window_modified(void* self);
void q_menubar_set_tool_tip(void* self, const char* toolTip);
const char* q_menubar_tool_tip(void* self);
void q_menubar_set_tool_tip_duration(void* self, int msec);
int32_t q_menubar_tool_tip_duration(void* self);
void q_menubar_set_status_tip(void* self, const char* statusTip);
const char* q_menubar_status_tip(void* self);
void q_menubar_set_whats_this(void* self, const char* whatsThis);
const char* q_menubar_whats_this(void* self);
const char* q_menubar_accessible_name(void* self);
void q_menubar_set_accessible_name(void* self, const char* name);
const char* q_menubar_accessible_description(void* self);
void q_menubar_set_accessible_description(void* self, const char* description);
void q_menubar_set_layout_direction(void* self, int64_t direction);
int64_t q_menubar_layout_direction(void* self);
void q_menubar_unset_layout_direction(void* self);
void q_menubar_set_locale(void* self, void* locale);
QLocale* q_menubar_locale(void* self);
void q_menubar_unset_locale(void* self);
bool q_menubar_is_right_to_left(void* self);
bool q_menubar_is_left_to_right(void* self);
void q_menubar_set_focus(void* self);
bool q_menubar_is_active_window(void* self);
void q_menubar_activate_window(void* self);
void q_menubar_clear_focus(void* self);
void q_menubar_set_focus_with_reason(void* self, int64_t reason);
int64_t q_menubar_focus_policy(void* self);
void q_menubar_set_focus_policy(void* self, int64_t policy);
bool q_menubar_has_focus(void* self);
void q_menubar_set_tab_order(void* param1, void* param2);
void q_menubar_set_focus_proxy(void* self, void* focusProxy);
QWidget* q_menubar_focus_proxy(void* self);
int64_t q_menubar_context_menu_policy(void* self);
void q_menubar_set_context_menu_policy(void* self, int64_t policy);
void q_menubar_grab_mouse(void* self);
void q_menubar_grab_mouse_with_q_cursor(void* self, void* param1);
void q_menubar_release_mouse(void* self);
void q_menubar_grab_keyboard(void* self);
void q_menubar_release_keyboard(void* self);
int32_t q_menubar_grab_shortcut(void* self, void* key);
void q_menubar_release_shortcut(void* self, int id);
void q_menubar_set_shortcut_enabled(void* self, int id);
void q_menubar_set_shortcut_auto_repeat(void* self, int id);
QWidget* q_menubar_mouse_grabber();
QWidget* q_menubar_keyboard_grabber();
bool q_menubar_updates_enabled(void* self);
void q_menubar_set_updates_enabled(void* self, bool enable);
QGraphicsProxyWidget* q_menubar_graphics_proxy_widget(void* self);
void q_menubar_update(void* self);
void q_menubar_repaint(void* self);
void q_menubar_update2(void* self, int x, int y, int w, int h);
void q_menubar_update_with_q_rect(void* self, void* param1);
void q_menubar_update_with_q_region(void* self, void* param1);
void q_menubar_repaint2(void* self, int x, int y, int w, int h);
void q_menubar_repaint_with_q_rect(void* self, void* param1);
void q_menubar_repaint_with_q_region(void* self, void* param1);
void q_menubar_set_hidden(void* self, bool hidden);
void q_menubar_show(void* self);
void q_menubar_hide(void* self);
void q_menubar_show_minimized(void* self);
void q_menubar_show_maximized(void* self);
void q_menubar_show_full_screen(void* self);
void q_menubar_show_normal(void* self);
bool q_menubar_close(void* self);
void q_menubar_raise(void* self);
void q_menubar_lower(void* self);
void q_menubar_stack_under(void* self, void* param1);
void q_menubar_move(void* self, int x, int y);
void q_menubar_move_with_q_point(void* self, void* param1);
void q_menubar_resize(void* self, int w, int h);
void q_menubar_resize_with_q_size(void* self, void* param1);
void q_menubar_set_geometry(void* self, int x, int y, int w, int h);
void q_menubar_set_geometry_with_geometry(void* self, void* geometry);
char* q_menubar_save_geometry(void* self);
bool q_menubar_restore_geometry(void* self, const char* geometry);
void q_menubar_adjust_size(void* self);
bool q_menubar_is_visible(void* self);
bool q_menubar_is_visible_to(void* self, void* param1);
bool q_menubar_is_hidden(void* self);
bool q_menubar_is_minimized(void* self);
bool q_menubar_is_maximized(void* self);
bool q_menubar_is_full_screen(void* self);
int64_t q_menubar_window_state(void* self);
void q_menubar_set_window_state(void* self, int64_t state);
void q_menubar_override_window_state(void* self, int64_t state);
QSizePolicy* q_menubar_size_policy(void* self);
void q_menubar_set_size_policy(void* self, void* sizePolicy);
void q_menubar_set_size_policy2(void* self, int64_t horizontal, int64_t vertical);
QRegion* q_menubar_visible_region(void* self);
void q_menubar_set_contents_margins(void* self, int left, int top, int right, int bottom);
void q_menubar_set_contents_margins_with_margins(void* self, void* margins);
QMargins* q_menubar_contents_margins(void* self);
QRect* q_menubar_contents_rect(void* self);
QLayout* q_menubar_layout(void* self);
void q_menubar_set_layout(void* self, void* layout);
void q_menubar_update_geometry(void* self);
void q_menubar_set_parent(void* self, void* parent);
void q_menubar_set_parent2(void* self, void* parent, int64_t f);
void q_menubar_scroll(void* self, int dx, int dy);
void q_menubar_scroll2(void* self, int dx, int dy, void* param3);
QWidget* q_menubar_focus_widget(void* self);
QWidget* q_menubar_next_in_focus_chain(void* self);
QWidget* q_menubar_previous_in_focus_chain(void* self);
bool q_menubar_accept_drops(void* self);
void q_menubar_set_accept_drops(void* self, bool on);
void q_menubar_add_action(void* self, void* action);
void q_menubar_add_actions(void* self, void* actions[]);
void q_menubar_insert_actions(void* self, void* before, void* actions[]);
void q_menubar_insert_action(void* self, void* before, void* action);
void q_menubar_remove_action(void* self, void* action);
libqt_list /* of QAction* */ q_menubar_actions(void* self);
QAction* q_menubar_add_action_with_text(void* self, const char* text);
QAction* q_menubar_add_action2(void* self, void* icon, const char* text);
QAction* q_menubar_add_action3(void* self, const char* text, void* shortcut);
QAction* q_menubar_add_action4(void* self, void* icon, const char* text, void* shortcut);
QWidget* q_menubar_parent_widget(void* self);
void q_menubar_set_window_flags(void* self, int64_t typeVal);
int64_t q_menubar_window_flags(void* self);
void q_menubar_set_window_flag(void* self, int64_t param1);
void q_menubar_override_window_flags(void* self, int64_t typeVal);
int64_t q_menubar_window_type(void* self);
QWidget* q_menubar_find(uint64_t param1);
QWidget* q_menubar_child_at(void* self, int x, int y);
QWidget* q_menubar_child_at_with_q_point(void* self, void* p);
void q_menubar_set_attribute(void* self, int64_t param1);
bool q_menubar_test_attribute(void* self, int64_t param1);
void q_menubar_ensure_polished(void* self);
bool q_menubar_is_ancestor_of(void* self, void* child);
bool q_menubar_auto_fill_background(void* self);
void q_menubar_set_auto_fill_background(void* self, bool enabled);
QBackingStore* q_menubar_backing_store(void* self);
QWindow* q_menubar_window_handle(void* self);
QScreen* q_menubar_screen(void* self);
void q_menubar_set_screen(void* self, void* screen);
QWidget* q_menubar_create_window_container(void* window);
void q_menubar_window_title_changed(void* self, const char* title);
void q_menubar_on_window_title_changed(void* self, void (*slot)(void*, const char*));
void q_menubar_window_icon_changed(void* self, void* icon);
void q_menubar_on_window_icon_changed(void* self, void (*slot)(void*, void*));
void q_menubar_window_icon_text_changed(void* self, const char* iconText);
void q_menubar_on_window_icon_text_changed(void* self, void (*slot)(void*, const char*));
void q_menubar_custom_context_menu_requested(void* self, void* pos);
void q_menubar_on_custom_context_menu_requested(void* self, void (*slot)(void*, void*));
int64_t q_menubar_input_method_hints(void* self);
void q_menubar_set_input_method_hints(void* self, int64_t hints);
void q_menubar_render2(void* self, void* target, void* targetOffset);
void q_menubar_render3(void* self, void* target, void* targetOffset, void* sourceRegion);
void q_menubar_render4(void* self, void* target, void* targetOffset, void* sourceRegion, int64_t renderFlags);
void q_menubar_render22(void* self, void* painter, void* targetOffset);
void q_menubar_render32(void* self, void* painter, void* targetOffset, void* sourceRegion);
void q_menubar_render42(void* self, void* painter, void* targetOffset, void* sourceRegion, int64_t renderFlags);
QPixmap* q_menubar_grab1(void* self, void* rectangle);
void q_menubar_grab_gesture2(void* self, int64_t typeVal, int64_t flags);
int32_t q_menubar_grab_shortcut2(void* self, void* key, int64_t context);
void q_menubar_set_shortcut_enabled2(void* self, int id, bool enable);
void q_menubar_set_shortcut_auto_repeat2(void* self, int id, bool enable);
void q_menubar_set_window_flag2(void* self, int64_t param1, bool on);
void q_menubar_set_attribute2(void* self, int64_t param1, bool on);
QWidget* q_menubar_create_window_container2(void* window, void* parent);
QWidget* q_menubar_create_window_container3(void* window, void* parent, int64_t flags);
const char* q_menubar_object_name(void* self);
void q_menubar_set_object_name(void* self, const char* name);
bool q_menubar_is_widget_type(void* self);
bool q_menubar_is_window_type(void* self);
bool q_menubar_is_quick_item_type(void* self);
bool q_menubar_signals_blocked(void* self);
bool q_menubar_block_signals(void* self, bool b);
QThread* q_menubar_thread(void* self);
void q_menubar_move_to_thread(void* self, void* thread);
int32_t q_menubar_start_timer(void* self, int interval);
void q_menubar_kill_timer(void* self, int id);
libqt_list /* of QObject* */ q_menubar_children(void* self);
void q_menubar_install_event_filter(void* self, void* filterObj);
void q_menubar_remove_event_filter(void* self, void* obj);
QMetaObject__Connection* q_menubar_connect(void* sender, void* signal, void* receiver, void* method);
QMetaObject__Connection* q_menubar_connect2(void* self, void* sender, const char* signal, const char* member);
bool q_menubar_disconnect(void* sender, void* signal, void* receiver, void* member);
bool q_menubar_disconnect_with_q_meta_object_connection(void* param1);
void q_menubar_dump_object_tree(void* self);
void q_menubar_dump_object_info(void* self);
bool q_menubar_set_property(void* self, const char* name, void* value);
QVariant* q_menubar_property(void* self, const char* name);
const char** q_menubar_dynamic_property_names(void* self);
QBindingStorage* q_menubar_binding_storage(void* self);
QBindingStorage* q_menubar_binding_storage2(void* self);
void q_menubar_destroyed(void* self);
void q_menubar_on_destroyed(void* self, void (*slot)(void*));
QObject* q_menubar_parent(void* self);
bool q_menubar_inherits(void* self, const char* classname);
void q_menubar_delete_later(void* self);
int32_t q_menubar_start_timer2(void* self, int interval, int64_t timerType);
QMetaObject__Connection* q_menubar_connect5(void* sender, void* signal, void* receiver, void* method, int64_t typeVal);
QMetaObject__Connection* q_menubar_connect4(void* self, void* sender, const char* signal, const char* member, int64_t typeVal);
void q_menubar_destroyed1(void* self, void* param1);
void q_menubar_on_destroyed1(void* self, void (*slot)(void*, void*));
bool q_menubar_painting_active(void* self);
int32_t q_menubar_width_m_m(void* self);
int32_t q_menubar_height_m_m(void* self);
int32_t q_menubar_logical_dpi_x(void* self);
int32_t q_menubar_logical_dpi_y(void* self);
int32_t q_menubar_physical_dpi_x(void* self);
int32_t q_menubar_physical_dpi_y(void* self);
double q_menubar_device_pixel_ratio(void* self);
double q_menubar_device_pixel_ratio_f(void* self);
int32_t q_menubar_color_count(void* self);
int32_t q_menubar_depth(void* self);
double q_menubar_device_pixel_ratio_f_scale();
int32_t q_menubar_dev_type(void* self);
int32_t q_menubar_qbase_dev_type(void* self);
void q_menubar_on_dev_type(void* self, int32_t (*slot)());
bool q_menubar_has_height_for_width(void* self);
bool q_menubar_qbase_has_height_for_width(void* self);
void q_menubar_on_has_height_for_width(void* self, bool (*slot)());
QPaintEngine* q_menubar_paint_engine(void* self);
QPaintEngine* q_menubar_qbase_paint_engine(void* self);
void q_menubar_on_paint_engine(void* self, QPaintEngine* (*slot)());
void q_menubar_mouse_double_click_event(void* self, void* event);
void q_menubar_qbase_mouse_double_click_event(void* self, void* event);
void q_menubar_on_mouse_double_click_event(void* self, void (*slot)(void*, void*));
void q_menubar_wheel_event(void* self, void* event);
void q_menubar_qbase_wheel_event(void* self, void* event);
void q_menubar_on_wheel_event(void* self, void (*slot)(void*, void*));
void q_menubar_key_release_event(void* self, void* event);
void q_menubar_qbase_key_release_event(void* self, void* event);
void q_menubar_on_key_release_event(void* self, void (*slot)(void*, void*));
void q_menubar_enter_event(void* self, void* event);
void q_menubar_qbase_enter_event(void* self, void* event);
void q_menubar_on_enter_event(void* self, void (*slot)(void*, void*));
void q_menubar_move_event(void* self, void* event);
void q_menubar_qbase_move_event(void* self, void* event);
void q_menubar_on_move_event(void* self, void (*slot)(void*, void*));
void q_menubar_close_event(void* self, void* event);
void q_menubar_qbase_close_event(void* self, void* event);
void q_menubar_on_close_event(void* self, void (*slot)(void*, void*));
void q_menubar_context_menu_event(void* self, void* event);
void q_menubar_qbase_context_menu_event(void* self, void* event);
void q_menubar_on_context_menu_event(void* self, void (*slot)(void*, void*));
void q_menubar_tablet_event(void* self, void* event);
void q_menubar_qbase_tablet_event(void* self, void* event);
void q_menubar_on_tablet_event(void* self, void (*slot)(void*, void*));
void q_menubar_drag_enter_event(void* self, void* event);
void q_menubar_qbase_drag_enter_event(void* self, void* event);
void q_menubar_on_drag_enter_event(void* self, void (*slot)(void*, void*));
void q_menubar_drag_move_event(void* self, void* event);
void q_menubar_qbase_drag_move_event(void* self, void* event);
void q_menubar_on_drag_move_event(void* self, void (*slot)(void*, void*));
void q_menubar_drag_leave_event(void* self, void* event);
void q_menubar_qbase_drag_leave_event(void* self, void* event);
void q_menubar_on_drag_leave_event(void* self, void (*slot)(void*, void*));
void q_menubar_drop_event(void* self, void* event);
void q_menubar_qbase_drop_event(void* self, void* event);
void q_menubar_on_drop_event(void* self, void (*slot)(void*, void*));
void q_menubar_show_event(void* self, void* event);
void q_menubar_qbase_show_event(void* self, void* event);
void q_menubar_on_show_event(void* self, void (*slot)(void*, void*));
void q_menubar_hide_event(void* self, void* event);
void q_menubar_qbase_hide_event(void* self, void* event);
void q_menubar_on_hide_event(void* self, void (*slot)(void*, void*));
bool q_menubar_native_event(void* self, const char* eventType, void* message, intptr_t* result);
bool q_menubar_qbase_native_event(void* self, const char* eventType, void* message, intptr_t* result);
void q_menubar_on_native_event(void* self, bool (*slot)(void*, const char*, void*, intptr_t*));
int32_t q_menubar_metric(void* self, int64_t param1);
int32_t q_menubar_qbase_metric(void* self, int64_t param1);
void q_menubar_on_metric(void* self, int32_t (*slot)(void*, int64_t));
void q_menubar_init_painter(void* self, void* painter);
void q_menubar_qbase_init_painter(void* self, void* painter);
void q_menubar_on_init_painter(void* self, void (*slot)(void*, void*));
QPaintDevice* q_menubar_redirected(void* self, void* offset);
QPaintDevice* q_menubar_qbase_redirected(void* self, void* offset);
void q_menubar_on_redirected(void* self, QPaintDevice* (*slot)(void*, void*));
QPainter* q_menubar_shared_painter(void* self);
QPainter* q_menubar_qbase_shared_painter(void* self);
void q_menubar_on_shared_painter(void* self, QPainter* (*slot)());
void q_menubar_input_method_event(void* self, void* param1);
void q_menubar_qbase_input_method_event(void* self, void* param1);
void q_menubar_on_input_method_event(void* self, void (*slot)(void*, void*));
QVariant* q_menubar_input_method_query(void* self, int64_t param1);
QVariant* q_menubar_qbase_input_method_query(void* self, int64_t param1);
void q_menubar_on_input_method_query(void* self, QVariant* (*slot)(void*, int64_t));
bool q_menubar_focus_next_prev_child(void* self, bool next);
bool q_menubar_qbase_focus_next_prev_child(void* self, bool next);
void q_menubar_on_focus_next_prev_child(void* self, bool (*slot)(void*, bool));
void q_menubar_child_event(void* self, void* event);
void q_menubar_qbase_child_event(void* self, void* event);
void q_menubar_on_child_event(void* self, void (*slot)(void*, void*));
void q_menubar_custom_event(void* self, void* event);
void q_menubar_qbase_custom_event(void* self, void* event);
void q_menubar_on_custom_event(void* self, void (*slot)(void*, void*));
void q_menubar_connect_notify(void* self, void* signal);
void q_menubar_qbase_connect_notify(void* self, void* signal);
void q_menubar_on_connect_notify(void* self, void (*slot)(void*, void*));
void q_menubar_disconnect_notify(void* self, void* signal);
void q_menubar_qbase_disconnect_notify(void* self, void* signal);
void q_menubar_on_disconnect_notify(void* self, void (*slot)(void*, void*));
void q_menubar_update_micro_focus(void* self);
void q_menubar_qbase_update_micro_focus(void* self);
void q_menubar_on_update_micro_focus(void* self, void (*slot)());
void q_menubar_create(void* self);
void q_menubar_qbase_create(void* self);
void q_menubar_on_create(void* self, void (*slot)());
void q_menubar_destroy(void* self);
void q_menubar_qbase_destroy(void* self);
void q_menubar_on_destroy(void* self, void (*slot)());
bool q_menubar_focus_next_child(void* self);
bool q_menubar_qbase_focus_next_child(void* self);
void q_menubar_on_focus_next_child(void* self, bool (*slot)());
bool q_menubar_focus_previous_child(void* self);
bool q_menubar_qbase_focus_previous_child(void* self);
void q_menubar_on_focus_previous_child(void* self, bool (*slot)());
QObject* q_menubar_sender(void* self);
QObject* q_menubar_qbase_sender(void* self);
void q_menubar_on_sender(void* self, QObject* (*slot)());
int32_t q_menubar_sender_signal_index(void* self);
int32_t q_menubar_qbase_sender_signal_index(void* self);
void q_menubar_on_sender_signal_index(void* self, int32_t (*slot)());
int32_t q_menubar_receivers(void* self, const char* signal);
int32_t q_menubar_qbase_receivers(void* self, const char* signal);
void q_menubar_on_receivers(void* self, int32_t (*slot)(void*, const char*));
bool q_menubar_is_signal_connected(void* self, void* signal);
bool q_menubar_qbase_is_signal_connected(void* self, void* signal);
void q_menubar_on_is_signal_connected(void* self, bool (*slot)(void*, void*));
void q_menubar_delete(void* self);

#endif
