#pragma once
#ifndef SRCQT6C_LIBQGRAPHICSPROXYWIDGET_H
#define SRCQT6C_LIBQGRAPHICSPROXYWIDGET_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#include "libqaction.h"
#include "libqanystringview.h"
#include "libqbindingstorage.h"
#include "libqevent.h"
#include "libqcursor.h"
#include "libqfont.h"
#include "libqgraphicseffect.h"
#include "libqgraphicsitem.h"
#include "libqgraphicslayout.h"
#include "libqgraphicslayoutitem.h"
#include "libqgraphicsscene.h"
#include "libqgraphicstransform.h"
#include "libqgraphicswidget.h"
#include "libqkeysequence.h"
#include "libqmargins.h"
#include "libqmetaobject.h"
#include "libqobject.h"
#include "libqpainter.h"
#include "libqpainterpath.h"
#include "libqpalette.h"
#include "libqpoint.h"
#include "libqrect.h"
#include "libqregion.h"
#include "libqsize.h"
#include "libqsizepolicy.h"
#include <string.h>
#include "libqstyle.h"
#include "libqstyleoption.h"
#include "libqthread.h"
#include "libqtransform.h"
#include "libqvariant.h"
#include "libqwidget.h"

QGraphicsProxyWidget* q_graphicsproxywidget_new();
QGraphicsProxyWidget* q_graphicsproxywidget_new2(void* parent);
QGraphicsProxyWidget* q_graphicsproxywidget_new3(void* parent, int64_t wFlags);
QMetaObject* q_graphicsproxywidget_meta_object(void* self);
void* q_graphicsproxywidget_metacast(void* self, const char* param1);
int32_t q_graphicsproxywidget_metacall(void* self, int64_t param1, int param2, void* param3);
void q_graphicsproxywidget_on_metacall(void* self, int32_t (*slot)(void*, int64_t, int, void*));
int32_t q_graphicsproxywidget_qbase_metacall(void* self, int64_t param1, int param2, void* param3);
const char* q_graphicsproxywidget_tr(const char* s);
void q_graphicsproxywidget_set_widget(void* self, void* widget);
QWidget* q_graphicsproxywidget_widget(void* self);
QRectF* q_graphicsproxywidget_sub_widget_rect(void* self, void* widget);
void q_graphicsproxywidget_set_geometry(void* self, void* rect);
void q_graphicsproxywidget_on_set_geometry(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_set_geometry(void* self, void* rect);
void q_graphicsproxywidget_paint(void* self, void* painter, void* option, void* widget);
void q_graphicsproxywidget_on_paint(void* self, void (*slot)(void*, void*, void*, void*));
void q_graphicsproxywidget_qbase_paint(void* self, void* painter, void* option, void* widget);
int32_t q_graphicsproxywidget_type(void* self);
void q_graphicsproxywidget_on_type(void* self, int32_t (*slot)());
int32_t q_graphicsproxywidget_qbase_type(void* self);
QGraphicsProxyWidget* q_graphicsproxywidget_create_proxy_for_child_widget(void* self, void* child);
QVariant* q_graphicsproxywidget_item_change(void* self, int64_t change, void* value);
void q_graphicsproxywidget_on_item_change(void* self, QVariant* (*slot)(void*, int64_t, void*));
QVariant* q_graphicsproxywidget_qbase_item_change(void* self, int64_t change, void* value);
bool q_graphicsproxywidget_event(void* self, void* event);
void q_graphicsproxywidget_on_event(void* self, bool (*slot)(void*, void*));
bool q_graphicsproxywidget_qbase_event(void* self, void* event);
bool q_graphicsproxywidget_event_filter(void* self, void* object, void* event);
void q_graphicsproxywidget_on_event_filter(void* self, bool (*slot)(void*, void*, void*));
bool q_graphicsproxywidget_qbase_event_filter(void* self, void* object, void* event);
void q_graphicsproxywidget_show_event(void* self, void* event);
void q_graphicsproxywidget_on_show_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_show_event(void* self, void* event);
void q_graphicsproxywidget_hide_event(void* self, void* event);
void q_graphicsproxywidget_on_hide_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_hide_event(void* self, void* event);
void q_graphicsproxywidget_context_menu_event(void* self, void* event);
void q_graphicsproxywidget_on_context_menu_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_context_menu_event(void* self, void* event);
void q_graphicsproxywidget_drag_enter_event(void* self, void* event);
void q_graphicsproxywidget_on_drag_enter_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_drag_enter_event(void* self, void* event);
void q_graphicsproxywidget_drag_leave_event(void* self, void* event);
void q_graphicsproxywidget_on_drag_leave_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_drag_leave_event(void* self, void* event);
void q_graphicsproxywidget_drag_move_event(void* self, void* event);
void q_graphicsproxywidget_on_drag_move_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_drag_move_event(void* self, void* event);
void q_graphicsproxywidget_drop_event(void* self, void* event);
void q_graphicsproxywidget_on_drop_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_drop_event(void* self, void* event);
void q_graphicsproxywidget_hover_enter_event(void* self, void* event);
void q_graphicsproxywidget_on_hover_enter_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_hover_enter_event(void* self, void* event);
void q_graphicsproxywidget_hover_leave_event(void* self, void* event);
void q_graphicsproxywidget_on_hover_leave_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_hover_leave_event(void* self, void* event);
void q_graphicsproxywidget_hover_move_event(void* self, void* event);
void q_graphicsproxywidget_on_hover_move_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_hover_move_event(void* self, void* event);
void q_graphicsproxywidget_grab_mouse_event(void* self, void* event);
void q_graphicsproxywidget_on_grab_mouse_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_grab_mouse_event(void* self, void* event);
void q_graphicsproxywidget_ungrab_mouse_event(void* self, void* event);
void q_graphicsproxywidget_on_ungrab_mouse_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_ungrab_mouse_event(void* self, void* event);
void q_graphicsproxywidget_mouse_move_event(void* self, void* event);
void q_graphicsproxywidget_on_mouse_move_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_mouse_move_event(void* self, void* event);
void q_graphicsproxywidget_mouse_press_event(void* self, void* event);
void q_graphicsproxywidget_on_mouse_press_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_mouse_press_event(void* self, void* event);
void q_graphicsproxywidget_mouse_release_event(void* self, void* event);
void q_graphicsproxywidget_on_mouse_release_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_mouse_release_event(void* self, void* event);
void q_graphicsproxywidget_mouse_double_click_event(void* self, void* event);
void q_graphicsproxywidget_on_mouse_double_click_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_mouse_double_click_event(void* self, void* event);
void q_graphicsproxywidget_wheel_event(void* self, void* event);
void q_graphicsproxywidget_on_wheel_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_wheel_event(void* self, void* event);
void q_graphicsproxywidget_key_press_event(void* self, void* event);
void q_graphicsproxywidget_on_key_press_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_key_press_event(void* self, void* event);
void q_graphicsproxywidget_key_release_event(void* self, void* event);
void q_graphicsproxywidget_on_key_release_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_key_release_event(void* self, void* event);
void q_graphicsproxywidget_focus_in_event(void* self, void* event);
void q_graphicsproxywidget_on_focus_in_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_focus_in_event(void* self, void* event);
void q_graphicsproxywidget_focus_out_event(void* self, void* event);
void q_graphicsproxywidget_on_focus_out_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_focus_out_event(void* self, void* event);
bool q_graphicsproxywidget_focus_next_prev_child(void* self, bool next);
void q_graphicsproxywidget_on_focus_next_prev_child(void* self, bool (*slot)(void*, bool));
bool q_graphicsproxywidget_qbase_focus_next_prev_child(void* self, bool next);
QVariant* q_graphicsproxywidget_input_method_query(void* self, int64_t query);
void q_graphicsproxywidget_on_input_method_query(void* self, QVariant* (*slot)(void*, int64_t));
QVariant* q_graphicsproxywidget_qbase_input_method_query(void* self, int64_t query);
void q_graphicsproxywidget_input_method_event(void* self, void* event);
void q_graphicsproxywidget_on_input_method_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_input_method_event(void* self, void* event);
QSizeF* q_graphicsproxywidget_size_hint(void* self, int64_t which, void* constraint);
void q_graphicsproxywidget_on_size_hint(void* self, QSizeF* (*slot)(void*, int64_t, void*));
QSizeF* q_graphicsproxywidget_qbase_size_hint(void* self, int64_t which, void* constraint);
void q_graphicsproxywidget_resize_event(void* self, void* event);
void q_graphicsproxywidget_on_resize_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_qbase_resize_event(void* self, void* event);
QGraphicsProxyWidget* q_graphicsproxywidget_new_proxy_widget(void* self, void* param1);
void q_graphicsproxywidget_on_new_proxy_widget(void* self, QGraphicsProxyWidget* (*slot)(void*, void*));
QGraphicsProxyWidget* q_graphicsproxywidget_qbase_new_proxy_widget(void* self, void* param1);
const char* q_graphicsproxywidget_tr2(const char* s, const char* c);
const char* q_graphicsproxywidget_tr3(const char* s, const char* c, int n);
QGraphicsLayout* q_graphicsproxywidget_layout(void* self);
void q_graphicsproxywidget_set_layout(void* self, void* layout);
void q_graphicsproxywidget_adjust_size(void* self);
int64_t q_graphicsproxywidget_layout_direction(void* self);
void q_graphicsproxywidget_set_layout_direction(void* self, int64_t direction);
void q_graphicsproxywidget_unset_layout_direction(void* self);
QStyle* q_graphicsproxywidget_style(void* self);
void q_graphicsproxywidget_set_style(void* self, void* style);
QFont* q_graphicsproxywidget_font(void* self);
void q_graphicsproxywidget_set_font(void* self, void* font);
QPalette* q_graphicsproxywidget_palette(void* self);
void q_graphicsproxywidget_set_palette(void* self, void* palette);
bool q_graphicsproxywidget_auto_fill_background(void* self);
void q_graphicsproxywidget_set_auto_fill_background(void* self, bool enabled);
void q_graphicsproxywidget_resize(void* self, void* size);
void q_graphicsproxywidget_resize2(void* self, double w, double h);
QSizeF* q_graphicsproxywidget_size(void* self);
void q_graphicsproxywidget_set_geometry2(void* self, double x, double y, double w, double h);
QRectF* q_graphicsproxywidget_rect(void* self);
void q_graphicsproxywidget_set_contents_margins(void* self, double left, double top, double right, double bottom);
void q_graphicsproxywidget_set_contents_margins_with_margins(void* self, void* margins);
void q_graphicsproxywidget_set_window_frame_margins(void* self, double left, double top, double right, double bottom);
void q_graphicsproxywidget_set_window_frame_margins_with_margins(void* self, void* margins);
void q_graphicsproxywidget_get_window_frame_margins(void* self, double* left, double* top, double* right, double* bottom);
void q_graphicsproxywidget_unset_window_frame_margins(void* self);
QRectF* q_graphicsproxywidget_window_frame_geometry(void* self);
QRectF* q_graphicsproxywidget_window_frame_rect(void* self);
int64_t q_graphicsproxywidget_window_flags(void* self);
int64_t q_graphicsproxywidget_window_type(void* self);
void q_graphicsproxywidget_set_window_flags(void* self, int64_t wFlags);
bool q_graphicsproxywidget_is_active_window(void* self);
void q_graphicsproxywidget_set_window_title(void* self, const char* title);
const char* q_graphicsproxywidget_window_title(void* self);
int64_t q_graphicsproxywidget_focus_policy(void* self);
void q_graphicsproxywidget_set_focus_policy(void* self, int64_t policy);
void q_graphicsproxywidget_set_tab_order(void* first, void* second);
QGraphicsWidget* q_graphicsproxywidget_focus_widget(void* self);
int32_t q_graphicsproxywidget_grab_shortcut(void* self, void* sequence);
void q_graphicsproxywidget_release_shortcut(void* self, int id);
void q_graphicsproxywidget_set_shortcut_enabled(void* self, int id);
void q_graphicsproxywidget_set_shortcut_auto_repeat(void* self, int id);
void q_graphicsproxywidget_add_action(void* self, void* action);
void q_graphicsproxywidget_add_actions(void* self, void* actions[]);
void q_graphicsproxywidget_insert_actions(void* self, void* before, void* actions[]);
void q_graphicsproxywidget_insert_action(void* self, void* before, void* action);
void q_graphicsproxywidget_remove_action(void* self, void* action);
libqt_list /* of QAction* */ q_graphicsproxywidget_actions(void* self);
void q_graphicsproxywidget_set_attribute(void* self, int64_t attribute);
bool q_graphicsproxywidget_test_attribute(void* self, int64_t attribute);
void q_graphicsproxywidget_geometry_changed(void* self);
void q_graphicsproxywidget_on_geometry_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_layout_changed(void* self);
void q_graphicsproxywidget_on_layout_changed(void* self, void (*slot)(void*));
bool q_graphicsproxywidget_close(void* self);
int32_t q_graphicsproxywidget_grab_shortcut2(void* self, void* sequence, int64_t context);
void q_graphicsproxywidget_set_shortcut_enabled2(void* self, int id, bool enabled);
void q_graphicsproxywidget_set_shortcut_auto_repeat2(void* self, int id, bool enabled);
void q_graphicsproxywidget_set_attribute2(void* self, int64_t attribute, bool on);
void q_graphicsproxywidget_grab_gesture(void* self, int64_t typeVal);
void q_graphicsproxywidget_ungrab_gesture(void* self, int64_t typeVal);
void q_graphicsproxywidget_parent_changed(void* self);
void q_graphicsproxywidget_on_parent_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_opacity_changed(void* self);
void q_graphicsproxywidget_on_opacity_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_visible_changed(void* self);
void q_graphicsproxywidget_on_visible_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_enabled_changed(void* self);
void q_graphicsproxywidget_on_enabled_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_x_changed(void* self);
void q_graphicsproxywidget_on_x_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_y_changed(void* self);
void q_graphicsproxywidget_on_y_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_z_changed(void* self);
void q_graphicsproxywidget_on_z_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_rotation_changed(void* self);
void q_graphicsproxywidget_on_rotation_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_scale_changed(void* self);
void q_graphicsproxywidget_on_scale_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_children_changed(void* self);
void q_graphicsproxywidget_on_children_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_width_changed(void* self);
void q_graphicsproxywidget_on_width_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_height_changed(void* self);
void q_graphicsproxywidget_on_height_changed(void* self, void (*slot)(void*));
void q_graphicsproxywidget_grab_gesture2(void* self, int64_t typeVal, int64_t flags);
const char* q_graphicsproxywidget_object_name(void* self);
void q_graphicsproxywidget_set_object_name(void* self, const char* name);
bool q_graphicsproxywidget_is_widget_type(void* self);
bool q_graphicsproxywidget_is_window_type(void* self);
bool q_graphicsproxywidget_is_quick_item_type(void* self);
bool q_graphicsproxywidget_signals_blocked(void* self);
bool q_graphicsproxywidget_block_signals(void* self, bool b);
QThread* q_graphicsproxywidget_thread(void* self);
void q_graphicsproxywidget_move_to_thread(void* self, void* thread);
int32_t q_graphicsproxywidget_start_timer(void* self, int interval);
void q_graphicsproxywidget_kill_timer(void* self, int id);
libqt_list /* of QObject* */ q_graphicsproxywidget_children(void* self);
void q_graphicsproxywidget_set_parent(void* self, void* parent);
void q_graphicsproxywidget_install_event_filter(void* self, void* filterObj);
void q_graphicsproxywidget_remove_event_filter(void* self, void* obj);
QMetaObject__Connection* q_graphicsproxywidget_connect(void* sender, void* signal, void* receiver, void* method);
QMetaObject__Connection* q_graphicsproxywidget_connect2(void* self, void* sender, const char* signal, const char* member);
bool q_graphicsproxywidget_disconnect(void* sender, void* signal, void* receiver, void* member);
bool q_graphicsproxywidget_disconnect_with_q_meta_object_connection(void* param1);
void q_graphicsproxywidget_dump_object_tree(void* self);
void q_graphicsproxywidget_dump_object_info(void* self);
bool q_graphicsproxywidget_set_property(void* self, const char* name, void* value);
QVariant* q_graphicsproxywidget_property(void* self, const char* name);
const char** q_graphicsproxywidget_dynamic_property_names(void* self);
QBindingStorage* q_graphicsproxywidget_binding_storage(void* self);
QBindingStorage* q_graphicsproxywidget_binding_storage2(void* self);
void q_graphicsproxywidget_destroyed(void* self);
void q_graphicsproxywidget_on_destroyed(void* self, void (*slot)(void*));
QObject* q_graphicsproxywidget_parent(void* self);
bool q_graphicsproxywidget_inherits(void* self, const char* classname);
void q_graphicsproxywidget_delete_later(void* self);
int32_t q_graphicsproxywidget_start_timer2(void* self, int interval, int64_t timerType);
QMetaObject__Connection* q_graphicsproxywidget_connect5(void* sender, void* signal, void* receiver, void* method, int64_t typeVal);
QMetaObject__Connection* q_graphicsproxywidget_connect4(void* self, void* sender, const char* signal, const char* member, int64_t typeVal);
void q_graphicsproxywidget_destroyed1(void* self, void* param1);
void q_graphicsproxywidget_on_destroyed1(void* self, void (*slot)(void*, void*));
QGraphicsScene* q_graphicsproxywidget_scene(void* self);
QGraphicsItem* q_graphicsproxywidget_parent_item(void* self);
QGraphicsItem* q_graphicsproxywidget_top_level_item(void* self);
QGraphicsObject* q_graphicsproxywidget_parent_object(void* self);
QGraphicsWidget* q_graphicsproxywidget_parent_widget(void* self);
QGraphicsWidget* q_graphicsproxywidget_top_level_widget(void* self);
QGraphicsWidget* q_graphicsproxywidget_window(void* self);
QGraphicsItem* q_graphicsproxywidget_panel(void* self);
void q_graphicsproxywidget_set_parent_item(void* self, void* parent);
libqt_list /* of QGraphicsItem* */ q_graphicsproxywidget_child_items(void* self);
bool q_graphicsproxywidget_is_widget(void* self);
bool q_graphicsproxywidget_is_window(void* self);
bool q_graphicsproxywidget_is_panel(void* self);
QGraphicsObject* q_graphicsproxywidget_to_graphics_object(void* self);
QGraphicsObject* q_graphicsproxywidget_to_graphics_object2(void* self);
QGraphicsItemGroup* q_graphicsproxywidget_group(void* self);
void q_graphicsproxywidget_set_group(void* self, void* group);
int64_t q_graphicsproxywidget_flags(void* self);
void q_graphicsproxywidget_set_flag(void* self, int64_t flag);
void q_graphicsproxywidget_set_flags(void* self, int64_t flags);
int64_t q_graphicsproxywidget_cache_mode(void* self);
void q_graphicsproxywidget_set_cache_mode(void* self, int64_t mode);
int64_t q_graphicsproxywidget_panel_modality(void* self);
void q_graphicsproxywidget_set_panel_modality(void* self, int64_t panelModality);
bool q_graphicsproxywidget_is_blocked_by_modal_panel(void* self);
const char* q_graphicsproxywidget_tool_tip(void* self);
void q_graphicsproxywidget_set_tool_tip(void* self, const char* toolTip);
QCursor* q_graphicsproxywidget_cursor(void* self);
void q_graphicsproxywidget_set_cursor(void* self, void* cursor);
bool q_graphicsproxywidget_has_cursor(void* self);
void q_graphicsproxywidget_unset_cursor(void* self);
bool q_graphicsproxywidget_is_visible(void* self);
bool q_graphicsproxywidget_is_visible_to(void* self, void* parent);
void q_graphicsproxywidget_set_visible(void* self, bool visible);
void q_graphicsproxywidget_hide(void* self);
void q_graphicsproxywidget_show(void* self);
bool q_graphicsproxywidget_is_enabled(void* self);
void q_graphicsproxywidget_set_enabled(void* self, bool enabled);
bool q_graphicsproxywidget_is_selected(void* self);
void q_graphicsproxywidget_set_selected(void* self, bool selected);
bool q_graphicsproxywidget_accept_drops(void* self);
void q_graphicsproxywidget_set_accept_drops(void* self, bool on);
double q_graphicsproxywidget_opacity(void* self);
double q_graphicsproxywidget_effective_opacity(void* self);
void q_graphicsproxywidget_set_opacity(void* self, double opacity);
QGraphicsEffect* q_graphicsproxywidget_graphics_effect(void* self);
void q_graphicsproxywidget_set_graphics_effect(void* self, void* effect);
int64_t q_graphicsproxywidget_accepted_mouse_buttons(void* self);
void q_graphicsproxywidget_set_accepted_mouse_buttons(void* self, int64_t buttons);
bool q_graphicsproxywidget_accept_hover_events(void* self);
void q_graphicsproxywidget_set_accept_hover_events(void* self, bool enabled);
bool q_graphicsproxywidget_accept_touch_events(void* self);
void q_graphicsproxywidget_set_accept_touch_events(void* self, bool enabled);
bool q_graphicsproxywidget_filters_child_events(void* self);
void q_graphicsproxywidget_set_filters_child_events(void* self, bool enabled);
bool q_graphicsproxywidget_handles_child_events(void* self);
void q_graphicsproxywidget_set_handles_child_events(void* self, bool enabled);
bool q_graphicsproxywidget_is_active(void* self);
void q_graphicsproxywidget_set_active(void* self, bool active);
bool q_graphicsproxywidget_has_focus(void* self);
void q_graphicsproxywidget_set_focus(void* self);
void q_graphicsproxywidget_clear_focus(void* self);
QGraphicsItem* q_graphicsproxywidget_focus_proxy(void* self);
void q_graphicsproxywidget_set_focus_proxy(void* self, void* item);
QGraphicsItem* q_graphicsproxywidget_focus_item(void* self);
QGraphicsItem* q_graphicsproxywidget_focus_scope_item(void* self);
void q_graphicsproxywidget_grab_mouse(void* self);
void q_graphicsproxywidget_ungrab_mouse(void* self);
void q_graphicsproxywidget_grab_keyboard(void* self);
void q_graphicsproxywidget_ungrab_keyboard(void* self);
QPointF* q_graphicsproxywidget_pos(void* self);
double q_graphicsproxywidget_x(void* self);
void q_graphicsproxywidget_set_x(void* self, double x);
double q_graphicsproxywidget_y(void* self);
void q_graphicsproxywidget_set_y(void* self, double y);
QPointF* q_graphicsproxywidget_scene_pos(void* self);
void q_graphicsproxywidget_set_pos(void* self, void* pos);
void q_graphicsproxywidget_set_pos2(void* self, double x, double y);
void q_graphicsproxywidget_move_by(void* self, double dx, double dy);
void q_graphicsproxywidget_ensure_visible(void* self);
void q_graphicsproxywidget_ensure_visible2(void* self, double x, double y, double w, double h);
QTransform* q_graphicsproxywidget_transform(void* self);
QTransform* q_graphicsproxywidget_scene_transform(void* self);
QTransform* q_graphicsproxywidget_device_transform(void* self, void* viewportTransform);
QTransform* q_graphicsproxywidget_item_transform(void* self, void* other);
void q_graphicsproxywidget_set_transform(void* self, void* matrix);
void q_graphicsproxywidget_reset_transform(void* self);
void q_graphicsproxywidget_set_rotation(void* self, double angle);
double q_graphicsproxywidget_rotation(void* self);
void q_graphicsproxywidget_set_scale(void* self, double scale);
double q_graphicsproxywidget_scale(void* self);
libqt_list /* of QGraphicsTransform* */ q_graphicsproxywidget_transformations(void* self);
void q_graphicsproxywidget_set_transformations(void* self, void* transformations[]);
QPointF* q_graphicsproxywidget_transform_origin_point(void* self);
void q_graphicsproxywidget_set_transform_origin_point(void* self, void* origin);
void q_graphicsproxywidget_set_transform_origin_point2(void* self, double ax, double ay);
double q_graphicsproxywidget_z_value(void* self);
void q_graphicsproxywidget_set_z_value(void* self, double z);
void q_graphicsproxywidget_stack_before(void* self, void* sibling);
QRectF* q_graphicsproxywidget_children_bounding_rect(void* self);
QRectF* q_graphicsproxywidget_scene_bounding_rect(void* self);
bool q_graphicsproxywidget_is_clipped(void* self);
QPainterPath* q_graphicsproxywidget_clip_path(void* self);
libqt_list /* of QGraphicsItem* */ q_graphicsproxywidget_colliding_items(void* self);
bool q_graphicsproxywidget_is_obscured(void* self);
bool q_graphicsproxywidget_is_obscured2(void* self, double x, double y, double w, double h);
QRegion* q_graphicsproxywidget_bounding_region(void* self, void* itemToDeviceTransform);
double q_graphicsproxywidget_bounding_region_granularity(void* self);
void q_graphicsproxywidget_set_bounding_region_granularity(void* self, double granularity);
void q_graphicsproxywidget_update(void* self);
void q_graphicsproxywidget_update2(void* self, double x, double y, double width, double height);
void q_graphicsproxywidget_scroll(void* self, double dx, double dy);
QPointF* q_graphicsproxywidget_map_to_item(void* self, void* item, void* point);
QPointF* q_graphicsproxywidget_map_to_parent(void* self, void* point);
QPointF* q_graphicsproxywidget_map_to_scene(void* self, void* point);
QRectF* q_graphicsproxywidget_map_rect_to_item(void* self, void* item, void* rect);
QRectF* q_graphicsproxywidget_map_rect_to_parent(void* self, void* rect);
QRectF* q_graphicsproxywidget_map_rect_to_scene(void* self, void* rect);
QPainterPath* q_graphicsproxywidget_map_to_item4(void* self, void* item, void* path);
QPainterPath* q_graphicsproxywidget_map_to_parent_with_path(void* self, void* path);
QPainterPath* q_graphicsproxywidget_map_to_scene_with_path(void* self, void* path);
QPointF* q_graphicsproxywidget_map_from_item(void* self, void* item, void* point);
QPointF* q_graphicsproxywidget_map_from_parent(void* self, void* point);
QPointF* q_graphicsproxywidget_map_from_scene(void* self, void* point);
QRectF* q_graphicsproxywidget_map_rect_from_item(void* self, void* item, void* rect);
QRectF* q_graphicsproxywidget_map_rect_from_parent(void* self, void* rect);
QRectF* q_graphicsproxywidget_map_rect_from_scene(void* self, void* rect);
QPainterPath* q_graphicsproxywidget_map_from_item4(void* self, void* item, void* path);
QPainterPath* q_graphicsproxywidget_map_from_parent_with_path(void* self, void* path);
QPainterPath* q_graphicsproxywidget_map_from_scene_with_path(void* self, void* path);
QPointF* q_graphicsproxywidget_map_to_item5(void* self, void* item, double x, double y);
QPointF* q_graphicsproxywidget_map_to_parent2(void* self, double x, double y);
QPointF* q_graphicsproxywidget_map_to_scene2(void* self, double x, double y);
QRectF* q_graphicsproxywidget_map_rect_to_item2(void* self, void* item, double x, double y, double w, double h);
QRectF* q_graphicsproxywidget_map_rect_to_parent2(void* self, double x, double y, double w, double h);
QRectF* q_graphicsproxywidget_map_rect_to_scene2(void* self, double x, double y, double w, double h);
QPointF* q_graphicsproxywidget_map_from_item5(void* self, void* item, double x, double y);
QPointF* q_graphicsproxywidget_map_from_parent2(void* self, double x, double y);
QPointF* q_graphicsproxywidget_map_from_scene2(void* self, double x, double y);
QRectF* q_graphicsproxywidget_map_rect_from_item2(void* self, void* item, double x, double y, double w, double h);
QRectF* q_graphicsproxywidget_map_rect_from_parent2(void* self, double x, double y, double w, double h);
QRectF* q_graphicsproxywidget_map_rect_from_scene2(void* self, double x, double y, double w, double h);
bool q_graphicsproxywidget_is_ancestor_of(void* self, void* child);
QGraphicsItem* q_graphicsproxywidget_common_ancestor_item(void* self, void* other);
bool q_graphicsproxywidget_is_under_mouse(void* self);
QVariant* q_graphicsproxywidget_data(void* self, int key);
void q_graphicsproxywidget_set_data(void* self, int key, void* value);
int64_t q_graphicsproxywidget_input_method_hints(void* self);
void q_graphicsproxywidget_set_input_method_hints(void* self, int64_t hints);
void q_graphicsproxywidget_install_scene_event_filter(void* self, void* filterItem);
void q_graphicsproxywidget_remove_scene_event_filter(void* self, void* filterItem);
void q_graphicsproxywidget_set_flag2(void* self, int64_t flag, bool enabled);
void q_graphicsproxywidget_set_cache_mode2(void* self, int64_t mode, void* cacheSize);
void q_graphicsproxywidget_set_focus1(void* self, int64_t focusReason);
void q_graphicsproxywidget_ensure_visible1(void* self, void* rect);
void q_graphicsproxywidget_ensure_visible22(void* self, void* rect, int xmargin);
void q_graphicsproxywidget_ensure_visible3(void* self, void* rect, int xmargin, int ymargin);
void q_graphicsproxywidget_ensure_visible5(void* self, double x, double y, double w, double h, int xmargin);
void q_graphicsproxywidget_ensure_visible6(void* self, double x, double y, double w, double h, int xmargin, int ymargin);
QTransform* q_graphicsproxywidget_item_transform2(void* self, void* other, bool* ok);
void q_graphicsproxywidget_set_transform2(void* self, void* matrix, bool combine);
libqt_list /* of QGraphicsItem* */ q_graphicsproxywidget_colliding_items1(void* self, int64_t mode);
bool q_graphicsproxywidget_is_obscured1(void* self, void* rect);
void q_graphicsproxywidget_update1(void* self, void* rect);
void q_graphicsproxywidget_scroll3(void* self, double dx, double dy, void* rect);
void q_graphicsproxywidget_set_size_policy(void* self, void* policy);
void q_graphicsproxywidget_set_size_policy2(void* self, int64_t hPolicy, int64_t vPolicy);
QSizePolicy* q_graphicsproxywidget_size_policy(void* self);
void q_graphicsproxywidget_set_minimum_size(void* self, void* size);
void q_graphicsproxywidget_set_minimum_size2(void* self, double w, double h);
QSizeF* q_graphicsproxywidget_minimum_size(void* self);
void q_graphicsproxywidget_set_minimum_width(void* self, double width);
double q_graphicsproxywidget_minimum_width(void* self);
void q_graphicsproxywidget_set_minimum_height(void* self, double height);
double q_graphicsproxywidget_minimum_height(void* self);
void q_graphicsproxywidget_set_preferred_size(void* self, void* size);
void q_graphicsproxywidget_set_preferred_size2(void* self, double w, double h);
QSizeF* q_graphicsproxywidget_preferred_size(void* self);
void q_graphicsproxywidget_set_preferred_width(void* self, double width);
double q_graphicsproxywidget_preferred_width(void* self);
void q_graphicsproxywidget_set_preferred_height(void* self, double height);
double q_graphicsproxywidget_preferred_height(void* self);
void q_graphicsproxywidget_set_maximum_size(void* self, void* size);
void q_graphicsproxywidget_set_maximum_size2(void* self, double w, double h);
QSizeF* q_graphicsproxywidget_maximum_size(void* self);
void q_graphicsproxywidget_set_maximum_width(void* self, double width);
double q_graphicsproxywidget_maximum_width(void* self);
void q_graphicsproxywidget_set_maximum_height(void* self, double height);
double q_graphicsproxywidget_maximum_height(void* self);
QRectF* q_graphicsproxywidget_geometry(void* self);
QRectF* q_graphicsproxywidget_contents_rect(void* self);
QSizeF* q_graphicsproxywidget_effective_size_hint(void* self, int64_t which);
QGraphicsLayoutItem* q_graphicsproxywidget_parent_layout_item(void* self);
void q_graphicsproxywidget_set_parent_layout_item(void* self, void* parent);
bool q_graphicsproxywidget_is_layout(void* self);
QGraphicsItem* q_graphicsproxywidget_graphics_item(void* self);
bool q_graphicsproxywidget_owned_by_layout(void* self);
void q_graphicsproxywidget_set_size_policy3(void* self, int64_t hPolicy, int64_t vPolicy, int64_t controlType);
QSizeF* q_graphicsproxywidget_effective_size_hint2(void* self, int64_t which, void* constraint);
void q_graphicsproxywidget_get_contents_margins(void* self, double* left, double* top, double* right, double* bottom);
void q_graphicsproxywidget_qbase_get_contents_margins(void* self, double* left, double* top, double* right, double* bottom);
void q_graphicsproxywidget_on_get_contents_margins(void* self, void (*slot)(void*, double*, double*, double*, double*));
void q_graphicsproxywidget_paint_window_frame(void* self, void* painter, void* option, void* widget);
void q_graphicsproxywidget_qbase_paint_window_frame(void* self, void* painter, void* option, void* widget);
void q_graphicsproxywidget_on_paint_window_frame(void* self, void (*slot)(void*, void*, void*, void*));
QRectF* q_graphicsproxywidget_bounding_rect(void* self);
QRectF* q_graphicsproxywidget_qbase_bounding_rect(void* self);
void q_graphicsproxywidget_on_bounding_rect(void* self, QRectF* (*slot)());
QPainterPath* q_graphicsproxywidget_shape(void* self);
QPainterPath* q_graphicsproxywidget_qbase_shape(void* self);
void q_graphicsproxywidget_on_shape(void* self, QPainterPath* (*slot)());
void q_graphicsproxywidget_init_style_option(void* self, void* option);
void q_graphicsproxywidget_qbase_init_style_option(void* self, void* option);
void q_graphicsproxywidget_on_init_style_option(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_update_geometry(void* self);
void q_graphicsproxywidget_qbase_update_geometry(void* self);
void q_graphicsproxywidget_on_update_geometry(void* self, void (*slot)());
QVariant* q_graphicsproxywidget_property_change(void* self, const char* propertyName, void* value);
QVariant* q_graphicsproxywidget_qbase_property_change(void* self, const char* propertyName, void* value);
void q_graphicsproxywidget_on_property_change(void* self, QVariant* (*slot)(void*, const char*, void*));
bool q_graphicsproxywidget_scene_event(void* self, void* event);
bool q_graphicsproxywidget_qbase_scene_event(void* self, void* event);
void q_graphicsproxywidget_on_scene_event(void* self, bool (*slot)(void*, void*));
bool q_graphicsproxywidget_window_frame_event(void* self, void* e);
bool q_graphicsproxywidget_qbase_window_frame_event(void* self, void* e);
void q_graphicsproxywidget_on_window_frame_event(void* self, bool (*slot)(void*, void*));
int64_t q_graphicsproxywidget_window_frame_section_at(void* self, void* pos);
int64_t q_graphicsproxywidget_qbase_window_frame_section_at(void* self, void* pos);
void q_graphicsproxywidget_on_window_frame_section_at(void* self, int64_t (*slot)(void*, void*));
void q_graphicsproxywidget_change_event(void* self, void* event);
void q_graphicsproxywidget_qbase_change_event(void* self, void* event);
void q_graphicsproxywidget_on_change_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_close_event(void* self, void* event);
void q_graphicsproxywidget_qbase_close_event(void* self, void* event);
void q_graphicsproxywidget_on_close_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_move_event(void* self, void* event);
void q_graphicsproxywidget_qbase_move_event(void* self, void* event);
void q_graphicsproxywidget_on_move_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_polish_event(void* self);
void q_graphicsproxywidget_qbase_polish_event(void* self);
void q_graphicsproxywidget_on_polish_event(void* self, void (*slot)());
void q_graphicsproxywidget_grab_keyboard_event(void* self, void* event);
void q_graphicsproxywidget_qbase_grab_keyboard_event(void* self, void* event);
void q_graphicsproxywidget_on_grab_keyboard_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_ungrab_keyboard_event(void* self, void* event);
void q_graphicsproxywidget_qbase_ungrab_keyboard_event(void* self, void* event);
void q_graphicsproxywidget_on_ungrab_keyboard_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_timer_event(void* self, void* event);
void q_graphicsproxywidget_qbase_timer_event(void* self, void* event);
void q_graphicsproxywidget_on_timer_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_child_event(void* self, void* event);
void q_graphicsproxywidget_qbase_child_event(void* self, void* event);
void q_graphicsproxywidget_on_child_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_custom_event(void* self, void* event);
void q_graphicsproxywidget_qbase_custom_event(void* self, void* event);
void q_graphicsproxywidget_on_custom_event(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_connect_notify(void* self, void* signal);
void q_graphicsproxywidget_qbase_connect_notify(void* self, void* signal);
void q_graphicsproxywidget_on_connect_notify(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_disconnect_notify(void* self, void* signal);
void q_graphicsproxywidget_qbase_disconnect_notify(void* self, void* signal);
void q_graphicsproxywidget_on_disconnect_notify(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_advance(void* self, int phase);
void q_graphicsproxywidget_qbase_advance(void* self, int phase);
void q_graphicsproxywidget_on_advance(void* self, void (*slot)(void*, int));
bool q_graphicsproxywidget_contains(void* self, void* point);
bool q_graphicsproxywidget_qbase_contains(void* self, void* point);
void q_graphicsproxywidget_on_contains(void* self, bool (*slot)(void*, void*));
bool q_graphicsproxywidget_collides_with_item(void* self, void* other, int64_t mode);
bool q_graphicsproxywidget_qbase_collides_with_item(void* self, void* other, int64_t mode);
void q_graphicsproxywidget_on_collides_with_item(void* self, bool (*slot)(void*, void*, int64_t));
bool q_graphicsproxywidget_collides_with_path(void* self, void* path, int64_t mode);
bool q_graphicsproxywidget_qbase_collides_with_path(void* self, void* path, int64_t mode);
void q_graphicsproxywidget_on_collides_with_path(void* self, bool (*slot)(void*, void*, int64_t));
bool q_graphicsproxywidget_is_obscured_by(void* self, void* item);
bool q_graphicsproxywidget_qbase_is_obscured_by(void* self, void* item);
void q_graphicsproxywidget_on_is_obscured_by(void* self, bool (*slot)(void*, void*));
QPainterPath* q_graphicsproxywidget_opaque_area(void* self);
QPainterPath* q_graphicsproxywidget_qbase_opaque_area(void* self);
void q_graphicsproxywidget_on_opaque_area(void* self, QPainterPath* (*slot)());
bool q_graphicsproxywidget_scene_event_filter(void* self, void* watched, void* event);
bool q_graphicsproxywidget_qbase_scene_event_filter(void* self, void* watched, void* event);
void q_graphicsproxywidget_on_scene_event_filter(void* self, bool (*slot)(void*, void*, void*));
bool q_graphicsproxywidget_supports_extension(void* self, int64_t extension);
bool q_graphicsproxywidget_qbase_supports_extension(void* self, int64_t extension);
void q_graphicsproxywidget_on_supports_extension(void* self, bool (*slot)(void*, int64_t));
void q_graphicsproxywidget_set_extension(void* self, int64_t extension, void* variant);
void q_graphicsproxywidget_qbase_set_extension(void* self, int64_t extension, void* variant);
void q_graphicsproxywidget_on_set_extension(void* self, void (*slot)(void*, int64_t, void*));
QVariant* q_graphicsproxywidget_extension(void* self, void* variant);
QVariant* q_graphicsproxywidget_qbase_extension(void* self, void* variant);
void q_graphicsproxywidget_on_extension(void* self, QVariant* (*slot)(void*, void*));
bool q_graphicsproxywidget_is_empty(void* self);
bool q_graphicsproxywidget_qbase_is_empty(void* self);
void q_graphicsproxywidget_on_is_empty(void* self, bool (*slot)());
void q_graphicsproxywidget_update_micro_focus(void* self);
void q_graphicsproxywidget_qbase_update_micro_focus(void* self);
void q_graphicsproxywidget_on_update_micro_focus(void* self, void (*slot)());
QObject* q_graphicsproxywidget_sender(void* self);
QObject* q_graphicsproxywidget_qbase_sender(void* self);
void q_graphicsproxywidget_on_sender(void* self, QObject* (*slot)());
int32_t q_graphicsproxywidget_sender_signal_index(void* self);
int32_t q_graphicsproxywidget_qbase_sender_signal_index(void* self);
void q_graphicsproxywidget_on_sender_signal_index(void* self, int32_t (*slot)());
int32_t q_graphicsproxywidget_receivers(void* self, const char* signal);
int32_t q_graphicsproxywidget_qbase_receivers(void* self, const char* signal);
void q_graphicsproxywidget_on_receivers(void* self, int32_t (*slot)(void*, const char*));
bool q_graphicsproxywidget_is_signal_connected(void* self, void* signal);
bool q_graphicsproxywidget_qbase_is_signal_connected(void* self, void* signal);
void q_graphicsproxywidget_on_is_signal_connected(void* self, bool (*slot)(void*, void*));
void q_graphicsproxywidget_add_to_index(void* self);
void q_graphicsproxywidget_qbase_add_to_index(void* self);
void q_graphicsproxywidget_on_add_to_index(void* self, void (*slot)());
void q_graphicsproxywidget_remove_from_index(void* self);
void q_graphicsproxywidget_qbase_remove_from_index(void* self);
void q_graphicsproxywidget_on_remove_from_index(void* self, void (*slot)());
void q_graphicsproxywidget_prepare_geometry_change(void* self);
void q_graphicsproxywidget_qbase_prepare_geometry_change(void* self);
void q_graphicsproxywidget_on_prepare_geometry_change(void* self, void (*slot)());
void q_graphicsproxywidget_set_graphics_item(void* self, void* item);
void q_graphicsproxywidget_qbase_set_graphics_item(void* self, void* item);
void q_graphicsproxywidget_on_set_graphics_item(void* self, void (*slot)(void*, void*));
void q_graphicsproxywidget_set_owned_by_layout(void* self, bool ownedByLayout);
void q_graphicsproxywidget_qbase_set_owned_by_layout(void* self, bool ownedByLayout);
void q_graphicsproxywidget_on_set_owned_by_layout(void* self, void (*slot)(void*, bool));
void q_graphicsproxywidget_delete(void* self);

/// https://doc.qt.io/qt-6/qgraphicsproxywidget.html#types

typedef enum {
    QGRAPHICSPROXYWIDGET__TYPE = 12
} QGraphicsProxyWidget__;

#endif
