#pragma once
#ifndef SRCQT6C_LIBQDIAL_H
#define SRCQT6C_LIBQDIAL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#include "libqabstractslider.h"
#include "libqaction.h"
#include "libqevent.h"
#include "libqanystringview.h"
#include "libqbackingstore.h"
#include "libqbindingstorage.h"
#include "libqbitmap.h"
#include "libqcursor.h"
#include "libqfont.h"
#include "libqfontinfo.h"
#include "libqfontmetrics.h"
#include "libqgraphicseffect.h"
#include "libqgraphicsproxywidget.h"
#include "libqicon.h"
#include "libqkeysequence.h"
#include "libqlayout.h"
#include "libqlocale.h"
#include "libqmargins.h"
#include "libqmetaobject.h"
#include "libqobject.h"
#include "libqpaintdevice.h"
#include "libqpaintengine.h"
#include "libqpainter.h"
#include "libqpalette.h"
#include "libqpixmap.h"
#include "libqpoint.h"
#include "libqrect.h"
#include "libqregion.h"
#include "libqscreen.h"
#include "libqsize.h"
#include "libqsizepolicy.h"
#include <string.h>
#include "libqstyle.h"
#include "libqstyleoption.h"
#include "libqthread.h"
#include "libqvariant.h"
#include "libqwidget.h"
#include "libqwindow.h"

QDial* q_dial_new(void* parent);
QDial* q_dial_new2();
QMetaObject* q_dial_meta_object(void* self);
void* q_dial_metacast(void* self, const char* param1);
int32_t q_dial_metacall(void* self, int64_t param1, int param2, void* param3);
void q_dial_on_metacall(void* self, int32_t (*slot)(void*, int64_t, int, void*));
int32_t q_dial_qbase_metacall(void* self, int64_t param1, int param2, void* param3);
const char* q_dial_tr(const char* s);
bool q_dial_wrapping(void* self);
int32_t q_dial_notch_size(void* self);
void q_dial_set_notch_target(void* self, double target);
double q_dial_notch_target(void* self);
bool q_dial_notches_visible(void* self);
QSize* q_dial_size_hint(void* self);
void q_dial_on_size_hint(void* self, QSize* (*slot)());
QSize* q_dial_qbase_size_hint(void* self);
QSize* q_dial_minimum_size_hint(void* self);
void q_dial_on_minimum_size_hint(void* self, QSize* (*slot)());
QSize* q_dial_qbase_minimum_size_hint(void* self);
void q_dial_set_notches_visible(void* self, bool visible);
void q_dial_set_wrapping(void* self, bool on);
bool q_dial_event(void* self, void* e);
void q_dial_on_event(void* self, bool (*slot)(void*, void*));
bool q_dial_qbase_event(void* self, void* e);
void q_dial_resize_event(void* self, void* re);
void q_dial_on_resize_event(void* self, void (*slot)(void*, void*));
void q_dial_qbase_resize_event(void* self, void* re);
void q_dial_paint_event(void* self, void* pe);
void q_dial_on_paint_event(void* self, void (*slot)(void*, void*));
void q_dial_qbase_paint_event(void* self, void* pe);
void q_dial_mouse_press_event(void* self, void* me);
void q_dial_on_mouse_press_event(void* self, void (*slot)(void*, void*));
void q_dial_qbase_mouse_press_event(void* self, void* me);
void q_dial_mouse_release_event(void* self, void* me);
void q_dial_on_mouse_release_event(void* self, void (*slot)(void*, void*));
void q_dial_qbase_mouse_release_event(void* self, void* me);
void q_dial_mouse_move_event(void* self, void* me);
void q_dial_on_mouse_move_event(void* self, void (*slot)(void*, void*));
void q_dial_qbase_mouse_move_event(void* self, void* me);
void q_dial_slider_change(void* self, int64_t change);
void q_dial_on_slider_change(void* self, void (*slot)(void*, int64_t));
void q_dial_qbase_slider_change(void* self, int64_t change);
void q_dial_init_style_option(void* self, void* option);
void q_dial_on_init_style_option(void* self, void (*slot)(void*, void*));
void q_dial_qbase_init_style_option(void* self, void* option);
const char* q_dial_tr2(const char* s, const char* c);
const char* q_dial_tr3(const char* s, const char* c, int n);
int64_t q_dial_orientation(void* self);
void q_dial_set_minimum(void* self, int minimum);
int32_t q_dial_minimum(void* self);
void q_dial_set_maximum(void* self, int maximum);
int32_t q_dial_maximum(void* self);
void q_dial_set_single_step(void* self, int singleStep);
int32_t q_dial_single_step(void* self);
void q_dial_set_page_step(void* self, int pageStep);
int32_t q_dial_page_step(void* self);
void q_dial_set_tracking(void* self, bool enable);
bool q_dial_has_tracking(void* self);
void q_dial_set_slider_down(void* self, bool sliderDown);
bool q_dial_is_slider_down(void* self);
void q_dial_set_slider_position(void* self, int sliderPosition);
int32_t q_dial_slider_position(void* self);
void q_dial_set_inverted_appearance(void* self, bool invertedAppearance);
bool q_dial_inverted_appearance(void* self);
void q_dial_set_inverted_controls(void* self, bool invertedControls);
bool q_dial_inverted_controls(void* self);
int32_t q_dial_value(void* self);
void q_dial_trigger_action(void* self, int64_t action);
void q_dial_set_value(void* self, int value);
void q_dial_set_orientation(void* self, int64_t orientation);
void q_dial_set_range(void* self, int min, int max);
void q_dial_value_changed(void* self, int value);
void q_dial_on_value_changed(void* self, void (*slot)(void*, int));
void q_dial_slider_pressed(void* self);
void q_dial_on_slider_pressed(void* self, void (*slot)(void*));
void q_dial_slider_moved(void* self, int position);
void q_dial_on_slider_moved(void* self, void (*slot)(void*, int));
void q_dial_slider_released(void* self);
void q_dial_on_slider_released(void* self, void (*slot)(void*));
void q_dial_range_changed(void* self, int min, int max);
void q_dial_on_range_changed(void* self, void (*slot)(void*, int, int));
void q_dial_action_triggered(void* self, int action);
void q_dial_on_action_triggered(void* self, void (*slot)(void*, int));
uintptr_t q_dial_win_id(void* self);
void q_dial_create_win_id(void* self);
uintptr_t q_dial_internal_win_id(void* self);
uintptr_t q_dial_effective_win_id(void* self);
QStyle* q_dial_style(void* self);
void q_dial_set_style(void* self, void* style);
bool q_dial_is_top_level(void* self);
bool q_dial_is_window(void* self);
bool q_dial_is_modal(void* self);
int64_t q_dial_window_modality(void* self);
void q_dial_set_window_modality(void* self, int64_t windowModality);
bool q_dial_is_enabled(void* self);
bool q_dial_is_enabled_to(void* self, void* param1);
void q_dial_set_enabled(void* self, bool enabled);
void q_dial_set_disabled(void* self, bool disabled);
void q_dial_set_window_modified(void* self, bool windowModified);
QRect* q_dial_frame_geometry(void* self);
QRect* q_dial_geometry(void* self);
QRect* q_dial_normal_geometry(void* self);
int32_t q_dial_x(void* self);
int32_t q_dial_y(void* self);
QPoint* q_dial_pos(void* self);
QSize* q_dial_frame_size(void* self);
QSize* q_dial_size(void* self);
int32_t q_dial_width(void* self);
int32_t q_dial_height(void* self);
QRect* q_dial_rect(void* self);
QRect* q_dial_children_rect(void* self);
QRegion* q_dial_children_region(void* self);
QSize* q_dial_minimum_size(void* self);
QSize* q_dial_maximum_size(void* self);
int32_t q_dial_minimum_width(void* self);
int32_t q_dial_minimum_height(void* self);
int32_t q_dial_maximum_width(void* self);
int32_t q_dial_maximum_height(void* self);
void q_dial_set_minimum_size(void* self, void* minimumSize);
void q_dial_set_minimum_size2(void* self, int minw, int minh);
void q_dial_set_maximum_size(void* self, void* maximumSize);
void q_dial_set_maximum_size2(void* self, int maxw, int maxh);
void q_dial_set_minimum_width(void* self, int minw);
void q_dial_set_minimum_height(void* self, int minh);
void q_dial_set_maximum_width(void* self, int maxw);
void q_dial_set_maximum_height(void* self, int maxh);
QSize* q_dial_size_increment(void* self);
void q_dial_set_size_increment(void* self, void* sizeIncrement);
void q_dial_set_size_increment2(void* self, int w, int h);
QSize* q_dial_base_size(void* self);
void q_dial_set_base_size(void* self, void* baseSize);
void q_dial_set_base_size2(void* self, int basew, int baseh);
void q_dial_set_fixed_size(void* self, void* fixedSize);
void q_dial_set_fixed_size2(void* self, int w, int h);
void q_dial_set_fixed_width(void* self, int w);
void q_dial_set_fixed_height(void* self, int h);
QPointF* q_dial_map_to_global(void* self, void* param1);
QPoint* q_dial_map_to_global_with_q_point(void* self, void* param1);
QPointF* q_dial_map_from_global(void* self, void* param1);
QPoint* q_dial_map_from_global_with_q_point(void* self, void* param1);
QPointF* q_dial_map_to_parent(void* self, void* param1);
QPoint* q_dial_map_to_parent_with_q_point(void* self, void* param1);
QPointF* q_dial_map_from_parent(void* self, void* param1);
QPoint* q_dial_map_from_parent_with_q_point(void* self, void* param1);
QPointF* q_dial_map_to(void* self, void* param1, void* param2);
QPoint* q_dial_map_to2(void* self, void* param1, void* param2);
QPointF* q_dial_map_from(void* self, void* param1, void* param2);
QPoint* q_dial_map_from2(void* self, void* param1, void* param2);
QWidget* q_dial_window(void* self);
QWidget* q_dial_native_parent_widget(void* self);
QWidget* q_dial_top_level_widget(void* self);
QPalette* q_dial_palette(void* self);
void q_dial_set_palette(void* self, void* palette);
void q_dial_set_background_role(void* self, int64_t backgroundRole);
int64_t q_dial_background_role(void* self);
void q_dial_set_foreground_role(void* self, int64_t foregroundRole);
int64_t q_dial_foreground_role(void* self);
QFont* q_dial_font(void* self);
void q_dial_set_font(void* self, void* font);
QFontMetrics* q_dial_font_metrics(void* self);
QFontInfo* q_dial_font_info(void* self);
QCursor* q_dial_cursor(void* self);
void q_dial_set_cursor(void* self, void* cursor);
void q_dial_unset_cursor(void* self);
void q_dial_set_mouse_tracking(void* self, bool enable);
bool q_dial_has_mouse_tracking(void* self);
bool q_dial_under_mouse(void* self);
void q_dial_set_tablet_tracking(void* self, bool enable);
bool q_dial_has_tablet_tracking(void* self);
void q_dial_set_mask(void* self, void* mask);
void q_dial_set_mask_with_mask(void* self, void* mask);
QRegion* q_dial_mask(void* self);
void q_dial_clear_mask(void* self);
void q_dial_render(void* self, void* target);
void q_dial_render_with_painter(void* self, void* painter);
QPixmap* q_dial_grab(void* self);
QGraphicsEffect* q_dial_graphics_effect(void* self);
void q_dial_set_graphics_effect(void* self, void* effect);
void q_dial_grab_gesture(void* self, int64_t typeVal);
void q_dial_ungrab_gesture(void* self, int64_t typeVal);
void q_dial_set_window_title(void* self, const char* windowTitle);
void q_dial_set_style_sheet(void* self, const char* styleSheet);
const char* q_dial_style_sheet(void* self);
const char* q_dial_window_title(void* self);
void q_dial_set_window_icon(void* self, void* icon);
QIcon* q_dial_window_icon(void* self);
void q_dial_set_window_icon_text(void* self, const char* windowIconText);
const char* q_dial_window_icon_text(void* self);
void q_dial_set_window_role(void* self, const char* windowRole);
const char* q_dial_window_role(void* self);
void q_dial_set_window_file_path(void* self, const char* filePath);
const char* q_dial_window_file_path(void* self);
void q_dial_set_window_opacity(void* self, double level);
double q_dial_window_opacity(void* self);
bool q_dial_is_window_modified(void* self);
void q_dial_set_tool_tip(void* self, const char* toolTip);
const char* q_dial_tool_tip(void* self);
void q_dial_set_tool_tip_duration(void* self, int msec);
int32_t q_dial_tool_tip_duration(void* self);
void q_dial_set_status_tip(void* self, const char* statusTip);
const char* q_dial_status_tip(void* self);
void q_dial_set_whats_this(void* self, const char* whatsThis);
const char* q_dial_whats_this(void* self);
const char* q_dial_accessible_name(void* self);
void q_dial_set_accessible_name(void* self, const char* name);
const char* q_dial_accessible_description(void* self);
void q_dial_set_accessible_description(void* self, const char* description);
void q_dial_set_layout_direction(void* self, int64_t direction);
int64_t q_dial_layout_direction(void* self);
void q_dial_unset_layout_direction(void* self);
void q_dial_set_locale(void* self, void* locale);
QLocale* q_dial_locale(void* self);
void q_dial_unset_locale(void* self);
bool q_dial_is_right_to_left(void* self);
bool q_dial_is_left_to_right(void* self);
void q_dial_set_focus(void* self);
bool q_dial_is_active_window(void* self);
void q_dial_activate_window(void* self);
void q_dial_clear_focus(void* self);
void q_dial_set_focus_with_reason(void* self, int64_t reason);
int64_t q_dial_focus_policy(void* self);
void q_dial_set_focus_policy(void* self, int64_t policy);
bool q_dial_has_focus(void* self);
void q_dial_set_tab_order(void* param1, void* param2);
void q_dial_set_focus_proxy(void* self, void* focusProxy);
QWidget* q_dial_focus_proxy(void* self);
int64_t q_dial_context_menu_policy(void* self);
void q_dial_set_context_menu_policy(void* self, int64_t policy);
void q_dial_grab_mouse(void* self);
void q_dial_grab_mouse_with_q_cursor(void* self, void* param1);
void q_dial_release_mouse(void* self);
void q_dial_grab_keyboard(void* self);
void q_dial_release_keyboard(void* self);
int32_t q_dial_grab_shortcut(void* self, void* key);
void q_dial_release_shortcut(void* self, int id);
void q_dial_set_shortcut_enabled(void* self, int id);
void q_dial_set_shortcut_auto_repeat(void* self, int id);
QWidget* q_dial_mouse_grabber();
QWidget* q_dial_keyboard_grabber();
bool q_dial_updates_enabled(void* self);
void q_dial_set_updates_enabled(void* self, bool enable);
QGraphicsProxyWidget* q_dial_graphics_proxy_widget(void* self);
void q_dial_update(void* self);
void q_dial_repaint(void* self);
void q_dial_update2(void* self, int x, int y, int w, int h);
void q_dial_update_with_q_rect(void* self, void* param1);
void q_dial_update_with_q_region(void* self, void* param1);
void q_dial_repaint2(void* self, int x, int y, int w, int h);
void q_dial_repaint_with_q_rect(void* self, void* param1);
void q_dial_repaint_with_q_region(void* self, void* param1);
void q_dial_set_hidden(void* self, bool hidden);
void q_dial_show(void* self);
void q_dial_hide(void* self);
void q_dial_show_minimized(void* self);
void q_dial_show_maximized(void* self);
void q_dial_show_full_screen(void* self);
void q_dial_show_normal(void* self);
bool q_dial_close(void* self);
void q_dial_raise(void* self);
void q_dial_lower(void* self);
void q_dial_stack_under(void* self, void* param1);
void q_dial_move(void* self, int x, int y);
void q_dial_move_with_q_point(void* self, void* param1);
void q_dial_resize(void* self, int w, int h);
void q_dial_resize_with_q_size(void* self, void* param1);
void q_dial_set_geometry(void* self, int x, int y, int w, int h);
void q_dial_set_geometry_with_geometry(void* self, void* geometry);
char* q_dial_save_geometry(void* self);
bool q_dial_restore_geometry(void* self, const char* geometry);
void q_dial_adjust_size(void* self);
bool q_dial_is_visible(void* self);
bool q_dial_is_visible_to(void* self, void* param1);
bool q_dial_is_hidden(void* self);
bool q_dial_is_minimized(void* self);
bool q_dial_is_maximized(void* self);
bool q_dial_is_full_screen(void* self);
int64_t q_dial_window_state(void* self);
void q_dial_set_window_state(void* self, int64_t state);
void q_dial_override_window_state(void* self, int64_t state);
QSizePolicy* q_dial_size_policy(void* self);
void q_dial_set_size_policy(void* self, void* sizePolicy);
void q_dial_set_size_policy2(void* self, int64_t horizontal, int64_t vertical);
QRegion* q_dial_visible_region(void* self);
void q_dial_set_contents_margins(void* self, int left, int top, int right, int bottom);
void q_dial_set_contents_margins_with_margins(void* self, void* margins);
QMargins* q_dial_contents_margins(void* self);
QRect* q_dial_contents_rect(void* self);
QLayout* q_dial_layout(void* self);
void q_dial_set_layout(void* self, void* layout);
void q_dial_update_geometry(void* self);
void q_dial_set_parent(void* self, void* parent);
void q_dial_set_parent2(void* self, void* parent, int64_t f);
void q_dial_scroll(void* self, int dx, int dy);
void q_dial_scroll2(void* self, int dx, int dy, void* param3);
QWidget* q_dial_focus_widget(void* self);
QWidget* q_dial_next_in_focus_chain(void* self);
QWidget* q_dial_previous_in_focus_chain(void* self);
bool q_dial_accept_drops(void* self);
void q_dial_set_accept_drops(void* self, bool on);
void q_dial_add_action(void* self, void* action);
void q_dial_add_actions(void* self, void* actions[]);
void q_dial_insert_actions(void* self, void* before, void* actions[]);
void q_dial_insert_action(void* self, void* before, void* action);
void q_dial_remove_action(void* self, void* action);
libqt_list /* of QAction* */ q_dial_actions(void* self);
QAction* q_dial_add_action_with_text(void* self, const char* text);
QAction* q_dial_add_action2(void* self, void* icon, const char* text);
QAction* q_dial_add_action3(void* self, const char* text, void* shortcut);
QAction* q_dial_add_action4(void* self, void* icon, const char* text, void* shortcut);
QWidget* q_dial_parent_widget(void* self);
void q_dial_set_window_flags(void* self, int64_t typeVal);
int64_t q_dial_window_flags(void* self);
void q_dial_set_window_flag(void* self, int64_t param1);
void q_dial_override_window_flags(void* self, int64_t typeVal);
int64_t q_dial_window_type(void* self);
QWidget* q_dial_find(uint64_t param1);
QWidget* q_dial_child_at(void* self, int x, int y);
QWidget* q_dial_child_at_with_q_point(void* self, void* p);
void q_dial_set_attribute(void* self, int64_t param1);
bool q_dial_test_attribute(void* self, int64_t param1);
void q_dial_ensure_polished(void* self);
bool q_dial_is_ancestor_of(void* self, void* child);
bool q_dial_auto_fill_background(void* self);
void q_dial_set_auto_fill_background(void* self, bool enabled);
QBackingStore* q_dial_backing_store(void* self);
QWindow* q_dial_window_handle(void* self);
QScreen* q_dial_screen(void* self);
void q_dial_set_screen(void* self, void* screen);
QWidget* q_dial_create_window_container(void* window);
void q_dial_window_title_changed(void* self, const char* title);
void q_dial_on_window_title_changed(void* self, void (*slot)(void*, const char*));
void q_dial_window_icon_changed(void* self, void* icon);
void q_dial_on_window_icon_changed(void* self, void (*slot)(void*, void*));
void q_dial_window_icon_text_changed(void* self, const char* iconText);
void q_dial_on_window_icon_text_changed(void* self, void (*slot)(void*, const char*));
void q_dial_custom_context_menu_requested(void* self, void* pos);
void q_dial_on_custom_context_menu_requested(void* self, void (*slot)(void*, void*));
int64_t q_dial_input_method_hints(void* self);
void q_dial_set_input_method_hints(void* self, int64_t hints);
void q_dial_render2(void* self, void* target, void* targetOffset);
void q_dial_render3(void* self, void* target, void* targetOffset, void* sourceRegion);
void q_dial_render4(void* self, void* target, void* targetOffset, void* sourceRegion, int64_t renderFlags);
void q_dial_render22(void* self, void* painter, void* targetOffset);
void q_dial_render32(void* self, void* painter, void* targetOffset, void* sourceRegion);
void q_dial_render42(void* self, void* painter, void* targetOffset, void* sourceRegion, int64_t renderFlags);
QPixmap* q_dial_grab1(void* self, void* rectangle);
void q_dial_grab_gesture2(void* self, int64_t typeVal, int64_t flags);
int32_t q_dial_grab_shortcut2(void* self, void* key, int64_t context);
void q_dial_set_shortcut_enabled2(void* self, int id, bool enable);
void q_dial_set_shortcut_auto_repeat2(void* self, int id, bool enable);
void q_dial_set_window_flag2(void* self, int64_t param1, bool on);
void q_dial_set_attribute2(void* self, int64_t param1, bool on);
QWidget* q_dial_create_window_container2(void* window, void* parent);
QWidget* q_dial_create_window_container3(void* window, void* parent, int64_t flags);
const char* q_dial_object_name(void* self);
void q_dial_set_object_name(void* self, const char* name);
bool q_dial_is_widget_type(void* self);
bool q_dial_is_window_type(void* self);
bool q_dial_is_quick_item_type(void* self);
bool q_dial_signals_blocked(void* self);
bool q_dial_block_signals(void* self, bool b);
QThread* q_dial_thread(void* self);
void q_dial_move_to_thread(void* self, void* thread);
int32_t q_dial_start_timer(void* self, int interval);
void q_dial_kill_timer(void* self, int id);
libqt_list /* of QObject* */ q_dial_children(void* self);
void q_dial_install_event_filter(void* self, void* filterObj);
void q_dial_remove_event_filter(void* self, void* obj);
QMetaObject__Connection* q_dial_connect(void* sender, void* signal, void* receiver, void* method);
QMetaObject__Connection* q_dial_connect2(void* self, void* sender, const char* signal, const char* member);
bool q_dial_disconnect(void* sender, void* signal, void* receiver, void* member);
bool q_dial_disconnect_with_q_meta_object_connection(void* param1);
void q_dial_dump_object_tree(void* self);
void q_dial_dump_object_info(void* self);
bool q_dial_set_property(void* self, const char* name, void* value);
QVariant* q_dial_property(void* self, const char* name);
const char** q_dial_dynamic_property_names(void* self);
QBindingStorage* q_dial_binding_storage(void* self);
QBindingStorage* q_dial_binding_storage2(void* self);
void q_dial_destroyed(void* self);
void q_dial_on_destroyed(void* self, void (*slot)(void*));
QObject* q_dial_parent(void* self);
bool q_dial_inherits(void* self, const char* classname);
void q_dial_delete_later(void* self);
int32_t q_dial_start_timer2(void* self, int interval, int64_t timerType);
QMetaObject__Connection* q_dial_connect5(void* sender, void* signal, void* receiver, void* method, int64_t typeVal);
QMetaObject__Connection* q_dial_connect4(void* self, void* sender, const char* signal, const char* member, int64_t typeVal);
void q_dial_destroyed1(void* self, void* param1);
void q_dial_on_destroyed1(void* self, void (*slot)(void*, void*));
bool q_dial_painting_active(void* self);
int32_t q_dial_width_m_m(void* self);
int32_t q_dial_height_m_m(void* self);
int32_t q_dial_logical_dpi_x(void* self);
int32_t q_dial_logical_dpi_y(void* self);
int32_t q_dial_physical_dpi_x(void* self);
int32_t q_dial_physical_dpi_y(void* self);
double q_dial_device_pixel_ratio(void* self);
double q_dial_device_pixel_ratio_f(void* self);
int32_t q_dial_color_count(void* self);
int32_t q_dial_depth(void* self);
double q_dial_device_pixel_ratio_f_scale();
void q_dial_key_press_event(void* self, void* ev);
void q_dial_qbase_key_press_event(void* self, void* ev);
void q_dial_on_key_press_event(void* self, void (*slot)(void*, void*));
void q_dial_timer_event(void* self, void* param1);
void q_dial_qbase_timer_event(void* self, void* param1);
void q_dial_on_timer_event(void* self, void (*slot)(void*, void*));
void q_dial_wheel_event(void* self, void* e);
void q_dial_qbase_wheel_event(void* self, void* e);
void q_dial_on_wheel_event(void* self, void (*slot)(void*, void*));
void q_dial_change_event(void* self, void* e);
void q_dial_qbase_change_event(void* self, void* e);
void q_dial_on_change_event(void* self, void (*slot)(void*, void*));
int32_t q_dial_dev_type(void* self);
int32_t q_dial_qbase_dev_type(void* self);
void q_dial_on_dev_type(void* self, int32_t (*slot)());
void q_dial_set_visible(void* self, bool visible);
void q_dial_qbase_set_visible(void* self, bool visible);
void q_dial_on_set_visible(void* self, void (*slot)(void*, bool));
int32_t q_dial_height_for_width(void* self, int param1);
int32_t q_dial_qbase_height_for_width(void* self, int param1);
void q_dial_on_height_for_width(void* self, int32_t (*slot)(void*, int));
bool q_dial_has_height_for_width(void* self);
bool q_dial_qbase_has_height_for_width(void* self);
void q_dial_on_has_height_for_width(void* self, bool (*slot)());
QPaintEngine* q_dial_paint_engine(void* self);
QPaintEngine* q_dial_qbase_paint_engine(void* self);
void q_dial_on_paint_engine(void* self, QPaintEngine* (*slot)());
void q_dial_mouse_double_click_event(void* self, void* event);
void q_dial_qbase_mouse_double_click_event(void* self, void* event);
void q_dial_on_mouse_double_click_event(void* self, void (*slot)(void*, void*));
void q_dial_key_release_event(void* self, void* event);
void q_dial_qbase_key_release_event(void* self, void* event);
void q_dial_on_key_release_event(void* self, void (*slot)(void*, void*));
void q_dial_focus_in_event(void* self, void* event);
void q_dial_qbase_focus_in_event(void* self, void* event);
void q_dial_on_focus_in_event(void* self, void (*slot)(void*, void*));
void q_dial_focus_out_event(void* self, void* event);
void q_dial_qbase_focus_out_event(void* self, void* event);
void q_dial_on_focus_out_event(void* self, void (*slot)(void*, void*));
void q_dial_enter_event(void* self, void* event);
void q_dial_qbase_enter_event(void* self, void* event);
void q_dial_on_enter_event(void* self, void (*slot)(void*, void*));
void q_dial_leave_event(void* self, void* event);
void q_dial_qbase_leave_event(void* self, void* event);
void q_dial_on_leave_event(void* self, void (*slot)(void*, void*));
void q_dial_move_event(void* self, void* event);
void q_dial_qbase_move_event(void* self, void* event);
void q_dial_on_move_event(void* self, void (*slot)(void*, void*));
void q_dial_close_event(void* self, void* event);
void q_dial_qbase_close_event(void* self, void* event);
void q_dial_on_close_event(void* self, void (*slot)(void*, void*));
void q_dial_context_menu_event(void* self, void* event);
void q_dial_qbase_context_menu_event(void* self, void* event);
void q_dial_on_context_menu_event(void* self, void (*slot)(void*, void*));
void q_dial_tablet_event(void* self, void* event);
void q_dial_qbase_tablet_event(void* self, void* event);
void q_dial_on_tablet_event(void* self, void (*slot)(void*, void*));
void q_dial_action_event(void* self, void* event);
void q_dial_qbase_action_event(void* self, void* event);
void q_dial_on_action_event(void* self, void (*slot)(void*, void*));
void q_dial_drag_enter_event(void* self, void* event);
void q_dial_qbase_drag_enter_event(void* self, void* event);
void q_dial_on_drag_enter_event(void* self, void (*slot)(void*, void*));
void q_dial_drag_move_event(void* self, void* event);
void q_dial_qbase_drag_move_event(void* self, void* event);
void q_dial_on_drag_move_event(void* self, void (*slot)(void*, void*));
void q_dial_drag_leave_event(void* self, void* event);
void q_dial_qbase_drag_leave_event(void* self, void* event);
void q_dial_on_drag_leave_event(void* self, void (*slot)(void*, void*));
void q_dial_drop_event(void* self, void* event);
void q_dial_qbase_drop_event(void* self, void* event);
void q_dial_on_drop_event(void* self, void (*slot)(void*, void*));
void q_dial_show_event(void* self, void* event);
void q_dial_qbase_show_event(void* self, void* event);
void q_dial_on_show_event(void* self, void (*slot)(void*, void*));
void q_dial_hide_event(void* self, void* event);
void q_dial_qbase_hide_event(void* self, void* event);
void q_dial_on_hide_event(void* self, void (*slot)(void*, void*));
bool q_dial_native_event(void* self, const char* eventType, void* message, intptr_t* result);
bool q_dial_qbase_native_event(void* self, const char* eventType, void* message, intptr_t* result);
void q_dial_on_native_event(void* self, bool (*slot)(void*, const char*, void*, intptr_t*));
int32_t q_dial_metric(void* self, int64_t param1);
int32_t q_dial_qbase_metric(void* self, int64_t param1);
void q_dial_on_metric(void* self, int32_t (*slot)(void*, int64_t));
void q_dial_init_painter(void* self, void* painter);
void q_dial_qbase_init_painter(void* self, void* painter);
void q_dial_on_init_painter(void* self, void (*slot)(void*, void*));
QPaintDevice* q_dial_redirected(void* self, void* offset);
QPaintDevice* q_dial_qbase_redirected(void* self, void* offset);
void q_dial_on_redirected(void* self, QPaintDevice* (*slot)(void*, void*));
QPainter* q_dial_shared_painter(void* self);
QPainter* q_dial_qbase_shared_painter(void* self);
void q_dial_on_shared_painter(void* self, QPainter* (*slot)());
void q_dial_input_method_event(void* self, void* param1);
void q_dial_qbase_input_method_event(void* self, void* param1);
void q_dial_on_input_method_event(void* self, void (*slot)(void*, void*));
QVariant* q_dial_input_method_query(void* self, int64_t param1);
QVariant* q_dial_qbase_input_method_query(void* self, int64_t param1);
void q_dial_on_input_method_query(void* self, QVariant* (*slot)(void*, int64_t));
bool q_dial_focus_next_prev_child(void* self, bool next);
bool q_dial_qbase_focus_next_prev_child(void* self, bool next);
void q_dial_on_focus_next_prev_child(void* self, bool (*slot)(void*, bool));
bool q_dial_event_filter(void* self, void* watched, void* event);
bool q_dial_qbase_event_filter(void* self, void* watched, void* event);
void q_dial_on_event_filter(void* self, bool (*slot)(void*, void*, void*));
void q_dial_child_event(void* self, void* event);
void q_dial_qbase_child_event(void* self, void* event);
void q_dial_on_child_event(void* self, void (*slot)(void*, void*));
void q_dial_custom_event(void* self, void* event);
void q_dial_qbase_custom_event(void* self, void* event);
void q_dial_on_custom_event(void* self, void (*slot)(void*, void*));
void q_dial_connect_notify(void* self, void* signal);
void q_dial_qbase_connect_notify(void* self, void* signal);
void q_dial_on_connect_notify(void* self, void (*slot)(void*, void*));
void q_dial_disconnect_notify(void* self, void* signal);
void q_dial_qbase_disconnect_notify(void* self, void* signal);
void q_dial_on_disconnect_notify(void* self, void (*slot)(void*, void*));
void q_dial_set_repeat_action(void* self, int64_t action);
void q_dial_qbase_set_repeat_action(void* self, int64_t action);
void q_dial_on_set_repeat_action(void* self, void (*slot)(void*, int64_t));
int64_t q_dial_repeat_action(void* self);
int64_t q_dial_qbase_repeat_action(void* self);
void q_dial_on_repeat_action(void* self, int64_t (*slot)());
void q_dial_update_micro_focus(void* self);
void q_dial_qbase_update_micro_focus(void* self);
void q_dial_on_update_micro_focus(void* self, void (*slot)());
void q_dial_create(void* self);
void q_dial_qbase_create(void* self);
void q_dial_on_create(void* self, void (*slot)());
void q_dial_destroy(void* self);
void q_dial_qbase_destroy(void* self);
void q_dial_on_destroy(void* self, void (*slot)());
bool q_dial_focus_next_child(void* self);
bool q_dial_qbase_focus_next_child(void* self);
void q_dial_on_focus_next_child(void* self, bool (*slot)());
bool q_dial_focus_previous_child(void* self);
bool q_dial_qbase_focus_previous_child(void* self);
void q_dial_on_focus_previous_child(void* self, bool (*slot)());
QObject* q_dial_sender(void* self);
QObject* q_dial_qbase_sender(void* self);
void q_dial_on_sender(void* self, QObject* (*slot)());
int32_t q_dial_sender_signal_index(void* self);
int32_t q_dial_qbase_sender_signal_index(void* self);
void q_dial_on_sender_signal_index(void* self, int32_t (*slot)());
int32_t q_dial_receivers(void* self, const char* signal);
int32_t q_dial_qbase_receivers(void* self, const char* signal);
void q_dial_on_receivers(void* self, int32_t (*slot)(void*, const char*));
bool q_dial_is_signal_connected(void* self, void* signal);
bool q_dial_qbase_is_signal_connected(void* self, void* signal);
void q_dial_on_is_signal_connected(void* self, bool (*slot)(void*, void*));
void q_dial_delete(void* self);

#endif
