#pragma once
#ifndef SRCQT6C_LIBQLISTWIDGET_H
#define SRCQT6C_LIBQLISTWIDGET_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#include "libqabstractitemdelegate.h"
#include "libqabstractitemmodel.h"
#include "libqabstractitemview.h"
#include "libqabstractscrollarea.h"
#include "libqaction.h"
#include "libqevent.h"
#include "libqanystringview.h"
#include "libqbackingstore.h"
#include "libqbindingstorage.h"
#include "libqbitmap.h"
#include "libqbrush.h"
#include "libqcursor.h"
#include "libqdatastream.h"
#include "libqfont.h"
#include "libqfontinfo.h"
#include "libqfontmetrics.h"
#include "libqframe.h"
#include "libqgraphicseffect.h"
#include "libqgraphicsproxywidget.h"
#include "libqicon.h"
#include "libqitemselectionmodel.h"
#include "libqkeysequence.h"
#include "libqlayout.h"
#include "libqlistview.h"
#include "libqlocale.h"
#include "libqmargins.h"
#include "libqmetaobject.h"
#include "libqmimedata.h"
#include "libqobject.h"
#include "libqpaintdevice.h"
#include "libqpaintengine.h"
#include "libqpainter.h"
#include "libqpalette.h"
#include "libqpixmap.h"
#include "libqpoint.h"
#include "libqrect.h"
#include "libqregion.h"
#include "libqscreen.h"
#include "libqscrollbar.h"
#include "libqsize.h"
#include "libqsizepolicy.h"
#include <string.h>
#include "libqstyle.h"
#include "libqstyleoption.h"
#include "libqthread.h"
#include "libqvariant.h"
#include "libqwidget.h"
#include "libqwindow.h"

QListWidgetItem* q_listwidgetitem_new();
QListWidgetItem* q_listwidgetitem_new2(const char* text);
QListWidgetItem* q_listwidgetitem_new3(void* icon, const char* text);
QListWidgetItem* q_listwidgetitem_new4(void* other);
QListWidgetItem* q_listwidgetitem_new5(void* listview);
QListWidgetItem* q_listwidgetitem_new6(void* listview, int typeVal);
QListWidgetItem* q_listwidgetitem_new7(const char* text, void* listview);
QListWidgetItem* q_listwidgetitem_new8(const char* text, void* listview, int typeVal);
QListWidgetItem* q_listwidgetitem_new9(void* icon, const char* text, void* listview);
QListWidgetItem* q_listwidgetitem_new10(void* icon, const char* text, void* listview, int typeVal);
QListWidgetItem* q_listwidgetitem_clone(void* self);
void q_listwidgetitem_on_clone(void* self, QListWidgetItem* (*slot)());
QListWidgetItem* q_listwidgetitem_qbase_clone(void* self);
QListWidget* q_listwidgetitem_list_widget(void* self);
void q_listwidgetitem_set_selected(void* self, bool selectVal);
bool q_listwidgetitem_is_selected(void* self);
void q_listwidgetitem_set_hidden(void* self, bool hide);
bool q_listwidgetitem_is_hidden(void* self);
int64_t q_listwidgetitem_flags(void* self);
void q_listwidgetitem_set_flags(void* self, int64_t flags);
const char* q_listwidgetitem_text(void* self);
void q_listwidgetitem_set_text(void* self, const char* text);
QIcon* q_listwidgetitem_icon(void* self);
void q_listwidgetitem_set_icon(void* self, void* icon);
const char* q_listwidgetitem_status_tip(void* self);
void q_listwidgetitem_set_status_tip(void* self, const char* statusTip);
const char* q_listwidgetitem_tool_tip(void* self);
void q_listwidgetitem_set_tool_tip(void* self, const char* toolTip);
const char* q_listwidgetitem_whats_this(void* self);
void q_listwidgetitem_set_whats_this(void* self, const char* whatsThis);
QFont* q_listwidgetitem_font(void* self);
void q_listwidgetitem_set_font(void* self, void* font);
int32_t q_listwidgetitem_text_alignment(void* self);
void q_listwidgetitem_set_text_alignment(void* self, int alignment);
void q_listwidgetitem_set_text_alignment_with_alignment(void* self, int64_t alignment);
void q_listwidgetitem_set_text_alignment2(void* self, int64_t alignment);
QBrush* q_listwidgetitem_background(void* self);
void q_listwidgetitem_set_background(void* self, void* brush);
QBrush* q_listwidgetitem_foreground(void* self);
void q_listwidgetitem_set_foreground(void* self, void* brush);
int64_t q_listwidgetitem_check_state(void* self);
void q_listwidgetitem_set_check_state(void* self, int64_t state);
QSize* q_listwidgetitem_size_hint(void* self);
void q_listwidgetitem_set_size_hint(void* self, void* size);
QVariant* q_listwidgetitem_data(void* self, int role);
void q_listwidgetitem_on_data(void* self, QVariant* (*slot)(void*, int));
QVariant* q_listwidgetitem_qbase_data(void* self, int role);
void q_listwidgetitem_set_data(void* self, int role, void* value);
void q_listwidgetitem_on_set_data(void* self, void (*slot)(void*, int, void*));
void q_listwidgetitem_qbase_set_data(void* self, int role, void* value);
bool q_listwidgetitem_operator_lesser(void* self, void* other);
void q_listwidgetitem_on_operator_lesser(void* self, bool (*slot)(void*, void*));
bool q_listwidgetitem_qbase_operator_lesser(void* self, void* other);
void q_listwidgetitem_read(void* self, void* in);
void q_listwidgetitem_on_read(void* self, void (*slot)(void*, void*));
void q_listwidgetitem_qbase_read(void* self, void* in);
void q_listwidgetitem_write(void* self, void* out);
void q_listwidgetitem_on_write(void* self, void (*slot)(void*, void*));
void q_listwidgetitem_qbase_write(void* self, void* out);
void q_listwidgetitem_operator_assign(void* self, void* other);
int32_t q_listwidgetitem_type(void* self);
void q_listwidgetitem_delete(void* self);

QListWidget* q_listwidget_new(void* parent);
QListWidget* q_listwidget_new2();
QMetaObject* q_listwidget_meta_object(void* self);
void* q_listwidget_metacast(void* self, const char* param1);
int32_t q_listwidget_metacall(void* self, int64_t param1, int param2, void* param3);
void q_listwidget_on_metacall(void* self, int32_t (*slot)(void*, int64_t, int, void*));
int32_t q_listwidget_qbase_metacall(void* self, int64_t param1, int param2, void* param3);
const char* q_listwidget_tr(const char* s);
void q_listwidget_set_selection_model(void* self, void* selectionModel);
void q_listwidget_on_set_selection_model(void* self, void (*slot)(void*, void*));
void q_listwidget_qbase_set_selection_model(void* self, void* selectionModel);
QListWidgetItem* q_listwidget_item(void* self, int row);
int32_t q_listwidget_row(void* self, void* item);
void q_listwidget_insert_item(void* self, int row, void* item);
void q_listwidget_insert_item2(void* self, int row, const char* label);
void q_listwidget_insert_items(void* self, int row, const char* labels[]);
void q_listwidget_add_item(void* self, const char* label);
void q_listwidget_add_item_with_item(void* self, void* item);
void q_listwidget_add_items(void* self, const char* labels[]);
QListWidgetItem* q_listwidget_take_item(void* self, int row);
int32_t q_listwidget_count(void* self);
QListWidgetItem* q_listwidget_current_item(void* self);
void q_listwidget_set_current_item(void* self, void* item);
void q_listwidget_set_current_item2(void* self, void* item, int64_t command);
int32_t q_listwidget_current_row(void* self);
void q_listwidget_set_current_row(void* self, int row);
void q_listwidget_set_current_row2(void* self, int row, int64_t command);
QListWidgetItem* q_listwidget_item_at(void* self, void* p);
QListWidgetItem* q_listwidget_item_at2(void* self, int x, int y);
QRect* q_listwidget_visual_item_rect(void* self, void* item);
void q_listwidget_sort_items(void* self);
void q_listwidget_set_sorting_enabled(void* self, bool enable);
bool q_listwidget_is_sorting_enabled(void* self);
void q_listwidget_edit_item(void* self, void* item);
void q_listwidget_open_persistent_editor(void* self, void* item);
void q_listwidget_close_persistent_editor(void* self, void* item);
bool q_listwidget_is_persistent_editor_open(void* self, void* item);
QWidget* q_listwidget_item_widget(void* self, void* item);
void q_listwidget_set_item_widget(void* self, void* item, void* widget);
void q_listwidget_remove_item_widget(void* self, void* item);
libqt_list /* of QListWidgetItem* */ q_listwidget_selected_items(void* self);
libqt_list /* of QListWidgetItem* */ q_listwidget_find_items(void* self, const char* text, int64_t flags);
libqt_list /* of QListWidgetItem* */ q_listwidget_items(void* self, void* data);
QModelIndex* q_listwidget_index_from_item(void* self, void* item);
QListWidgetItem* q_listwidget_item_from_index(void* self, void* index);
void q_listwidget_drop_event(void* self, void* event);
void q_listwidget_on_drop_event(void* self, void (*slot)(void*, void*));
void q_listwidget_qbase_drop_event(void* self, void* event);
void q_listwidget_scroll_to_item(void* self, void* item);
void q_listwidget_clear(void* self);
void q_listwidget_item_pressed(void* self, void* item);
void q_listwidget_on_item_pressed(void* self, void (*slot)(void*, void*));
void q_listwidget_item_clicked(void* self, void* item);
void q_listwidget_on_item_clicked(void* self, void (*slot)(void*, void*));
void q_listwidget_item_double_clicked(void* self, void* item);
void q_listwidget_on_item_double_clicked(void* self, void (*slot)(void*, void*));
void q_listwidget_item_activated(void* self, void* item);
void q_listwidget_on_item_activated(void* self, void (*slot)(void*, void*));
void q_listwidget_item_entered(void* self, void* item);
void q_listwidget_on_item_entered(void* self, void (*slot)(void*, void*));
void q_listwidget_item_changed(void* self, void* item);
void q_listwidget_on_item_changed(void* self, void (*slot)(void*, void*));
void q_listwidget_current_item_changed(void* self, void* current, void* previous);
void q_listwidget_on_current_item_changed(void* self, void (*slot)(void*, void*, void*));
void q_listwidget_current_text_changed(void* self, const char* currentText);
void q_listwidget_on_current_text_changed(void* self, void (*slot)(void*, const char*));
void q_listwidget_current_row_changed(void* self, int currentRow);
void q_listwidget_on_current_row_changed(void* self, void (*slot)(void*, int));
void q_listwidget_item_selection_changed(void* self);
void q_listwidget_on_item_selection_changed(void* self, void (*slot)(void*));
bool q_listwidget_event(void* self, void* e);
void q_listwidget_on_event(void* self, bool (*slot)(void*, void*));
bool q_listwidget_qbase_event(void* self, void* e);
const char** q_listwidget_mime_types(void* self);
void q_listwidget_on_mime_types(void* self, const char** (*slot)());
const char** q_listwidget_qbase_mime_types(void* self);
QMimeData* q_listwidget_mime_data(void* self, void* items[]);
void q_listwidget_on_mime_data(void* self, QMimeData* (*slot)(void*, void*));
QMimeData* q_listwidget_qbase_mime_data(void* self, void* items[]);
bool q_listwidget_drop_mime_data(void* self, int index, void* data, int64_t action);
void q_listwidget_on_drop_mime_data(void* self, bool (*slot)(void*, int, void*, int64_t));
bool q_listwidget_qbase_drop_mime_data(void* self, int index, void* data, int64_t action);
int64_t q_listwidget_supported_drop_actions(void* self);
void q_listwidget_on_supported_drop_actions(void* self, int64_t (*slot)());
int64_t q_listwidget_qbase_supported_drop_actions(void* self);
const char* q_listwidget_tr2(const char* s, const char* c);
const char* q_listwidget_tr3(const char* s, const char* c, int n);
void q_listwidget_sort_items1(void* self, int64_t order);
void q_listwidget_scroll_to_item2(void* self, void* item, int64_t hint);
void q_listwidget_set_movement(void* self, int64_t movement);
int64_t q_listwidget_movement(void* self);
void q_listwidget_set_flow(void* self, int64_t flow);
int64_t q_listwidget_flow(void* self);
void q_listwidget_set_wrapping(void* self, bool enable);
bool q_listwidget_is_wrapping(void* self);
void q_listwidget_set_resize_mode(void* self, int64_t mode);
int64_t q_listwidget_resize_mode(void* self);
void q_listwidget_set_layout_mode(void* self, int64_t mode);
int64_t q_listwidget_layout_mode(void* self);
void q_listwidget_set_spacing(void* self, int space);
int32_t q_listwidget_spacing(void* self);
void q_listwidget_set_batch_size(void* self, int batchSize);
int32_t q_listwidget_batch_size(void* self);
void q_listwidget_set_grid_size(void* self, void* size);
QSize* q_listwidget_grid_size(void* self);
void q_listwidget_set_view_mode(void* self, int64_t mode);
int64_t q_listwidget_view_mode(void* self);
void q_listwidget_clear_property_flags(void* self);
bool q_listwidget_is_row_hidden(void* self, int row);
void q_listwidget_set_row_hidden(void* self, int row, bool hide);
void q_listwidget_set_model_column(void* self, int column);
int32_t q_listwidget_model_column(void* self);
void q_listwidget_set_uniform_item_sizes(void* self, bool enable);
bool q_listwidget_uniform_item_sizes(void* self);
void q_listwidget_set_word_wrap(void* self, bool on);
bool q_listwidget_word_wrap(void* self);
void q_listwidget_set_selection_rect_visible(void* self, bool show);
bool q_listwidget_is_selection_rect_visible(void* self);
void q_listwidget_set_item_alignment(void* self, int64_t alignment);
int64_t q_listwidget_item_alignment(void* self);
void q_listwidget_indexes_moved(void* self, void* indexes[]);
void q_listwidget_on_indexes_moved(void* self, void (*slot)(void*, void*));
void q_listwidget_set_model(void* self, void* model);
void q_listwidget_on_set_model(void* self, void (*slot)(void*, void*));
void q_listwidget_qbase_set_model(void* self, void* model);
QAbstractItemModel* q_listwidget_model(void* self);
QItemSelectionModel* q_listwidget_selection_model(void* self);
void q_listwidget_set_item_delegate(void* self, void* delegate);
QAbstractItemDelegate* q_listwidget_item_delegate(void* self);
void q_listwidget_set_selection_mode(void* self, int64_t mode);
int64_t q_listwidget_selection_mode(void* self);
void q_listwidget_set_selection_behavior(void* self, int64_t behavior);
int64_t q_listwidget_selection_behavior(void* self);
QModelIndex* q_listwidget_current_index(void* self);
QModelIndex* q_listwidget_root_index(void* self);
void q_listwidget_set_edit_triggers(void* self, int64_t triggers);
int64_t q_listwidget_edit_triggers(void* self);
void q_listwidget_set_vertical_scroll_mode(void* self, int64_t mode);
int64_t q_listwidget_vertical_scroll_mode(void* self);
void q_listwidget_reset_vertical_scroll_mode(void* self);
void q_listwidget_set_horizontal_scroll_mode(void* self, int64_t mode);
int64_t q_listwidget_horizontal_scroll_mode(void* self);
void q_listwidget_reset_horizontal_scroll_mode(void* self);
void q_listwidget_set_auto_scroll(void* self, bool enable);
bool q_listwidget_has_auto_scroll(void* self);
void q_listwidget_set_auto_scroll_margin(void* self, int margin);
int32_t q_listwidget_auto_scroll_margin(void* self);
void q_listwidget_set_tab_key_navigation(void* self, bool enable);
bool q_listwidget_tab_key_navigation(void* self);
void q_listwidget_set_drop_indicator_shown(void* self, bool enable);
bool q_listwidget_show_drop_indicator(void* self);
void q_listwidget_set_drag_enabled(void* self, bool enable);
bool q_listwidget_drag_enabled(void* self);
void q_listwidget_set_drag_drop_overwrite_mode(void* self, bool overwrite);
bool q_listwidget_drag_drop_overwrite_mode(void* self);
void q_listwidget_set_drag_drop_mode(void* self, int64_t behavior);
int64_t q_listwidget_drag_drop_mode(void* self);
void q_listwidget_set_default_drop_action(void* self, int64_t dropAction);
int64_t q_listwidget_default_drop_action(void* self);
void q_listwidget_set_alternating_row_colors(void* self, bool enable);
bool q_listwidget_alternating_row_colors(void* self);
void q_listwidget_set_icon_size(void* self, void* size);
QSize* q_listwidget_icon_size(void* self);
void q_listwidget_set_text_elide_mode(void* self, int64_t mode);
int64_t q_listwidget_text_elide_mode(void* self);
QSize* q_listwidget_size_hint_for_index(void* self, void* index);
void q_listwidget_set_index_widget(void* self, void* index, void* widget);
QWidget* q_listwidget_index_widget(void* self, void* index);
void q_listwidget_set_item_delegate_for_row(void* self, int row, void* delegate);
QAbstractItemDelegate* q_listwidget_item_delegate_for_row(void* self, int row);
void q_listwidget_set_item_delegate_for_column(void* self, int column, void* delegate);
QAbstractItemDelegate* q_listwidget_item_delegate_for_column(void* self, int column);
QAbstractItemDelegate* q_listwidget_item_delegate_with_index(void* self, void* index);
void q_listwidget_edit(void* self, void* index);
void q_listwidget_clear_selection(void* self);
void q_listwidget_set_current_index(void* self, void* index);
void q_listwidget_scroll_to_top(void* self);
void q_listwidget_scroll_to_bottom(void* self);
void q_listwidget_update(void* self, void* index);
void q_listwidget_pressed(void* self, void* index);
void q_listwidget_on_pressed(void* self, void (*slot)(void*, void*));
void q_listwidget_clicked(void* self, void* index);
void q_listwidget_on_clicked(void* self, void (*slot)(void*, void*));
void q_listwidget_double_clicked(void* self, void* index);
void q_listwidget_on_double_clicked(void* self, void (*slot)(void*, void*));
void q_listwidget_activated(void* self, void* index);
void q_listwidget_on_activated(void* self, void (*slot)(void*, void*));
void q_listwidget_entered(void* self, void* index);
void q_listwidget_on_entered(void* self, void (*slot)(void*, void*));
void q_listwidget_viewport_entered(void* self);
void q_listwidget_on_viewport_entered(void* self, void (*slot)(void*));
void q_listwidget_icon_size_changed(void* self, void* size);
void q_listwidget_on_icon_size_changed(void* self, void (*slot)(void*, void*));
int64_t q_listwidget_vertical_scroll_bar_policy(void* self);
void q_listwidget_set_vertical_scroll_bar_policy(void* self, int64_t verticalScrollBarPolicy);
QScrollBar* q_listwidget_vertical_scroll_bar(void* self);
void q_listwidget_set_vertical_scroll_bar(void* self, void* scrollbar);
int64_t q_listwidget_horizontal_scroll_bar_policy(void* self);
void q_listwidget_set_horizontal_scroll_bar_policy(void* self, int64_t horizontalScrollBarPolicy);
QScrollBar* q_listwidget_horizontal_scroll_bar(void* self);
void q_listwidget_set_horizontal_scroll_bar(void* self, void* scrollbar);
QWidget* q_listwidget_corner_widget(void* self);
void q_listwidget_set_corner_widget(void* self, void* widget);
void q_listwidget_add_scroll_bar_widget(void* self, void* widget, int64_t alignment);
libqt_list /* of QWidget* */ q_listwidget_scroll_bar_widgets(void* self, int64_t alignment);
QWidget* q_listwidget_viewport(void* self);
void q_listwidget_set_viewport(void* self, void* widget);
QSize* q_listwidget_maximum_viewport_size(void* self);
int64_t q_listwidget_size_adjust_policy(void* self);
void q_listwidget_set_size_adjust_policy(void* self, int64_t policy);
int32_t q_listwidget_frame_style(void* self);
void q_listwidget_set_frame_style(void* self, int frameStyle);
int32_t q_listwidget_frame_width(void* self);
int64_t q_listwidget_frame_shape(void* self);
void q_listwidget_set_frame_shape(void* self, int64_t frameShape);
int64_t q_listwidget_frame_shadow(void* self);
void q_listwidget_set_frame_shadow(void* self, int64_t frameShadow);
int32_t q_listwidget_line_width(void* self);
void q_listwidget_set_line_width(void* self, int lineWidth);
int32_t q_listwidget_mid_line_width(void* self);
void q_listwidget_set_mid_line_width(void* self, int midLineWidth);
QRect* q_listwidget_frame_rect(void* self);
void q_listwidget_set_frame_rect(void* self, void* frameRect);
uintptr_t q_listwidget_win_id(void* self);
void q_listwidget_create_win_id(void* self);
uintptr_t q_listwidget_internal_win_id(void* self);
uintptr_t q_listwidget_effective_win_id(void* self);
QStyle* q_listwidget_style(void* self);
void q_listwidget_set_style(void* self, void* style);
bool q_listwidget_is_top_level(void* self);
bool q_listwidget_is_window(void* self);
bool q_listwidget_is_modal(void* self);
int64_t q_listwidget_window_modality(void* self);
void q_listwidget_set_window_modality(void* self, int64_t windowModality);
bool q_listwidget_is_enabled(void* self);
bool q_listwidget_is_enabled_to(void* self, void* param1);
void q_listwidget_set_enabled(void* self, bool enabled);
void q_listwidget_set_disabled(void* self, bool disabled);
void q_listwidget_set_window_modified(void* self, bool windowModified);
QRect* q_listwidget_frame_geometry(void* self);
QRect* q_listwidget_geometry(void* self);
QRect* q_listwidget_normal_geometry(void* self);
int32_t q_listwidget_x(void* self);
int32_t q_listwidget_y(void* self);
QPoint* q_listwidget_pos(void* self);
QSize* q_listwidget_frame_size(void* self);
QSize* q_listwidget_size(void* self);
int32_t q_listwidget_width(void* self);
int32_t q_listwidget_height(void* self);
QRect* q_listwidget_rect(void* self);
QRect* q_listwidget_children_rect(void* self);
QRegion* q_listwidget_children_region(void* self);
QSize* q_listwidget_minimum_size(void* self);
QSize* q_listwidget_maximum_size(void* self);
int32_t q_listwidget_minimum_width(void* self);
int32_t q_listwidget_minimum_height(void* self);
int32_t q_listwidget_maximum_width(void* self);
int32_t q_listwidget_maximum_height(void* self);
void q_listwidget_set_minimum_size(void* self, void* minimumSize);
void q_listwidget_set_minimum_size2(void* self, int minw, int minh);
void q_listwidget_set_maximum_size(void* self, void* maximumSize);
void q_listwidget_set_maximum_size2(void* self, int maxw, int maxh);
void q_listwidget_set_minimum_width(void* self, int minw);
void q_listwidget_set_minimum_height(void* self, int minh);
void q_listwidget_set_maximum_width(void* self, int maxw);
void q_listwidget_set_maximum_height(void* self, int maxh);
QSize* q_listwidget_size_increment(void* self);
void q_listwidget_set_size_increment(void* self, void* sizeIncrement);
void q_listwidget_set_size_increment2(void* self, int w, int h);
QSize* q_listwidget_base_size(void* self);
void q_listwidget_set_base_size(void* self, void* baseSize);
void q_listwidget_set_base_size2(void* self, int basew, int baseh);
void q_listwidget_set_fixed_size(void* self, void* fixedSize);
void q_listwidget_set_fixed_size2(void* self, int w, int h);
void q_listwidget_set_fixed_width(void* self, int w);
void q_listwidget_set_fixed_height(void* self, int h);
QPointF* q_listwidget_map_to_global(void* self, void* param1);
QPoint* q_listwidget_map_to_global_with_q_point(void* self, void* param1);
QPointF* q_listwidget_map_from_global(void* self, void* param1);
QPoint* q_listwidget_map_from_global_with_q_point(void* self, void* param1);
QPointF* q_listwidget_map_to_parent(void* self, void* param1);
QPoint* q_listwidget_map_to_parent_with_q_point(void* self, void* param1);
QPointF* q_listwidget_map_from_parent(void* self, void* param1);
QPoint* q_listwidget_map_from_parent_with_q_point(void* self, void* param1);
QPointF* q_listwidget_map_to(void* self, void* param1, void* param2);
QPoint* q_listwidget_map_to2(void* self, void* param1, void* param2);
QPointF* q_listwidget_map_from(void* self, void* param1, void* param2);
QPoint* q_listwidget_map_from2(void* self, void* param1, void* param2);
QWidget* q_listwidget_window(void* self);
QWidget* q_listwidget_native_parent_widget(void* self);
QWidget* q_listwidget_top_level_widget(void* self);
QPalette* q_listwidget_palette(void* self);
void q_listwidget_set_palette(void* self, void* palette);
void q_listwidget_set_background_role(void* self, int64_t backgroundRole);
int64_t q_listwidget_background_role(void* self);
void q_listwidget_set_foreground_role(void* self, int64_t foregroundRole);
int64_t q_listwidget_foreground_role(void* self);
QFont* q_listwidget_font(void* self);
void q_listwidget_set_font(void* self, void* font);
QFontMetrics* q_listwidget_font_metrics(void* self);
QFontInfo* q_listwidget_font_info(void* self);
QCursor* q_listwidget_cursor(void* self);
void q_listwidget_set_cursor(void* self, void* cursor);
void q_listwidget_unset_cursor(void* self);
void q_listwidget_set_mouse_tracking(void* self, bool enable);
bool q_listwidget_has_mouse_tracking(void* self);
bool q_listwidget_under_mouse(void* self);
void q_listwidget_set_tablet_tracking(void* self, bool enable);
bool q_listwidget_has_tablet_tracking(void* self);
void q_listwidget_set_mask(void* self, void* mask);
void q_listwidget_set_mask_with_mask(void* self, void* mask);
QRegion* q_listwidget_mask(void* self);
void q_listwidget_clear_mask(void* self);
void q_listwidget_render(void* self, void* target);
void q_listwidget_render_with_painter(void* self, void* painter);
QPixmap* q_listwidget_grab(void* self);
QGraphicsEffect* q_listwidget_graphics_effect(void* self);
void q_listwidget_set_graphics_effect(void* self, void* effect);
void q_listwidget_grab_gesture(void* self, int64_t typeVal);
void q_listwidget_ungrab_gesture(void* self, int64_t typeVal);
void q_listwidget_set_window_title(void* self, const char* windowTitle);
void q_listwidget_set_style_sheet(void* self, const char* styleSheet);
const char* q_listwidget_style_sheet(void* self);
const char* q_listwidget_window_title(void* self);
void q_listwidget_set_window_icon(void* self, void* icon);
QIcon* q_listwidget_window_icon(void* self);
void q_listwidget_set_window_icon_text(void* self, const char* windowIconText);
const char* q_listwidget_window_icon_text(void* self);
void q_listwidget_set_window_role(void* self, const char* windowRole);
const char* q_listwidget_window_role(void* self);
void q_listwidget_set_window_file_path(void* self, const char* filePath);
const char* q_listwidget_window_file_path(void* self);
void q_listwidget_set_window_opacity(void* self, double level);
double q_listwidget_window_opacity(void* self);
bool q_listwidget_is_window_modified(void* self);
void q_listwidget_set_tool_tip(void* self, const char* toolTip);
const char* q_listwidget_tool_tip(void* self);
void q_listwidget_set_tool_tip_duration(void* self, int msec);
int32_t q_listwidget_tool_tip_duration(void* self);
void q_listwidget_set_status_tip(void* self, const char* statusTip);
const char* q_listwidget_status_tip(void* self);
void q_listwidget_set_whats_this(void* self, const char* whatsThis);
const char* q_listwidget_whats_this(void* self);
const char* q_listwidget_accessible_name(void* self);
void q_listwidget_set_accessible_name(void* self, const char* name);
const char* q_listwidget_accessible_description(void* self);
void q_listwidget_set_accessible_description(void* self, const char* description);
void q_listwidget_set_layout_direction(void* self, int64_t direction);
int64_t q_listwidget_layout_direction(void* self);
void q_listwidget_unset_layout_direction(void* self);
void q_listwidget_set_locale(void* self, void* locale);
QLocale* q_listwidget_locale(void* self);
void q_listwidget_unset_locale(void* self);
bool q_listwidget_is_right_to_left(void* self);
bool q_listwidget_is_left_to_right(void* self);
void q_listwidget_set_focus(void* self);
bool q_listwidget_is_active_window(void* self);
void q_listwidget_activate_window(void* self);
void q_listwidget_clear_focus(void* self);
void q_listwidget_set_focus_with_reason(void* self, int64_t reason);
int64_t q_listwidget_focus_policy(void* self);
void q_listwidget_set_focus_policy(void* self, int64_t policy);
bool q_listwidget_has_focus(void* self);
void q_listwidget_set_tab_order(void* param1, void* param2);
void q_listwidget_set_focus_proxy(void* self, void* focusProxy);
QWidget* q_listwidget_focus_proxy(void* self);
int64_t q_listwidget_context_menu_policy(void* self);
void q_listwidget_set_context_menu_policy(void* self, int64_t policy);
void q_listwidget_grab_mouse(void* self);
void q_listwidget_grab_mouse_with_q_cursor(void* self, void* param1);
void q_listwidget_release_mouse(void* self);
void q_listwidget_grab_keyboard(void* self);
void q_listwidget_release_keyboard(void* self);
int32_t q_listwidget_grab_shortcut(void* self, void* key);
void q_listwidget_release_shortcut(void* self, int id);
void q_listwidget_set_shortcut_enabled(void* self, int id);
void q_listwidget_set_shortcut_auto_repeat(void* self, int id);
QWidget* q_listwidget_mouse_grabber();
QWidget* q_listwidget_keyboard_grabber();
bool q_listwidget_updates_enabled(void* self);
void q_listwidget_set_updates_enabled(void* self, bool enable);
QGraphicsProxyWidget* q_listwidget_graphics_proxy_widget(void* self);
void q_listwidget_repaint(void* self);
void q_listwidget_update2(void* self, int x, int y, int w, int h);
void q_listwidget_update_with_q_rect(void* self, void* param1);
void q_listwidget_update_with_q_region(void* self, void* param1);
void q_listwidget_repaint2(void* self, int x, int y, int w, int h);
void q_listwidget_repaint_with_q_rect(void* self, void* param1);
void q_listwidget_repaint_with_q_region(void* self, void* param1);
void q_listwidget_set_hidden(void* self, bool hidden);
void q_listwidget_show(void* self);
void q_listwidget_hide(void* self);
void q_listwidget_show_minimized(void* self);
void q_listwidget_show_maximized(void* self);
void q_listwidget_show_full_screen(void* self);
void q_listwidget_show_normal(void* self);
bool q_listwidget_close(void* self);
void q_listwidget_raise(void* self);
void q_listwidget_lower(void* self);
void q_listwidget_stack_under(void* self, void* param1);
void q_listwidget_move(void* self, int x, int y);
void q_listwidget_move_with_q_point(void* self, void* param1);
void q_listwidget_resize(void* self, int w, int h);
void q_listwidget_resize_with_q_size(void* self, void* param1);
void q_listwidget_set_geometry(void* self, int x, int y, int w, int h);
void q_listwidget_set_geometry_with_geometry(void* self, void* geometry);
char* q_listwidget_save_geometry(void* self);
bool q_listwidget_restore_geometry(void* self, const char* geometry);
void q_listwidget_adjust_size(void* self);
bool q_listwidget_is_visible(void* self);
bool q_listwidget_is_visible_to(void* self, void* param1);
bool q_listwidget_is_hidden(void* self);
bool q_listwidget_is_minimized(void* self);
bool q_listwidget_is_maximized(void* self);
bool q_listwidget_is_full_screen(void* self);
int64_t q_listwidget_window_state(void* self);
void q_listwidget_set_window_state(void* self, int64_t state);
void q_listwidget_override_window_state(void* self, int64_t state);
QSizePolicy* q_listwidget_size_policy(void* self);
void q_listwidget_set_size_policy(void* self, void* sizePolicy);
void q_listwidget_set_size_policy2(void* self, int64_t horizontal, int64_t vertical);
QRegion* q_listwidget_visible_region(void* self);
void q_listwidget_set_contents_margins(void* self, int left, int top, int right, int bottom);
void q_listwidget_set_contents_margins_with_margins(void* self, void* margins);
QMargins* q_listwidget_contents_margins(void* self);
QRect* q_listwidget_contents_rect(void* self);
QLayout* q_listwidget_layout(void* self);
void q_listwidget_set_layout(void* self, void* layout);
void q_listwidget_update_geometry(void* self);
void q_listwidget_set_parent(void* self, void* parent);
void q_listwidget_set_parent2(void* self, void* parent, int64_t f);
void q_listwidget_scroll(void* self, int dx, int dy);
void q_listwidget_scroll2(void* self, int dx, int dy, void* param3);
QWidget* q_listwidget_focus_widget(void* self);
QWidget* q_listwidget_next_in_focus_chain(void* self);
QWidget* q_listwidget_previous_in_focus_chain(void* self);
bool q_listwidget_accept_drops(void* self);
void q_listwidget_set_accept_drops(void* self, bool on);
void q_listwidget_add_action(void* self, void* action);
void q_listwidget_add_actions(void* self, void* actions[]);
void q_listwidget_insert_actions(void* self, void* before, void* actions[]);
void q_listwidget_insert_action(void* self, void* before, void* action);
void q_listwidget_remove_action(void* self, void* action);
libqt_list /* of QAction* */ q_listwidget_actions(void* self);
QAction* q_listwidget_add_action_with_text(void* self, const char* text);
QAction* q_listwidget_add_action2(void* self, void* icon, const char* text);
QAction* q_listwidget_add_action3(void* self, const char* text, void* shortcut);
QAction* q_listwidget_add_action4(void* self, void* icon, const char* text, void* shortcut);
QWidget* q_listwidget_parent_widget(void* self);
void q_listwidget_set_window_flags(void* self, int64_t typeVal);
int64_t q_listwidget_window_flags(void* self);
void q_listwidget_set_window_flag(void* self, int64_t param1);
void q_listwidget_override_window_flags(void* self, int64_t typeVal);
int64_t q_listwidget_window_type(void* self);
QWidget* q_listwidget_find(uint64_t param1);
QWidget* q_listwidget_child_at(void* self, int x, int y);
QWidget* q_listwidget_child_at_with_q_point(void* self, void* p);
void q_listwidget_set_attribute(void* self, int64_t param1);
bool q_listwidget_test_attribute(void* self, int64_t param1);
void q_listwidget_ensure_polished(void* self);
bool q_listwidget_is_ancestor_of(void* self, void* child);
bool q_listwidget_auto_fill_background(void* self);
void q_listwidget_set_auto_fill_background(void* self, bool enabled);
QBackingStore* q_listwidget_backing_store(void* self);
QWindow* q_listwidget_window_handle(void* self);
QScreen* q_listwidget_screen(void* self);
void q_listwidget_set_screen(void* self, void* screen);
QWidget* q_listwidget_create_window_container(void* window);
void q_listwidget_window_title_changed(void* self, const char* title);
void q_listwidget_on_window_title_changed(void* self, void (*slot)(void*, const char*));
void q_listwidget_window_icon_changed(void* self, void* icon);
void q_listwidget_on_window_icon_changed(void* self, void (*slot)(void*, void*));
void q_listwidget_window_icon_text_changed(void* self, const char* iconText);
void q_listwidget_on_window_icon_text_changed(void* self, void (*slot)(void*, const char*));
void q_listwidget_custom_context_menu_requested(void* self, void* pos);
void q_listwidget_on_custom_context_menu_requested(void* self, void (*slot)(void*, void*));
int64_t q_listwidget_input_method_hints(void* self);
void q_listwidget_set_input_method_hints(void* self, int64_t hints);
void q_listwidget_render2(void* self, void* target, void* targetOffset);
void q_listwidget_render3(void* self, void* target, void* targetOffset, void* sourceRegion);
void q_listwidget_render4(void* self, void* target, void* targetOffset, void* sourceRegion, int64_t renderFlags);
void q_listwidget_render22(void* self, void* painter, void* targetOffset);
void q_listwidget_render32(void* self, void* painter, void* targetOffset, void* sourceRegion);
void q_listwidget_render42(void* self, void* painter, void* targetOffset, void* sourceRegion, int64_t renderFlags);
QPixmap* q_listwidget_grab1(void* self, void* rectangle);
void q_listwidget_grab_gesture2(void* self, int64_t typeVal, int64_t flags);
int32_t q_listwidget_grab_shortcut2(void* self, void* key, int64_t context);
void q_listwidget_set_shortcut_enabled2(void* self, int id, bool enable);
void q_listwidget_set_shortcut_auto_repeat2(void* self, int id, bool enable);
void q_listwidget_set_window_flag2(void* self, int64_t param1, bool on);
void q_listwidget_set_attribute2(void* self, int64_t param1, bool on);
QWidget* q_listwidget_create_window_container2(void* window, void* parent);
QWidget* q_listwidget_create_window_container3(void* window, void* parent, int64_t flags);
const char* q_listwidget_object_name(void* self);
void q_listwidget_set_object_name(void* self, const char* name);
bool q_listwidget_is_widget_type(void* self);
bool q_listwidget_is_window_type(void* self);
bool q_listwidget_is_quick_item_type(void* self);
bool q_listwidget_signals_blocked(void* self);
bool q_listwidget_block_signals(void* self, bool b);
QThread* q_listwidget_thread(void* self);
void q_listwidget_move_to_thread(void* self, void* thread);
int32_t q_listwidget_start_timer(void* self, int interval);
void q_listwidget_kill_timer(void* self, int id);
libqt_list /* of QObject* */ q_listwidget_children(void* self);
void q_listwidget_install_event_filter(void* self, void* filterObj);
void q_listwidget_remove_event_filter(void* self, void* obj);
QMetaObject__Connection* q_listwidget_connect(void* sender, void* signal, void* receiver, void* method);
QMetaObject__Connection* q_listwidget_connect2(void* self, void* sender, const char* signal, const char* member);
bool q_listwidget_disconnect(void* sender, void* signal, void* receiver, void* member);
bool q_listwidget_disconnect_with_q_meta_object_connection(void* param1);
void q_listwidget_dump_object_tree(void* self);
void q_listwidget_dump_object_info(void* self);
bool q_listwidget_set_property(void* self, const char* name, void* value);
QVariant* q_listwidget_property(void* self, const char* name);
const char** q_listwidget_dynamic_property_names(void* self);
QBindingStorage* q_listwidget_binding_storage(void* self);
QBindingStorage* q_listwidget_binding_storage2(void* self);
void q_listwidget_destroyed(void* self);
void q_listwidget_on_destroyed(void* self, void (*slot)(void*));
QObject* q_listwidget_parent(void* self);
bool q_listwidget_inherits(void* self, const char* classname);
void q_listwidget_delete_later(void* self);
int32_t q_listwidget_start_timer2(void* self, int interval, int64_t timerType);
QMetaObject__Connection* q_listwidget_connect5(void* sender, void* signal, void* receiver, void* method, int64_t typeVal);
QMetaObject__Connection* q_listwidget_connect4(void* self, void* sender, const char* signal, const char* member, int64_t typeVal);
void q_listwidget_destroyed1(void* self, void* param1);
void q_listwidget_on_destroyed1(void* self, void (*slot)(void*, void*));
bool q_listwidget_painting_active(void* self);
int32_t q_listwidget_width_m_m(void* self);
int32_t q_listwidget_height_m_m(void* self);
int32_t q_listwidget_logical_dpi_x(void* self);
int32_t q_listwidget_logical_dpi_y(void* self);
int32_t q_listwidget_physical_dpi_x(void* self);
int32_t q_listwidget_physical_dpi_y(void* self);
double q_listwidget_device_pixel_ratio(void* self);
double q_listwidget_device_pixel_ratio_f(void* self);
int32_t q_listwidget_color_count(void* self);
int32_t q_listwidget_depth(void* self);
double q_listwidget_device_pixel_ratio_f_scale();
QRect* q_listwidget_visual_rect(void* self, void* index);
QRect* q_listwidget_qbase_visual_rect(void* self, void* index);
void q_listwidget_on_visual_rect(void* self, QRect* (*slot)(void*, void*));
void q_listwidget_scroll_to(void* self, void* index, int64_t hint);
void q_listwidget_qbase_scroll_to(void* self, void* index, int64_t hint);
void q_listwidget_on_scroll_to(void* self, void (*slot)(void*, void*, int64_t));
QModelIndex* q_listwidget_index_at(void* self, void* p);
QModelIndex* q_listwidget_qbase_index_at(void* self, void* p);
void q_listwidget_on_index_at(void* self, QModelIndex* (*slot)(void*, void*));
void q_listwidget_do_items_layout(void* self);
void q_listwidget_qbase_do_items_layout(void* self);
void q_listwidget_on_do_items_layout(void* self, void (*slot)());
void q_listwidget_reset(void* self);
void q_listwidget_qbase_reset(void* self);
void q_listwidget_on_reset(void* self, void (*slot)());
void q_listwidget_set_root_index(void* self, void* index);
void q_listwidget_qbase_set_root_index(void* self, void* index);
void q_listwidget_on_set_root_index(void* self, void (*slot)(void*, void*));
void q_listwidget_scroll_contents_by(void* self, int dx, int dy);
void q_listwidget_qbase_scroll_contents_by(void* self, int dx, int dy);
void q_listwidget_on_scroll_contents_by(void* self, void (*slot)(void*, int, int));
void q_listwidget_data_changed(void* self, void* topLeft, void* bottomRight, int* roles[]);
void q_listwidget_qbase_data_changed(void* self, void* topLeft, void* bottomRight, int* roles[]);
void q_listwidget_on_data_changed(void* self, void (*slot)(void*, void*, void*, int*));
void q_listwidget_rows_inserted(void* self, void* parent, int start, int end);
void q_listwidget_qbase_rows_inserted(void* self, void* parent, int start, int end);
void q_listwidget_on_rows_inserted(void* self, void (*slot)(void*, void*, int, int));
void q_listwidget_rows_about_to_be_removed(void* self, void* parent, int start, int end);
void q_listwidget_qbase_rows_about_to_be_removed(void* self, void* parent, int start, int end);
void q_listwidget_on_rows_about_to_be_removed(void* self, void (*slot)(void*, void*, int, int));
void q_listwidget_mouse_move_event(void* self, void* e);
void q_listwidget_qbase_mouse_move_event(void* self, void* e);
void q_listwidget_on_mouse_move_event(void* self, void (*slot)(void*, void*));
void q_listwidget_mouse_release_event(void* self, void* e);
void q_listwidget_qbase_mouse_release_event(void* self, void* e);
void q_listwidget_on_mouse_release_event(void* self, void (*slot)(void*, void*));
void q_listwidget_wheel_event(void* self, void* e);
void q_listwidget_qbase_wheel_event(void* self, void* e);
void q_listwidget_on_wheel_event(void* self, void (*slot)(void*, void*));
void q_listwidget_timer_event(void* self, void* e);
void q_listwidget_qbase_timer_event(void* self, void* e);
void q_listwidget_on_timer_event(void* self, void (*slot)(void*, void*));
void q_listwidget_resize_event(void* self, void* e);
void q_listwidget_qbase_resize_event(void* self, void* e);
void q_listwidget_on_resize_event(void* self, void (*slot)(void*, void*));
void q_listwidget_drag_move_event(void* self, void* e);
void q_listwidget_qbase_drag_move_event(void* self, void* e);
void q_listwidget_on_drag_move_event(void* self, void (*slot)(void*, void*));
void q_listwidget_drag_leave_event(void* self, void* e);
void q_listwidget_qbase_drag_leave_event(void* self, void* e);
void q_listwidget_on_drag_leave_event(void* self, void (*slot)(void*, void*));
void q_listwidget_start_drag(void* self, int64_t supportedActions);
void q_listwidget_qbase_start_drag(void* self, int64_t supportedActions);
void q_listwidget_on_start_drag(void* self, void (*slot)(void*, int64_t));
void q_listwidget_init_view_item_option(void* self, void* option);
void q_listwidget_qbase_init_view_item_option(void* self, void* option);
void q_listwidget_on_init_view_item_option(void* self, void (*slot)(void*, void*));
void q_listwidget_paint_event(void* self, void* e);
void q_listwidget_qbase_paint_event(void* self, void* e);
void q_listwidget_on_paint_event(void* self, void (*slot)(void*, void*));
int32_t q_listwidget_horizontal_offset(void* self);
int32_t q_listwidget_qbase_horizontal_offset(void* self);
void q_listwidget_on_horizontal_offset(void* self, int32_t (*slot)());
int32_t q_listwidget_vertical_offset(void* self);
int32_t q_listwidget_qbase_vertical_offset(void* self);
void q_listwidget_on_vertical_offset(void* self, int32_t (*slot)());
QModelIndex* q_listwidget_move_cursor(void* self, int64_t cursorAction, int64_t modifiers);
QModelIndex* q_listwidget_qbase_move_cursor(void* self, int64_t cursorAction, int64_t modifiers);
void q_listwidget_on_move_cursor(void* self, QModelIndex* (*slot)(void*, int64_t, int64_t));
void q_listwidget_set_selection(void* self, void* rect, int64_t command);
void q_listwidget_qbase_set_selection(void* self, void* rect, int64_t command);
void q_listwidget_on_set_selection(void* self, void (*slot)(void*, void*, int64_t));
QRegion* q_listwidget_visual_region_for_selection(void* self, void* selection);
QRegion* q_listwidget_qbase_visual_region_for_selection(void* self, void* selection);
void q_listwidget_on_visual_region_for_selection(void* self, QRegion* (*slot)(void*, void*));
libqt_list /* of QModelIndex* */ q_listwidget_selected_indexes(void* self);
libqt_list /* of QModelIndex* */ q_listwidget_qbase_selected_indexes(void* self);
void q_listwidget_on_selected_indexes(void* self, libqt_list /* of QModelIndex* */ (*slot)());
void q_listwidget_update_geometries(void* self);
void q_listwidget_qbase_update_geometries(void* self);
void q_listwidget_on_update_geometries(void* self, void (*slot)());
bool q_listwidget_is_index_hidden(void* self, void* index);
bool q_listwidget_qbase_is_index_hidden(void* self, void* index);
void q_listwidget_on_is_index_hidden(void* self, bool (*slot)(void*, void*));
void q_listwidget_selection_changed(void* self, void* selected, void* deselected);
void q_listwidget_qbase_selection_changed(void* self, void* selected, void* deselected);
void q_listwidget_on_selection_changed(void* self, void (*slot)(void*, void*, void*));
void q_listwidget_current_changed(void* self, void* current, void* previous);
void q_listwidget_qbase_current_changed(void* self, void* current, void* previous);
void q_listwidget_on_current_changed(void* self, void (*slot)(void*, void*, void*));
QSize* q_listwidget_viewport_size_hint(void* self);
QSize* q_listwidget_qbase_viewport_size_hint(void* self);
void q_listwidget_on_viewport_size_hint(void* self, QSize* (*slot)());
void q_listwidget_keyboard_search(void* self, const char* search);
void q_listwidget_qbase_keyboard_search(void* self, const char* search);
void q_listwidget_on_keyboard_search(void* self, void (*slot)(void*, const char*));
int32_t q_listwidget_size_hint_for_row(void* self, int row);
int32_t q_listwidget_qbase_size_hint_for_row(void* self, int row);
void q_listwidget_on_size_hint_for_row(void* self, int32_t (*slot)(void*, int));
int32_t q_listwidget_size_hint_for_column(void* self, int column);
int32_t q_listwidget_qbase_size_hint_for_column(void* self, int column);
void q_listwidget_on_size_hint_for_column(void* self, int32_t (*slot)(void*, int));
QAbstractItemDelegate* q_listwidget_item_delegate_for_index(void* self, void* index);
QAbstractItemDelegate* q_listwidget_qbase_item_delegate_for_index(void* self, void* index);
void q_listwidget_on_item_delegate_for_index(void* self, QAbstractItemDelegate* (*slot)(void*, void*));
QVariant* q_listwidget_input_method_query(void* self, int64_t query);
QVariant* q_listwidget_qbase_input_method_query(void* self, int64_t query);
void q_listwidget_on_input_method_query(void* self, QVariant* (*slot)(void*, int64_t));
void q_listwidget_select_all(void* self);
void q_listwidget_qbase_select_all(void* self);
void q_listwidget_on_select_all(void* self, void (*slot)());
void q_listwidget_update_editor_data(void* self);
void q_listwidget_qbase_update_editor_data(void* self);
void q_listwidget_on_update_editor_data(void* self, void (*slot)());
void q_listwidget_update_editor_geometries(void* self);
void q_listwidget_qbase_update_editor_geometries(void* self);
void q_listwidget_on_update_editor_geometries(void* self, void (*slot)());
void q_listwidget_vertical_scrollbar_action(void* self, int action);
void q_listwidget_qbase_vertical_scrollbar_action(void* self, int action);
void q_listwidget_on_vertical_scrollbar_action(void* self, void (*slot)(void*, int));
void q_listwidget_horizontal_scrollbar_action(void* self, int action);
void q_listwidget_qbase_horizontal_scrollbar_action(void* self, int action);
void q_listwidget_on_horizontal_scrollbar_action(void* self, void (*slot)(void*, int));
void q_listwidget_vertical_scrollbar_value_changed(void* self, int value);
void q_listwidget_qbase_vertical_scrollbar_value_changed(void* self, int value);
void q_listwidget_on_vertical_scrollbar_value_changed(void* self, void (*slot)(void*, int));
void q_listwidget_horizontal_scrollbar_value_changed(void* self, int value);
void q_listwidget_qbase_horizontal_scrollbar_value_changed(void* self, int value);
void q_listwidget_on_horizontal_scrollbar_value_changed(void* self, void (*slot)(void*, int));
void q_listwidget_close_editor(void* self, void* editor, int64_t hint);
void q_listwidget_qbase_close_editor(void* self, void* editor, int64_t hint);
void q_listwidget_on_close_editor(void* self, void (*slot)(void*, void*, int64_t));
void q_listwidget_commit_data(void* self, void* editor);
void q_listwidget_qbase_commit_data(void* self, void* editor);
void q_listwidget_on_commit_data(void* self, void (*slot)(void*, void*));
void q_listwidget_editor_destroyed(void* self, void* editor);
void q_listwidget_qbase_editor_destroyed(void* self, void* editor);
void q_listwidget_on_editor_destroyed(void* self, void (*slot)(void*, void*));
bool q_listwidget_edit2(void* self, void* index, int64_t trigger, void* event);
bool q_listwidget_qbase_edit2(void* self, void* index, int64_t trigger, void* event);
void q_listwidget_on_edit2(void* self, bool (*slot)(void*, void*, int64_t, void*));
int64_t q_listwidget_selection_command(void* self, void* index, void* event);
int64_t q_listwidget_qbase_selection_command(void* self, void* index, void* event);
void q_listwidget_on_selection_command(void* self, int64_t (*slot)(void*, void*, void*));
bool q_listwidget_focus_next_prev_child(void* self, bool next);
bool q_listwidget_qbase_focus_next_prev_child(void* self, bool next);
void q_listwidget_on_focus_next_prev_child(void* self, bool (*slot)(void*, bool));
bool q_listwidget_viewport_event(void* self, void* event);
bool q_listwidget_qbase_viewport_event(void* self, void* event);
void q_listwidget_on_viewport_event(void* self, bool (*slot)(void*, void*));
void q_listwidget_mouse_press_event(void* self, void* event);
void q_listwidget_qbase_mouse_press_event(void* self, void* event);
void q_listwidget_on_mouse_press_event(void* self, void (*slot)(void*, void*));
void q_listwidget_mouse_double_click_event(void* self, void* event);
void q_listwidget_qbase_mouse_double_click_event(void* self, void* event);
void q_listwidget_on_mouse_double_click_event(void* self, void (*slot)(void*, void*));
void q_listwidget_drag_enter_event(void* self, void* event);
void q_listwidget_qbase_drag_enter_event(void* self, void* event);
void q_listwidget_on_drag_enter_event(void* self, void (*slot)(void*, void*));
void q_listwidget_focus_in_event(void* self, void* event);
void q_listwidget_qbase_focus_in_event(void* self, void* event);
void q_listwidget_on_focus_in_event(void* self, void (*slot)(void*, void*));
void q_listwidget_focus_out_event(void* self, void* event);
void q_listwidget_qbase_focus_out_event(void* self, void* event);
void q_listwidget_on_focus_out_event(void* self, void (*slot)(void*, void*));
void q_listwidget_key_press_event(void* self, void* event);
void q_listwidget_qbase_key_press_event(void* self, void* event);
void q_listwidget_on_key_press_event(void* self, void (*slot)(void*, void*));
void q_listwidget_input_method_event(void* self, void* event);
void q_listwidget_qbase_input_method_event(void* self, void* event);
void q_listwidget_on_input_method_event(void* self, void (*slot)(void*, void*));
bool q_listwidget_event_filter(void* self, void* object, void* event);
bool q_listwidget_qbase_event_filter(void* self, void* object, void* event);
void q_listwidget_on_event_filter(void* self, bool (*slot)(void*, void*, void*));
QSize* q_listwidget_minimum_size_hint(void* self);
QSize* q_listwidget_qbase_minimum_size_hint(void* self);
void q_listwidget_on_minimum_size_hint(void* self, QSize* (*slot)());
QSize* q_listwidget_size_hint(void* self);
QSize* q_listwidget_qbase_size_hint(void* self);
void q_listwidget_on_size_hint(void* self, QSize* (*slot)());
void q_listwidget_setup_viewport(void* self, void* viewport);
void q_listwidget_qbase_setup_viewport(void* self, void* viewport);
void q_listwidget_on_setup_viewport(void* self, void (*slot)(void*, void*));
void q_listwidget_context_menu_event(void* self, void* param1);
void q_listwidget_qbase_context_menu_event(void* self, void* param1);
void q_listwidget_on_context_menu_event(void* self, void (*slot)(void*, void*));
void q_listwidget_change_event(void* self, void* param1);
void q_listwidget_qbase_change_event(void* self, void* param1);
void q_listwidget_on_change_event(void* self, void (*slot)(void*, void*));
void q_listwidget_init_style_option(void* self, void* option);
void q_listwidget_qbase_init_style_option(void* self, void* option);
void q_listwidget_on_init_style_option(void* self, void (*slot)(void*, void*));
int32_t q_listwidget_dev_type(void* self);
int32_t q_listwidget_qbase_dev_type(void* self);
void q_listwidget_on_dev_type(void* self, int32_t (*slot)());
void q_listwidget_set_visible(void* self, bool visible);
void q_listwidget_qbase_set_visible(void* self, bool visible);
void q_listwidget_on_set_visible(void* self, void (*slot)(void*, bool));
int32_t q_listwidget_height_for_width(void* self, int param1);
int32_t q_listwidget_qbase_height_for_width(void* self, int param1);
void q_listwidget_on_height_for_width(void* self, int32_t (*slot)(void*, int));
bool q_listwidget_has_height_for_width(void* self);
bool q_listwidget_qbase_has_height_for_width(void* self);
void q_listwidget_on_has_height_for_width(void* self, bool (*slot)());
QPaintEngine* q_listwidget_paint_engine(void* self);
QPaintEngine* q_listwidget_qbase_paint_engine(void* self);
void q_listwidget_on_paint_engine(void* self, QPaintEngine* (*slot)());
void q_listwidget_key_release_event(void* self, void* event);
void q_listwidget_qbase_key_release_event(void* self, void* event);
void q_listwidget_on_key_release_event(void* self, void (*slot)(void*, void*));
void q_listwidget_enter_event(void* self, void* event);
void q_listwidget_qbase_enter_event(void* self, void* event);
void q_listwidget_on_enter_event(void* self, void (*slot)(void*, void*));
void q_listwidget_leave_event(void* self, void* event);
void q_listwidget_qbase_leave_event(void* self, void* event);
void q_listwidget_on_leave_event(void* self, void (*slot)(void*, void*));
void q_listwidget_move_event(void* self, void* event);
void q_listwidget_qbase_move_event(void* self, void* event);
void q_listwidget_on_move_event(void* self, void (*slot)(void*, void*));
void q_listwidget_close_event(void* self, void* event);
void q_listwidget_qbase_close_event(void* self, void* event);
void q_listwidget_on_close_event(void* self, void (*slot)(void*, void*));
void q_listwidget_tablet_event(void* self, void* event);
void q_listwidget_qbase_tablet_event(void* self, void* event);
void q_listwidget_on_tablet_event(void* self, void (*slot)(void*, void*));
void q_listwidget_action_event(void* self, void* event);
void q_listwidget_qbase_action_event(void* self, void* event);
void q_listwidget_on_action_event(void* self, void (*slot)(void*, void*));
void q_listwidget_show_event(void* self, void* event);
void q_listwidget_qbase_show_event(void* self, void* event);
void q_listwidget_on_show_event(void* self, void (*slot)(void*, void*));
void q_listwidget_hide_event(void* self, void* event);
void q_listwidget_qbase_hide_event(void* self, void* event);
void q_listwidget_on_hide_event(void* self, void (*slot)(void*, void*));
bool q_listwidget_native_event(void* self, const char* eventType, void* message, intptr_t* result);
bool q_listwidget_qbase_native_event(void* self, const char* eventType, void* message, intptr_t* result);
void q_listwidget_on_native_event(void* self, bool (*slot)(void*, const char*, void*, intptr_t*));
int32_t q_listwidget_metric(void* self, int64_t param1);
int32_t q_listwidget_qbase_metric(void* self, int64_t param1);
void q_listwidget_on_metric(void* self, int32_t (*slot)(void*, int64_t));
void q_listwidget_init_painter(void* self, void* painter);
void q_listwidget_qbase_init_painter(void* self, void* painter);
void q_listwidget_on_init_painter(void* self, void (*slot)(void*, void*));
QPaintDevice* q_listwidget_redirected(void* self, void* offset);
QPaintDevice* q_listwidget_qbase_redirected(void* self, void* offset);
void q_listwidget_on_redirected(void* self, QPaintDevice* (*slot)(void*, void*));
QPainter* q_listwidget_shared_painter(void* self);
QPainter* q_listwidget_qbase_shared_painter(void* self);
void q_listwidget_on_shared_painter(void* self, QPainter* (*slot)());
void q_listwidget_child_event(void* self, void* event);
void q_listwidget_qbase_child_event(void* self, void* event);
void q_listwidget_on_child_event(void* self, void (*slot)(void*, void*));
void q_listwidget_custom_event(void* self, void* event);
void q_listwidget_qbase_custom_event(void* self, void* event);
void q_listwidget_on_custom_event(void* self, void (*slot)(void*, void*));
void q_listwidget_connect_notify(void* self, void* signal);
void q_listwidget_qbase_connect_notify(void* self, void* signal);
void q_listwidget_on_connect_notify(void* self, void (*slot)(void*, void*));
void q_listwidget_disconnect_notify(void* self, void* signal);
void q_listwidget_qbase_disconnect_notify(void* self, void* signal);
void q_listwidget_on_disconnect_notify(void* self, void (*slot)(void*, void*));
void q_listwidget_resize_contents(void* self, int width, int height);
void q_listwidget_qbase_resize_contents(void* self, int width, int height);
void q_listwidget_on_resize_contents(void* self, void (*slot)(void*, int, int));
QSize* q_listwidget_contents_size(void* self);
QSize* q_listwidget_qbase_contents_size(void* self);
void q_listwidget_on_contents_size(void* self, QSize* (*slot)());
QRect* q_listwidget_rect_for_index(void* self, void* index);
QRect* q_listwidget_qbase_rect_for_index(void* self, void* index);
void q_listwidget_on_rect_for_index(void* self, QRect* (*slot)(void*, void*));
void q_listwidget_set_position_for_index(void* self, void* position, void* index);
void q_listwidget_qbase_set_position_for_index(void* self, void* position, void* index);
void q_listwidget_on_set_position_for_index(void* self, void (*slot)(void*, void*, void*));
int64_t q_listwidget_state(void* self);
int64_t q_listwidget_qbase_state(void* self);
void q_listwidget_on_state(void* self, int64_t (*slot)());
void q_listwidget_set_state(void* self, int64_t state);
void q_listwidget_qbase_set_state(void* self, int64_t state);
void q_listwidget_on_set_state(void* self, void (*slot)(void*, int64_t));
void q_listwidget_schedule_delayed_items_layout(void* self);
void q_listwidget_qbase_schedule_delayed_items_layout(void* self);
void q_listwidget_on_schedule_delayed_items_layout(void* self, void (*slot)());
void q_listwidget_execute_delayed_items_layout(void* self);
void q_listwidget_qbase_execute_delayed_items_layout(void* self);
void q_listwidget_on_execute_delayed_items_layout(void* self, void (*slot)());
void q_listwidget_set_dirty_region(void* self, void* region);
void q_listwidget_qbase_set_dirty_region(void* self, void* region);
void q_listwidget_on_set_dirty_region(void* self, void (*slot)(void*, void*));
void q_listwidget_scroll_dirty_region(void* self, int dx, int dy);
void q_listwidget_qbase_scroll_dirty_region(void* self, int dx, int dy);
void q_listwidget_on_scroll_dirty_region(void* self, void (*slot)(void*, int, int));
QPoint* q_listwidget_dirty_region_offset(void* self);
QPoint* q_listwidget_qbase_dirty_region_offset(void* self);
void q_listwidget_on_dirty_region_offset(void* self, QPoint* (*slot)());
void q_listwidget_start_auto_scroll(void* self);
void q_listwidget_qbase_start_auto_scroll(void* self);
void q_listwidget_on_start_auto_scroll(void* self, void (*slot)());
void q_listwidget_stop_auto_scroll(void* self);
void q_listwidget_qbase_stop_auto_scroll(void* self);
void q_listwidget_on_stop_auto_scroll(void* self, void (*slot)());
void q_listwidget_do_auto_scroll(void* self);
void q_listwidget_qbase_do_auto_scroll(void* self);
void q_listwidget_on_do_auto_scroll(void* self, void (*slot)());
int64_t q_listwidget_drop_indicator_position(void* self);
int64_t q_listwidget_qbase_drop_indicator_position(void* self);
void q_listwidget_on_drop_indicator_position(void* self, int64_t (*slot)());
void q_listwidget_set_viewport_margins(void* self, int left, int top, int right, int bottom);
void q_listwidget_qbase_set_viewport_margins(void* self, int left, int top, int right, int bottom);
void q_listwidget_on_set_viewport_margins(void* self, void (*slot)(void*, int, int, int, int));
QMargins* q_listwidget_viewport_margins(void* self);
QMargins* q_listwidget_qbase_viewport_margins(void* self);
void q_listwidget_on_viewport_margins(void* self, QMargins* (*slot)());
void q_listwidget_draw_frame(void* self, void* param1);
void q_listwidget_qbase_draw_frame(void* self, void* param1);
void q_listwidget_on_draw_frame(void* self, void (*slot)(void*, void*));
void q_listwidget_update_micro_focus(void* self);
void q_listwidget_qbase_update_micro_focus(void* self);
void q_listwidget_on_update_micro_focus(void* self, void (*slot)());
void q_listwidget_create(void* self);
void q_listwidget_qbase_create(void* self);
void q_listwidget_on_create(void* self, void (*slot)());
void q_listwidget_destroy(void* self);
void q_listwidget_qbase_destroy(void* self);
void q_listwidget_on_destroy(void* self, void (*slot)());
bool q_listwidget_focus_next_child(void* self);
bool q_listwidget_qbase_focus_next_child(void* self);
void q_listwidget_on_focus_next_child(void* self, bool (*slot)());
bool q_listwidget_focus_previous_child(void* self);
bool q_listwidget_qbase_focus_previous_child(void* self);
void q_listwidget_on_focus_previous_child(void* self, bool (*slot)());
QObject* q_listwidget_sender(void* self);
QObject* q_listwidget_qbase_sender(void* self);
void q_listwidget_on_sender(void* self, QObject* (*slot)());
int32_t q_listwidget_sender_signal_index(void* self);
int32_t q_listwidget_qbase_sender_signal_index(void* self);
void q_listwidget_on_sender_signal_index(void* self, int32_t (*slot)());
int32_t q_listwidget_receivers(void* self, const char* signal);
int32_t q_listwidget_qbase_receivers(void* self, const char* signal);
void q_listwidget_on_receivers(void* self, int32_t (*slot)(void*, const char*));
bool q_listwidget_is_signal_connected(void* self, void* signal);
bool q_listwidget_qbase_is_signal_connected(void* self, void* signal);
void q_listwidget_on_is_signal_connected(void* self, bool (*slot)(void*, void*));
void q_listwidget_delete(void* self);

/// https://doc.qt.io/qt-6/qlistwidget.html#types

typedef enum {
    QLISTWIDGETITEM_ITEMTYPE_TYPE = 0,
    QLISTWIDGETITEM_ITEMTYPE_USERTYPE = 1000
} QListWidgetItem__ItemType;

#endif
