#pragma once
#ifndef SRCQT6C_LIBQUNDOVIEW_H
#define SRCQT6C_LIBQUNDOVIEW_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#include "libqabstractitemdelegate.h"
#include "libqabstractitemmodel.h"
#include "libqabstractitemview.h"
#include "libqabstractscrollarea.h"
#include "libqaction.h"
#include "libqevent.h"
#include "libqanystringview.h"
#include "libqbackingstore.h"
#include "libqbindingstorage.h"
#include "libqbitmap.h"
#include "libqcursor.h"
#include "libqfont.h"
#include "libqfontinfo.h"
#include "libqfontmetrics.h"
#include "libqframe.h"
#include "libqgraphicseffect.h"
#include "libqgraphicsproxywidget.h"
#include "libqicon.h"
#include "libqitemselectionmodel.h"
#include "libqkeysequence.h"
#include "libqlayout.h"
#include "libqlistview.h"
#include "libqlocale.h"
#include "libqmargins.h"
#include "libqmetaobject.h"
#include "libqobject.h"
#include "libqpaintdevice.h"
#include "libqpaintengine.h"
#include "libqpainter.h"
#include "libqpalette.h"
#include "libqpixmap.h"
#include "libqpoint.h"
#include "libqrect.h"
#include "libqregion.h"
#include "libqscreen.h"
#include "libqscrollbar.h"
#include "libqsize.h"
#include "libqsizepolicy.h"
#include <string.h>
#include "libqstyle.h"
#include "libqstyleoption.h"
#include "libqthread.h"
#include "libqundogroup.h"
#include "libqundostack.h"
#include "libqvariant.h"
#include "libqwidget.h"
#include "libqwindow.h"

QUndoView* q_undoview_new(void* parent);
QUndoView* q_undoview_new2();
QUndoView* q_undoview_new3(void* stack);
QUndoView* q_undoview_new4(void* group);
QUndoView* q_undoview_new5(void* stack, void* parent);
QUndoView* q_undoview_new6(void* group, void* parent);
QMetaObject* q_undoview_meta_object(void* self);
void* q_undoview_metacast(void* self, const char* param1);
int32_t q_undoview_metacall(void* self, int64_t param1, int param2, void* param3);
void q_undoview_on_metacall(void* self, int32_t (*slot)(void*, int64_t, int, void*));
int32_t q_undoview_qbase_metacall(void* self, int64_t param1, int param2, void* param3);
const char* q_undoview_tr(const char* s);
QUndoStack* q_undoview_stack(void* self);
QUndoGroup* q_undoview_group(void* self);
void q_undoview_set_empty_label(void* self, const char* label);
const char* q_undoview_empty_label(void* self);
void q_undoview_set_clean_icon(void* self, void* icon);
QIcon* q_undoview_clean_icon(void* self);
void q_undoview_set_stack(void* self, void* stack);
void q_undoview_set_group(void* self, void* group);
const char* q_undoview_tr2(const char* s, const char* c);
const char* q_undoview_tr3(const char* s, const char* c, int n);
void q_undoview_set_movement(void* self, int64_t movement);
int64_t q_undoview_movement(void* self);
void q_undoview_set_flow(void* self, int64_t flow);
int64_t q_undoview_flow(void* self);
void q_undoview_set_wrapping(void* self, bool enable);
bool q_undoview_is_wrapping(void* self);
void q_undoview_set_resize_mode(void* self, int64_t mode);
int64_t q_undoview_resize_mode(void* self);
void q_undoview_set_layout_mode(void* self, int64_t mode);
int64_t q_undoview_layout_mode(void* self);
void q_undoview_set_spacing(void* self, int space);
int32_t q_undoview_spacing(void* self);
void q_undoview_set_batch_size(void* self, int batchSize);
int32_t q_undoview_batch_size(void* self);
void q_undoview_set_grid_size(void* self, void* size);
QSize* q_undoview_grid_size(void* self);
void q_undoview_set_view_mode(void* self, int64_t mode);
int64_t q_undoview_view_mode(void* self);
void q_undoview_clear_property_flags(void* self);
bool q_undoview_is_row_hidden(void* self, int row);
void q_undoview_set_row_hidden(void* self, int row, bool hide);
void q_undoview_set_model_column(void* self, int column);
int32_t q_undoview_model_column(void* self);
void q_undoview_set_uniform_item_sizes(void* self, bool enable);
bool q_undoview_uniform_item_sizes(void* self);
void q_undoview_set_word_wrap(void* self, bool on);
bool q_undoview_word_wrap(void* self);
void q_undoview_set_selection_rect_visible(void* self, bool show);
bool q_undoview_is_selection_rect_visible(void* self);
void q_undoview_set_item_alignment(void* self, int64_t alignment);
int64_t q_undoview_item_alignment(void* self);
void q_undoview_indexes_moved(void* self, void* indexes[]);
void q_undoview_on_indexes_moved(void* self, void (*slot)(void*, void*));
QAbstractItemModel* q_undoview_model(void* self);
QItemSelectionModel* q_undoview_selection_model(void* self);
void q_undoview_set_item_delegate(void* self, void* delegate);
QAbstractItemDelegate* q_undoview_item_delegate(void* self);
void q_undoview_set_selection_mode(void* self, int64_t mode);
int64_t q_undoview_selection_mode(void* self);
void q_undoview_set_selection_behavior(void* self, int64_t behavior);
int64_t q_undoview_selection_behavior(void* self);
QModelIndex* q_undoview_current_index(void* self);
QModelIndex* q_undoview_root_index(void* self);
void q_undoview_set_edit_triggers(void* self, int64_t triggers);
int64_t q_undoview_edit_triggers(void* self);
void q_undoview_set_vertical_scroll_mode(void* self, int64_t mode);
int64_t q_undoview_vertical_scroll_mode(void* self);
void q_undoview_reset_vertical_scroll_mode(void* self);
void q_undoview_set_horizontal_scroll_mode(void* self, int64_t mode);
int64_t q_undoview_horizontal_scroll_mode(void* self);
void q_undoview_reset_horizontal_scroll_mode(void* self);
void q_undoview_set_auto_scroll(void* self, bool enable);
bool q_undoview_has_auto_scroll(void* self);
void q_undoview_set_auto_scroll_margin(void* self, int margin);
int32_t q_undoview_auto_scroll_margin(void* self);
void q_undoview_set_tab_key_navigation(void* self, bool enable);
bool q_undoview_tab_key_navigation(void* self);
void q_undoview_set_drop_indicator_shown(void* self, bool enable);
bool q_undoview_show_drop_indicator(void* self);
void q_undoview_set_drag_enabled(void* self, bool enable);
bool q_undoview_drag_enabled(void* self);
void q_undoview_set_drag_drop_overwrite_mode(void* self, bool overwrite);
bool q_undoview_drag_drop_overwrite_mode(void* self);
void q_undoview_set_drag_drop_mode(void* self, int64_t behavior);
int64_t q_undoview_drag_drop_mode(void* self);
void q_undoview_set_default_drop_action(void* self, int64_t dropAction);
int64_t q_undoview_default_drop_action(void* self);
void q_undoview_set_alternating_row_colors(void* self, bool enable);
bool q_undoview_alternating_row_colors(void* self);
void q_undoview_set_icon_size(void* self, void* size);
QSize* q_undoview_icon_size(void* self);
void q_undoview_set_text_elide_mode(void* self, int64_t mode);
int64_t q_undoview_text_elide_mode(void* self);
QSize* q_undoview_size_hint_for_index(void* self, void* index);
void q_undoview_open_persistent_editor(void* self, void* index);
void q_undoview_close_persistent_editor(void* self, void* index);
bool q_undoview_is_persistent_editor_open(void* self, void* index);
void q_undoview_set_index_widget(void* self, void* index, void* widget);
QWidget* q_undoview_index_widget(void* self, void* index);
void q_undoview_set_item_delegate_for_row(void* self, int row, void* delegate);
QAbstractItemDelegate* q_undoview_item_delegate_for_row(void* self, int row);
void q_undoview_set_item_delegate_for_column(void* self, int column, void* delegate);
QAbstractItemDelegate* q_undoview_item_delegate_for_column(void* self, int column);
QAbstractItemDelegate* q_undoview_item_delegate_with_index(void* self, void* index);
void q_undoview_edit(void* self, void* index);
void q_undoview_clear_selection(void* self);
void q_undoview_set_current_index(void* self, void* index);
void q_undoview_scroll_to_top(void* self);
void q_undoview_scroll_to_bottom(void* self);
void q_undoview_update(void* self, void* index);
void q_undoview_pressed(void* self, void* index);
void q_undoview_on_pressed(void* self, void (*slot)(void*, void*));
void q_undoview_clicked(void* self, void* index);
void q_undoview_on_clicked(void* self, void (*slot)(void*, void*));
void q_undoview_double_clicked(void* self, void* index);
void q_undoview_on_double_clicked(void* self, void (*slot)(void*, void*));
void q_undoview_activated(void* self, void* index);
void q_undoview_on_activated(void* self, void (*slot)(void*, void*));
void q_undoview_entered(void* self, void* index);
void q_undoview_on_entered(void* self, void (*slot)(void*, void*));
void q_undoview_viewport_entered(void* self);
void q_undoview_on_viewport_entered(void* self, void (*slot)(void*));
void q_undoview_icon_size_changed(void* self, void* size);
void q_undoview_on_icon_size_changed(void* self, void (*slot)(void*, void*));
int64_t q_undoview_vertical_scroll_bar_policy(void* self);
void q_undoview_set_vertical_scroll_bar_policy(void* self, int64_t verticalScrollBarPolicy);
QScrollBar* q_undoview_vertical_scroll_bar(void* self);
void q_undoview_set_vertical_scroll_bar(void* self, void* scrollbar);
int64_t q_undoview_horizontal_scroll_bar_policy(void* self);
void q_undoview_set_horizontal_scroll_bar_policy(void* self, int64_t horizontalScrollBarPolicy);
QScrollBar* q_undoview_horizontal_scroll_bar(void* self);
void q_undoview_set_horizontal_scroll_bar(void* self, void* scrollbar);
QWidget* q_undoview_corner_widget(void* self);
void q_undoview_set_corner_widget(void* self, void* widget);
void q_undoview_add_scroll_bar_widget(void* self, void* widget, int64_t alignment);
libqt_list /* of QWidget* */ q_undoview_scroll_bar_widgets(void* self, int64_t alignment);
QWidget* q_undoview_viewport(void* self);
void q_undoview_set_viewport(void* self, void* widget);
QSize* q_undoview_maximum_viewport_size(void* self);
int64_t q_undoview_size_adjust_policy(void* self);
void q_undoview_set_size_adjust_policy(void* self, int64_t policy);
int32_t q_undoview_frame_style(void* self);
void q_undoview_set_frame_style(void* self, int frameStyle);
int32_t q_undoview_frame_width(void* self);
int64_t q_undoview_frame_shape(void* self);
void q_undoview_set_frame_shape(void* self, int64_t frameShape);
int64_t q_undoview_frame_shadow(void* self);
void q_undoview_set_frame_shadow(void* self, int64_t frameShadow);
int32_t q_undoview_line_width(void* self);
void q_undoview_set_line_width(void* self, int lineWidth);
int32_t q_undoview_mid_line_width(void* self);
void q_undoview_set_mid_line_width(void* self, int midLineWidth);
QRect* q_undoview_frame_rect(void* self);
void q_undoview_set_frame_rect(void* self, void* frameRect);
uintptr_t q_undoview_win_id(void* self);
void q_undoview_create_win_id(void* self);
uintptr_t q_undoview_internal_win_id(void* self);
uintptr_t q_undoview_effective_win_id(void* self);
QStyle* q_undoview_style(void* self);
void q_undoview_set_style(void* self, void* style);
bool q_undoview_is_top_level(void* self);
bool q_undoview_is_window(void* self);
bool q_undoview_is_modal(void* self);
int64_t q_undoview_window_modality(void* self);
void q_undoview_set_window_modality(void* self, int64_t windowModality);
bool q_undoview_is_enabled(void* self);
bool q_undoview_is_enabled_to(void* self, void* param1);
void q_undoview_set_enabled(void* self, bool enabled);
void q_undoview_set_disabled(void* self, bool disabled);
void q_undoview_set_window_modified(void* self, bool windowModified);
QRect* q_undoview_frame_geometry(void* self);
QRect* q_undoview_geometry(void* self);
QRect* q_undoview_normal_geometry(void* self);
int32_t q_undoview_x(void* self);
int32_t q_undoview_y(void* self);
QPoint* q_undoview_pos(void* self);
QSize* q_undoview_frame_size(void* self);
QSize* q_undoview_size(void* self);
int32_t q_undoview_width(void* self);
int32_t q_undoview_height(void* self);
QRect* q_undoview_rect(void* self);
QRect* q_undoview_children_rect(void* self);
QRegion* q_undoview_children_region(void* self);
QSize* q_undoview_minimum_size(void* self);
QSize* q_undoview_maximum_size(void* self);
int32_t q_undoview_minimum_width(void* self);
int32_t q_undoview_minimum_height(void* self);
int32_t q_undoview_maximum_width(void* self);
int32_t q_undoview_maximum_height(void* self);
void q_undoview_set_minimum_size(void* self, void* minimumSize);
void q_undoview_set_minimum_size2(void* self, int minw, int minh);
void q_undoview_set_maximum_size(void* self, void* maximumSize);
void q_undoview_set_maximum_size2(void* self, int maxw, int maxh);
void q_undoview_set_minimum_width(void* self, int minw);
void q_undoview_set_minimum_height(void* self, int minh);
void q_undoview_set_maximum_width(void* self, int maxw);
void q_undoview_set_maximum_height(void* self, int maxh);
QSize* q_undoview_size_increment(void* self);
void q_undoview_set_size_increment(void* self, void* sizeIncrement);
void q_undoview_set_size_increment2(void* self, int w, int h);
QSize* q_undoview_base_size(void* self);
void q_undoview_set_base_size(void* self, void* baseSize);
void q_undoview_set_base_size2(void* self, int basew, int baseh);
void q_undoview_set_fixed_size(void* self, void* fixedSize);
void q_undoview_set_fixed_size2(void* self, int w, int h);
void q_undoview_set_fixed_width(void* self, int w);
void q_undoview_set_fixed_height(void* self, int h);
QPointF* q_undoview_map_to_global(void* self, void* param1);
QPoint* q_undoview_map_to_global_with_q_point(void* self, void* param1);
QPointF* q_undoview_map_from_global(void* self, void* param1);
QPoint* q_undoview_map_from_global_with_q_point(void* self, void* param1);
QPointF* q_undoview_map_to_parent(void* self, void* param1);
QPoint* q_undoview_map_to_parent_with_q_point(void* self, void* param1);
QPointF* q_undoview_map_from_parent(void* self, void* param1);
QPoint* q_undoview_map_from_parent_with_q_point(void* self, void* param1);
QPointF* q_undoview_map_to(void* self, void* param1, void* param2);
QPoint* q_undoview_map_to2(void* self, void* param1, void* param2);
QPointF* q_undoview_map_from(void* self, void* param1, void* param2);
QPoint* q_undoview_map_from2(void* self, void* param1, void* param2);
QWidget* q_undoview_window(void* self);
QWidget* q_undoview_native_parent_widget(void* self);
QWidget* q_undoview_top_level_widget(void* self);
QPalette* q_undoview_palette(void* self);
void q_undoview_set_palette(void* self, void* palette);
void q_undoview_set_background_role(void* self, int64_t backgroundRole);
int64_t q_undoview_background_role(void* self);
void q_undoview_set_foreground_role(void* self, int64_t foregroundRole);
int64_t q_undoview_foreground_role(void* self);
QFont* q_undoview_font(void* self);
void q_undoview_set_font(void* self, void* font);
QFontMetrics* q_undoview_font_metrics(void* self);
QFontInfo* q_undoview_font_info(void* self);
QCursor* q_undoview_cursor(void* self);
void q_undoview_set_cursor(void* self, void* cursor);
void q_undoview_unset_cursor(void* self);
void q_undoview_set_mouse_tracking(void* self, bool enable);
bool q_undoview_has_mouse_tracking(void* self);
bool q_undoview_under_mouse(void* self);
void q_undoview_set_tablet_tracking(void* self, bool enable);
bool q_undoview_has_tablet_tracking(void* self);
void q_undoview_set_mask(void* self, void* mask);
void q_undoview_set_mask_with_mask(void* self, void* mask);
QRegion* q_undoview_mask(void* self);
void q_undoview_clear_mask(void* self);
void q_undoview_render(void* self, void* target);
void q_undoview_render_with_painter(void* self, void* painter);
QPixmap* q_undoview_grab(void* self);
QGraphicsEffect* q_undoview_graphics_effect(void* self);
void q_undoview_set_graphics_effect(void* self, void* effect);
void q_undoview_grab_gesture(void* self, int64_t typeVal);
void q_undoview_ungrab_gesture(void* self, int64_t typeVal);
void q_undoview_set_window_title(void* self, const char* windowTitle);
void q_undoview_set_style_sheet(void* self, const char* styleSheet);
const char* q_undoview_style_sheet(void* self);
const char* q_undoview_window_title(void* self);
void q_undoview_set_window_icon(void* self, void* icon);
QIcon* q_undoview_window_icon(void* self);
void q_undoview_set_window_icon_text(void* self, const char* windowIconText);
const char* q_undoview_window_icon_text(void* self);
void q_undoview_set_window_role(void* self, const char* windowRole);
const char* q_undoview_window_role(void* self);
void q_undoview_set_window_file_path(void* self, const char* filePath);
const char* q_undoview_window_file_path(void* self);
void q_undoview_set_window_opacity(void* self, double level);
double q_undoview_window_opacity(void* self);
bool q_undoview_is_window_modified(void* self);
void q_undoview_set_tool_tip(void* self, const char* toolTip);
const char* q_undoview_tool_tip(void* self);
void q_undoview_set_tool_tip_duration(void* self, int msec);
int32_t q_undoview_tool_tip_duration(void* self);
void q_undoview_set_status_tip(void* self, const char* statusTip);
const char* q_undoview_status_tip(void* self);
void q_undoview_set_whats_this(void* self, const char* whatsThis);
const char* q_undoview_whats_this(void* self);
const char* q_undoview_accessible_name(void* self);
void q_undoview_set_accessible_name(void* self, const char* name);
const char* q_undoview_accessible_description(void* self);
void q_undoview_set_accessible_description(void* self, const char* description);
void q_undoview_set_layout_direction(void* self, int64_t direction);
int64_t q_undoview_layout_direction(void* self);
void q_undoview_unset_layout_direction(void* self);
void q_undoview_set_locale(void* self, void* locale);
QLocale* q_undoview_locale(void* self);
void q_undoview_unset_locale(void* self);
bool q_undoview_is_right_to_left(void* self);
bool q_undoview_is_left_to_right(void* self);
void q_undoview_set_focus(void* self);
bool q_undoview_is_active_window(void* self);
void q_undoview_activate_window(void* self);
void q_undoview_clear_focus(void* self);
void q_undoview_set_focus_with_reason(void* self, int64_t reason);
int64_t q_undoview_focus_policy(void* self);
void q_undoview_set_focus_policy(void* self, int64_t policy);
bool q_undoview_has_focus(void* self);
void q_undoview_set_tab_order(void* param1, void* param2);
void q_undoview_set_focus_proxy(void* self, void* focusProxy);
QWidget* q_undoview_focus_proxy(void* self);
int64_t q_undoview_context_menu_policy(void* self);
void q_undoview_set_context_menu_policy(void* self, int64_t policy);
void q_undoview_grab_mouse(void* self);
void q_undoview_grab_mouse_with_q_cursor(void* self, void* param1);
void q_undoview_release_mouse(void* self);
void q_undoview_grab_keyboard(void* self);
void q_undoview_release_keyboard(void* self);
int32_t q_undoview_grab_shortcut(void* self, void* key);
void q_undoview_release_shortcut(void* self, int id);
void q_undoview_set_shortcut_enabled(void* self, int id);
void q_undoview_set_shortcut_auto_repeat(void* self, int id);
QWidget* q_undoview_mouse_grabber();
QWidget* q_undoview_keyboard_grabber();
bool q_undoview_updates_enabled(void* self);
void q_undoview_set_updates_enabled(void* self, bool enable);
QGraphicsProxyWidget* q_undoview_graphics_proxy_widget(void* self);
void q_undoview_repaint(void* self);
void q_undoview_update2(void* self, int x, int y, int w, int h);
void q_undoview_update_with_q_rect(void* self, void* param1);
void q_undoview_update_with_q_region(void* self, void* param1);
void q_undoview_repaint2(void* self, int x, int y, int w, int h);
void q_undoview_repaint_with_q_rect(void* self, void* param1);
void q_undoview_repaint_with_q_region(void* self, void* param1);
void q_undoview_set_hidden(void* self, bool hidden);
void q_undoview_show(void* self);
void q_undoview_hide(void* self);
void q_undoview_show_minimized(void* self);
void q_undoview_show_maximized(void* self);
void q_undoview_show_full_screen(void* self);
void q_undoview_show_normal(void* self);
bool q_undoview_close(void* self);
void q_undoview_raise(void* self);
void q_undoview_lower(void* self);
void q_undoview_stack_under(void* self, void* param1);
void q_undoview_move(void* self, int x, int y);
void q_undoview_move_with_q_point(void* self, void* param1);
void q_undoview_resize(void* self, int w, int h);
void q_undoview_resize_with_q_size(void* self, void* param1);
void q_undoview_set_geometry(void* self, int x, int y, int w, int h);
void q_undoview_set_geometry_with_geometry(void* self, void* geometry);
char* q_undoview_save_geometry(void* self);
bool q_undoview_restore_geometry(void* self, const char* geometry);
void q_undoview_adjust_size(void* self);
bool q_undoview_is_visible(void* self);
bool q_undoview_is_visible_to(void* self, void* param1);
bool q_undoview_is_hidden(void* self);
bool q_undoview_is_minimized(void* self);
bool q_undoview_is_maximized(void* self);
bool q_undoview_is_full_screen(void* self);
int64_t q_undoview_window_state(void* self);
void q_undoview_set_window_state(void* self, int64_t state);
void q_undoview_override_window_state(void* self, int64_t state);
QSizePolicy* q_undoview_size_policy(void* self);
void q_undoview_set_size_policy(void* self, void* sizePolicy);
void q_undoview_set_size_policy2(void* self, int64_t horizontal, int64_t vertical);
QRegion* q_undoview_visible_region(void* self);
void q_undoview_set_contents_margins(void* self, int left, int top, int right, int bottom);
void q_undoview_set_contents_margins_with_margins(void* self, void* margins);
QMargins* q_undoview_contents_margins(void* self);
QRect* q_undoview_contents_rect(void* self);
QLayout* q_undoview_layout(void* self);
void q_undoview_set_layout(void* self, void* layout);
void q_undoview_update_geometry(void* self);
void q_undoview_set_parent(void* self, void* parent);
void q_undoview_set_parent2(void* self, void* parent, int64_t f);
void q_undoview_scroll(void* self, int dx, int dy);
void q_undoview_scroll2(void* self, int dx, int dy, void* param3);
QWidget* q_undoview_focus_widget(void* self);
QWidget* q_undoview_next_in_focus_chain(void* self);
QWidget* q_undoview_previous_in_focus_chain(void* self);
bool q_undoview_accept_drops(void* self);
void q_undoview_set_accept_drops(void* self, bool on);
void q_undoview_add_action(void* self, void* action);
void q_undoview_add_actions(void* self, void* actions[]);
void q_undoview_insert_actions(void* self, void* before, void* actions[]);
void q_undoview_insert_action(void* self, void* before, void* action);
void q_undoview_remove_action(void* self, void* action);
libqt_list /* of QAction* */ q_undoview_actions(void* self);
QAction* q_undoview_add_action_with_text(void* self, const char* text);
QAction* q_undoview_add_action2(void* self, void* icon, const char* text);
QAction* q_undoview_add_action3(void* self, const char* text, void* shortcut);
QAction* q_undoview_add_action4(void* self, void* icon, const char* text, void* shortcut);
QWidget* q_undoview_parent_widget(void* self);
void q_undoview_set_window_flags(void* self, int64_t typeVal);
int64_t q_undoview_window_flags(void* self);
void q_undoview_set_window_flag(void* self, int64_t param1);
void q_undoview_override_window_flags(void* self, int64_t typeVal);
int64_t q_undoview_window_type(void* self);
QWidget* q_undoview_find(uint64_t param1);
QWidget* q_undoview_child_at(void* self, int x, int y);
QWidget* q_undoview_child_at_with_q_point(void* self, void* p);
void q_undoview_set_attribute(void* self, int64_t param1);
bool q_undoview_test_attribute(void* self, int64_t param1);
void q_undoview_ensure_polished(void* self);
bool q_undoview_is_ancestor_of(void* self, void* child);
bool q_undoview_auto_fill_background(void* self);
void q_undoview_set_auto_fill_background(void* self, bool enabled);
QBackingStore* q_undoview_backing_store(void* self);
QWindow* q_undoview_window_handle(void* self);
QScreen* q_undoview_screen(void* self);
void q_undoview_set_screen(void* self, void* screen);
QWidget* q_undoview_create_window_container(void* window);
void q_undoview_window_title_changed(void* self, const char* title);
void q_undoview_on_window_title_changed(void* self, void (*slot)(void*, const char*));
void q_undoview_window_icon_changed(void* self, void* icon);
void q_undoview_on_window_icon_changed(void* self, void (*slot)(void*, void*));
void q_undoview_window_icon_text_changed(void* self, const char* iconText);
void q_undoview_on_window_icon_text_changed(void* self, void (*slot)(void*, const char*));
void q_undoview_custom_context_menu_requested(void* self, void* pos);
void q_undoview_on_custom_context_menu_requested(void* self, void (*slot)(void*, void*));
int64_t q_undoview_input_method_hints(void* self);
void q_undoview_set_input_method_hints(void* self, int64_t hints);
void q_undoview_render2(void* self, void* target, void* targetOffset);
void q_undoview_render3(void* self, void* target, void* targetOffset, void* sourceRegion);
void q_undoview_render4(void* self, void* target, void* targetOffset, void* sourceRegion, int64_t renderFlags);
void q_undoview_render22(void* self, void* painter, void* targetOffset);
void q_undoview_render32(void* self, void* painter, void* targetOffset, void* sourceRegion);
void q_undoview_render42(void* self, void* painter, void* targetOffset, void* sourceRegion, int64_t renderFlags);
QPixmap* q_undoview_grab1(void* self, void* rectangle);
void q_undoview_grab_gesture2(void* self, int64_t typeVal, int64_t flags);
int32_t q_undoview_grab_shortcut2(void* self, void* key, int64_t context);
void q_undoview_set_shortcut_enabled2(void* self, int id, bool enable);
void q_undoview_set_shortcut_auto_repeat2(void* self, int id, bool enable);
void q_undoview_set_window_flag2(void* self, int64_t param1, bool on);
void q_undoview_set_attribute2(void* self, int64_t param1, bool on);
QWidget* q_undoview_create_window_container2(void* window, void* parent);
QWidget* q_undoview_create_window_container3(void* window, void* parent, int64_t flags);
const char* q_undoview_object_name(void* self);
void q_undoview_set_object_name(void* self, const char* name);
bool q_undoview_is_widget_type(void* self);
bool q_undoview_is_window_type(void* self);
bool q_undoview_is_quick_item_type(void* self);
bool q_undoview_signals_blocked(void* self);
bool q_undoview_block_signals(void* self, bool b);
QThread* q_undoview_thread(void* self);
void q_undoview_move_to_thread(void* self, void* thread);
int32_t q_undoview_start_timer(void* self, int interval);
void q_undoview_kill_timer(void* self, int id);
libqt_list /* of QObject* */ q_undoview_children(void* self);
void q_undoview_install_event_filter(void* self, void* filterObj);
void q_undoview_remove_event_filter(void* self, void* obj);
QMetaObject__Connection* q_undoview_connect(void* sender, void* signal, void* receiver, void* method);
QMetaObject__Connection* q_undoview_connect2(void* self, void* sender, const char* signal, const char* member);
bool q_undoview_disconnect(void* sender, void* signal, void* receiver, void* member);
bool q_undoview_disconnect_with_q_meta_object_connection(void* param1);
void q_undoview_dump_object_tree(void* self);
void q_undoview_dump_object_info(void* self);
bool q_undoview_set_property(void* self, const char* name, void* value);
QVariant* q_undoview_property(void* self, const char* name);
const char** q_undoview_dynamic_property_names(void* self);
QBindingStorage* q_undoview_binding_storage(void* self);
QBindingStorage* q_undoview_binding_storage2(void* self);
void q_undoview_destroyed(void* self);
void q_undoview_on_destroyed(void* self, void (*slot)(void*));
QObject* q_undoview_parent(void* self);
bool q_undoview_inherits(void* self, const char* classname);
void q_undoview_delete_later(void* self);
int32_t q_undoview_start_timer2(void* self, int interval, int64_t timerType);
QMetaObject__Connection* q_undoview_connect5(void* sender, void* signal, void* receiver, void* method, int64_t typeVal);
QMetaObject__Connection* q_undoview_connect4(void* self, void* sender, const char* signal, const char* member, int64_t typeVal);
void q_undoview_destroyed1(void* self, void* param1);
void q_undoview_on_destroyed1(void* self, void (*slot)(void*, void*));
bool q_undoview_painting_active(void* self);
int32_t q_undoview_width_m_m(void* self);
int32_t q_undoview_height_m_m(void* self);
int32_t q_undoview_logical_dpi_x(void* self);
int32_t q_undoview_logical_dpi_y(void* self);
int32_t q_undoview_physical_dpi_x(void* self);
int32_t q_undoview_physical_dpi_y(void* self);
double q_undoview_device_pixel_ratio(void* self);
double q_undoview_device_pixel_ratio_f(void* self);
int32_t q_undoview_color_count(void* self);
int32_t q_undoview_depth(void* self);
double q_undoview_device_pixel_ratio_f_scale();
QRect* q_undoview_visual_rect(void* self, void* index);
QRect* q_undoview_qbase_visual_rect(void* self, void* index);
void q_undoview_on_visual_rect(void* self, QRect* (*slot)(void*, void*));
void q_undoview_scroll_to(void* self, void* index, int64_t hint);
void q_undoview_qbase_scroll_to(void* self, void* index, int64_t hint);
void q_undoview_on_scroll_to(void* self, void (*slot)(void*, void*, int64_t));
QModelIndex* q_undoview_index_at(void* self, void* p);
QModelIndex* q_undoview_qbase_index_at(void* self, void* p);
void q_undoview_on_index_at(void* self, QModelIndex* (*slot)(void*, void*));
void q_undoview_do_items_layout(void* self);
void q_undoview_qbase_do_items_layout(void* self);
void q_undoview_on_do_items_layout(void* self, void (*slot)());
void q_undoview_reset(void* self);
void q_undoview_qbase_reset(void* self);
void q_undoview_on_reset(void* self, void (*slot)());
void q_undoview_set_root_index(void* self, void* index);
void q_undoview_qbase_set_root_index(void* self, void* index);
void q_undoview_on_set_root_index(void* self, void (*slot)(void*, void*));
bool q_undoview_event(void* self, void* e);
bool q_undoview_qbase_event(void* self, void* e);
void q_undoview_on_event(void* self, bool (*slot)(void*, void*));
void q_undoview_scroll_contents_by(void* self, int dx, int dy);
void q_undoview_qbase_scroll_contents_by(void* self, int dx, int dy);
void q_undoview_on_scroll_contents_by(void* self, void (*slot)(void*, int, int));
void q_undoview_data_changed(void* self, void* topLeft, void* bottomRight, int* roles[]);
void q_undoview_qbase_data_changed(void* self, void* topLeft, void* bottomRight, int* roles[]);
void q_undoview_on_data_changed(void* self, void (*slot)(void*, void*, void*, int*));
void q_undoview_rows_inserted(void* self, void* parent, int start, int end);
void q_undoview_qbase_rows_inserted(void* self, void* parent, int start, int end);
void q_undoview_on_rows_inserted(void* self, void (*slot)(void*, void*, int, int));
void q_undoview_rows_about_to_be_removed(void* self, void* parent, int start, int end);
void q_undoview_qbase_rows_about_to_be_removed(void* self, void* parent, int start, int end);
void q_undoview_on_rows_about_to_be_removed(void* self, void (*slot)(void*, void*, int, int));
void q_undoview_mouse_move_event(void* self, void* e);
void q_undoview_qbase_mouse_move_event(void* self, void* e);
void q_undoview_on_mouse_move_event(void* self, void (*slot)(void*, void*));
void q_undoview_mouse_release_event(void* self, void* e);
void q_undoview_qbase_mouse_release_event(void* self, void* e);
void q_undoview_on_mouse_release_event(void* self, void (*slot)(void*, void*));
void q_undoview_wheel_event(void* self, void* e);
void q_undoview_qbase_wheel_event(void* self, void* e);
void q_undoview_on_wheel_event(void* self, void (*slot)(void*, void*));
void q_undoview_timer_event(void* self, void* e);
void q_undoview_qbase_timer_event(void* self, void* e);
void q_undoview_on_timer_event(void* self, void (*slot)(void*, void*));
void q_undoview_resize_event(void* self, void* e);
void q_undoview_qbase_resize_event(void* self, void* e);
void q_undoview_on_resize_event(void* self, void (*slot)(void*, void*));
void q_undoview_drag_move_event(void* self, void* e);
void q_undoview_qbase_drag_move_event(void* self, void* e);
void q_undoview_on_drag_move_event(void* self, void (*slot)(void*, void*));
void q_undoview_drag_leave_event(void* self, void* e);
void q_undoview_qbase_drag_leave_event(void* self, void* e);
void q_undoview_on_drag_leave_event(void* self, void (*slot)(void*, void*));
void q_undoview_drop_event(void* self, void* e);
void q_undoview_qbase_drop_event(void* self, void* e);
void q_undoview_on_drop_event(void* self, void (*slot)(void*, void*));
void q_undoview_start_drag(void* self, int64_t supportedActions);
void q_undoview_qbase_start_drag(void* self, int64_t supportedActions);
void q_undoview_on_start_drag(void* self, void (*slot)(void*, int64_t));
void q_undoview_init_view_item_option(void* self, void* option);
void q_undoview_qbase_init_view_item_option(void* self, void* option);
void q_undoview_on_init_view_item_option(void* self, void (*slot)(void*, void*));
void q_undoview_paint_event(void* self, void* e);
void q_undoview_qbase_paint_event(void* self, void* e);
void q_undoview_on_paint_event(void* self, void (*slot)(void*, void*));
int32_t q_undoview_horizontal_offset(void* self);
int32_t q_undoview_qbase_horizontal_offset(void* self);
void q_undoview_on_horizontal_offset(void* self, int32_t (*slot)());
int32_t q_undoview_vertical_offset(void* self);
int32_t q_undoview_qbase_vertical_offset(void* self);
void q_undoview_on_vertical_offset(void* self, int32_t (*slot)());
QModelIndex* q_undoview_move_cursor(void* self, int64_t cursorAction, int64_t modifiers);
QModelIndex* q_undoview_qbase_move_cursor(void* self, int64_t cursorAction, int64_t modifiers);
void q_undoview_on_move_cursor(void* self, QModelIndex* (*slot)(void*, int64_t, int64_t));
void q_undoview_set_selection(void* self, void* rect, int64_t command);
void q_undoview_qbase_set_selection(void* self, void* rect, int64_t command);
void q_undoview_on_set_selection(void* self, void (*slot)(void*, void*, int64_t));
QRegion* q_undoview_visual_region_for_selection(void* self, void* selection);
QRegion* q_undoview_qbase_visual_region_for_selection(void* self, void* selection);
void q_undoview_on_visual_region_for_selection(void* self, QRegion* (*slot)(void*, void*));
libqt_list /* of QModelIndex* */ q_undoview_selected_indexes(void* self);
libqt_list /* of QModelIndex* */ q_undoview_qbase_selected_indexes(void* self);
void q_undoview_on_selected_indexes(void* self, libqt_list /* of QModelIndex* */ (*slot)());
void q_undoview_update_geometries(void* self);
void q_undoview_qbase_update_geometries(void* self);
void q_undoview_on_update_geometries(void* self, void (*slot)());
bool q_undoview_is_index_hidden(void* self, void* index);
bool q_undoview_qbase_is_index_hidden(void* self, void* index);
void q_undoview_on_is_index_hidden(void* self, bool (*slot)(void*, void*));
void q_undoview_selection_changed(void* self, void* selected, void* deselected);
void q_undoview_qbase_selection_changed(void* self, void* selected, void* deselected);
void q_undoview_on_selection_changed(void* self, void (*slot)(void*, void*, void*));
void q_undoview_current_changed(void* self, void* current, void* previous);
void q_undoview_qbase_current_changed(void* self, void* current, void* previous);
void q_undoview_on_current_changed(void* self, void (*slot)(void*, void*, void*));
QSize* q_undoview_viewport_size_hint(void* self);
QSize* q_undoview_qbase_viewport_size_hint(void* self);
void q_undoview_on_viewport_size_hint(void* self, QSize* (*slot)());
void q_undoview_set_model(void* self, void* model);
void q_undoview_qbase_set_model(void* self, void* model);
void q_undoview_on_set_model(void* self, void (*slot)(void*, void*));
void q_undoview_set_selection_model(void* self, void* selectionModel);
void q_undoview_qbase_set_selection_model(void* self, void* selectionModel);
void q_undoview_on_set_selection_model(void* self, void (*slot)(void*, void*));
void q_undoview_keyboard_search(void* self, const char* search);
void q_undoview_qbase_keyboard_search(void* self, const char* search);
void q_undoview_on_keyboard_search(void* self, void (*slot)(void*, const char*));
int32_t q_undoview_size_hint_for_row(void* self, int row);
int32_t q_undoview_qbase_size_hint_for_row(void* self, int row);
void q_undoview_on_size_hint_for_row(void* self, int32_t (*slot)(void*, int));
int32_t q_undoview_size_hint_for_column(void* self, int column);
int32_t q_undoview_qbase_size_hint_for_column(void* self, int column);
void q_undoview_on_size_hint_for_column(void* self, int32_t (*slot)(void*, int));
QAbstractItemDelegate* q_undoview_item_delegate_for_index(void* self, void* index);
QAbstractItemDelegate* q_undoview_qbase_item_delegate_for_index(void* self, void* index);
void q_undoview_on_item_delegate_for_index(void* self, QAbstractItemDelegate* (*slot)(void*, void*));
QVariant* q_undoview_input_method_query(void* self, int64_t query);
QVariant* q_undoview_qbase_input_method_query(void* self, int64_t query);
void q_undoview_on_input_method_query(void* self, QVariant* (*slot)(void*, int64_t));
void q_undoview_select_all(void* self);
void q_undoview_qbase_select_all(void* self);
void q_undoview_on_select_all(void* self, void (*slot)());
void q_undoview_update_editor_data(void* self);
void q_undoview_qbase_update_editor_data(void* self);
void q_undoview_on_update_editor_data(void* self, void (*slot)());
void q_undoview_update_editor_geometries(void* self);
void q_undoview_qbase_update_editor_geometries(void* self);
void q_undoview_on_update_editor_geometries(void* self, void (*slot)());
void q_undoview_vertical_scrollbar_action(void* self, int action);
void q_undoview_qbase_vertical_scrollbar_action(void* self, int action);
void q_undoview_on_vertical_scrollbar_action(void* self, void (*slot)(void*, int));
void q_undoview_horizontal_scrollbar_action(void* self, int action);
void q_undoview_qbase_horizontal_scrollbar_action(void* self, int action);
void q_undoview_on_horizontal_scrollbar_action(void* self, void (*slot)(void*, int));
void q_undoview_vertical_scrollbar_value_changed(void* self, int value);
void q_undoview_qbase_vertical_scrollbar_value_changed(void* self, int value);
void q_undoview_on_vertical_scrollbar_value_changed(void* self, void (*slot)(void*, int));
void q_undoview_horizontal_scrollbar_value_changed(void* self, int value);
void q_undoview_qbase_horizontal_scrollbar_value_changed(void* self, int value);
void q_undoview_on_horizontal_scrollbar_value_changed(void* self, void (*slot)(void*, int));
void q_undoview_close_editor(void* self, void* editor, int64_t hint);
void q_undoview_qbase_close_editor(void* self, void* editor, int64_t hint);
void q_undoview_on_close_editor(void* self, void (*slot)(void*, void*, int64_t));
void q_undoview_commit_data(void* self, void* editor);
void q_undoview_qbase_commit_data(void* self, void* editor);
void q_undoview_on_commit_data(void* self, void (*slot)(void*, void*));
void q_undoview_editor_destroyed(void* self, void* editor);
void q_undoview_qbase_editor_destroyed(void* self, void* editor);
void q_undoview_on_editor_destroyed(void* self, void (*slot)(void*, void*));
bool q_undoview_edit2(void* self, void* index, int64_t trigger, void* event);
bool q_undoview_qbase_edit2(void* self, void* index, int64_t trigger, void* event);
void q_undoview_on_edit2(void* self, bool (*slot)(void*, void*, int64_t, void*));
int64_t q_undoview_selection_command(void* self, void* index, void* event);
int64_t q_undoview_qbase_selection_command(void* self, void* index, void* event);
void q_undoview_on_selection_command(void* self, int64_t (*slot)(void*, void*, void*));
bool q_undoview_focus_next_prev_child(void* self, bool next);
bool q_undoview_qbase_focus_next_prev_child(void* self, bool next);
void q_undoview_on_focus_next_prev_child(void* self, bool (*slot)(void*, bool));
bool q_undoview_viewport_event(void* self, void* event);
bool q_undoview_qbase_viewport_event(void* self, void* event);
void q_undoview_on_viewport_event(void* self, bool (*slot)(void*, void*));
void q_undoview_mouse_press_event(void* self, void* event);
void q_undoview_qbase_mouse_press_event(void* self, void* event);
void q_undoview_on_mouse_press_event(void* self, void (*slot)(void*, void*));
void q_undoview_mouse_double_click_event(void* self, void* event);
void q_undoview_qbase_mouse_double_click_event(void* self, void* event);
void q_undoview_on_mouse_double_click_event(void* self, void (*slot)(void*, void*));
void q_undoview_drag_enter_event(void* self, void* event);
void q_undoview_qbase_drag_enter_event(void* self, void* event);
void q_undoview_on_drag_enter_event(void* self, void (*slot)(void*, void*));
void q_undoview_focus_in_event(void* self, void* event);
void q_undoview_qbase_focus_in_event(void* self, void* event);
void q_undoview_on_focus_in_event(void* self, void (*slot)(void*, void*));
void q_undoview_focus_out_event(void* self, void* event);
void q_undoview_qbase_focus_out_event(void* self, void* event);
void q_undoview_on_focus_out_event(void* self, void (*slot)(void*, void*));
void q_undoview_key_press_event(void* self, void* event);
void q_undoview_qbase_key_press_event(void* self, void* event);
void q_undoview_on_key_press_event(void* self, void (*slot)(void*, void*));
void q_undoview_input_method_event(void* self, void* event);
void q_undoview_qbase_input_method_event(void* self, void* event);
void q_undoview_on_input_method_event(void* self, void (*slot)(void*, void*));
bool q_undoview_event_filter(void* self, void* object, void* event);
bool q_undoview_qbase_event_filter(void* self, void* object, void* event);
void q_undoview_on_event_filter(void* self, bool (*slot)(void*, void*, void*));
QSize* q_undoview_minimum_size_hint(void* self);
QSize* q_undoview_qbase_minimum_size_hint(void* self);
void q_undoview_on_minimum_size_hint(void* self, QSize* (*slot)());
QSize* q_undoview_size_hint(void* self);
QSize* q_undoview_qbase_size_hint(void* self);
void q_undoview_on_size_hint(void* self, QSize* (*slot)());
void q_undoview_setup_viewport(void* self, void* viewport);
void q_undoview_qbase_setup_viewport(void* self, void* viewport);
void q_undoview_on_setup_viewport(void* self, void (*slot)(void*, void*));
void q_undoview_context_menu_event(void* self, void* param1);
void q_undoview_qbase_context_menu_event(void* self, void* param1);
void q_undoview_on_context_menu_event(void* self, void (*slot)(void*, void*));
void q_undoview_change_event(void* self, void* param1);
void q_undoview_qbase_change_event(void* self, void* param1);
void q_undoview_on_change_event(void* self, void (*slot)(void*, void*));
void q_undoview_init_style_option(void* self, void* option);
void q_undoview_qbase_init_style_option(void* self, void* option);
void q_undoview_on_init_style_option(void* self, void (*slot)(void*, void*));
int32_t q_undoview_dev_type(void* self);
int32_t q_undoview_qbase_dev_type(void* self);
void q_undoview_on_dev_type(void* self, int32_t (*slot)());
void q_undoview_set_visible(void* self, bool visible);
void q_undoview_qbase_set_visible(void* self, bool visible);
void q_undoview_on_set_visible(void* self, void (*slot)(void*, bool));
int32_t q_undoview_height_for_width(void* self, int param1);
int32_t q_undoview_qbase_height_for_width(void* self, int param1);
void q_undoview_on_height_for_width(void* self, int32_t (*slot)(void*, int));
bool q_undoview_has_height_for_width(void* self);
bool q_undoview_qbase_has_height_for_width(void* self);
void q_undoview_on_has_height_for_width(void* self, bool (*slot)());
QPaintEngine* q_undoview_paint_engine(void* self);
QPaintEngine* q_undoview_qbase_paint_engine(void* self);
void q_undoview_on_paint_engine(void* self, QPaintEngine* (*slot)());
void q_undoview_key_release_event(void* self, void* event);
void q_undoview_qbase_key_release_event(void* self, void* event);
void q_undoview_on_key_release_event(void* self, void (*slot)(void*, void*));
void q_undoview_enter_event(void* self, void* event);
void q_undoview_qbase_enter_event(void* self, void* event);
void q_undoview_on_enter_event(void* self, void (*slot)(void*, void*));
void q_undoview_leave_event(void* self, void* event);
void q_undoview_qbase_leave_event(void* self, void* event);
void q_undoview_on_leave_event(void* self, void (*slot)(void*, void*));
void q_undoview_move_event(void* self, void* event);
void q_undoview_qbase_move_event(void* self, void* event);
void q_undoview_on_move_event(void* self, void (*slot)(void*, void*));
void q_undoview_close_event(void* self, void* event);
void q_undoview_qbase_close_event(void* self, void* event);
void q_undoview_on_close_event(void* self, void (*slot)(void*, void*));
void q_undoview_tablet_event(void* self, void* event);
void q_undoview_qbase_tablet_event(void* self, void* event);
void q_undoview_on_tablet_event(void* self, void (*slot)(void*, void*));
void q_undoview_action_event(void* self, void* event);
void q_undoview_qbase_action_event(void* self, void* event);
void q_undoview_on_action_event(void* self, void (*slot)(void*, void*));
void q_undoview_show_event(void* self, void* event);
void q_undoview_qbase_show_event(void* self, void* event);
void q_undoview_on_show_event(void* self, void (*slot)(void*, void*));
void q_undoview_hide_event(void* self, void* event);
void q_undoview_qbase_hide_event(void* self, void* event);
void q_undoview_on_hide_event(void* self, void (*slot)(void*, void*));
bool q_undoview_native_event(void* self, const char* eventType, void* message, intptr_t* result);
bool q_undoview_qbase_native_event(void* self, const char* eventType, void* message, intptr_t* result);
void q_undoview_on_native_event(void* self, bool (*slot)(void*, const char*, void*, intptr_t*));
int32_t q_undoview_metric(void* self, int64_t param1);
int32_t q_undoview_qbase_metric(void* self, int64_t param1);
void q_undoview_on_metric(void* self, int32_t (*slot)(void*, int64_t));
void q_undoview_init_painter(void* self, void* painter);
void q_undoview_qbase_init_painter(void* self, void* painter);
void q_undoview_on_init_painter(void* self, void (*slot)(void*, void*));
QPaintDevice* q_undoview_redirected(void* self, void* offset);
QPaintDevice* q_undoview_qbase_redirected(void* self, void* offset);
void q_undoview_on_redirected(void* self, QPaintDevice* (*slot)(void*, void*));
QPainter* q_undoview_shared_painter(void* self);
QPainter* q_undoview_qbase_shared_painter(void* self);
void q_undoview_on_shared_painter(void* self, QPainter* (*slot)());
void q_undoview_child_event(void* self, void* event);
void q_undoview_qbase_child_event(void* self, void* event);
void q_undoview_on_child_event(void* self, void (*slot)(void*, void*));
void q_undoview_custom_event(void* self, void* event);
void q_undoview_qbase_custom_event(void* self, void* event);
void q_undoview_on_custom_event(void* self, void (*slot)(void*, void*));
void q_undoview_connect_notify(void* self, void* signal);
void q_undoview_qbase_connect_notify(void* self, void* signal);
void q_undoview_on_connect_notify(void* self, void (*slot)(void*, void*));
void q_undoview_disconnect_notify(void* self, void* signal);
void q_undoview_qbase_disconnect_notify(void* self, void* signal);
void q_undoview_on_disconnect_notify(void* self, void (*slot)(void*, void*));
void q_undoview_resize_contents(void* self, int width, int height);
void q_undoview_qbase_resize_contents(void* self, int width, int height);
void q_undoview_on_resize_contents(void* self, void (*slot)(void*, int, int));
QSize* q_undoview_contents_size(void* self);
QSize* q_undoview_qbase_contents_size(void* self);
void q_undoview_on_contents_size(void* self, QSize* (*slot)());
QRect* q_undoview_rect_for_index(void* self, void* index);
QRect* q_undoview_qbase_rect_for_index(void* self, void* index);
void q_undoview_on_rect_for_index(void* self, QRect* (*slot)(void*, void*));
void q_undoview_set_position_for_index(void* self, void* position, void* index);
void q_undoview_qbase_set_position_for_index(void* self, void* position, void* index);
void q_undoview_on_set_position_for_index(void* self, void (*slot)(void*, void*, void*));
int64_t q_undoview_state(void* self);
int64_t q_undoview_qbase_state(void* self);
void q_undoview_on_state(void* self, int64_t (*slot)());
void q_undoview_set_state(void* self, int64_t state);
void q_undoview_qbase_set_state(void* self, int64_t state);
void q_undoview_on_set_state(void* self, void (*slot)(void*, int64_t));
void q_undoview_schedule_delayed_items_layout(void* self);
void q_undoview_qbase_schedule_delayed_items_layout(void* self);
void q_undoview_on_schedule_delayed_items_layout(void* self, void (*slot)());
void q_undoview_execute_delayed_items_layout(void* self);
void q_undoview_qbase_execute_delayed_items_layout(void* self);
void q_undoview_on_execute_delayed_items_layout(void* self, void (*slot)());
void q_undoview_set_dirty_region(void* self, void* region);
void q_undoview_qbase_set_dirty_region(void* self, void* region);
void q_undoview_on_set_dirty_region(void* self, void (*slot)(void*, void*));
void q_undoview_scroll_dirty_region(void* self, int dx, int dy);
void q_undoview_qbase_scroll_dirty_region(void* self, int dx, int dy);
void q_undoview_on_scroll_dirty_region(void* self, void (*slot)(void*, int, int));
QPoint* q_undoview_dirty_region_offset(void* self);
QPoint* q_undoview_qbase_dirty_region_offset(void* self);
void q_undoview_on_dirty_region_offset(void* self, QPoint* (*slot)());
void q_undoview_start_auto_scroll(void* self);
void q_undoview_qbase_start_auto_scroll(void* self);
void q_undoview_on_start_auto_scroll(void* self, void (*slot)());
void q_undoview_stop_auto_scroll(void* self);
void q_undoview_qbase_stop_auto_scroll(void* self);
void q_undoview_on_stop_auto_scroll(void* self, void (*slot)());
void q_undoview_do_auto_scroll(void* self);
void q_undoview_qbase_do_auto_scroll(void* self);
void q_undoview_on_do_auto_scroll(void* self, void (*slot)());
int64_t q_undoview_drop_indicator_position(void* self);
int64_t q_undoview_qbase_drop_indicator_position(void* self);
void q_undoview_on_drop_indicator_position(void* self, int64_t (*slot)());
void q_undoview_set_viewport_margins(void* self, int left, int top, int right, int bottom);
void q_undoview_qbase_set_viewport_margins(void* self, int left, int top, int right, int bottom);
void q_undoview_on_set_viewport_margins(void* self, void (*slot)(void*, int, int, int, int));
QMargins* q_undoview_viewport_margins(void* self);
QMargins* q_undoview_qbase_viewport_margins(void* self);
void q_undoview_on_viewport_margins(void* self, QMargins* (*slot)());
void q_undoview_draw_frame(void* self, void* param1);
void q_undoview_qbase_draw_frame(void* self, void* param1);
void q_undoview_on_draw_frame(void* self, void (*slot)(void*, void*));
void q_undoview_update_micro_focus(void* self);
void q_undoview_qbase_update_micro_focus(void* self);
void q_undoview_on_update_micro_focus(void* self, void (*slot)());
void q_undoview_create(void* self);
void q_undoview_qbase_create(void* self);
void q_undoview_on_create(void* self, void (*slot)());
void q_undoview_destroy(void* self);
void q_undoview_qbase_destroy(void* self);
void q_undoview_on_destroy(void* self, void (*slot)());
bool q_undoview_focus_next_child(void* self);
bool q_undoview_qbase_focus_next_child(void* self);
void q_undoview_on_focus_next_child(void* self, bool (*slot)());
bool q_undoview_focus_previous_child(void* self);
bool q_undoview_qbase_focus_previous_child(void* self);
void q_undoview_on_focus_previous_child(void* self, bool (*slot)());
QObject* q_undoview_sender(void* self);
QObject* q_undoview_qbase_sender(void* self);
void q_undoview_on_sender(void* self, QObject* (*slot)());
int32_t q_undoview_sender_signal_index(void* self);
int32_t q_undoview_qbase_sender_signal_index(void* self);
void q_undoview_on_sender_signal_index(void* self, int32_t (*slot)());
int32_t q_undoview_receivers(void* self, const char* signal);
int32_t q_undoview_qbase_receivers(void* self, const char* signal);
void q_undoview_on_receivers(void* self, int32_t (*slot)(void*, const char*));
bool q_undoview_is_signal_connected(void* self, void* signal);
bool q_undoview_qbase_is_signal_connected(void* self, void* signal);
void q_undoview_on_is_signal_connected(void* self, bool (*slot)(void*, void*));
void q_undoview_delete(void* self);

#endif
