#pragma once
#ifndef SRCQT6C_LIBQSORTFILTERPROXYMODEL_H
#define SRCQT6C_LIBQSORTFILTERPROXYMODEL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#include "libqabstractitemmodel.h"
#include "libqabstractproxymodel.h"
#include "libqanystringview.h"
#include "libqbindingstorage.h"
#include "libqevent.h"
#include "libqdatastream.h"
#include "libqitemselectionmodel.h"
#include "libqmetaobject.h"
#include "libqmimedata.h"
#include "libqobject.h"
#include "libqregularexpression.h"
#include "libqsize.h"
#include <string.h>
#include "libqthread.h"
#include "libqvariant.h"

QSortFilterProxyModel* q_sortfilterproxymodel_new();
QSortFilterProxyModel* q_sortfilterproxymodel_new2(void* parent);
QMetaObject* q_sortfilterproxymodel_meta_object(void* self);
void* q_sortfilterproxymodel_metacast(void* self, const char* param1);
int32_t q_sortfilterproxymodel_metacall(void* self, int64_t param1, int param2, void* param3);
void q_sortfilterproxymodel_on_metacall(void* self, int32_t (*slot)(void*, int64_t, int, void*));
int32_t q_sortfilterproxymodel_qbase_metacall(void* self, int64_t param1, int param2, void* param3);
const char* q_sortfilterproxymodel_tr(const char* s);
void q_sortfilterproxymodel_set_source_model(void* self, void* sourceModel);
void q_sortfilterproxymodel_on_set_source_model(void* self, void (*slot)(void*, void*));
void q_sortfilterproxymodel_qbase_set_source_model(void* self, void* sourceModel);
QModelIndex* q_sortfilterproxymodel_map_to_source(void* self, void* proxyIndex);
void q_sortfilterproxymodel_on_map_to_source(void* self, QModelIndex* (*slot)(void*, void*));
QModelIndex* q_sortfilterproxymodel_qbase_map_to_source(void* self, void* proxyIndex);
QModelIndex* q_sortfilterproxymodel_map_from_source(void* self, void* sourceIndex);
void q_sortfilterproxymodel_on_map_from_source(void* self, QModelIndex* (*slot)(void*, void*));
QModelIndex* q_sortfilterproxymodel_qbase_map_from_source(void* self, void* sourceIndex);
QItemSelection* q_sortfilterproxymodel_map_selection_to_source(void* self, void* proxySelection);
void q_sortfilterproxymodel_on_map_selection_to_source(void* self, QItemSelection* (*slot)(void*, void*));
QItemSelection* q_sortfilterproxymodel_qbase_map_selection_to_source(void* self, void* proxySelection);
QItemSelection* q_sortfilterproxymodel_map_selection_from_source(void* self, void* sourceSelection);
void q_sortfilterproxymodel_on_map_selection_from_source(void* self, QItemSelection* (*slot)(void*, void*));
QItemSelection* q_sortfilterproxymodel_qbase_map_selection_from_source(void* self, void* sourceSelection);
QRegularExpression* q_sortfilterproxymodel_filter_regular_expression(void* self);
int32_t q_sortfilterproxymodel_filter_key_column(void* self);
void q_sortfilterproxymodel_set_filter_key_column(void* self, int column);
int64_t q_sortfilterproxymodel_filter_case_sensitivity(void* self);
void q_sortfilterproxymodel_set_filter_case_sensitivity(void* self, int64_t cs);
int64_t q_sortfilterproxymodel_sort_case_sensitivity(void* self);
void q_sortfilterproxymodel_set_sort_case_sensitivity(void* self, int64_t cs);
bool q_sortfilterproxymodel_is_sort_locale_aware(void* self);
void q_sortfilterproxymodel_set_sort_locale_aware(void* self, bool on);
int32_t q_sortfilterproxymodel_sort_column(void* self);
int64_t q_sortfilterproxymodel_sort_order(void* self);
bool q_sortfilterproxymodel_dynamic_sort_filter(void* self);
void q_sortfilterproxymodel_set_dynamic_sort_filter(void* self, bool enable);
int32_t q_sortfilterproxymodel_sort_role(void* self);
void q_sortfilterproxymodel_set_sort_role(void* self, int role);
int32_t q_sortfilterproxymodel_filter_role(void* self);
void q_sortfilterproxymodel_set_filter_role(void* self, int role);
bool q_sortfilterproxymodel_is_recursive_filtering_enabled(void* self);
void q_sortfilterproxymodel_set_recursive_filtering_enabled(void* self, bool recursive);
bool q_sortfilterproxymodel_auto_accept_child_rows(void* self);
void q_sortfilterproxymodel_set_auto_accept_child_rows(void* self, bool accept);
void q_sortfilterproxymodel_set_filter_regular_expression(void* self, const char* pattern);
void q_sortfilterproxymodel_set_filter_regular_expression_with_regular_expression(void* self, void* regularExpression);
void q_sortfilterproxymodel_set_filter_wildcard(void* self, const char* pattern);
void q_sortfilterproxymodel_set_filter_fixed_string(void* self, const char* pattern);
void q_sortfilterproxymodel_invalidate(void* self);
bool q_sortfilterproxymodel_filter_accepts_row(void* self, int source_row, void* source_parent);
void q_sortfilterproxymodel_on_filter_accepts_row(void* self, bool (*slot)(void*, int, void*));
bool q_sortfilterproxymodel_qbase_filter_accepts_row(void* self, int source_row, void* source_parent);
bool q_sortfilterproxymodel_filter_accepts_column(void* self, int source_column, void* source_parent);
void q_sortfilterproxymodel_on_filter_accepts_column(void* self, bool (*slot)(void*, int, void*));
bool q_sortfilterproxymodel_qbase_filter_accepts_column(void* self, int source_column, void* source_parent);
bool q_sortfilterproxymodel_less_than(void* self, void* source_left, void* source_right);
void q_sortfilterproxymodel_on_less_than(void* self, bool (*slot)(void*, void*, void*));
bool q_sortfilterproxymodel_qbase_less_than(void* self, void* source_left, void* source_right);
void q_sortfilterproxymodel_invalidate_filter(void* self);
void q_sortfilterproxymodel_on_invalidate_filter(void* self, void (*slot)());
void q_sortfilterproxymodel_qbase_invalidate_filter(void* self);
void q_sortfilterproxymodel_invalidate_rows_filter(void* self);
void q_sortfilterproxymodel_on_invalidate_rows_filter(void* self, void (*slot)());
void q_sortfilterproxymodel_qbase_invalidate_rows_filter(void* self);
void q_sortfilterproxymodel_invalidate_columns_filter(void* self);
void q_sortfilterproxymodel_on_invalidate_columns_filter(void* self, void (*slot)());
void q_sortfilterproxymodel_qbase_invalidate_columns_filter(void* self);
QModelIndex* q_sortfilterproxymodel_index(void* self, int row, int column, void* parent);
void q_sortfilterproxymodel_on_index(void* self, QModelIndex* (*slot)(void*, int, int, void*));
QModelIndex* q_sortfilterproxymodel_qbase_index(void* self, int row, int column, void* parent);
QModelIndex* q_sortfilterproxymodel_parent(void* self, void* child);
void q_sortfilterproxymodel_on_parent(void* self, QModelIndex* (*slot)(void*, void*));
QModelIndex* q_sortfilterproxymodel_qbase_parent(void* self, void* child);
QModelIndex* q_sortfilterproxymodel_sibling(void* self, int row, int column, void* idx);
void q_sortfilterproxymodel_on_sibling(void* self, QModelIndex* (*slot)(void*, int, int, void*));
QModelIndex* q_sortfilterproxymodel_qbase_sibling(void* self, int row, int column, void* idx);
int32_t q_sortfilterproxymodel_row_count(void* self, void* parent);
void q_sortfilterproxymodel_on_row_count(void* self, int32_t (*slot)(void*, void*));
int32_t q_sortfilterproxymodel_qbase_row_count(void* self, void* parent);
int32_t q_sortfilterproxymodel_column_count(void* self, void* parent);
void q_sortfilterproxymodel_on_column_count(void* self, int32_t (*slot)(void*, void*));
int32_t q_sortfilterproxymodel_qbase_column_count(void* self, void* parent);
bool q_sortfilterproxymodel_has_children(void* self, void* parent);
void q_sortfilterproxymodel_on_has_children(void* self, bool (*slot)(void*, void*));
bool q_sortfilterproxymodel_qbase_has_children(void* self, void* parent);
QVariant* q_sortfilterproxymodel_data(void* self, void* index, int role);
void q_sortfilterproxymodel_on_data(void* self, QVariant* (*slot)(void*, void*, int));
QVariant* q_sortfilterproxymodel_qbase_data(void* self, void* index, int role);
bool q_sortfilterproxymodel_set_data(void* self, void* index, void* value, int role);
void q_sortfilterproxymodel_on_set_data(void* self, bool (*slot)(void*, void*, void*, int));
bool q_sortfilterproxymodel_qbase_set_data(void* self, void* index, void* value, int role);
QVariant* q_sortfilterproxymodel_header_data(void* self, int section, int64_t orientation, int role);
void q_sortfilterproxymodel_on_header_data(void* self, QVariant* (*slot)(void*, int, int64_t, int));
QVariant* q_sortfilterproxymodel_qbase_header_data(void* self, int section, int64_t orientation, int role);
bool q_sortfilterproxymodel_set_header_data(void* self, int section, int64_t orientation, void* value, int role);
void q_sortfilterproxymodel_on_set_header_data(void* self, bool (*slot)(void*, int, int64_t, void*, int));
bool q_sortfilterproxymodel_qbase_set_header_data(void* self, int section, int64_t orientation, void* value, int role);
QMimeData* q_sortfilterproxymodel_mime_data(void* self, void* indexes[]);
void q_sortfilterproxymodel_on_mime_data(void* self, QMimeData* (*slot)(void*, void*));
QMimeData* q_sortfilterproxymodel_qbase_mime_data(void* self, void* indexes[]);
bool q_sortfilterproxymodel_drop_mime_data(void* self, void* data, int64_t action, int row, int column, void* parent);
void q_sortfilterproxymodel_on_drop_mime_data(void* self, bool (*slot)(void*, void*, int64_t, int, int, void*));
bool q_sortfilterproxymodel_qbase_drop_mime_data(void* self, void* data, int64_t action, int row, int column, void* parent);
bool q_sortfilterproxymodel_insert_rows(void* self, int row, int count, void* parent);
void q_sortfilterproxymodel_on_insert_rows(void* self, bool (*slot)(void*, int, int, void*));
bool q_sortfilterproxymodel_qbase_insert_rows(void* self, int row, int count, void* parent);
bool q_sortfilterproxymodel_insert_columns(void* self, int column, int count, void* parent);
void q_sortfilterproxymodel_on_insert_columns(void* self, bool (*slot)(void*, int, int, void*));
bool q_sortfilterproxymodel_qbase_insert_columns(void* self, int column, int count, void* parent);
bool q_sortfilterproxymodel_remove_rows(void* self, int row, int count, void* parent);
void q_sortfilterproxymodel_on_remove_rows(void* self, bool (*slot)(void*, int, int, void*));
bool q_sortfilterproxymodel_qbase_remove_rows(void* self, int row, int count, void* parent);
bool q_sortfilterproxymodel_remove_columns(void* self, int column, int count, void* parent);
void q_sortfilterproxymodel_on_remove_columns(void* self, bool (*slot)(void*, int, int, void*));
bool q_sortfilterproxymodel_qbase_remove_columns(void* self, int column, int count, void* parent);
void q_sortfilterproxymodel_fetch_more(void* self, void* parent);
void q_sortfilterproxymodel_on_fetch_more(void* self, void (*slot)(void*, void*));
void q_sortfilterproxymodel_qbase_fetch_more(void* self, void* parent);
bool q_sortfilterproxymodel_can_fetch_more(void* self, void* parent);
void q_sortfilterproxymodel_on_can_fetch_more(void* self, bool (*slot)(void*, void*));
bool q_sortfilterproxymodel_qbase_can_fetch_more(void* self, void* parent);
int64_t q_sortfilterproxymodel_flags(void* self, void* index);
void q_sortfilterproxymodel_on_flags(void* self, int64_t (*slot)(void*, void*));
int64_t q_sortfilterproxymodel_qbase_flags(void* self, void* index);
QModelIndex* q_sortfilterproxymodel_buddy(void* self, void* index);
void q_sortfilterproxymodel_on_buddy(void* self, QModelIndex* (*slot)(void*, void*));
QModelIndex* q_sortfilterproxymodel_qbase_buddy(void* self, void* index);
libqt_list /* of QModelIndex* */ q_sortfilterproxymodel_match(void* self, void* start, int role, void* value, int hits, int64_t flags);
void q_sortfilterproxymodel_on_match(void* self, libqt_list /* of QModelIndex* */ (*slot)(void*, void*, int, void*, int, int64_t));
libqt_list /* of QModelIndex* */ q_sortfilterproxymodel_qbase_match(void* self, void* start, int role, void* value, int hits, int64_t flags);
QSize* q_sortfilterproxymodel_span(void* self, void* index);
void q_sortfilterproxymodel_on_span(void* self, QSize* (*slot)(void*, void*));
QSize* q_sortfilterproxymodel_qbase_span(void* self, void* index);
void q_sortfilterproxymodel_sort(void* self, int column, int64_t order);
void q_sortfilterproxymodel_on_sort(void* self, void (*slot)(void*, int, int64_t));
void q_sortfilterproxymodel_qbase_sort(void* self, int column, int64_t order);
const char** q_sortfilterproxymodel_mime_types(void* self);
void q_sortfilterproxymodel_on_mime_types(void* self, const char** (*slot)());
const char** q_sortfilterproxymodel_qbase_mime_types(void* self);
int64_t q_sortfilterproxymodel_supported_drop_actions(void* self);
void q_sortfilterproxymodel_on_supported_drop_actions(void* self, int64_t (*slot)());
int64_t q_sortfilterproxymodel_qbase_supported_drop_actions(void* self);
void q_sortfilterproxymodel_dynamic_sort_filter_changed(void* self, bool dynamicSortFilter);
void q_sortfilterproxymodel_on_dynamic_sort_filter_changed(void* self, void (*slot)(void*, bool));
void q_sortfilterproxymodel_filter_case_sensitivity_changed(void* self, int64_t filterCaseSensitivity);
void q_sortfilterproxymodel_on_filter_case_sensitivity_changed(void* self, void (*slot)(void*, int64_t));
void q_sortfilterproxymodel_sort_case_sensitivity_changed(void* self, int64_t sortCaseSensitivity);
void q_sortfilterproxymodel_on_sort_case_sensitivity_changed(void* self, void (*slot)(void*, int64_t));
void q_sortfilterproxymodel_sort_locale_aware_changed(void* self, bool sortLocaleAware);
void q_sortfilterproxymodel_on_sort_locale_aware_changed(void* self, void (*slot)(void*, bool));
void q_sortfilterproxymodel_sort_role_changed(void* self, int sortRole);
void q_sortfilterproxymodel_on_sort_role_changed(void* self, void (*slot)(void*, int));
void q_sortfilterproxymodel_filter_role_changed(void* self, int filterRole);
void q_sortfilterproxymodel_on_filter_role_changed(void* self, void (*slot)(void*, int));
void q_sortfilterproxymodel_recursive_filtering_enabled_changed(void* self, bool recursiveFilteringEnabled);
void q_sortfilterproxymodel_on_recursive_filtering_enabled_changed(void* self, void (*slot)(void*, bool));
void q_sortfilterproxymodel_auto_accept_child_rows_changed(void* self, bool autoAcceptChildRows);
void q_sortfilterproxymodel_on_auto_accept_child_rows_changed(void* self, void (*slot)(void*, bool));
const char* q_sortfilterproxymodel_tr2(const char* s, const char* c);
const char* q_sortfilterproxymodel_tr3(const char* s, const char* c, int n);
QAbstractItemModel* q_sortfilterproxymodel_source_model(void* self);
bool q_sortfilterproxymodel_has_index(void* self, int row, int column);
bool q_sortfilterproxymodel_insert_row(void* self, int row);
bool q_sortfilterproxymodel_insert_column(void* self, int column);
bool q_sortfilterproxymodel_remove_row(void* self, int row);
bool q_sortfilterproxymodel_remove_column(void* self, int column);
bool q_sortfilterproxymodel_move_row(void* self, void* sourceParent, int sourceRow, void* destinationParent, int destinationChild);
bool q_sortfilterproxymodel_move_column(void* self, void* sourceParent, int sourceColumn, void* destinationParent, int destinationChild);
bool q_sortfilterproxymodel_check_index(void* self, void* index);
void q_sortfilterproxymodel_data_changed(void* self, void* topLeft, void* bottomRight);
void q_sortfilterproxymodel_on_data_changed(void* self, void (*slot)(void*, void*, void*));
void q_sortfilterproxymodel_header_data_changed(void* self, int64_t orientation, int first, int last);
void q_sortfilterproxymodel_on_header_data_changed(void* self, void (*slot)(void*, int64_t, int, int));
void q_sortfilterproxymodel_layout_changed(void* self);
void q_sortfilterproxymodel_on_layout_changed(void* self, void (*slot)(void*));
void q_sortfilterproxymodel_layout_about_to_be_changed(void* self);
void q_sortfilterproxymodel_on_layout_about_to_be_changed(void* self, void (*slot)(void*));
bool q_sortfilterproxymodel_has_index3(void* self, int row, int column, void* parent);
bool q_sortfilterproxymodel_insert_row2(void* self, int row, void* parent);
bool q_sortfilterproxymodel_insert_column2(void* self, int column, void* parent);
bool q_sortfilterproxymodel_remove_row2(void* self, int row, void* parent);
bool q_sortfilterproxymodel_remove_column2(void* self, int column, void* parent);
bool q_sortfilterproxymodel_check_index2(void* self, void* index, int64_t options);
void q_sortfilterproxymodel_data_changed3(void* self, void* topLeft, void* bottomRight, int* roles[]);
void q_sortfilterproxymodel_on_data_changed3(void* self, void (*slot)(void*, void*, void*, int*));
void q_sortfilterproxymodel_layout_changed1(void* self, void* parents[]);
void q_sortfilterproxymodel_on_layout_changed1(void* self, void (*slot)(void*, void*));
void q_sortfilterproxymodel_layout_changed2(void* self, void* parents[], int64_t hint);
void q_sortfilterproxymodel_on_layout_changed2(void* self, void (*slot)(void*, void*, int64_t));
void q_sortfilterproxymodel_layout_about_to_be_changed1(void* self, void* parents[]);
void q_sortfilterproxymodel_on_layout_about_to_be_changed1(void* self, void (*slot)(void*, void*));
void q_sortfilterproxymodel_layout_about_to_be_changed2(void* self, void* parents[], int64_t hint);
void q_sortfilterproxymodel_on_layout_about_to_be_changed2(void* self, void (*slot)(void*, void*, int64_t));
const char* q_sortfilterproxymodel_object_name(void* self);
void q_sortfilterproxymodel_set_object_name(void* self, const char* name);
bool q_sortfilterproxymodel_is_widget_type(void* self);
bool q_sortfilterproxymodel_is_window_type(void* self);
bool q_sortfilterproxymodel_is_quick_item_type(void* self);
bool q_sortfilterproxymodel_signals_blocked(void* self);
bool q_sortfilterproxymodel_block_signals(void* self, bool b);
QThread* q_sortfilterproxymodel_thread(void* self);
void q_sortfilterproxymodel_move_to_thread(void* self, void* thread);
int32_t q_sortfilterproxymodel_start_timer(void* self, int interval);
void q_sortfilterproxymodel_kill_timer(void* self, int id);
libqt_list /* of QObject* */ q_sortfilterproxymodel_children(void* self);
void q_sortfilterproxymodel_set_parent(void* self, void* parent);
void q_sortfilterproxymodel_install_event_filter(void* self, void* filterObj);
void q_sortfilterproxymodel_remove_event_filter(void* self, void* obj);
QMetaObject__Connection* q_sortfilterproxymodel_connect(void* sender, void* signal, void* receiver, void* method);
QMetaObject__Connection* q_sortfilterproxymodel_connect2(void* self, void* sender, const char* signal, const char* member);
bool q_sortfilterproxymodel_disconnect(void* sender, void* signal, void* receiver, void* member);
bool q_sortfilterproxymodel_disconnect_with_q_meta_object_connection(void* param1);
void q_sortfilterproxymodel_dump_object_tree(void* self);
void q_sortfilterproxymodel_dump_object_info(void* self);
bool q_sortfilterproxymodel_set_property(void* self, const char* name, void* value);
QVariant* q_sortfilterproxymodel_property(void* self, const char* name);
const char** q_sortfilterproxymodel_dynamic_property_names(void* self);
QBindingStorage* q_sortfilterproxymodel_binding_storage(void* self);
QBindingStorage* q_sortfilterproxymodel_binding_storage2(void* self);
void q_sortfilterproxymodel_destroyed(void* self);
void q_sortfilterproxymodel_on_destroyed(void* self, void (*slot)(void*));
bool q_sortfilterproxymodel_inherits(void* self, const char* classname);
void q_sortfilterproxymodel_delete_later(void* self);
int32_t q_sortfilterproxymodel_start_timer2(void* self, int interval, int64_t timerType);
QMetaObject__Connection* q_sortfilterproxymodel_connect5(void* sender, void* signal, void* receiver, void* method, int64_t typeVal);
QMetaObject__Connection* q_sortfilterproxymodel_connect4(void* self, void* sender, const char* signal, const char* member, int64_t typeVal);
void q_sortfilterproxymodel_destroyed1(void* self, void* param1);
void q_sortfilterproxymodel_on_destroyed1(void* self, void (*slot)(void*, void*));
bool q_sortfilterproxymodel_submit(void* self);
bool q_sortfilterproxymodel_qbase_submit(void* self);
void q_sortfilterproxymodel_on_submit(void* self, bool (*slot)());
void q_sortfilterproxymodel_revert(void* self);
void q_sortfilterproxymodel_qbase_revert(void* self);
void q_sortfilterproxymodel_on_revert(void* self, void (*slot)());
libqt_map /* of int to QVariant* */ q_sortfilterproxymodel_item_data(void* self, void* index);
libqt_map /* of int to QVariant* */ q_sortfilterproxymodel_qbase_item_data(void* self, void* index);
void q_sortfilterproxymodel_on_item_data(void* self, libqt_map /* of int to QVariant* */ (*slot)(void*, void*));
bool q_sortfilterproxymodel_set_item_data(void* self, void* index, libqt_map /* of int to QVariant* */ roles);
bool q_sortfilterproxymodel_qbase_set_item_data(void* self, void* index, libqt_map /* of int to QVariant* */ roles);
void q_sortfilterproxymodel_on_set_item_data(void* self, bool (*slot)(void*, void*, libqt_map /* of int to QVariant* */));
bool q_sortfilterproxymodel_clear_item_data(void* self, void* index);
bool q_sortfilterproxymodel_qbase_clear_item_data(void* self, void* index);
void q_sortfilterproxymodel_on_clear_item_data(void* self, bool (*slot)(void*, void*));
bool q_sortfilterproxymodel_can_drop_mime_data(void* self, void* data, int64_t action, int row, int column, void* parent);
bool q_sortfilterproxymodel_qbase_can_drop_mime_data(void* self, void* data, int64_t action, int row, int column, void* parent);
void q_sortfilterproxymodel_on_can_drop_mime_data(void* self, bool (*slot)(void*, void*, int64_t, int, int, void*));
int64_t q_sortfilterproxymodel_supported_drag_actions(void* self);
int64_t q_sortfilterproxymodel_qbase_supported_drag_actions(void* self);
void q_sortfilterproxymodel_on_supported_drag_actions(void* self, int64_t (*slot)());
libqt_map /* of int to char* */ q_sortfilterproxymodel_role_names(void* self);
libqt_map /* of int to char* */ q_sortfilterproxymodel_qbase_role_names(void* self);
void q_sortfilterproxymodel_on_role_names(void* self, libqt_map /* of int to char* */ (*slot)());
bool q_sortfilterproxymodel_move_rows(void* self, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
bool q_sortfilterproxymodel_qbase_move_rows(void* self, void* sourceParent, int sourceRow, int count, void* destinationParent, int destinationChild);
void q_sortfilterproxymodel_on_move_rows(void* self, bool (*slot)(void*, void*, int, int, void*, int));
bool q_sortfilterproxymodel_move_columns(void* self, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
bool q_sortfilterproxymodel_qbase_move_columns(void* self, void* sourceParent, int sourceColumn, int count, void* destinationParent, int destinationChild);
void q_sortfilterproxymodel_on_move_columns(void* self, bool (*slot)(void*, void*, int, int, void*, int));
void q_sortfilterproxymodel_multi_data(void* self, void* index, void* roleDataSpan);
void q_sortfilterproxymodel_qbase_multi_data(void* self, void* index, void* roleDataSpan);
void q_sortfilterproxymodel_on_multi_data(void* self, void (*slot)(void*, void*, void*));
void q_sortfilterproxymodel_reset_internal_data(void* self);
void q_sortfilterproxymodel_qbase_reset_internal_data(void* self);
void q_sortfilterproxymodel_on_reset_internal_data(void* self, void (*slot)());
bool q_sortfilterproxymodel_event(void* self, void* event);
bool q_sortfilterproxymodel_qbase_event(void* self, void* event);
void q_sortfilterproxymodel_on_event(void* self, bool (*slot)(void*, void*));
bool q_sortfilterproxymodel_event_filter(void* self, void* watched, void* event);
bool q_sortfilterproxymodel_qbase_event_filter(void* self, void* watched, void* event);
void q_sortfilterproxymodel_on_event_filter(void* self, bool (*slot)(void*, void*, void*));
void q_sortfilterproxymodel_timer_event(void* self, void* event);
void q_sortfilterproxymodel_qbase_timer_event(void* self, void* event);
void q_sortfilterproxymodel_on_timer_event(void* self, void (*slot)(void*, void*));
void q_sortfilterproxymodel_child_event(void* self, void* event);
void q_sortfilterproxymodel_qbase_child_event(void* self, void* event);
void q_sortfilterproxymodel_on_child_event(void* self, void (*slot)(void*, void*));
void q_sortfilterproxymodel_custom_event(void* self, void* event);
void q_sortfilterproxymodel_qbase_custom_event(void* self, void* event);
void q_sortfilterproxymodel_on_custom_event(void* self, void (*slot)(void*, void*));
void q_sortfilterproxymodel_connect_notify(void* self, void* signal);
void q_sortfilterproxymodel_qbase_connect_notify(void* self, void* signal);
void q_sortfilterproxymodel_on_connect_notify(void* self, void (*slot)(void*, void*));
void q_sortfilterproxymodel_disconnect_notify(void* self, void* signal);
void q_sortfilterproxymodel_qbase_disconnect_notify(void* self, void* signal);
void q_sortfilterproxymodel_on_disconnect_notify(void* self, void (*slot)(void*, void*));
QModelIndex* q_sortfilterproxymodel_create_source_index(void* self, int row, int col, void* internalPtr);
QModelIndex* q_sortfilterproxymodel_qbase_create_source_index(void* self, int row, int col, void* internalPtr);
void q_sortfilterproxymodel_on_create_source_index(void* self, QModelIndex* (*slot)(void*, int, int, void*));
QModelIndex* q_sortfilterproxymodel_create_index(void* self, int row, int column);
QModelIndex* q_sortfilterproxymodel_qbase_create_index(void* self, int row, int column);
void q_sortfilterproxymodel_on_create_index(void* self, QModelIndex* (*slot)(void*, int, int));
void q_sortfilterproxymodel_encode_data(void* self, void* indexes[], void* stream);
void q_sortfilterproxymodel_qbase_encode_data(void* self, void* indexes[], void* stream);
void q_sortfilterproxymodel_on_encode_data(void* self, void (*slot)(void*, void*, void*));
bool q_sortfilterproxymodel_decode_data(void* self, int row, int column, void* parent, void* stream);
bool q_sortfilterproxymodel_qbase_decode_data(void* self, int row, int column, void* parent, void* stream);
void q_sortfilterproxymodel_on_decode_data(void* self, bool (*slot)(void*, int, int, void*, void*));
void q_sortfilterproxymodel_begin_insert_rows(void* self, void* parent, int first, int last);
void q_sortfilterproxymodel_qbase_begin_insert_rows(void* self, void* parent, int first, int last);
void q_sortfilterproxymodel_on_begin_insert_rows(void* self, void (*slot)(void*, void*, int, int));
void q_sortfilterproxymodel_end_insert_rows(void* self);
void q_sortfilterproxymodel_qbase_end_insert_rows(void* self);
void q_sortfilterproxymodel_on_end_insert_rows(void* self, void (*slot)());
void q_sortfilterproxymodel_begin_remove_rows(void* self, void* parent, int first, int last);
void q_sortfilterproxymodel_qbase_begin_remove_rows(void* self, void* parent, int first, int last);
void q_sortfilterproxymodel_on_begin_remove_rows(void* self, void (*slot)(void*, void*, int, int));
void q_sortfilterproxymodel_end_remove_rows(void* self);
void q_sortfilterproxymodel_qbase_end_remove_rows(void* self);
void q_sortfilterproxymodel_on_end_remove_rows(void* self, void (*slot)());
bool q_sortfilterproxymodel_begin_move_rows(void* self, void* sourceParent, int sourceFirst, int sourceLast, void* destinationParent, int destinationRow);
bool q_sortfilterproxymodel_qbase_begin_move_rows(void* self, void* sourceParent, int sourceFirst, int sourceLast, void* destinationParent, int destinationRow);
void q_sortfilterproxymodel_on_begin_move_rows(void* self, bool (*slot)(void*, void*, int, int, void*, int));
void q_sortfilterproxymodel_end_move_rows(void* self);
void q_sortfilterproxymodel_qbase_end_move_rows(void* self);
void q_sortfilterproxymodel_on_end_move_rows(void* self, void (*slot)());
void q_sortfilterproxymodel_begin_insert_columns(void* self, void* parent, int first, int last);
void q_sortfilterproxymodel_qbase_begin_insert_columns(void* self, void* parent, int first, int last);
void q_sortfilterproxymodel_on_begin_insert_columns(void* self, void (*slot)(void*, void*, int, int));
void q_sortfilterproxymodel_end_insert_columns(void* self);
void q_sortfilterproxymodel_qbase_end_insert_columns(void* self);
void q_sortfilterproxymodel_on_end_insert_columns(void* self, void (*slot)());
void q_sortfilterproxymodel_begin_remove_columns(void* self, void* parent, int first, int last);
void q_sortfilterproxymodel_qbase_begin_remove_columns(void* self, void* parent, int first, int last);
void q_sortfilterproxymodel_on_begin_remove_columns(void* self, void (*slot)(void*, void*, int, int));
void q_sortfilterproxymodel_end_remove_columns(void* self);
void q_sortfilterproxymodel_qbase_end_remove_columns(void* self);
void q_sortfilterproxymodel_on_end_remove_columns(void* self, void (*slot)());
bool q_sortfilterproxymodel_begin_move_columns(void* self, void* sourceParent, int sourceFirst, int sourceLast, void* destinationParent, int destinationColumn);
bool q_sortfilterproxymodel_qbase_begin_move_columns(void* self, void* sourceParent, int sourceFirst, int sourceLast, void* destinationParent, int destinationColumn);
void q_sortfilterproxymodel_on_begin_move_columns(void* self, bool (*slot)(void*, void*, int, int, void*, int));
void q_sortfilterproxymodel_end_move_columns(void* self);
void q_sortfilterproxymodel_qbase_end_move_columns(void* self);
void q_sortfilterproxymodel_on_end_move_columns(void* self, void (*slot)());
void q_sortfilterproxymodel_begin_reset_model(void* self);
void q_sortfilterproxymodel_qbase_begin_reset_model(void* self);
void q_sortfilterproxymodel_on_begin_reset_model(void* self, void (*slot)());
void q_sortfilterproxymodel_end_reset_model(void* self);
void q_sortfilterproxymodel_qbase_end_reset_model(void* self);
void q_sortfilterproxymodel_on_end_reset_model(void* self, void (*slot)());
void q_sortfilterproxymodel_change_persistent_index(void* self, void* from, void* to);
void q_sortfilterproxymodel_qbase_change_persistent_index(void* self, void* from, void* to);
void q_sortfilterproxymodel_on_change_persistent_index(void* self, void (*slot)(void*, void*, void*));
void q_sortfilterproxymodel_change_persistent_index_list(void* self, void* from[], void* to[]);
void q_sortfilterproxymodel_qbase_change_persistent_index_list(void* self, void* from[], void* to[]);
void q_sortfilterproxymodel_on_change_persistent_index_list(void* self, void (*slot)(void*, void*, void*));
libqt_list /* of QModelIndex* */ q_sortfilterproxymodel_persistent_index_list(void* self);
libqt_list /* of QModelIndex* */ q_sortfilterproxymodel_qbase_persistent_index_list(void* self);
void q_sortfilterproxymodel_on_persistent_index_list(void* self, libqt_list /* of QModelIndex* */ (*slot)());
QObject* q_sortfilterproxymodel_sender(void* self);
QObject* q_sortfilterproxymodel_qbase_sender(void* self);
void q_sortfilterproxymodel_on_sender(void* self, QObject* (*slot)());
int32_t q_sortfilterproxymodel_sender_signal_index(void* self);
int32_t q_sortfilterproxymodel_qbase_sender_signal_index(void* self);
void q_sortfilterproxymodel_on_sender_signal_index(void* self, int32_t (*slot)());
int32_t q_sortfilterproxymodel_receivers(void* self, const char* signal);
int32_t q_sortfilterproxymodel_qbase_receivers(void* self, const char* signal);
void q_sortfilterproxymodel_on_receivers(void* self, int32_t (*slot)(void*, const char*));
bool q_sortfilterproxymodel_is_signal_connected(void* self, void* signal);
bool q_sortfilterproxymodel_qbase_is_signal_connected(void* self, void* signal);
void q_sortfilterproxymodel_on_is_signal_connected(void* self, bool (*slot)(void*, void*));
void q_sortfilterproxymodel_delete(void* self);

#endif
