#pragma once
#ifndef SRCQT6C_LIBQTABLEWIDGET_H
#define SRCQT6C_LIBQTABLEWIDGET_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#include "libqabstractitemdelegate.h"
#include "libqabstractitemmodel.h"
#include "libqabstractitemview.h"
#include "libqabstractscrollarea.h"
#include "libqaction.h"
#include "libqevent.h"
#include "libqanystringview.h"
#include "libqbackingstore.h"
#include "libqbindingstorage.h"
#include "libqbitmap.h"
#include "libqbrush.h"
#include "libqcursor.h"
#include "libqdatastream.h"
#include "libqfont.h"
#include "libqfontinfo.h"
#include "libqfontmetrics.h"
#include "libqframe.h"
#include "libqgraphicseffect.h"
#include "libqgraphicsproxywidget.h"
#include "libqheaderview.h"
#include "libqicon.h"
#include "libqitemselectionmodel.h"
#include "libqkeysequence.h"
#include "libqlayout.h"
#include "libqlocale.h"
#include "libqmargins.h"
#include "libqmetaobject.h"
#include "libqmimedata.h"
#include "libqobject.h"
#include "libqpaintdevice.h"
#include "libqpaintengine.h"
#include "libqpainter.h"
#include "libqpalette.h"
#include "libqpixmap.h"
#include "libqpoint.h"
#include "libqrect.h"
#include "libqregion.h"
#include "libqscreen.h"
#include "libqscrollbar.h"
#include "libqsize.h"
#include "libqsizepolicy.h"
#include <string.h>
#include "libqstyle.h"
#include "libqstyleoption.h"
#include "libqtableview.h"
#include "libqthread.h"
#include "libqvariant.h"
#include "libqwidget.h"
#include "libqwindow.h"

QTableWidgetSelectionRange* q_tablewidgetselectionrange_new(void* other);
QTableWidgetSelectionRange* q_tablewidgetselectionrange_new2(void* other);
QTableWidgetSelectionRange* q_tablewidgetselectionrange_new3();
QTableWidgetSelectionRange* q_tablewidgetselectionrange_new4(int top, int left, int bottom, int right);
void q_tablewidgetselectionrange_copy_assign(void* self, void* other);
void q_tablewidgetselectionrange_move_assign(void* self, void* other);
int32_t q_tablewidgetselectionrange_top_row(void* self);
int32_t q_tablewidgetselectionrange_bottom_row(void* self);
int32_t q_tablewidgetselectionrange_left_column(void* self);
int32_t q_tablewidgetselectionrange_right_column(void* self);
int32_t q_tablewidgetselectionrange_row_count(void* self);
int32_t q_tablewidgetselectionrange_column_count(void* self);
void q_tablewidgetselectionrange_delete(void* self);

QTableWidgetItem* q_tablewidgetitem_new();
QTableWidgetItem* q_tablewidgetitem_new2(const char* text);
QTableWidgetItem* q_tablewidgetitem_new3(void* icon, const char* text);
QTableWidgetItem* q_tablewidgetitem_new4(void* other);
QTableWidgetItem* q_tablewidgetitem_new5(int typeVal);
QTableWidgetItem* q_tablewidgetitem_new6(const char* text, int typeVal);
QTableWidgetItem* q_tablewidgetitem_new7(void* icon, const char* text, int typeVal);
QTableWidgetItem* q_tablewidgetitem_clone(void* self);
void q_tablewidgetitem_on_clone(void* self, QTableWidgetItem* (*slot)());
QTableWidgetItem* q_tablewidgetitem_qbase_clone(void* self);
QTableWidget* q_tablewidgetitem_table_widget(void* self);
int32_t q_tablewidgetitem_row(void* self);
int32_t q_tablewidgetitem_column(void* self);
void q_tablewidgetitem_set_selected(void* self, bool selectVal);
bool q_tablewidgetitem_is_selected(void* self);
int64_t q_tablewidgetitem_flags(void* self);
void q_tablewidgetitem_set_flags(void* self, int64_t flags);
const char* q_tablewidgetitem_text(void* self);
void q_tablewidgetitem_set_text(void* self, const char* text);
QIcon* q_tablewidgetitem_icon(void* self);
void q_tablewidgetitem_set_icon(void* self, void* icon);
const char* q_tablewidgetitem_status_tip(void* self);
void q_tablewidgetitem_set_status_tip(void* self, const char* statusTip);
const char* q_tablewidgetitem_tool_tip(void* self);
void q_tablewidgetitem_set_tool_tip(void* self, const char* toolTip);
const char* q_tablewidgetitem_whats_this(void* self);
void q_tablewidgetitem_set_whats_this(void* self, const char* whatsThis);
QFont* q_tablewidgetitem_font(void* self);
void q_tablewidgetitem_set_font(void* self, void* font);
int32_t q_tablewidgetitem_text_alignment(void* self);
void q_tablewidgetitem_set_text_alignment(void* self, int alignment);
void q_tablewidgetitem_set_text_alignment_with_alignment(void* self, int64_t alignment);
void q_tablewidgetitem_set_text_alignment2(void* self, int64_t alignment);
QBrush* q_tablewidgetitem_background(void* self);
void q_tablewidgetitem_set_background(void* self, void* brush);
QBrush* q_tablewidgetitem_foreground(void* self);
void q_tablewidgetitem_set_foreground(void* self, void* brush);
int64_t q_tablewidgetitem_check_state(void* self);
void q_tablewidgetitem_set_check_state(void* self, int64_t state);
QSize* q_tablewidgetitem_size_hint(void* self);
void q_tablewidgetitem_set_size_hint(void* self, void* size);
QVariant* q_tablewidgetitem_data(void* self, int role);
void q_tablewidgetitem_on_data(void* self, QVariant* (*slot)(void*, int));
QVariant* q_tablewidgetitem_qbase_data(void* self, int role);
void q_tablewidgetitem_set_data(void* self, int role, void* value);
void q_tablewidgetitem_on_set_data(void* self, void (*slot)(void*, int, void*));
void q_tablewidgetitem_qbase_set_data(void* self, int role, void* value);
bool q_tablewidgetitem_operator_lesser(void* self, void* other);
void q_tablewidgetitem_on_operator_lesser(void* self, bool (*slot)(void*, void*));
bool q_tablewidgetitem_qbase_operator_lesser(void* self, void* other);
void q_tablewidgetitem_read(void* self, void* in);
void q_tablewidgetitem_on_read(void* self, void (*slot)(void*, void*));
void q_tablewidgetitem_qbase_read(void* self, void* in);
void q_tablewidgetitem_write(void* self, void* out);
void q_tablewidgetitem_on_write(void* self, void (*slot)(void*, void*));
void q_tablewidgetitem_qbase_write(void* self, void* out);
void q_tablewidgetitem_operator_assign(void* self, void* other);
int32_t q_tablewidgetitem_type(void* self);
void q_tablewidgetitem_delete(void* self);

QTableWidget* q_tablewidget_new(void* parent);
QTableWidget* q_tablewidget_new2();
QTableWidget* q_tablewidget_new3(int rows, int columns);
QTableWidget* q_tablewidget_new4(int rows, int columns, void* parent);
QMetaObject* q_tablewidget_meta_object(void* self);
void* q_tablewidget_metacast(void* self, const char* param1);
int32_t q_tablewidget_metacall(void* self, int64_t param1, int param2, void* param3);
void q_tablewidget_on_metacall(void* self, int32_t (*slot)(void*, int64_t, int, void*));
int32_t q_tablewidget_qbase_metacall(void* self, int64_t param1, int param2, void* param3);
const char* q_tablewidget_tr(const char* s);
void q_tablewidget_set_row_count(void* self, int rows);
int32_t q_tablewidget_row_count(void* self);
void q_tablewidget_set_column_count(void* self, int columns);
int32_t q_tablewidget_column_count(void* self);
int32_t q_tablewidget_row(void* self, void* item);
int32_t q_tablewidget_column(void* self, void* item);
QTableWidgetItem* q_tablewidget_item(void* self, int row, int column);
void q_tablewidget_set_item(void* self, int row, int column, void* item);
QTableWidgetItem* q_tablewidget_take_item(void* self, int row, int column);
libqt_list /* of QTableWidgetItem* */ q_tablewidget_items(void* self, void* data);
QModelIndex* q_tablewidget_index_from_item(void* self, void* item);
QTableWidgetItem* q_tablewidget_item_from_index(void* self, void* index);
QTableWidgetItem* q_tablewidget_vertical_header_item(void* self, int row);
void q_tablewidget_set_vertical_header_item(void* self, int row, void* item);
QTableWidgetItem* q_tablewidget_take_vertical_header_item(void* self, int row);
QTableWidgetItem* q_tablewidget_horizontal_header_item(void* self, int column);
void q_tablewidget_set_horizontal_header_item(void* self, int column, void* item);
QTableWidgetItem* q_tablewidget_take_horizontal_header_item(void* self, int column);
void q_tablewidget_set_vertical_header_labels(void* self, const char* labels[]);
void q_tablewidget_set_horizontal_header_labels(void* self, const char* labels[]);
int32_t q_tablewidget_current_row(void* self);
int32_t q_tablewidget_current_column(void* self);
QTableWidgetItem* q_tablewidget_current_item(void* self);
void q_tablewidget_set_current_item(void* self, void* item);
void q_tablewidget_set_current_item2(void* self, void* item, int64_t command);
void q_tablewidget_set_current_cell(void* self, int row, int column);
void q_tablewidget_set_current_cell2(void* self, int row, int column, int64_t command);
void q_tablewidget_sort_items(void* self, int column);
void q_tablewidget_set_sorting_enabled(void* self, bool enable);
bool q_tablewidget_is_sorting_enabled(void* self);
void q_tablewidget_edit_item(void* self, void* item);
void q_tablewidget_open_persistent_editor(void* self, void* item);
void q_tablewidget_close_persistent_editor(void* self, void* item);
bool q_tablewidget_is_persistent_editor_open(void* self, void* item);
QWidget* q_tablewidget_cell_widget(void* self, int row, int column);
void q_tablewidget_set_cell_widget(void* self, int row, int column, void* widget);
void q_tablewidget_remove_cell_widget(void* self, int row, int column);
void q_tablewidget_set_range_selected(void* self, void* range, bool selectVal);
libqt_list /* of QTableWidgetSelectionRange* */ q_tablewidget_selected_ranges(void* self);
libqt_list /* of QTableWidgetItem* */ q_tablewidget_selected_items(void* self);
libqt_list /* of QTableWidgetItem* */ q_tablewidget_find_items(void* self, const char* text, int64_t flags);
int32_t q_tablewidget_visual_row(void* self, int logicalRow);
int32_t q_tablewidget_visual_column(void* self, int logicalColumn);
QTableWidgetItem* q_tablewidget_item_at(void* self, void* p);
QTableWidgetItem* q_tablewidget_item_at2(void* self, int x, int y);
QRect* q_tablewidget_visual_item_rect(void* self, void* item);
QTableWidgetItem* q_tablewidget_item_prototype(void* self);
void q_tablewidget_set_item_prototype(void* self, void* item);
void q_tablewidget_scroll_to_item(void* self, void* item);
void q_tablewidget_insert_row(void* self, int row);
void q_tablewidget_insert_column(void* self, int column);
void q_tablewidget_remove_row(void* self, int row);
void q_tablewidget_remove_column(void* self, int column);
void q_tablewidget_clear(void* self);
void q_tablewidget_clear_contents(void* self);
void q_tablewidget_item_pressed(void* self, void* item);
void q_tablewidget_on_item_pressed(void* self, void (*slot)(void*, void*));
void q_tablewidget_item_clicked(void* self, void* item);
void q_tablewidget_on_item_clicked(void* self, void (*slot)(void*, void*));
void q_tablewidget_item_double_clicked(void* self, void* item);
void q_tablewidget_on_item_double_clicked(void* self, void (*slot)(void*, void*));
void q_tablewidget_item_activated(void* self, void* item);
void q_tablewidget_on_item_activated(void* self, void (*slot)(void*, void*));
void q_tablewidget_item_entered(void* self, void* item);
void q_tablewidget_on_item_entered(void* self, void (*slot)(void*, void*));
void q_tablewidget_item_changed(void* self, void* item);
void q_tablewidget_on_item_changed(void* self, void (*slot)(void*, void*));
void q_tablewidget_current_item_changed(void* self, void* current, void* previous);
void q_tablewidget_on_current_item_changed(void* self, void (*slot)(void*, void*, void*));
void q_tablewidget_item_selection_changed(void* self);
void q_tablewidget_on_item_selection_changed(void* self, void (*slot)(void*));
void q_tablewidget_cell_pressed(void* self, int row, int column);
void q_tablewidget_on_cell_pressed(void* self, void (*slot)(void*, int, int));
void q_tablewidget_cell_clicked(void* self, int row, int column);
void q_tablewidget_on_cell_clicked(void* self, void (*slot)(void*, int, int));
void q_tablewidget_cell_double_clicked(void* self, int row, int column);
void q_tablewidget_on_cell_double_clicked(void* self, void (*slot)(void*, int, int));
void q_tablewidget_cell_activated(void* self, int row, int column);
void q_tablewidget_on_cell_activated(void* self, void (*slot)(void*, int, int));
void q_tablewidget_cell_entered(void* self, int row, int column);
void q_tablewidget_on_cell_entered(void* self, void (*slot)(void*, int, int));
void q_tablewidget_cell_changed(void* self, int row, int column);
void q_tablewidget_on_cell_changed(void* self, void (*slot)(void*, int, int));
void q_tablewidget_current_cell_changed(void* self, int currentRow, int currentColumn, int previousRow, int previousColumn);
void q_tablewidget_on_current_cell_changed(void* self, void (*slot)(void*, int, int, int, int));
bool q_tablewidget_event(void* self, void* e);
void q_tablewidget_on_event(void* self, bool (*slot)(void*, void*));
bool q_tablewidget_qbase_event(void* self, void* e);
const char** q_tablewidget_mime_types(void* self);
void q_tablewidget_on_mime_types(void* self, const char** (*slot)());
const char** q_tablewidget_qbase_mime_types(void* self);
QMimeData* q_tablewidget_mime_data(void* self, void* items[]);
void q_tablewidget_on_mime_data(void* self, QMimeData* (*slot)(void*, void*));
QMimeData* q_tablewidget_qbase_mime_data(void* self, void* items[]);
bool q_tablewidget_drop_mime_data(void* self, int row, int column, void* data, int64_t action);
void q_tablewidget_on_drop_mime_data(void* self, bool (*slot)(void*, int, int, void*, int64_t));
bool q_tablewidget_qbase_drop_mime_data(void* self, int row, int column, void* data, int64_t action);
int64_t q_tablewidget_supported_drop_actions(void* self);
void q_tablewidget_on_supported_drop_actions(void* self, int64_t (*slot)());
int64_t q_tablewidget_qbase_supported_drop_actions(void* self);
void q_tablewidget_drop_event(void* self, void* event);
void q_tablewidget_on_drop_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_qbase_drop_event(void* self, void* event);
const char* q_tablewidget_tr2(const char* s, const char* c);
const char* q_tablewidget_tr3(const char* s, const char* c, int n);
void q_tablewidget_sort_items2(void* self, int column, int64_t order);
void q_tablewidget_scroll_to_item2(void* self, void* item, int64_t hint);
void q_tablewidget_set_model(void* self, void* model);
void q_tablewidget_on_set_model(void* self, void (*slot)(void*, void*));
void q_tablewidget_qbase_set_model(void* self, void* model);
QHeaderView* q_tablewidget_horizontal_header(void* self);
QHeaderView* q_tablewidget_vertical_header(void* self);
void q_tablewidget_set_horizontal_header(void* self, void* header);
void q_tablewidget_set_vertical_header(void* self, void* header);
int32_t q_tablewidget_row_viewport_position(void* self, int row);
int32_t q_tablewidget_row_at(void* self, int y);
void q_tablewidget_set_row_height(void* self, int row, int height);
int32_t q_tablewidget_row_height(void* self, int row);
int32_t q_tablewidget_column_viewport_position(void* self, int column);
int32_t q_tablewidget_column_at(void* self, int x);
void q_tablewidget_set_column_width(void* self, int column, int width);
int32_t q_tablewidget_column_width(void* self, int column);
bool q_tablewidget_is_row_hidden(void* self, int row);
void q_tablewidget_set_row_hidden(void* self, int row, bool hide);
bool q_tablewidget_is_column_hidden(void* self, int column);
void q_tablewidget_set_column_hidden(void* self, int column, bool hide);
bool q_tablewidget_show_grid(void* self);
int64_t q_tablewidget_grid_style(void* self);
void q_tablewidget_set_grid_style(void* self, int64_t style);
void q_tablewidget_set_word_wrap(void* self, bool on);
bool q_tablewidget_word_wrap(void* self);
void q_tablewidget_set_corner_button_enabled(void* self, bool enable);
bool q_tablewidget_is_corner_button_enabled(void* self);
void q_tablewidget_set_span(void* self, int row, int column, int rowSpan, int columnSpan);
int32_t q_tablewidget_row_span(void* self, int row, int column);
int32_t q_tablewidget_column_span(void* self, int row, int column);
void q_tablewidget_clear_spans(void* self);
void q_tablewidget_select_row(void* self, int row);
void q_tablewidget_select_column(void* self, int column);
void q_tablewidget_hide_row(void* self, int row);
void q_tablewidget_hide_column(void* self, int column);
void q_tablewidget_show_row(void* self, int row);
void q_tablewidget_show_column(void* self, int column);
void q_tablewidget_resize_row_to_contents(void* self, int row);
void q_tablewidget_resize_rows_to_contents(void* self);
void q_tablewidget_resize_column_to_contents(void* self, int column);
void q_tablewidget_resize_columns_to_contents(void* self);
void q_tablewidget_sort_by_column(void* self, int column, int64_t order);
void q_tablewidget_set_show_grid(void* self, bool show);
QAbstractItemModel* q_tablewidget_model(void* self);
QItemSelectionModel* q_tablewidget_selection_model(void* self);
void q_tablewidget_set_item_delegate(void* self, void* delegate);
QAbstractItemDelegate* q_tablewidget_item_delegate(void* self);
void q_tablewidget_set_selection_mode(void* self, int64_t mode);
int64_t q_tablewidget_selection_mode(void* self);
void q_tablewidget_set_selection_behavior(void* self, int64_t behavior);
int64_t q_tablewidget_selection_behavior(void* self);
QModelIndex* q_tablewidget_current_index(void* self);
QModelIndex* q_tablewidget_root_index(void* self);
void q_tablewidget_set_edit_triggers(void* self, int64_t triggers);
int64_t q_tablewidget_edit_triggers(void* self);
void q_tablewidget_set_vertical_scroll_mode(void* self, int64_t mode);
int64_t q_tablewidget_vertical_scroll_mode(void* self);
void q_tablewidget_reset_vertical_scroll_mode(void* self);
void q_tablewidget_set_horizontal_scroll_mode(void* self, int64_t mode);
int64_t q_tablewidget_horizontal_scroll_mode(void* self);
void q_tablewidget_reset_horizontal_scroll_mode(void* self);
void q_tablewidget_set_auto_scroll(void* self, bool enable);
bool q_tablewidget_has_auto_scroll(void* self);
void q_tablewidget_set_auto_scroll_margin(void* self, int margin);
int32_t q_tablewidget_auto_scroll_margin(void* self);
void q_tablewidget_set_tab_key_navigation(void* self, bool enable);
bool q_tablewidget_tab_key_navigation(void* self);
void q_tablewidget_set_drop_indicator_shown(void* self, bool enable);
bool q_tablewidget_show_drop_indicator(void* self);
void q_tablewidget_set_drag_enabled(void* self, bool enable);
bool q_tablewidget_drag_enabled(void* self);
void q_tablewidget_set_drag_drop_overwrite_mode(void* self, bool overwrite);
bool q_tablewidget_drag_drop_overwrite_mode(void* self);
void q_tablewidget_set_drag_drop_mode(void* self, int64_t behavior);
int64_t q_tablewidget_drag_drop_mode(void* self);
void q_tablewidget_set_default_drop_action(void* self, int64_t dropAction);
int64_t q_tablewidget_default_drop_action(void* self);
void q_tablewidget_set_alternating_row_colors(void* self, bool enable);
bool q_tablewidget_alternating_row_colors(void* self);
void q_tablewidget_set_icon_size(void* self, void* size);
QSize* q_tablewidget_icon_size(void* self);
void q_tablewidget_set_text_elide_mode(void* self, int64_t mode);
int64_t q_tablewidget_text_elide_mode(void* self);
QSize* q_tablewidget_size_hint_for_index(void* self, void* index);
void q_tablewidget_set_index_widget(void* self, void* index, void* widget);
QWidget* q_tablewidget_index_widget(void* self, void* index);
void q_tablewidget_set_item_delegate_for_row(void* self, int row, void* delegate);
QAbstractItemDelegate* q_tablewidget_item_delegate_for_row(void* self, int row);
void q_tablewidget_set_item_delegate_for_column(void* self, int column, void* delegate);
QAbstractItemDelegate* q_tablewidget_item_delegate_for_column(void* self, int column);
QAbstractItemDelegate* q_tablewidget_item_delegate_with_index(void* self, void* index);
void q_tablewidget_edit(void* self, void* index);
void q_tablewidget_clear_selection(void* self);
void q_tablewidget_set_current_index(void* self, void* index);
void q_tablewidget_scroll_to_top(void* self);
void q_tablewidget_scroll_to_bottom(void* self);
void q_tablewidget_update(void* self, void* index);
void q_tablewidget_pressed(void* self, void* index);
void q_tablewidget_on_pressed(void* self, void (*slot)(void*, void*));
void q_tablewidget_clicked(void* self, void* index);
void q_tablewidget_on_clicked(void* self, void (*slot)(void*, void*));
void q_tablewidget_double_clicked(void* self, void* index);
void q_tablewidget_on_double_clicked(void* self, void (*slot)(void*, void*));
void q_tablewidget_activated(void* self, void* index);
void q_tablewidget_on_activated(void* self, void (*slot)(void*, void*));
void q_tablewidget_entered(void* self, void* index);
void q_tablewidget_on_entered(void* self, void (*slot)(void*, void*));
void q_tablewidget_viewport_entered(void* self);
void q_tablewidget_on_viewport_entered(void* self, void (*slot)(void*));
void q_tablewidget_icon_size_changed(void* self, void* size);
void q_tablewidget_on_icon_size_changed(void* self, void (*slot)(void*, void*));
int64_t q_tablewidget_vertical_scroll_bar_policy(void* self);
void q_tablewidget_set_vertical_scroll_bar_policy(void* self, int64_t verticalScrollBarPolicy);
QScrollBar* q_tablewidget_vertical_scroll_bar(void* self);
void q_tablewidget_set_vertical_scroll_bar(void* self, void* scrollbar);
int64_t q_tablewidget_horizontal_scroll_bar_policy(void* self);
void q_tablewidget_set_horizontal_scroll_bar_policy(void* self, int64_t horizontalScrollBarPolicy);
QScrollBar* q_tablewidget_horizontal_scroll_bar(void* self);
void q_tablewidget_set_horizontal_scroll_bar(void* self, void* scrollbar);
QWidget* q_tablewidget_corner_widget(void* self);
void q_tablewidget_set_corner_widget(void* self, void* widget);
void q_tablewidget_add_scroll_bar_widget(void* self, void* widget, int64_t alignment);
libqt_list /* of QWidget* */ q_tablewidget_scroll_bar_widgets(void* self, int64_t alignment);
QWidget* q_tablewidget_viewport(void* self);
void q_tablewidget_set_viewport(void* self, void* widget);
QSize* q_tablewidget_maximum_viewport_size(void* self);
int64_t q_tablewidget_size_adjust_policy(void* self);
void q_tablewidget_set_size_adjust_policy(void* self, int64_t policy);
int32_t q_tablewidget_frame_style(void* self);
void q_tablewidget_set_frame_style(void* self, int frameStyle);
int32_t q_tablewidget_frame_width(void* self);
int64_t q_tablewidget_frame_shape(void* self);
void q_tablewidget_set_frame_shape(void* self, int64_t frameShape);
int64_t q_tablewidget_frame_shadow(void* self);
void q_tablewidget_set_frame_shadow(void* self, int64_t frameShadow);
int32_t q_tablewidget_line_width(void* self);
void q_tablewidget_set_line_width(void* self, int lineWidth);
int32_t q_tablewidget_mid_line_width(void* self);
void q_tablewidget_set_mid_line_width(void* self, int midLineWidth);
QRect* q_tablewidget_frame_rect(void* self);
void q_tablewidget_set_frame_rect(void* self, void* frameRect);
uintptr_t q_tablewidget_win_id(void* self);
void q_tablewidget_create_win_id(void* self);
uintptr_t q_tablewidget_internal_win_id(void* self);
uintptr_t q_tablewidget_effective_win_id(void* self);
QStyle* q_tablewidget_style(void* self);
void q_tablewidget_set_style(void* self, void* style);
bool q_tablewidget_is_top_level(void* self);
bool q_tablewidget_is_window(void* self);
bool q_tablewidget_is_modal(void* self);
int64_t q_tablewidget_window_modality(void* self);
void q_tablewidget_set_window_modality(void* self, int64_t windowModality);
bool q_tablewidget_is_enabled(void* self);
bool q_tablewidget_is_enabled_to(void* self, void* param1);
void q_tablewidget_set_enabled(void* self, bool enabled);
void q_tablewidget_set_disabled(void* self, bool disabled);
void q_tablewidget_set_window_modified(void* self, bool windowModified);
QRect* q_tablewidget_frame_geometry(void* self);
QRect* q_tablewidget_geometry(void* self);
QRect* q_tablewidget_normal_geometry(void* self);
int32_t q_tablewidget_x(void* self);
int32_t q_tablewidget_y(void* self);
QPoint* q_tablewidget_pos(void* self);
QSize* q_tablewidget_frame_size(void* self);
QSize* q_tablewidget_size(void* self);
int32_t q_tablewidget_width(void* self);
int32_t q_tablewidget_height(void* self);
QRect* q_tablewidget_rect(void* self);
QRect* q_tablewidget_children_rect(void* self);
QRegion* q_tablewidget_children_region(void* self);
QSize* q_tablewidget_minimum_size(void* self);
QSize* q_tablewidget_maximum_size(void* self);
int32_t q_tablewidget_minimum_width(void* self);
int32_t q_tablewidget_minimum_height(void* self);
int32_t q_tablewidget_maximum_width(void* self);
int32_t q_tablewidget_maximum_height(void* self);
void q_tablewidget_set_minimum_size(void* self, void* minimumSize);
void q_tablewidget_set_minimum_size2(void* self, int minw, int minh);
void q_tablewidget_set_maximum_size(void* self, void* maximumSize);
void q_tablewidget_set_maximum_size2(void* self, int maxw, int maxh);
void q_tablewidget_set_minimum_width(void* self, int minw);
void q_tablewidget_set_minimum_height(void* self, int minh);
void q_tablewidget_set_maximum_width(void* self, int maxw);
void q_tablewidget_set_maximum_height(void* self, int maxh);
QSize* q_tablewidget_size_increment(void* self);
void q_tablewidget_set_size_increment(void* self, void* sizeIncrement);
void q_tablewidget_set_size_increment2(void* self, int w, int h);
QSize* q_tablewidget_base_size(void* self);
void q_tablewidget_set_base_size(void* self, void* baseSize);
void q_tablewidget_set_base_size2(void* self, int basew, int baseh);
void q_tablewidget_set_fixed_size(void* self, void* fixedSize);
void q_tablewidget_set_fixed_size2(void* self, int w, int h);
void q_tablewidget_set_fixed_width(void* self, int w);
void q_tablewidget_set_fixed_height(void* self, int h);
QPointF* q_tablewidget_map_to_global(void* self, void* param1);
QPoint* q_tablewidget_map_to_global_with_q_point(void* self, void* param1);
QPointF* q_tablewidget_map_from_global(void* self, void* param1);
QPoint* q_tablewidget_map_from_global_with_q_point(void* self, void* param1);
QPointF* q_tablewidget_map_to_parent(void* self, void* param1);
QPoint* q_tablewidget_map_to_parent_with_q_point(void* self, void* param1);
QPointF* q_tablewidget_map_from_parent(void* self, void* param1);
QPoint* q_tablewidget_map_from_parent_with_q_point(void* self, void* param1);
QPointF* q_tablewidget_map_to(void* self, void* param1, void* param2);
QPoint* q_tablewidget_map_to2(void* self, void* param1, void* param2);
QPointF* q_tablewidget_map_from(void* self, void* param1, void* param2);
QPoint* q_tablewidget_map_from2(void* self, void* param1, void* param2);
QWidget* q_tablewidget_window(void* self);
QWidget* q_tablewidget_native_parent_widget(void* self);
QWidget* q_tablewidget_top_level_widget(void* self);
QPalette* q_tablewidget_palette(void* self);
void q_tablewidget_set_palette(void* self, void* palette);
void q_tablewidget_set_background_role(void* self, int64_t backgroundRole);
int64_t q_tablewidget_background_role(void* self);
void q_tablewidget_set_foreground_role(void* self, int64_t foregroundRole);
int64_t q_tablewidget_foreground_role(void* self);
QFont* q_tablewidget_font(void* self);
void q_tablewidget_set_font(void* self, void* font);
QFontMetrics* q_tablewidget_font_metrics(void* self);
QFontInfo* q_tablewidget_font_info(void* self);
QCursor* q_tablewidget_cursor(void* self);
void q_tablewidget_set_cursor(void* self, void* cursor);
void q_tablewidget_unset_cursor(void* self);
void q_tablewidget_set_mouse_tracking(void* self, bool enable);
bool q_tablewidget_has_mouse_tracking(void* self);
bool q_tablewidget_under_mouse(void* self);
void q_tablewidget_set_tablet_tracking(void* self, bool enable);
bool q_tablewidget_has_tablet_tracking(void* self);
void q_tablewidget_set_mask(void* self, void* mask);
void q_tablewidget_set_mask_with_mask(void* self, void* mask);
QRegion* q_tablewidget_mask(void* self);
void q_tablewidget_clear_mask(void* self);
void q_tablewidget_render(void* self, void* target);
void q_tablewidget_render_with_painter(void* self, void* painter);
QPixmap* q_tablewidget_grab(void* self);
QGraphicsEffect* q_tablewidget_graphics_effect(void* self);
void q_tablewidget_set_graphics_effect(void* self, void* effect);
void q_tablewidget_grab_gesture(void* self, int64_t typeVal);
void q_tablewidget_ungrab_gesture(void* self, int64_t typeVal);
void q_tablewidget_set_window_title(void* self, const char* windowTitle);
void q_tablewidget_set_style_sheet(void* self, const char* styleSheet);
const char* q_tablewidget_style_sheet(void* self);
const char* q_tablewidget_window_title(void* self);
void q_tablewidget_set_window_icon(void* self, void* icon);
QIcon* q_tablewidget_window_icon(void* self);
void q_tablewidget_set_window_icon_text(void* self, const char* windowIconText);
const char* q_tablewidget_window_icon_text(void* self);
void q_tablewidget_set_window_role(void* self, const char* windowRole);
const char* q_tablewidget_window_role(void* self);
void q_tablewidget_set_window_file_path(void* self, const char* filePath);
const char* q_tablewidget_window_file_path(void* self);
void q_tablewidget_set_window_opacity(void* self, double level);
double q_tablewidget_window_opacity(void* self);
bool q_tablewidget_is_window_modified(void* self);
void q_tablewidget_set_tool_tip(void* self, const char* toolTip);
const char* q_tablewidget_tool_tip(void* self);
void q_tablewidget_set_tool_tip_duration(void* self, int msec);
int32_t q_tablewidget_tool_tip_duration(void* self);
void q_tablewidget_set_status_tip(void* self, const char* statusTip);
const char* q_tablewidget_status_tip(void* self);
void q_tablewidget_set_whats_this(void* self, const char* whatsThis);
const char* q_tablewidget_whats_this(void* self);
const char* q_tablewidget_accessible_name(void* self);
void q_tablewidget_set_accessible_name(void* self, const char* name);
const char* q_tablewidget_accessible_description(void* self);
void q_tablewidget_set_accessible_description(void* self, const char* description);
void q_tablewidget_set_layout_direction(void* self, int64_t direction);
int64_t q_tablewidget_layout_direction(void* self);
void q_tablewidget_unset_layout_direction(void* self);
void q_tablewidget_set_locale(void* self, void* locale);
QLocale* q_tablewidget_locale(void* self);
void q_tablewidget_unset_locale(void* self);
bool q_tablewidget_is_right_to_left(void* self);
bool q_tablewidget_is_left_to_right(void* self);
void q_tablewidget_set_focus(void* self);
bool q_tablewidget_is_active_window(void* self);
void q_tablewidget_activate_window(void* self);
void q_tablewidget_clear_focus(void* self);
void q_tablewidget_set_focus_with_reason(void* self, int64_t reason);
int64_t q_tablewidget_focus_policy(void* self);
void q_tablewidget_set_focus_policy(void* self, int64_t policy);
bool q_tablewidget_has_focus(void* self);
void q_tablewidget_set_tab_order(void* param1, void* param2);
void q_tablewidget_set_focus_proxy(void* self, void* focusProxy);
QWidget* q_tablewidget_focus_proxy(void* self);
int64_t q_tablewidget_context_menu_policy(void* self);
void q_tablewidget_set_context_menu_policy(void* self, int64_t policy);
void q_tablewidget_grab_mouse(void* self);
void q_tablewidget_grab_mouse_with_q_cursor(void* self, void* param1);
void q_tablewidget_release_mouse(void* self);
void q_tablewidget_grab_keyboard(void* self);
void q_tablewidget_release_keyboard(void* self);
int32_t q_tablewidget_grab_shortcut(void* self, void* key);
void q_tablewidget_release_shortcut(void* self, int id);
void q_tablewidget_set_shortcut_enabled(void* self, int id);
void q_tablewidget_set_shortcut_auto_repeat(void* self, int id);
QWidget* q_tablewidget_mouse_grabber();
QWidget* q_tablewidget_keyboard_grabber();
bool q_tablewidget_updates_enabled(void* self);
void q_tablewidget_set_updates_enabled(void* self, bool enable);
QGraphicsProxyWidget* q_tablewidget_graphics_proxy_widget(void* self);
void q_tablewidget_repaint(void* self);
void q_tablewidget_update2(void* self, int x, int y, int w, int h);
void q_tablewidget_update_with_q_rect(void* self, void* param1);
void q_tablewidget_update_with_q_region(void* self, void* param1);
void q_tablewidget_repaint2(void* self, int x, int y, int w, int h);
void q_tablewidget_repaint_with_q_rect(void* self, void* param1);
void q_tablewidget_repaint_with_q_region(void* self, void* param1);
void q_tablewidget_set_hidden(void* self, bool hidden);
void q_tablewidget_show(void* self);
void q_tablewidget_hide(void* self);
void q_tablewidget_show_minimized(void* self);
void q_tablewidget_show_maximized(void* self);
void q_tablewidget_show_full_screen(void* self);
void q_tablewidget_show_normal(void* self);
bool q_tablewidget_close(void* self);
void q_tablewidget_raise(void* self);
void q_tablewidget_lower(void* self);
void q_tablewidget_stack_under(void* self, void* param1);
void q_tablewidget_move(void* self, int x, int y);
void q_tablewidget_move_with_q_point(void* self, void* param1);
void q_tablewidget_resize(void* self, int w, int h);
void q_tablewidget_resize_with_q_size(void* self, void* param1);
void q_tablewidget_set_geometry(void* self, int x, int y, int w, int h);
void q_tablewidget_set_geometry_with_geometry(void* self, void* geometry);
char* q_tablewidget_save_geometry(void* self);
bool q_tablewidget_restore_geometry(void* self, const char* geometry);
void q_tablewidget_adjust_size(void* self);
bool q_tablewidget_is_visible(void* self);
bool q_tablewidget_is_visible_to(void* self, void* param1);
bool q_tablewidget_is_hidden(void* self);
bool q_tablewidget_is_minimized(void* self);
bool q_tablewidget_is_maximized(void* self);
bool q_tablewidget_is_full_screen(void* self);
int64_t q_tablewidget_window_state(void* self);
void q_tablewidget_set_window_state(void* self, int64_t state);
void q_tablewidget_override_window_state(void* self, int64_t state);
QSizePolicy* q_tablewidget_size_policy(void* self);
void q_tablewidget_set_size_policy(void* self, void* sizePolicy);
void q_tablewidget_set_size_policy2(void* self, int64_t horizontal, int64_t vertical);
QRegion* q_tablewidget_visible_region(void* self);
void q_tablewidget_set_contents_margins(void* self, int left, int top, int right, int bottom);
void q_tablewidget_set_contents_margins_with_margins(void* self, void* margins);
QMargins* q_tablewidget_contents_margins(void* self);
QRect* q_tablewidget_contents_rect(void* self);
QLayout* q_tablewidget_layout(void* self);
void q_tablewidget_set_layout(void* self, void* layout);
void q_tablewidget_update_geometry(void* self);
void q_tablewidget_set_parent(void* self, void* parent);
void q_tablewidget_set_parent2(void* self, void* parent, int64_t f);
void q_tablewidget_scroll(void* self, int dx, int dy);
void q_tablewidget_scroll2(void* self, int dx, int dy, void* param3);
QWidget* q_tablewidget_focus_widget(void* self);
QWidget* q_tablewidget_next_in_focus_chain(void* self);
QWidget* q_tablewidget_previous_in_focus_chain(void* self);
bool q_tablewidget_accept_drops(void* self);
void q_tablewidget_set_accept_drops(void* self, bool on);
void q_tablewidget_add_action(void* self, void* action);
void q_tablewidget_add_actions(void* self, void* actions[]);
void q_tablewidget_insert_actions(void* self, void* before, void* actions[]);
void q_tablewidget_insert_action(void* self, void* before, void* action);
void q_tablewidget_remove_action(void* self, void* action);
libqt_list /* of QAction* */ q_tablewidget_actions(void* self);
QAction* q_tablewidget_add_action_with_text(void* self, const char* text);
QAction* q_tablewidget_add_action2(void* self, void* icon, const char* text);
QAction* q_tablewidget_add_action3(void* self, const char* text, void* shortcut);
QAction* q_tablewidget_add_action4(void* self, void* icon, const char* text, void* shortcut);
QWidget* q_tablewidget_parent_widget(void* self);
void q_tablewidget_set_window_flags(void* self, int64_t typeVal);
int64_t q_tablewidget_window_flags(void* self);
void q_tablewidget_set_window_flag(void* self, int64_t param1);
void q_tablewidget_override_window_flags(void* self, int64_t typeVal);
int64_t q_tablewidget_window_type(void* self);
QWidget* q_tablewidget_find(uint64_t param1);
QWidget* q_tablewidget_child_at(void* self, int x, int y);
QWidget* q_tablewidget_child_at_with_q_point(void* self, void* p);
void q_tablewidget_set_attribute(void* self, int64_t param1);
bool q_tablewidget_test_attribute(void* self, int64_t param1);
void q_tablewidget_ensure_polished(void* self);
bool q_tablewidget_is_ancestor_of(void* self, void* child);
bool q_tablewidget_auto_fill_background(void* self);
void q_tablewidget_set_auto_fill_background(void* self, bool enabled);
QBackingStore* q_tablewidget_backing_store(void* self);
QWindow* q_tablewidget_window_handle(void* self);
QScreen* q_tablewidget_screen(void* self);
void q_tablewidget_set_screen(void* self, void* screen);
QWidget* q_tablewidget_create_window_container(void* window);
void q_tablewidget_window_title_changed(void* self, const char* title);
void q_tablewidget_on_window_title_changed(void* self, void (*slot)(void*, const char*));
void q_tablewidget_window_icon_changed(void* self, void* icon);
void q_tablewidget_on_window_icon_changed(void* self, void (*slot)(void*, void*));
void q_tablewidget_window_icon_text_changed(void* self, const char* iconText);
void q_tablewidget_on_window_icon_text_changed(void* self, void (*slot)(void*, const char*));
void q_tablewidget_custom_context_menu_requested(void* self, void* pos);
void q_tablewidget_on_custom_context_menu_requested(void* self, void (*slot)(void*, void*));
int64_t q_tablewidget_input_method_hints(void* self);
void q_tablewidget_set_input_method_hints(void* self, int64_t hints);
void q_tablewidget_render2(void* self, void* target, void* targetOffset);
void q_tablewidget_render3(void* self, void* target, void* targetOffset, void* sourceRegion);
void q_tablewidget_render4(void* self, void* target, void* targetOffset, void* sourceRegion, int64_t renderFlags);
void q_tablewidget_render22(void* self, void* painter, void* targetOffset);
void q_tablewidget_render32(void* self, void* painter, void* targetOffset, void* sourceRegion);
void q_tablewidget_render42(void* self, void* painter, void* targetOffset, void* sourceRegion, int64_t renderFlags);
QPixmap* q_tablewidget_grab1(void* self, void* rectangle);
void q_tablewidget_grab_gesture2(void* self, int64_t typeVal, int64_t flags);
int32_t q_tablewidget_grab_shortcut2(void* self, void* key, int64_t context);
void q_tablewidget_set_shortcut_enabled2(void* self, int id, bool enable);
void q_tablewidget_set_shortcut_auto_repeat2(void* self, int id, bool enable);
void q_tablewidget_set_window_flag2(void* self, int64_t param1, bool on);
void q_tablewidget_set_attribute2(void* self, int64_t param1, bool on);
QWidget* q_tablewidget_create_window_container2(void* window, void* parent);
QWidget* q_tablewidget_create_window_container3(void* window, void* parent, int64_t flags);
const char* q_tablewidget_object_name(void* self);
void q_tablewidget_set_object_name(void* self, const char* name);
bool q_tablewidget_is_widget_type(void* self);
bool q_tablewidget_is_window_type(void* self);
bool q_tablewidget_is_quick_item_type(void* self);
bool q_tablewidget_signals_blocked(void* self);
bool q_tablewidget_block_signals(void* self, bool b);
QThread* q_tablewidget_thread(void* self);
void q_tablewidget_move_to_thread(void* self, void* thread);
int32_t q_tablewidget_start_timer(void* self, int interval);
void q_tablewidget_kill_timer(void* self, int id);
libqt_list /* of QObject* */ q_tablewidget_children(void* self);
void q_tablewidget_install_event_filter(void* self, void* filterObj);
void q_tablewidget_remove_event_filter(void* self, void* obj);
QMetaObject__Connection* q_tablewidget_connect(void* sender, void* signal, void* receiver, void* method);
QMetaObject__Connection* q_tablewidget_connect2(void* self, void* sender, const char* signal, const char* member);
bool q_tablewidget_disconnect(void* sender, void* signal, void* receiver, void* member);
bool q_tablewidget_disconnect_with_q_meta_object_connection(void* param1);
void q_tablewidget_dump_object_tree(void* self);
void q_tablewidget_dump_object_info(void* self);
bool q_tablewidget_set_property(void* self, const char* name, void* value);
QVariant* q_tablewidget_property(void* self, const char* name);
const char** q_tablewidget_dynamic_property_names(void* self);
QBindingStorage* q_tablewidget_binding_storage(void* self);
QBindingStorage* q_tablewidget_binding_storage2(void* self);
void q_tablewidget_destroyed(void* self);
void q_tablewidget_on_destroyed(void* self, void (*slot)(void*));
QObject* q_tablewidget_parent(void* self);
bool q_tablewidget_inherits(void* self, const char* classname);
void q_tablewidget_delete_later(void* self);
int32_t q_tablewidget_start_timer2(void* self, int interval, int64_t timerType);
QMetaObject__Connection* q_tablewidget_connect5(void* sender, void* signal, void* receiver, void* method, int64_t typeVal);
QMetaObject__Connection* q_tablewidget_connect4(void* self, void* sender, const char* signal, const char* member, int64_t typeVal);
void q_tablewidget_destroyed1(void* self, void* param1);
void q_tablewidget_on_destroyed1(void* self, void (*slot)(void*, void*));
bool q_tablewidget_painting_active(void* self);
int32_t q_tablewidget_width_m_m(void* self);
int32_t q_tablewidget_height_m_m(void* self);
int32_t q_tablewidget_logical_dpi_x(void* self);
int32_t q_tablewidget_logical_dpi_y(void* self);
int32_t q_tablewidget_physical_dpi_x(void* self);
int32_t q_tablewidget_physical_dpi_y(void* self);
double q_tablewidget_device_pixel_ratio(void* self);
double q_tablewidget_device_pixel_ratio_f(void* self);
int32_t q_tablewidget_color_count(void* self);
int32_t q_tablewidget_depth(void* self);
double q_tablewidget_device_pixel_ratio_f_scale();
void q_tablewidget_set_root_index(void* self, void* index);
void q_tablewidget_qbase_set_root_index(void* self, void* index);
void q_tablewidget_on_set_root_index(void* self, void (*slot)(void*, void*));
void q_tablewidget_set_selection_model(void* self, void* selectionModel);
void q_tablewidget_qbase_set_selection_model(void* self, void* selectionModel);
void q_tablewidget_on_set_selection_model(void* self, void (*slot)(void*, void*));
void q_tablewidget_do_items_layout(void* self);
void q_tablewidget_qbase_do_items_layout(void* self);
void q_tablewidget_on_do_items_layout(void* self, void (*slot)());
QRect* q_tablewidget_visual_rect(void* self, void* index);
QRect* q_tablewidget_qbase_visual_rect(void* self, void* index);
void q_tablewidget_on_visual_rect(void* self, QRect* (*slot)(void*, void*));
void q_tablewidget_scroll_to(void* self, void* index, int64_t hint);
void q_tablewidget_qbase_scroll_to(void* self, void* index, int64_t hint);
void q_tablewidget_on_scroll_to(void* self, void (*slot)(void*, void*, int64_t));
QModelIndex* q_tablewidget_index_at(void* self, void* p);
QModelIndex* q_tablewidget_qbase_index_at(void* self, void* p);
void q_tablewidget_on_index_at(void* self, QModelIndex* (*slot)(void*, void*));
void q_tablewidget_scroll_contents_by(void* self, int dx, int dy);
void q_tablewidget_qbase_scroll_contents_by(void* self, int dx, int dy);
void q_tablewidget_on_scroll_contents_by(void* self, void (*slot)(void*, int, int));
void q_tablewidget_init_view_item_option(void* self, void* option);
void q_tablewidget_qbase_init_view_item_option(void* self, void* option);
void q_tablewidget_on_init_view_item_option(void* self, void (*slot)(void*, void*));
void q_tablewidget_paint_event(void* self, void* e);
void q_tablewidget_qbase_paint_event(void* self, void* e);
void q_tablewidget_on_paint_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_timer_event(void* self, void* event);
void q_tablewidget_qbase_timer_event(void* self, void* event);
void q_tablewidget_on_timer_event(void* self, void (*slot)(void*, void*));
int32_t q_tablewidget_horizontal_offset(void* self);
int32_t q_tablewidget_qbase_horizontal_offset(void* self);
void q_tablewidget_on_horizontal_offset(void* self, int32_t (*slot)());
int32_t q_tablewidget_vertical_offset(void* self);
int32_t q_tablewidget_qbase_vertical_offset(void* self);
void q_tablewidget_on_vertical_offset(void* self, int32_t (*slot)());
QModelIndex* q_tablewidget_move_cursor(void* self, int64_t cursorAction, int64_t modifiers);
QModelIndex* q_tablewidget_qbase_move_cursor(void* self, int64_t cursorAction, int64_t modifiers);
void q_tablewidget_on_move_cursor(void* self, QModelIndex* (*slot)(void*, int64_t, int64_t));
void q_tablewidget_set_selection(void* self, void* rect, int64_t command);
void q_tablewidget_qbase_set_selection(void* self, void* rect, int64_t command);
void q_tablewidget_on_set_selection(void* self, void (*slot)(void*, void*, int64_t));
QRegion* q_tablewidget_visual_region_for_selection(void* self, void* selection);
QRegion* q_tablewidget_qbase_visual_region_for_selection(void* self, void* selection);
void q_tablewidget_on_visual_region_for_selection(void* self, QRegion* (*slot)(void*, void*));
libqt_list /* of QModelIndex* */ q_tablewidget_selected_indexes(void* self);
libqt_list /* of QModelIndex* */ q_tablewidget_qbase_selected_indexes(void* self);
void q_tablewidget_on_selected_indexes(void* self, libqt_list /* of QModelIndex* */ (*slot)());
void q_tablewidget_update_geometries(void* self);
void q_tablewidget_qbase_update_geometries(void* self);
void q_tablewidget_on_update_geometries(void* self, void (*slot)());
QSize* q_tablewidget_viewport_size_hint(void* self);
QSize* q_tablewidget_qbase_viewport_size_hint(void* self);
void q_tablewidget_on_viewport_size_hint(void* self, QSize* (*slot)());
int32_t q_tablewidget_size_hint_for_row(void* self, int row);
int32_t q_tablewidget_qbase_size_hint_for_row(void* self, int row);
void q_tablewidget_on_size_hint_for_row(void* self, int32_t (*slot)(void*, int));
int32_t q_tablewidget_size_hint_for_column(void* self, int column);
int32_t q_tablewidget_qbase_size_hint_for_column(void* self, int column);
void q_tablewidget_on_size_hint_for_column(void* self, int32_t (*slot)(void*, int));
void q_tablewidget_vertical_scrollbar_action(void* self, int action);
void q_tablewidget_qbase_vertical_scrollbar_action(void* self, int action);
void q_tablewidget_on_vertical_scrollbar_action(void* self, void (*slot)(void*, int));
void q_tablewidget_horizontal_scrollbar_action(void* self, int action);
void q_tablewidget_qbase_horizontal_scrollbar_action(void* self, int action);
void q_tablewidget_on_horizontal_scrollbar_action(void* self, void (*slot)(void*, int));
bool q_tablewidget_is_index_hidden(void* self, void* index);
bool q_tablewidget_qbase_is_index_hidden(void* self, void* index);
void q_tablewidget_on_is_index_hidden(void* self, bool (*slot)(void*, void*));
void q_tablewidget_selection_changed(void* self, void* selected, void* deselected);
void q_tablewidget_qbase_selection_changed(void* self, void* selected, void* deselected);
void q_tablewidget_on_selection_changed(void* self, void (*slot)(void*, void*, void*));
void q_tablewidget_current_changed(void* self, void* current, void* previous);
void q_tablewidget_qbase_current_changed(void* self, void* current, void* previous);
void q_tablewidget_on_current_changed(void* self, void (*slot)(void*, void*, void*));
void q_tablewidget_keyboard_search(void* self, const char* search);
void q_tablewidget_qbase_keyboard_search(void* self, const char* search);
void q_tablewidget_on_keyboard_search(void* self, void (*slot)(void*, const char*));
QAbstractItemDelegate* q_tablewidget_item_delegate_for_index(void* self, void* index);
QAbstractItemDelegate* q_tablewidget_qbase_item_delegate_for_index(void* self, void* index);
void q_tablewidget_on_item_delegate_for_index(void* self, QAbstractItemDelegate* (*slot)(void*, void*));
QVariant* q_tablewidget_input_method_query(void* self, int64_t query);
QVariant* q_tablewidget_qbase_input_method_query(void* self, int64_t query);
void q_tablewidget_on_input_method_query(void* self, QVariant* (*slot)(void*, int64_t));
void q_tablewidget_reset(void* self);
void q_tablewidget_qbase_reset(void* self);
void q_tablewidget_on_reset(void* self, void (*slot)());
void q_tablewidget_select_all(void* self);
void q_tablewidget_qbase_select_all(void* self);
void q_tablewidget_on_select_all(void* self, void (*slot)());
void q_tablewidget_data_changed(void* self, void* topLeft, void* bottomRight, int* roles[]);
void q_tablewidget_qbase_data_changed(void* self, void* topLeft, void* bottomRight, int* roles[]);
void q_tablewidget_on_data_changed(void* self, void (*slot)(void*, void*, void*, int*));
void q_tablewidget_rows_inserted(void* self, void* parent, int start, int end);
void q_tablewidget_qbase_rows_inserted(void* self, void* parent, int start, int end);
void q_tablewidget_on_rows_inserted(void* self, void (*slot)(void*, void*, int, int));
void q_tablewidget_rows_about_to_be_removed(void* self, void* parent, int start, int end);
void q_tablewidget_qbase_rows_about_to_be_removed(void* self, void* parent, int start, int end);
void q_tablewidget_on_rows_about_to_be_removed(void* self, void (*slot)(void*, void*, int, int));
void q_tablewidget_update_editor_data(void* self);
void q_tablewidget_qbase_update_editor_data(void* self);
void q_tablewidget_on_update_editor_data(void* self, void (*slot)());
void q_tablewidget_update_editor_geometries(void* self);
void q_tablewidget_qbase_update_editor_geometries(void* self);
void q_tablewidget_on_update_editor_geometries(void* self, void (*slot)());
void q_tablewidget_vertical_scrollbar_value_changed(void* self, int value);
void q_tablewidget_qbase_vertical_scrollbar_value_changed(void* self, int value);
void q_tablewidget_on_vertical_scrollbar_value_changed(void* self, void (*slot)(void*, int));
void q_tablewidget_horizontal_scrollbar_value_changed(void* self, int value);
void q_tablewidget_qbase_horizontal_scrollbar_value_changed(void* self, int value);
void q_tablewidget_on_horizontal_scrollbar_value_changed(void* self, void (*slot)(void*, int));
void q_tablewidget_close_editor(void* self, void* editor, int64_t hint);
void q_tablewidget_qbase_close_editor(void* self, void* editor, int64_t hint);
void q_tablewidget_on_close_editor(void* self, void (*slot)(void*, void*, int64_t));
void q_tablewidget_commit_data(void* self, void* editor);
void q_tablewidget_qbase_commit_data(void* self, void* editor);
void q_tablewidget_on_commit_data(void* self, void (*slot)(void*, void*));
void q_tablewidget_editor_destroyed(void* self, void* editor);
void q_tablewidget_qbase_editor_destroyed(void* self, void* editor);
void q_tablewidget_on_editor_destroyed(void* self, void (*slot)(void*, void*));
bool q_tablewidget_edit2(void* self, void* index, int64_t trigger, void* event);
bool q_tablewidget_qbase_edit2(void* self, void* index, int64_t trigger, void* event);
void q_tablewidget_on_edit2(void* self, bool (*slot)(void*, void*, int64_t, void*));
int64_t q_tablewidget_selection_command(void* self, void* index, void* event);
int64_t q_tablewidget_qbase_selection_command(void* self, void* index, void* event);
void q_tablewidget_on_selection_command(void* self, int64_t (*slot)(void*, void*, void*));
void q_tablewidget_start_drag(void* self, int64_t supportedActions);
void q_tablewidget_qbase_start_drag(void* self, int64_t supportedActions);
void q_tablewidget_on_start_drag(void* self, void (*slot)(void*, int64_t));
bool q_tablewidget_focus_next_prev_child(void* self, bool next);
bool q_tablewidget_qbase_focus_next_prev_child(void* self, bool next);
void q_tablewidget_on_focus_next_prev_child(void* self, bool (*slot)(void*, bool));
bool q_tablewidget_viewport_event(void* self, void* event);
bool q_tablewidget_qbase_viewport_event(void* self, void* event);
void q_tablewidget_on_viewport_event(void* self, bool (*slot)(void*, void*));
void q_tablewidget_mouse_press_event(void* self, void* event);
void q_tablewidget_qbase_mouse_press_event(void* self, void* event);
void q_tablewidget_on_mouse_press_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_mouse_move_event(void* self, void* event);
void q_tablewidget_qbase_mouse_move_event(void* self, void* event);
void q_tablewidget_on_mouse_move_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_mouse_release_event(void* self, void* event);
void q_tablewidget_qbase_mouse_release_event(void* self, void* event);
void q_tablewidget_on_mouse_release_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_mouse_double_click_event(void* self, void* event);
void q_tablewidget_qbase_mouse_double_click_event(void* self, void* event);
void q_tablewidget_on_mouse_double_click_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_drag_enter_event(void* self, void* event);
void q_tablewidget_qbase_drag_enter_event(void* self, void* event);
void q_tablewidget_on_drag_enter_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_drag_move_event(void* self, void* event);
void q_tablewidget_qbase_drag_move_event(void* self, void* event);
void q_tablewidget_on_drag_move_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_drag_leave_event(void* self, void* event);
void q_tablewidget_qbase_drag_leave_event(void* self, void* event);
void q_tablewidget_on_drag_leave_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_focus_in_event(void* self, void* event);
void q_tablewidget_qbase_focus_in_event(void* self, void* event);
void q_tablewidget_on_focus_in_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_focus_out_event(void* self, void* event);
void q_tablewidget_qbase_focus_out_event(void* self, void* event);
void q_tablewidget_on_focus_out_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_key_press_event(void* self, void* event);
void q_tablewidget_qbase_key_press_event(void* self, void* event);
void q_tablewidget_on_key_press_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_resize_event(void* self, void* event);
void q_tablewidget_qbase_resize_event(void* self, void* event);
void q_tablewidget_on_resize_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_input_method_event(void* self, void* event);
void q_tablewidget_qbase_input_method_event(void* self, void* event);
void q_tablewidget_on_input_method_event(void* self, void (*slot)(void*, void*));
bool q_tablewidget_event_filter(void* self, void* object, void* event);
bool q_tablewidget_qbase_event_filter(void* self, void* object, void* event);
void q_tablewidget_on_event_filter(void* self, bool (*slot)(void*, void*, void*));
QSize* q_tablewidget_minimum_size_hint(void* self);
QSize* q_tablewidget_qbase_minimum_size_hint(void* self);
void q_tablewidget_on_minimum_size_hint(void* self, QSize* (*slot)());
QSize* q_tablewidget_size_hint(void* self);
QSize* q_tablewidget_qbase_size_hint(void* self);
void q_tablewidget_on_size_hint(void* self, QSize* (*slot)());
void q_tablewidget_setup_viewport(void* self, void* viewport);
void q_tablewidget_qbase_setup_viewport(void* self, void* viewport);
void q_tablewidget_on_setup_viewport(void* self, void (*slot)(void*, void*));
void q_tablewidget_wheel_event(void* self, void* param1);
void q_tablewidget_qbase_wheel_event(void* self, void* param1);
void q_tablewidget_on_wheel_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_context_menu_event(void* self, void* param1);
void q_tablewidget_qbase_context_menu_event(void* self, void* param1);
void q_tablewidget_on_context_menu_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_change_event(void* self, void* param1);
void q_tablewidget_qbase_change_event(void* self, void* param1);
void q_tablewidget_on_change_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_init_style_option(void* self, void* option);
void q_tablewidget_qbase_init_style_option(void* self, void* option);
void q_tablewidget_on_init_style_option(void* self, void (*slot)(void*, void*));
int32_t q_tablewidget_dev_type(void* self);
int32_t q_tablewidget_qbase_dev_type(void* self);
void q_tablewidget_on_dev_type(void* self, int32_t (*slot)());
void q_tablewidget_set_visible(void* self, bool visible);
void q_tablewidget_qbase_set_visible(void* self, bool visible);
void q_tablewidget_on_set_visible(void* self, void (*slot)(void*, bool));
int32_t q_tablewidget_height_for_width(void* self, int param1);
int32_t q_tablewidget_qbase_height_for_width(void* self, int param1);
void q_tablewidget_on_height_for_width(void* self, int32_t (*slot)(void*, int));
bool q_tablewidget_has_height_for_width(void* self);
bool q_tablewidget_qbase_has_height_for_width(void* self);
void q_tablewidget_on_has_height_for_width(void* self, bool (*slot)());
QPaintEngine* q_tablewidget_paint_engine(void* self);
QPaintEngine* q_tablewidget_qbase_paint_engine(void* self);
void q_tablewidget_on_paint_engine(void* self, QPaintEngine* (*slot)());
void q_tablewidget_key_release_event(void* self, void* event);
void q_tablewidget_qbase_key_release_event(void* self, void* event);
void q_tablewidget_on_key_release_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_enter_event(void* self, void* event);
void q_tablewidget_qbase_enter_event(void* self, void* event);
void q_tablewidget_on_enter_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_leave_event(void* self, void* event);
void q_tablewidget_qbase_leave_event(void* self, void* event);
void q_tablewidget_on_leave_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_move_event(void* self, void* event);
void q_tablewidget_qbase_move_event(void* self, void* event);
void q_tablewidget_on_move_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_close_event(void* self, void* event);
void q_tablewidget_qbase_close_event(void* self, void* event);
void q_tablewidget_on_close_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_tablet_event(void* self, void* event);
void q_tablewidget_qbase_tablet_event(void* self, void* event);
void q_tablewidget_on_tablet_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_action_event(void* self, void* event);
void q_tablewidget_qbase_action_event(void* self, void* event);
void q_tablewidget_on_action_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_show_event(void* self, void* event);
void q_tablewidget_qbase_show_event(void* self, void* event);
void q_tablewidget_on_show_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_hide_event(void* self, void* event);
void q_tablewidget_qbase_hide_event(void* self, void* event);
void q_tablewidget_on_hide_event(void* self, void (*slot)(void*, void*));
bool q_tablewidget_native_event(void* self, const char* eventType, void* message, intptr_t* result);
bool q_tablewidget_qbase_native_event(void* self, const char* eventType, void* message, intptr_t* result);
void q_tablewidget_on_native_event(void* self, bool (*slot)(void*, const char*, void*, intptr_t*));
int32_t q_tablewidget_metric(void* self, int64_t param1);
int32_t q_tablewidget_qbase_metric(void* self, int64_t param1);
void q_tablewidget_on_metric(void* self, int32_t (*slot)(void*, int64_t));
void q_tablewidget_init_painter(void* self, void* painter);
void q_tablewidget_qbase_init_painter(void* self, void* painter);
void q_tablewidget_on_init_painter(void* self, void (*slot)(void*, void*));
QPaintDevice* q_tablewidget_redirected(void* self, void* offset);
QPaintDevice* q_tablewidget_qbase_redirected(void* self, void* offset);
void q_tablewidget_on_redirected(void* self, QPaintDevice* (*slot)(void*, void*));
QPainter* q_tablewidget_shared_painter(void* self);
QPainter* q_tablewidget_qbase_shared_painter(void* self);
void q_tablewidget_on_shared_painter(void* self, QPainter* (*slot)());
void q_tablewidget_child_event(void* self, void* event);
void q_tablewidget_qbase_child_event(void* self, void* event);
void q_tablewidget_on_child_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_custom_event(void* self, void* event);
void q_tablewidget_qbase_custom_event(void* self, void* event);
void q_tablewidget_on_custom_event(void* self, void (*slot)(void*, void*));
void q_tablewidget_connect_notify(void* self, void* signal);
void q_tablewidget_qbase_connect_notify(void* self, void* signal);
void q_tablewidget_on_connect_notify(void* self, void (*slot)(void*, void*));
void q_tablewidget_disconnect_notify(void* self, void* signal);
void q_tablewidget_qbase_disconnect_notify(void* self, void* signal);
void q_tablewidget_on_disconnect_notify(void* self, void (*slot)(void*, void*));
void q_tablewidget_row_moved(void* self, int row, int oldIndex, int newIndex);
void q_tablewidget_qbase_row_moved(void* self, int row, int oldIndex, int newIndex);
void q_tablewidget_on_row_moved(void* self, void (*slot)(void*, int, int, int));
void q_tablewidget_column_moved(void* self, int column, int oldIndex, int newIndex);
void q_tablewidget_qbase_column_moved(void* self, int column, int oldIndex, int newIndex);
void q_tablewidget_on_column_moved(void* self, void (*slot)(void*, int, int, int));
void q_tablewidget_row_resized(void* self, int row, int oldHeight, int newHeight);
void q_tablewidget_qbase_row_resized(void* self, int row, int oldHeight, int newHeight);
void q_tablewidget_on_row_resized(void* self, void (*slot)(void*, int, int, int));
void q_tablewidget_column_resized(void* self, int column, int oldWidth, int newWidth);
void q_tablewidget_qbase_column_resized(void* self, int column, int oldWidth, int newWidth);
void q_tablewidget_on_column_resized(void* self, void (*slot)(void*, int, int, int));
void q_tablewidget_row_count_changed(void* self, int oldCount, int newCount);
void q_tablewidget_qbase_row_count_changed(void* self, int oldCount, int newCount);
void q_tablewidget_on_row_count_changed(void* self, void (*slot)(void*, int, int));
void q_tablewidget_column_count_changed(void* self, int oldCount, int newCount);
void q_tablewidget_qbase_column_count_changed(void* self, int oldCount, int newCount);
void q_tablewidget_on_column_count_changed(void* self, void (*slot)(void*, int, int));
int64_t q_tablewidget_state(void* self);
int64_t q_tablewidget_qbase_state(void* self);
void q_tablewidget_on_state(void* self, int64_t (*slot)());
void q_tablewidget_set_state(void* self, int64_t state);
void q_tablewidget_qbase_set_state(void* self, int64_t state);
void q_tablewidget_on_set_state(void* self, void (*slot)(void*, int64_t));
void q_tablewidget_schedule_delayed_items_layout(void* self);
void q_tablewidget_qbase_schedule_delayed_items_layout(void* self);
void q_tablewidget_on_schedule_delayed_items_layout(void* self, void (*slot)());
void q_tablewidget_execute_delayed_items_layout(void* self);
void q_tablewidget_qbase_execute_delayed_items_layout(void* self);
void q_tablewidget_on_execute_delayed_items_layout(void* self, void (*slot)());
void q_tablewidget_set_dirty_region(void* self, void* region);
void q_tablewidget_qbase_set_dirty_region(void* self, void* region);
void q_tablewidget_on_set_dirty_region(void* self, void (*slot)(void*, void*));
void q_tablewidget_scroll_dirty_region(void* self, int dx, int dy);
void q_tablewidget_qbase_scroll_dirty_region(void* self, int dx, int dy);
void q_tablewidget_on_scroll_dirty_region(void* self, void (*slot)(void*, int, int));
QPoint* q_tablewidget_dirty_region_offset(void* self);
QPoint* q_tablewidget_qbase_dirty_region_offset(void* self);
void q_tablewidget_on_dirty_region_offset(void* self, QPoint* (*slot)());
void q_tablewidget_start_auto_scroll(void* self);
void q_tablewidget_qbase_start_auto_scroll(void* self);
void q_tablewidget_on_start_auto_scroll(void* self, void (*slot)());
void q_tablewidget_stop_auto_scroll(void* self);
void q_tablewidget_qbase_stop_auto_scroll(void* self);
void q_tablewidget_on_stop_auto_scroll(void* self, void (*slot)());
void q_tablewidget_do_auto_scroll(void* self);
void q_tablewidget_qbase_do_auto_scroll(void* self);
void q_tablewidget_on_do_auto_scroll(void* self, void (*slot)());
int64_t q_tablewidget_drop_indicator_position(void* self);
int64_t q_tablewidget_qbase_drop_indicator_position(void* self);
void q_tablewidget_on_drop_indicator_position(void* self, int64_t (*slot)());
void q_tablewidget_set_viewport_margins(void* self, int left, int top, int right, int bottom);
void q_tablewidget_qbase_set_viewport_margins(void* self, int left, int top, int right, int bottom);
void q_tablewidget_on_set_viewport_margins(void* self, void (*slot)(void*, int, int, int, int));
QMargins* q_tablewidget_viewport_margins(void* self);
QMargins* q_tablewidget_qbase_viewport_margins(void* self);
void q_tablewidget_on_viewport_margins(void* self, QMargins* (*slot)());
void q_tablewidget_draw_frame(void* self, void* param1);
void q_tablewidget_qbase_draw_frame(void* self, void* param1);
void q_tablewidget_on_draw_frame(void* self, void (*slot)(void*, void*));
void q_tablewidget_update_micro_focus(void* self);
void q_tablewidget_qbase_update_micro_focus(void* self);
void q_tablewidget_on_update_micro_focus(void* self, void (*slot)());
void q_tablewidget_create(void* self);
void q_tablewidget_qbase_create(void* self);
void q_tablewidget_on_create(void* self, void (*slot)());
void q_tablewidget_destroy(void* self);
void q_tablewidget_qbase_destroy(void* self);
void q_tablewidget_on_destroy(void* self, void (*slot)());
bool q_tablewidget_focus_next_child(void* self);
bool q_tablewidget_qbase_focus_next_child(void* self);
void q_tablewidget_on_focus_next_child(void* self, bool (*slot)());
bool q_tablewidget_focus_previous_child(void* self);
bool q_tablewidget_qbase_focus_previous_child(void* self);
void q_tablewidget_on_focus_previous_child(void* self, bool (*slot)());
QObject* q_tablewidget_sender(void* self);
QObject* q_tablewidget_qbase_sender(void* self);
void q_tablewidget_on_sender(void* self, QObject* (*slot)());
int32_t q_tablewidget_sender_signal_index(void* self);
int32_t q_tablewidget_qbase_sender_signal_index(void* self);
void q_tablewidget_on_sender_signal_index(void* self, int32_t (*slot)());
int32_t q_tablewidget_receivers(void* self, const char* signal);
int32_t q_tablewidget_qbase_receivers(void* self, const char* signal);
void q_tablewidget_on_receivers(void* self, int32_t (*slot)(void*, const char*));
bool q_tablewidget_is_signal_connected(void* self, void* signal);
bool q_tablewidget_qbase_is_signal_connected(void* self, void* signal);
void q_tablewidget_on_is_signal_connected(void* self, bool (*slot)(void*, void*));
void q_tablewidget_delete(void* self);

/// https://doc.qt.io/qt-6/qtablewidget.html#types

typedef enum {
    QTABLEWIDGETITEM_ITEMTYPE_TYPE = 0,
    QTABLEWIDGETITEM_ITEMTYPE_USERTYPE = 1000
} QTableWidgetItem__ItemType;

#endif
