#pragma once
#ifndef SRCQT6C_LIBQLABEL_H
#define SRCQT6C_LIBQLABEL_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "libqttypedefs.h"

#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#include "qtlibc.h"

#include "libqaction.h"
#include "libqevent.h"
#include "libqanystringview.h"
#include "libqbackingstore.h"
#include "libqbindingstorage.h"
#include "libqbitmap.h"
#include "libqcursor.h"
#include "libqfont.h"
#include "libqfontinfo.h"
#include "libqfontmetrics.h"
#include "libqframe.h"
#include "libqgraphicseffect.h"
#include "libqgraphicsproxywidget.h"
#include "libqicon.h"
#include "libqkeysequence.h"
#include "libqlayout.h"
#include "libqlocale.h"
#include "libqmargins.h"
#include "libqmetaobject.h"
#include "libqmovie.h"
#include "libqobject.h"
#include "libqpaintdevice.h"
#include "libqpaintengine.h"
#include "libqpainter.h"
#include "libqpalette.h"
#include "libqpicture.h"
#include "libqpixmap.h"
#include "libqpoint.h"
#include "libqrect.h"
#include "libqregion.h"
#include "libqscreen.h"
#include "libqsize.h"
#include "libqsizepolicy.h"
#include <string.h>
#include "libqstyle.h"
#include "libqstyleoption.h"
#include "libqthread.h"
#include "libqvariant.h"
#include "libqwidget.h"
#include "libqwindow.h"

QLabel* q_label_new(void* parent);
QLabel* q_label_new2();
QLabel* q_label_new3(const char* text);
QLabel* q_label_new4(void* parent, int64_t f);
QLabel* q_label_new5(const char* text, void* parent);
QLabel* q_label_new6(const char* text, void* parent, int64_t f);
QMetaObject* q_label_meta_object(void* self);
void* q_label_metacast(void* self, const char* param1);
int32_t q_label_metacall(void* self, int64_t param1, int param2, void* param3);
void q_label_on_metacall(void* self, int32_t (*slot)(void*, int64_t, int, void*));
int32_t q_label_qbase_metacall(void* self, int64_t param1, int param2, void* param3);
const char* q_label_tr(const char* s);
const char* q_label_text(void* self);
QPixmap* q_label_pixmap(void* self, int64_t param1);
QPixmap* q_label_pixmap2(void* self);
QPicture* q_label_picture(void* self, int64_t param1);
QPicture* q_label_picture2(void* self);
QMovie* q_label_movie(void* self);
int64_t q_label_text_format(void* self);
void q_label_set_text_format(void* self, int64_t textFormat);
int64_t q_label_alignment(void* self);
void q_label_set_alignment(void* self, int64_t alignment);
void q_label_set_word_wrap(void* self, bool on);
bool q_label_word_wrap(void* self);
int32_t q_label_indent(void* self);
void q_label_set_indent(void* self, int indent);
int32_t q_label_margin(void* self);
void q_label_set_margin(void* self, int margin);
bool q_label_has_scaled_contents(void* self);
void q_label_set_scaled_contents(void* self, bool scaledContents);
QSize* q_label_size_hint(void* self);
void q_label_on_size_hint(void* self, QSize* (*slot)());
QSize* q_label_qbase_size_hint(void* self);
QSize* q_label_minimum_size_hint(void* self);
void q_label_on_minimum_size_hint(void* self, QSize* (*slot)());
QSize* q_label_qbase_minimum_size_hint(void* self);
void q_label_set_buddy(void* self, void* buddy);
QWidget* q_label_buddy(void* self);
int32_t q_label_height_for_width(void* self, int param1);
void q_label_on_height_for_width(void* self, int32_t (*slot)(void*, int));
int32_t q_label_qbase_height_for_width(void* self, int param1);
bool q_label_open_external_links(void* self);
void q_label_set_open_external_links(void* self, bool open);
void q_label_set_text_interaction_flags(void* self, int64_t flags);
int64_t q_label_text_interaction_flags(void* self);
void q_label_set_selection(void* self, int param1, int param2);
bool q_label_has_selected_text(void* self);
const char* q_label_selected_text(void* self);
int32_t q_label_selection_start(void* self);
void q_label_set_text(void* self, const char* text);
void q_label_set_pixmap(void* self, void* pixmap);
void q_label_set_picture(void* self, void* picture);
void q_label_set_movie(void* self, void* movie);
void q_label_set_num(void* self, int num);
void q_label_set_num_with_num(void* self, double num);
void q_label_clear(void* self);
void q_label_link_activated(void* self, const char* link);
void q_label_on_link_activated(void* self, void (*slot)(void*, const char*));
void q_label_link_hovered(void* self, const char* link);
void q_label_on_link_hovered(void* self, void (*slot)(void*, const char*));
bool q_label_event(void* self, void* e);
void q_label_on_event(void* self, bool (*slot)(void*, void*));
bool q_label_qbase_event(void* self, void* e);
void q_label_key_press_event(void* self, void* ev);
void q_label_on_key_press_event(void* self, void (*slot)(void*, void*));
void q_label_qbase_key_press_event(void* self, void* ev);
void q_label_paint_event(void* self, void* param1);
void q_label_on_paint_event(void* self, void (*slot)(void*, void*));
void q_label_qbase_paint_event(void* self, void* param1);
void q_label_change_event(void* self, void* param1);
void q_label_on_change_event(void* self, void (*slot)(void*, void*));
void q_label_qbase_change_event(void* self, void* param1);
void q_label_mouse_press_event(void* self, void* ev);
void q_label_on_mouse_press_event(void* self, void (*slot)(void*, void*));
void q_label_qbase_mouse_press_event(void* self, void* ev);
void q_label_mouse_move_event(void* self, void* ev);
void q_label_on_mouse_move_event(void* self, void (*slot)(void*, void*));
void q_label_qbase_mouse_move_event(void* self, void* ev);
void q_label_mouse_release_event(void* self, void* ev);
void q_label_on_mouse_release_event(void* self, void (*slot)(void*, void*));
void q_label_qbase_mouse_release_event(void* self, void* ev);
void q_label_context_menu_event(void* self, void* ev);
void q_label_on_context_menu_event(void* self, void (*slot)(void*, void*));
void q_label_qbase_context_menu_event(void* self, void* ev);
void q_label_focus_in_event(void* self, void* ev);
void q_label_on_focus_in_event(void* self, void (*slot)(void*, void*));
void q_label_qbase_focus_in_event(void* self, void* ev);
void q_label_focus_out_event(void* self, void* ev);
void q_label_on_focus_out_event(void* self, void (*slot)(void*, void*));
void q_label_qbase_focus_out_event(void* self, void* ev);
bool q_label_focus_next_prev_child(void* self, bool next);
void q_label_on_focus_next_prev_child(void* self, bool (*slot)(void*, bool));
bool q_label_qbase_focus_next_prev_child(void* self, bool next);
const char* q_label_tr2(const char* s, const char* c);
const char* q_label_tr3(const char* s, const char* c, int n);
int32_t q_label_frame_style(void* self);
void q_label_set_frame_style(void* self, int frameStyle);
int32_t q_label_frame_width(void* self);
int64_t q_label_frame_shape(void* self);
void q_label_set_frame_shape(void* self, int64_t frameShape);
int64_t q_label_frame_shadow(void* self);
void q_label_set_frame_shadow(void* self, int64_t frameShadow);
int32_t q_label_line_width(void* self);
void q_label_set_line_width(void* self, int lineWidth);
int32_t q_label_mid_line_width(void* self);
void q_label_set_mid_line_width(void* self, int midLineWidth);
QRect* q_label_frame_rect(void* self);
void q_label_set_frame_rect(void* self, void* frameRect);
uintptr_t q_label_win_id(void* self);
void q_label_create_win_id(void* self);
uintptr_t q_label_internal_win_id(void* self);
uintptr_t q_label_effective_win_id(void* self);
QStyle* q_label_style(void* self);
void q_label_set_style(void* self, void* style);
bool q_label_is_top_level(void* self);
bool q_label_is_window(void* self);
bool q_label_is_modal(void* self);
int64_t q_label_window_modality(void* self);
void q_label_set_window_modality(void* self, int64_t windowModality);
bool q_label_is_enabled(void* self);
bool q_label_is_enabled_to(void* self, void* param1);
void q_label_set_enabled(void* self, bool enabled);
void q_label_set_disabled(void* self, bool disabled);
void q_label_set_window_modified(void* self, bool windowModified);
QRect* q_label_frame_geometry(void* self);
QRect* q_label_geometry(void* self);
QRect* q_label_normal_geometry(void* self);
int32_t q_label_x(void* self);
int32_t q_label_y(void* self);
QPoint* q_label_pos(void* self);
QSize* q_label_frame_size(void* self);
QSize* q_label_size(void* self);
int32_t q_label_width(void* self);
int32_t q_label_height(void* self);
QRect* q_label_rect(void* self);
QRect* q_label_children_rect(void* self);
QRegion* q_label_children_region(void* self);
QSize* q_label_minimum_size(void* self);
QSize* q_label_maximum_size(void* self);
int32_t q_label_minimum_width(void* self);
int32_t q_label_minimum_height(void* self);
int32_t q_label_maximum_width(void* self);
int32_t q_label_maximum_height(void* self);
void q_label_set_minimum_size(void* self, void* minimumSize);
void q_label_set_minimum_size2(void* self, int minw, int minh);
void q_label_set_maximum_size(void* self, void* maximumSize);
void q_label_set_maximum_size2(void* self, int maxw, int maxh);
void q_label_set_minimum_width(void* self, int minw);
void q_label_set_minimum_height(void* self, int minh);
void q_label_set_maximum_width(void* self, int maxw);
void q_label_set_maximum_height(void* self, int maxh);
QSize* q_label_size_increment(void* self);
void q_label_set_size_increment(void* self, void* sizeIncrement);
void q_label_set_size_increment2(void* self, int w, int h);
QSize* q_label_base_size(void* self);
void q_label_set_base_size(void* self, void* baseSize);
void q_label_set_base_size2(void* self, int basew, int baseh);
void q_label_set_fixed_size(void* self, void* fixedSize);
void q_label_set_fixed_size2(void* self, int w, int h);
void q_label_set_fixed_width(void* self, int w);
void q_label_set_fixed_height(void* self, int h);
QPointF* q_label_map_to_global(void* self, void* param1);
QPoint* q_label_map_to_global_with_q_point(void* self, void* param1);
QPointF* q_label_map_from_global(void* self, void* param1);
QPoint* q_label_map_from_global_with_q_point(void* self, void* param1);
QPointF* q_label_map_to_parent(void* self, void* param1);
QPoint* q_label_map_to_parent_with_q_point(void* self, void* param1);
QPointF* q_label_map_from_parent(void* self, void* param1);
QPoint* q_label_map_from_parent_with_q_point(void* self, void* param1);
QPointF* q_label_map_to(void* self, void* param1, void* param2);
QPoint* q_label_map_to2(void* self, void* param1, void* param2);
QPointF* q_label_map_from(void* self, void* param1, void* param2);
QPoint* q_label_map_from2(void* self, void* param1, void* param2);
QWidget* q_label_window(void* self);
QWidget* q_label_native_parent_widget(void* self);
QWidget* q_label_top_level_widget(void* self);
QPalette* q_label_palette(void* self);
void q_label_set_palette(void* self, void* palette);
void q_label_set_background_role(void* self, int64_t backgroundRole);
int64_t q_label_background_role(void* self);
void q_label_set_foreground_role(void* self, int64_t foregroundRole);
int64_t q_label_foreground_role(void* self);
QFont* q_label_font(void* self);
void q_label_set_font(void* self, void* font);
QFontMetrics* q_label_font_metrics(void* self);
QFontInfo* q_label_font_info(void* self);
QCursor* q_label_cursor(void* self);
void q_label_set_cursor(void* self, void* cursor);
void q_label_unset_cursor(void* self);
void q_label_set_mouse_tracking(void* self, bool enable);
bool q_label_has_mouse_tracking(void* self);
bool q_label_under_mouse(void* self);
void q_label_set_tablet_tracking(void* self, bool enable);
bool q_label_has_tablet_tracking(void* self);
void q_label_set_mask(void* self, void* mask);
void q_label_set_mask_with_mask(void* self, void* mask);
QRegion* q_label_mask(void* self);
void q_label_clear_mask(void* self);
void q_label_render(void* self, void* target);
void q_label_render_with_painter(void* self, void* painter);
QPixmap* q_label_grab(void* self);
QGraphicsEffect* q_label_graphics_effect(void* self);
void q_label_set_graphics_effect(void* self, void* effect);
void q_label_grab_gesture(void* self, int64_t typeVal);
void q_label_ungrab_gesture(void* self, int64_t typeVal);
void q_label_set_window_title(void* self, const char* windowTitle);
void q_label_set_style_sheet(void* self, const char* styleSheet);
const char* q_label_style_sheet(void* self);
const char* q_label_window_title(void* self);
void q_label_set_window_icon(void* self, void* icon);
QIcon* q_label_window_icon(void* self);
void q_label_set_window_icon_text(void* self, const char* windowIconText);
const char* q_label_window_icon_text(void* self);
void q_label_set_window_role(void* self, const char* windowRole);
const char* q_label_window_role(void* self);
void q_label_set_window_file_path(void* self, const char* filePath);
const char* q_label_window_file_path(void* self);
void q_label_set_window_opacity(void* self, double level);
double q_label_window_opacity(void* self);
bool q_label_is_window_modified(void* self);
void q_label_set_tool_tip(void* self, const char* toolTip);
const char* q_label_tool_tip(void* self);
void q_label_set_tool_tip_duration(void* self, int msec);
int32_t q_label_tool_tip_duration(void* self);
void q_label_set_status_tip(void* self, const char* statusTip);
const char* q_label_status_tip(void* self);
void q_label_set_whats_this(void* self, const char* whatsThis);
const char* q_label_whats_this(void* self);
const char* q_label_accessible_name(void* self);
void q_label_set_accessible_name(void* self, const char* name);
const char* q_label_accessible_description(void* self);
void q_label_set_accessible_description(void* self, const char* description);
void q_label_set_layout_direction(void* self, int64_t direction);
int64_t q_label_layout_direction(void* self);
void q_label_unset_layout_direction(void* self);
void q_label_set_locale(void* self, void* locale);
QLocale* q_label_locale(void* self);
void q_label_unset_locale(void* self);
bool q_label_is_right_to_left(void* self);
bool q_label_is_left_to_right(void* self);
void q_label_set_focus(void* self);
bool q_label_is_active_window(void* self);
void q_label_activate_window(void* self);
void q_label_clear_focus(void* self);
void q_label_set_focus_with_reason(void* self, int64_t reason);
int64_t q_label_focus_policy(void* self);
void q_label_set_focus_policy(void* self, int64_t policy);
bool q_label_has_focus(void* self);
void q_label_set_tab_order(void* param1, void* param2);
void q_label_set_focus_proxy(void* self, void* focusProxy);
QWidget* q_label_focus_proxy(void* self);
int64_t q_label_context_menu_policy(void* self);
void q_label_set_context_menu_policy(void* self, int64_t policy);
void q_label_grab_mouse(void* self);
void q_label_grab_mouse_with_q_cursor(void* self, void* param1);
void q_label_release_mouse(void* self);
void q_label_grab_keyboard(void* self);
void q_label_release_keyboard(void* self);
int32_t q_label_grab_shortcut(void* self, void* key);
void q_label_release_shortcut(void* self, int id);
void q_label_set_shortcut_enabled(void* self, int id);
void q_label_set_shortcut_auto_repeat(void* self, int id);
QWidget* q_label_mouse_grabber();
QWidget* q_label_keyboard_grabber();
bool q_label_updates_enabled(void* self);
void q_label_set_updates_enabled(void* self, bool enable);
QGraphicsProxyWidget* q_label_graphics_proxy_widget(void* self);
void q_label_update(void* self);
void q_label_repaint(void* self);
void q_label_update2(void* self, int x, int y, int w, int h);
void q_label_update_with_q_rect(void* self, void* param1);
void q_label_update_with_q_region(void* self, void* param1);
void q_label_repaint2(void* self, int x, int y, int w, int h);
void q_label_repaint_with_q_rect(void* self, void* param1);
void q_label_repaint_with_q_region(void* self, void* param1);
void q_label_set_hidden(void* self, bool hidden);
void q_label_show(void* self);
void q_label_hide(void* self);
void q_label_show_minimized(void* self);
void q_label_show_maximized(void* self);
void q_label_show_full_screen(void* self);
void q_label_show_normal(void* self);
bool q_label_close(void* self);
void q_label_raise(void* self);
void q_label_lower(void* self);
void q_label_stack_under(void* self, void* param1);
void q_label_move(void* self, int x, int y);
void q_label_move_with_q_point(void* self, void* param1);
void q_label_resize(void* self, int w, int h);
void q_label_resize_with_q_size(void* self, void* param1);
void q_label_set_geometry(void* self, int x, int y, int w, int h);
void q_label_set_geometry_with_geometry(void* self, void* geometry);
char* q_label_save_geometry(void* self);
bool q_label_restore_geometry(void* self, const char* geometry);
void q_label_adjust_size(void* self);
bool q_label_is_visible(void* self);
bool q_label_is_visible_to(void* self, void* param1);
bool q_label_is_hidden(void* self);
bool q_label_is_minimized(void* self);
bool q_label_is_maximized(void* self);
bool q_label_is_full_screen(void* self);
int64_t q_label_window_state(void* self);
void q_label_set_window_state(void* self, int64_t state);
void q_label_override_window_state(void* self, int64_t state);
QSizePolicy* q_label_size_policy(void* self);
void q_label_set_size_policy(void* self, void* sizePolicy);
void q_label_set_size_policy2(void* self, int64_t horizontal, int64_t vertical);
QRegion* q_label_visible_region(void* self);
void q_label_set_contents_margins(void* self, int left, int top, int right, int bottom);
void q_label_set_contents_margins_with_margins(void* self, void* margins);
QMargins* q_label_contents_margins(void* self);
QRect* q_label_contents_rect(void* self);
QLayout* q_label_layout(void* self);
void q_label_set_layout(void* self, void* layout);
void q_label_update_geometry(void* self);
void q_label_set_parent(void* self, void* parent);
void q_label_set_parent2(void* self, void* parent, int64_t f);
void q_label_scroll(void* self, int dx, int dy);
void q_label_scroll2(void* self, int dx, int dy, void* param3);
QWidget* q_label_focus_widget(void* self);
QWidget* q_label_next_in_focus_chain(void* self);
QWidget* q_label_previous_in_focus_chain(void* self);
bool q_label_accept_drops(void* self);
void q_label_set_accept_drops(void* self, bool on);
void q_label_add_action(void* self, void* action);
void q_label_add_actions(void* self, void* actions[]);
void q_label_insert_actions(void* self, void* before, void* actions[]);
void q_label_insert_action(void* self, void* before, void* action);
void q_label_remove_action(void* self, void* action);
libqt_list /* of QAction* */ q_label_actions(void* self);
QAction* q_label_add_action_with_text(void* self, const char* text);
QAction* q_label_add_action2(void* self, void* icon, const char* text);
QAction* q_label_add_action3(void* self, const char* text, void* shortcut);
QAction* q_label_add_action4(void* self, void* icon, const char* text, void* shortcut);
QWidget* q_label_parent_widget(void* self);
void q_label_set_window_flags(void* self, int64_t typeVal);
int64_t q_label_window_flags(void* self);
void q_label_set_window_flag(void* self, int64_t param1);
void q_label_override_window_flags(void* self, int64_t typeVal);
int64_t q_label_window_type(void* self);
QWidget* q_label_find(uint64_t param1);
QWidget* q_label_child_at(void* self, int x, int y);
QWidget* q_label_child_at_with_q_point(void* self, void* p);
void q_label_set_attribute(void* self, int64_t param1);
bool q_label_test_attribute(void* self, int64_t param1);
void q_label_ensure_polished(void* self);
bool q_label_is_ancestor_of(void* self, void* child);
bool q_label_auto_fill_background(void* self);
void q_label_set_auto_fill_background(void* self, bool enabled);
QBackingStore* q_label_backing_store(void* self);
QWindow* q_label_window_handle(void* self);
QScreen* q_label_screen(void* self);
void q_label_set_screen(void* self, void* screen);
QWidget* q_label_create_window_container(void* window);
void q_label_window_title_changed(void* self, const char* title);
void q_label_on_window_title_changed(void* self, void (*slot)(void*, const char*));
void q_label_window_icon_changed(void* self, void* icon);
void q_label_on_window_icon_changed(void* self, void (*slot)(void*, void*));
void q_label_window_icon_text_changed(void* self, const char* iconText);
void q_label_on_window_icon_text_changed(void* self, void (*slot)(void*, const char*));
void q_label_custom_context_menu_requested(void* self, void* pos);
void q_label_on_custom_context_menu_requested(void* self, void (*slot)(void*, void*));
int64_t q_label_input_method_hints(void* self);
void q_label_set_input_method_hints(void* self, int64_t hints);
void q_label_render2(void* self, void* target, void* targetOffset);
void q_label_render3(void* self, void* target, void* targetOffset, void* sourceRegion);
void q_label_render4(void* self, void* target, void* targetOffset, void* sourceRegion, int64_t renderFlags);
void q_label_render22(void* self, void* painter, void* targetOffset);
void q_label_render32(void* self, void* painter, void* targetOffset, void* sourceRegion);
void q_label_render42(void* self, void* painter, void* targetOffset, void* sourceRegion, int64_t renderFlags);
QPixmap* q_label_grab1(void* self, void* rectangle);
void q_label_grab_gesture2(void* self, int64_t typeVal, int64_t flags);
int32_t q_label_grab_shortcut2(void* self, void* key, int64_t context);
void q_label_set_shortcut_enabled2(void* self, int id, bool enable);
void q_label_set_shortcut_auto_repeat2(void* self, int id, bool enable);
void q_label_set_window_flag2(void* self, int64_t param1, bool on);
void q_label_set_attribute2(void* self, int64_t param1, bool on);
QWidget* q_label_create_window_container2(void* window, void* parent);
QWidget* q_label_create_window_container3(void* window, void* parent, int64_t flags);
const char* q_label_object_name(void* self);
void q_label_set_object_name(void* self, const char* name);
bool q_label_is_widget_type(void* self);
bool q_label_is_window_type(void* self);
bool q_label_is_quick_item_type(void* self);
bool q_label_signals_blocked(void* self);
bool q_label_block_signals(void* self, bool b);
QThread* q_label_thread(void* self);
void q_label_move_to_thread(void* self, void* thread);
int32_t q_label_start_timer(void* self, int interval);
void q_label_kill_timer(void* self, int id);
libqt_list /* of QObject* */ q_label_children(void* self);
void q_label_install_event_filter(void* self, void* filterObj);
void q_label_remove_event_filter(void* self, void* obj);
QMetaObject__Connection* q_label_connect(void* sender, void* signal, void* receiver, void* method);
QMetaObject__Connection* q_label_connect2(void* self, void* sender, const char* signal, const char* member);
bool q_label_disconnect(void* sender, void* signal, void* receiver, void* member);
bool q_label_disconnect_with_q_meta_object_connection(void* param1);
void q_label_dump_object_tree(void* self);
void q_label_dump_object_info(void* self);
bool q_label_set_property(void* self, const char* name, void* value);
QVariant* q_label_property(void* self, const char* name);
const char** q_label_dynamic_property_names(void* self);
QBindingStorage* q_label_binding_storage(void* self);
QBindingStorage* q_label_binding_storage2(void* self);
void q_label_destroyed(void* self);
void q_label_on_destroyed(void* self, void (*slot)(void*));
QObject* q_label_parent(void* self);
bool q_label_inherits(void* self, const char* classname);
void q_label_delete_later(void* self);
int32_t q_label_start_timer2(void* self, int interval, int64_t timerType);
QMetaObject__Connection* q_label_connect5(void* sender, void* signal, void* receiver, void* method, int64_t typeVal);
QMetaObject__Connection* q_label_connect4(void* self, void* sender, const char* signal, const char* member, int64_t typeVal);
void q_label_destroyed1(void* self, void* param1);
void q_label_on_destroyed1(void* self, void (*slot)(void*, void*));
bool q_label_painting_active(void* self);
int32_t q_label_width_m_m(void* self);
int32_t q_label_height_m_m(void* self);
int32_t q_label_logical_dpi_x(void* self);
int32_t q_label_logical_dpi_y(void* self);
int32_t q_label_physical_dpi_x(void* self);
int32_t q_label_physical_dpi_y(void* self);
double q_label_device_pixel_ratio(void* self);
double q_label_device_pixel_ratio_f(void* self);
int32_t q_label_color_count(void* self);
int32_t q_label_depth(void* self);
double q_label_device_pixel_ratio_f_scale();
void q_label_init_style_option(void* self, void* option);
void q_label_qbase_init_style_option(void* self, void* option);
void q_label_on_init_style_option(void* self, void (*slot)(void*, void*));
int32_t q_label_dev_type(void* self);
int32_t q_label_qbase_dev_type(void* self);
void q_label_on_dev_type(void* self, int32_t (*slot)());
void q_label_set_visible(void* self, bool visible);
void q_label_qbase_set_visible(void* self, bool visible);
void q_label_on_set_visible(void* self, void (*slot)(void*, bool));
bool q_label_has_height_for_width(void* self);
bool q_label_qbase_has_height_for_width(void* self);
void q_label_on_has_height_for_width(void* self, bool (*slot)());
QPaintEngine* q_label_paint_engine(void* self);
QPaintEngine* q_label_qbase_paint_engine(void* self);
void q_label_on_paint_engine(void* self, QPaintEngine* (*slot)());
void q_label_mouse_double_click_event(void* self, void* event);
void q_label_qbase_mouse_double_click_event(void* self, void* event);
void q_label_on_mouse_double_click_event(void* self, void (*slot)(void*, void*));
void q_label_wheel_event(void* self, void* event);
void q_label_qbase_wheel_event(void* self, void* event);
void q_label_on_wheel_event(void* self, void (*slot)(void*, void*));
void q_label_key_release_event(void* self, void* event);
void q_label_qbase_key_release_event(void* self, void* event);
void q_label_on_key_release_event(void* self, void (*slot)(void*, void*));
void q_label_enter_event(void* self, void* event);
void q_label_qbase_enter_event(void* self, void* event);
void q_label_on_enter_event(void* self, void (*slot)(void*, void*));
void q_label_leave_event(void* self, void* event);
void q_label_qbase_leave_event(void* self, void* event);
void q_label_on_leave_event(void* self, void (*slot)(void*, void*));
void q_label_move_event(void* self, void* event);
void q_label_qbase_move_event(void* self, void* event);
void q_label_on_move_event(void* self, void (*slot)(void*, void*));
void q_label_resize_event(void* self, void* event);
void q_label_qbase_resize_event(void* self, void* event);
void q_label_on_resize_event(void* self, void (*slot)(void*, void*));
void q_label_close_event(void* self, void* event);
void q_label_qbase_close_event(void* self, void* event);
void q_label_on_close_event(void* self, void (*slot)(void*, void*));
void q_label_tablet_event(void* self, void* event);
void q_label_qbase_tablet_event(void* self, void* event);
void q_label_on_tablet_event(void* self, void (*slot)(void*, void*));
void q_label_action_event(void* self, void* event);
void q_label_qbase_action_event(void* self, void* event);
void q_label_on_action_event(void* self, void (*slot)(void*, void*));
void q_label_drag_enter_event(void* self, void* event);
void q_label_qbase_drag_enter_event(void* self, void* event);
void q_label_on_drag_enter_event(void* self, void (*slot)(void*, void*));
void q_label_drag_move_event(void* self, void* event);
void q_label_qbase_drag_move_event(void* self, void* event);
void q_label_on_drag_move_event(void* self, void (*slot)(void*, void*));
void q_label_drag_leave_event(void* self, void* event);
void q_label_qbase_drag_leave_event(void* self, void* event);
void q_label_on_drag_leave_event(void* self, void (*slot)(void*, void*));
void q_label_drop_event(void* self, void* event);
void q_label_qbase_drop_event(void* self, void* event);
void q_label_on_drop_event(void* self, void (*slot)(void*, void*));
void q_label_show_event(void* self, void* event);
void q_label_qbase_show_event(void* self, void* event);
void q_label_on_show_event(void* self, void (*slot)(void*, void*));
void q_label_hide_event(void* self, void* event);
void q_label_qbase_hide_event(void* self, void* event);
void q_label_on_hide_event(void* self, void (*slot)(void*, void*));
bool q_label_native_event(void* self, const char* eventType, void* message, intptr_t* result);
bool q_label_qbase_native_event(void* self, const char* eventType, void* message, intptr_t* result);
void q_label_on_native_event(void* self, bool (*slot)(void*, const char*, void*, intptr_t*));
int32_t q_label_metric(void* self, int64_t param1);
int32_t q_label_qbase_metric(void* self, int64_t param1);
void q_label_on_metric(void* self, int32_t (*slot)(void*, int64_t));
void q_label_init_painter(void* self, void* painter);
void q_label_qbase_init_painter(void* self, void* painter);
void q_label_on_init_painter(void* self, void (*slot)(void*, void*));
QPaintDevice* q_label_redirected(void* self, void* offset);
QPaintDevice* q_label_qbase_redirected(void* self, void* offset);
void q_label_on_redirected(void* self, QPaintDevice* (*slot)(void*, void*));
QPainter* q_label_shared_painter(void* self);
QPainter* q_label_qbase_shared_painter(void* self);
void q_label_on_shared_painter(void* self, QPainter* (*slot)());
void q_label_input_method_event(void* self, void* param1);
void q_label_qbase_input_method_event(void* self, void* param1);
void q_label_on_input_method_event(void* self, void (*slot)(void*, void*));
QVariant* q_label_input_method_query(void* self, int64_t param1);
QVariant* q_label_qbase_input_method_query(void* self, int64_t param1);
void q_label_on_input_method_query(void* self, QVariant* (*slot)(void*, int64_t));
bool q_label_event_filter(void* self, void* watched, void* event);
bool q_label_qbase_event_filter(void* self, void* watched, void* event);
void q_label_on_event_filter(void* self, bool (*slot)(void*, void*, void*));
void q_label_timer_event(void* self, void* event);
void q_label_qbase_timer_event(void* self, void* event);
void q_label_on_timer_event(void* self, void (*slot)(void*, void*));
void q_label_child_event(void* self, void* event);
void q_label_qbase_child_event(void* self, void* event);
void q_label_on_child_event(void* self, void (*slot)(void*, void*));
void q_label_custom_event(void* self, void* event);
void q_label_qbase_custom_event(void* self, void* event);
void q_label_on_custom_event(void* self, void (*slot)(void*, void*));
void q_label_connect_notify(void* self, void* signal);
void q_label_qbase_connect_notify(void* self, void* signal);
void q_label_on_connect_notify(void* self, void (*slot)(void*, void*));
void q_label_disconnect_notify(void* self, void* signal);
void q_label_qbase_disconnect_notify(void* self, void* signal);
void q_label_on_disconnect_notify(void* self, void (*slot)(void*, void*));
void q_label_draw_frame(void* self, void* param1);
void q_label_qbase_draw_frame(void* self, void* param1);
void q_label_on_draw_frame(void* self, void (*slot)(void*, void*));
void q_label_update_micro_focus(void* self);
void q_label_qbase_update_micro_focus(void* self);
void q_label_on_update_micro_focus(void* self, void (*slot)());
void q_label_create(void* self);
void q_label_qbase_create(void* self);
void q_label_on_create(void* self, void (*slot)());
void q_label_destroy(void* self);
void q_label_qbase_destroy(void* self);
void q_label_on_destroy(void* self, void (*slot)());
bool q_label_focus_next_child(void* self);
bool q_label_qbase_focus_next_child(void* self);
void q_label_on_focus_next_child(void* self, bool (*slot)());
bool q_label_focus_previous_child(void* self);
bool q_label_qbase_focus_previous_child(void* self);
void q_label_on_focus_previous_child(void* self, bool (*slot)());
QObject* q_label_sender(void* self);
QObject* q_label_qbase_sender(void* self);
void q_label_on_sender(void* self, QObject* (*slot)());
int32_t q_label_sender_signal_index(void* self);
int32_t q_label_qbase_sender_signal_index(void* self);
void q_label_on_sender_signal_index(void* self, int32_t (*slot)());
int32_t q_label_receivers(void* self, const char* signal);
int32_t q_label_qbase_receivers(void* self, const char* signal);
void q_label_on_receivers(void* self, int32_t (*slot)(void*, const char*));
bool q_label_is_signal_connected(void* self, void* signal);
bool q_label_qbase_is_signal_connected(void* self, void* signal);
void q_label_on_is_signal_connected(void* self, bool (*slot)(void*, void*));
void q_label_delete(void* self);

#endif
